"""Generate training data - Mega batch 9. Heavy push to close the gap to 1500."""
import json
import os

rules = [
    {"instruction": "What is a replacement effect for drawing cards?", "input": "", "output": "Dredge is the most common draw replacement in Legacy. When you would draw a card and a card with dredge is in your graveyard, you may choose to mill N cards and return the dredge card to hand instead of drawing. Other draw replacements: Notion Thief replaces opponent's extra draws with your draws. Chains of Mephistopheles (Reserved List, very rare) replaces draws beyond the first with discard-then-draw. Spirit of the Labyrinth prevents extra draws entirely (replacement with nothing). These all apply before the draw happens and cannot be responded to since they are replacement effects."},
    {"instruction": "How does the London Mulligan interact with Leyline of the Void?", "input": "", "output": "With the London Mulligan, you draw 7 cards, decide whether to keep, and if you mulligan, you draw 7 again then put cards on the bottom. Leyline of the Void can start in play if it is in your opening hand. The process: 1) Draw 7. 2) If you have Leyline, you may reveal it. 3) Decide keep or mulligan. 4) If mulligan, shuffle all 7 back, draw 7 again. Leyline goes back too and might not be in the new 7. 5) After all mulligans, reveal any Leylines in your final hand. They start in play. The risk: mulliganing aggressively for Leyline means you might end up with a 5-card hand that has Leyline but no functional game plan."},
    {"instruction": "What is the difference between loses the game and damage?", "input": "", "output": "Losing the game is a game action that ends the game immediately for that player. Damage reduces life totals and can be prevented, redirected, or modified. Key distinction: effects that say 'loses the game' cannot be prevented by damage prevention (Solitary Confinement prevents damage but not losing). Poison counters (10 = lose), decking (drawing from empty library = lose), and Pact upkeep costs (cannot pay = lose) all cause game loss without dealing damage. Tendrils of Agony causes loss of life, which is different from damage - loss of life cannot be prevented by damage prevention effects. This is why Tendrils kills through Solitary Confinement."},
    {"instruction": "Can I sacrifice a permanent I do not own but control?", "input": "", "output": "Yes. You can sacrifice any permanent you control, regardless of who owns it. If you Reanimate an opponent's creature from their graveyard, you control it. You can sacrifice it to Goblin Bombardment, Cabal Therapy, or any sacrifice effect. When a permanent you control but do not own would go to the graveyard (from sacrifice, destruction, etc.), it goes to its OWNER's graveyard, not yours. So sacrificing your opponent's Reanimated creature puts it in THEIR graveyard, where they might Reanimate it again."},
    {"instruction": "How do MDFC (modal double-faced cards) work in Legacy?", "input": "", "output": "Modal double-faced cards have two faces and you choose which face to play. Unlike transform cards (Delver of Secrets), MDFCs are not cast and then flipped - you choose which face on casting. Agadeem's Awakening is a sorcery on the front and a land on the back. You can play it as a tapped land when you need mana or cast it as a spell when you need the effect. In Legacy, MDFCs see limited play because both sides are usually weaker than dedicated cards. The flexibility rarely compensates for the reduced power. The most played MDFC in Legacy is Agadeem's Awakening in some black combo lists as a spell that doubles as a land."},
    {"instruction": "What is the interaction between Stoneforge Mystic and Batterskull?", "input": "", "output": "Stoneforge Mystic has two abilities: 1) ETB: search library for an equipment card and put it in hand. 2) 1W, tap: put an equipment card from hand onto the battlefield. The key is the second ability: you search for Batterskull (a 4WW living weapon equipment) with the ETB, then use the tap ability to put it directly onto the battlefield for just 1W on the next turn. This cheats Batterskull's 5-mana equip cost and 5-mana casting cost. Batterskull enters with a 0/0 Germ token that immediately gets +4/+4 and vigilance/lifelink. A 4/4 vigilance lifelink on turn 3 for effectively 3 total mana across 2 turns is excellent."},
    {"instruction": "What is convoke and is it relevant in Legacy?", "input": "", "output": "Convoke lets you tap creatures to help pay for a spell. Each tapped creature pays for 1 generic mana or 1 mana of that creature's color. In Legacy, convoke is most relevant on Hogaak, Arisen Necropolis, which costs 5BG but has both convoke and delve. Hogaak is cast from the graveyard using a combination of tapping creatures (convoke) and exiling graveyard cards (delve). This means Hogaak costs 0 mana in practice - you just need 2 creatures and 5 graveyard cards. An 8/8 trample for free is extremely powerful in the Hogaak archetype."},
    {"instruction": "How does the Wish mechanic work in tournament play?", "input": "", "output": "Wish cards (Burning Wish, Cunning Wish, Living Wish, etc.) say 'you may choose a card you own from outside the game.' In tournament play, 'outside the game' means your sideboard. So Burning Wish searches your sideboard for a sorcery card. In The EPIC Storm, the sideboard contains sorceries for Burning Wish: Tendrils of Agony (win condition), Empty the Warrens (alternate win), Past in Flames (recursion), Pulverize (artifact destruction), etc. The card you Wish for goes to your hand and must be cast normally (paying mana costs). You cannot Wish for cards in exile, in other games, or from a card binder."},
    {"instruction": "What happens if a creature has both first strike and deathtouch?", "input": "", "output": "First strike means the creature deals damage in the first strike combat damage step, before normal combat damage. Deathtouch means any amount of damage dealt by this creature is lethal. Combined: the creature deals first strike damage with deathtouch, killing any creature it damages before that creature can deal normal combat damage back. In practice, a 1/1 first strike deathtouch creature can block and kill any non-first-strike creature without dying. In Legacy, this is relevant on Baleful Strix (1/1 flying deathtouch, also draws a card on ETB) which blocks Murktide Regent profitably."},
    {"instruction": "Can I use Force of Will to counter a land being played?", "input": "", "output": "No. Playing a land is a special action, not a spell. Force of Will can only counter spells (cards that are cast and go on the stack). Lands are played directly onto the battlefield without going on the stack. There is no opportunity to counter a land. To stop an opponent from benefiting from their lands, you need: Wasteland (destroy it), Blood Moon (change it to Mountain), Rishadan Port (tap it), or Stifle (counter an activated ability of the land, like a fetchland search). Preventing land drops requires proactive strategies, not reactive countermagic."},
    {"instruction": "What is a 'dies' trigger and how does it interact with exile effects?", "input": "", "output": "A 'dies' trigger means 'when this creature is put into the graveyard from the battlefield.' If a creature is exiled instead of going to the graveyard (Swords to Plowshares, Solitude, Path to Exile), it does NOT die and 'dies' triggers do NOT happen. However, with Leyline of the Void, creatures that would go to the graveyard are exiled instead, but the game still considers them to have 'died' because the replacement effect changed the destination but not the event type. This is a subtle but important distinction: Swords exiles directly (no death), while Leyline replaces the graveyard destination (still counts as death for triggers)."},
    {"instruction": "How does the Companion mechanic work after the 2020 errata?", "input": "", "output": "After the errata: 1) Before the game, reveal your companion from outside the game (sideboard). 2) Your deck must meet the companion's restriction. 3) Once per game, you may pay 3 generic mana to put the companion from outside the game into your hand. 4) Then cast it normally from hand, paying its mana cost. This means companions cost 3 extra mana on top of their casting cost. In Legacy, only Yorion, Sky Nomad sees significant play because the 80-card restriction is manageable and Yorion's blink effect is powerful enough to justify the total 8 mana investment (3 to hand + 3WU to cast). Lurrus and Zirda are banned."},
]

card_eval = [
    {"instruction": "Is Baleful Strix Legacy-playable?", "input": "", "output": "Marginally. Baleful Strix costs UB for a 1/1 flying deathtouch that draws a card on ETB. The ETB draw provides card advantage, and the deathtouch/flying body trades with any creature (including Murktide Regent). It was a staple in BUG and Esper lists for years. However, Orcish Bowmasters fills a similar slot (UB, ETB effect, body) but is significantly more impactful. Bowmasters punishes opponents proactively while Strix is purely defensive. Strix sees occasional play in Esper and BUG builds that want a defensive speed bump with card advantage, but it is no longer a Legacy staple."},
    {"instruction": "Is Spell Pierce Legacy-playable?", "input": "", "output": "Yes, as a sideboard card and occasional maindeck 1-of. Spell Pierce costs U and counters a noncreature spell unless the opponent pays 2. It is excellent on turns 1-3 when opponents are mana-constrained. It catches Show and Tell (3 mana, they need 5 total to play through Pierce), planeswalkers, enchantments (Up the Beanstalk), and artifacts. It is worse than Daze in tempo decks (Daze is free) and worse than Force of Will against must-counter spells (Pierce can be paid). Best in: combo protection (cheap counter for opponent's Force of Will), sideboard for specific matchups."},
    {"instruction": "Is Tombstalker Legacy-playable?", "input": "", "output": "No. Tombstalker was once played as a budget Murktide Regent: a 5/5 flyer for BB with delve. However, Murktide Regent is strictly better in almost every way: it has variable power (often 6/6 to 8/8+), it grows if more cards are exiled later, and it costs UU which is easier to cast in blue decks. Tombstalker's BB requirement limits it to black-heavy decks, and a fixed 5/5 without growth is underwhelming by current Legacy standards. Murktide completely replaced Tombstalker when it was printed in MH2."},
    {"instruction": "Is Cavern of Souls Legacy-playable?", "input": "", "output": "Yes, in tribal decks. Cavern of Souls enters untapped, produces colorless, and can tap for any color but only to cast creatures of the named type. Crucially, creatures cast with Cavern mana cannot be countered. In Elves, naming Elf means your Heritage Druid and Wirewood Symbiote resolve through Force of Will. In Goblins, naming Goblin protects Muxus and Goblin Ringleader. In Humans, naming Human protects the entire team. Cavern is essential in any tribal deck that needs to resolve key creatures against countermagic. It is in about 7% of Legacy decks."},
    {"instruction": "Is Unmask Legacy-playable?", "input": "", "output": "Marginally, in specific shells. Unmask costs 3B or exile a black card from hand (free). It lets you look at opponent's hand and discard a nonland card. It is a worse Thoughtseize in most scenarios (random discard from exile is a bigger cost than 2 life, and 3B is uncastable in Legacy). However, the free cost matters in all-in combo decks that need to clear disruption on turn 1 without spending mana. Some Reanimator and Storm lists have run Unmask as Thoughtseize copies 5-6 when maximal turn-1 disruption is needed."},
    {"instruction": "Is Mox Diamond Legacy-playable?", "input": "", "output": "Yes, in specific decks. Mox Diamond costs 0 and enters by discarding a land card, then taps for any color. In Lands, discarding a land is upside (Loam returns it). In Aggro Loam, same principle. In prison decks, the free mana enables turn-1 lock pieces. At $400-500 on the Reserved List, it is one of the most expensive Legacy staples. The card disadvantage (discard a land) limits it to decks that: recover the discarded land, need fast mana desperately, or have excess lands to discard. About 5% of Legacy decks play it."},
    {"instruction": "Is Teferi, Time Raveler Legacy-playable?", "input": "", "output": "Situationally. Teferi costs 1WU and has: +1 until your next turn opponents can only cast spells at sorcery speed (shuts off instants, flash, and Force of Will on your turn), -3 bounce a permanent and draw a card. The +1 is powerful against combo (they cannot go off at instant speed or end of turn), and the -3 provides card advantage and removal. At 3 mana, it is slow for Legacy but sees play in UW and Jeskai Control sideboards. It is not a mainboard staple due to the 3-mana cost competing with more impactful plays."},
    {"instruction": "Is Trinisphere Legacy-playable?", "input": "", "output": "Yes, as a prison piece. Trinisphere costs 3 and makes all spells cost at least 3 mana. This is devastating: Brainstorm costs 3, Force of Will's alternative cost adds 3 mana on top, Daze costs 3 + return Island, Dark Ritual costs 3. Almost every Legacy spell is undercosted by Trinisphere's standard. Deployed turn 1 via Ancient Tomb + Chrome Mox/Lotus Petal, Trinisphere locks out most of Legacy's best plays. It sees play in Red Stompy and some Eldrazi builds. The 3-mana casting cost means it cannot be deployed as fast as Chalice (which costs XX=0-2)."},
    {"instruction": "Is Thoughtcast Legacy-playable?", "input": "", "output": "Yes, in artifact-heavy decks. Thoughtcast costs 4U but has affinity for artifacts, reducing the cost by 1 for each artifact you control. With 4+ artifacts (trivial in 8-Cast/Affinity), Thoughtcast costs U to draw 2 cards - better rate than any cantrip. It is an automatic 4-of in Blue Artifacts/8-Cast at 1.1% meta share. Completely unplayable outside dedicated artifact decks because without artifacts, it is a 5-mana draw-2 which is absurdly expensive for Legacy."},
    {"instruction": "Is Council's Judgment Legacy-playable?", "input": "", "output": "Yes, as targeted removal for hard-to-kill permanents. Council's Judgment costs 1WW and each player votes for a nonland permanent they do not control. The permanent with the most votes is exiled. The key: it does not TARGET, so it hits True-Name Nemesis (protection does not stop non-targeting effects), hexproof/shroud creatures, and anything else that dodges targeting. In 1v1 Legacy, both players vote for different things (you vote for their best permanent, they vote for nothing useful of yours), so your choice is exiled. It is a 3-mana Vindicate that hits anything including protected permanents."},
]

deckbuilding = [
    {"instruction": "How do I build a Legacy deck that attacks the metagame rather than just playing good cards?", "input": "", "output": "Meta-attacking means exploiting specific weaknesses in popular decks: 1) If 14.6% is Dimir Tempo, play Lands (Wasteland-proof, Maze of Ith nullifies their threats). 2) If 36% play Leyline of the Void, avoid graveyard dependence or run enchantment removal. 3) If Chalice decks are rising, play 2-3 mana spells that dodge Chalice on 1. 4) If combo is declining, cut sideboard combo hate for more creature interaction. The process: identify the top 3 decks, find what they are weak to, and build a deck that exploits those weaknesses while maintaining a functional plan against the rest of the field. This is how Aluren won the Showcase Qualifier at 1.2% - nobody was prepared for it."},
    {"instruction": "Should I play Brainstorm in a deck without fetchlands?", "input": "", "output": "Almost never. Brainstorm without a shuffle effect (fetchland, Ponder) means you put 2 cards on top and draw them over 2 turns. This Brainstorm lock wastes your next 2 draw steps. Without fetchlands, Ponder is strictly better (look at 3, can shuffle all away). Preordain is also better (scry 2, put bad cards on bottom permanently). The only exception: decks that specifically want cards on top of their library (Counterbalance, Miracles for miracle triggers). Even then, you want fetchlands. If your deck has zero shuffle effects, do not play Brainstorm."},
    {"instruction": "How do I decide the right number of a sideboard card to include?", "input": "", "output": "Match the count to the frequency and importance of the matchup: 4 copies: must-have for a common bad matchup (4 Leyline of the Void when graveyard combo is 15%+ of meta). 3 copies: important for a common matchup but not mandatory in every game (3 Pyroblast in a blue-heavy meta). 2 copies: solid for multiple matchups (2 Flusterstorm covers Storm, counter wars, and combo generally). 1 copy: narrow but powerful when drawn (1 Surgical Extraction for specific combo pieces). 0 copies: the matchup is rare enough that dedicating a slot is not worth it. Also consider: if you have 8 cantrips, even 1-2 copies of a hate card are findable. You do not need 4 Surgical when Brainstorm and Ponder find it reliably."},
    {"instruction": "What is a transformational sideboard plan for Dimir Tempo?", "input": "", "output": "Dimir Tempo typically does not need a full transformational sideboard because the maindeck is already flexible. However, partial transformations exist: vs Prison (Chalice decks): transform from cantrip-heavy to threat-heavy. Board out Ponder and some Brainstorms (countered by Chalice on 1), bring in threats that cost 2+ mana (extra Murktide, Tombstalker, or Gurmag Angler). vs Control: transform from tempo to midrange. Board out Daze (opponent has plenty of mana), bring in card advantage (Jace, extra Thoughtseize, planeswalkers). vs Combo: stay the course but maximize disruption. Board in Leyline and Surgical, cut removal spells."},
    {"instruction": "Why does Red Stompy not play Force of Will?", "input": "", "output": "Red Stompy is mono-red. Force of Will requires exiling a blue card from hand, and Red Stompy plays zero blue cards. Even if it could somehow play Force, the deck strategy is fundamentally different: Stompy wants to deploy lock pieces (Chalice, Blood Moon) on turn 1, not hold up interaction. Chalice on 1 IS the deck's answer to most spells. Blood Moon IS the deck's answer to mana bases. The prison pieces serve as Force of Will's equivalent by preventing spells from being cast in the first place rather than countering them one at a time."},
    {"instruction": "How do you balance proactive and reactive cards in a Legacy deck?", "input": "", "output": "The balance depends on your role: Tempo (be proactive): 60% proactive (threats, Thoughtseize, Wasteland) / 40% reactive (Force, Daze). You want to present threats and disrupt. Control (be reactive): 30% proactive (win conditions, planeswalkers) / 70% reactive (counters, removal). You want to answer everything. Combo (be proactive): 80% proactive (combo pieces, protection) / 20% reactive (Force of Will, Pact). You want to execute your plan. Prison (be proactive): 70% proactive (lock pieces, threats) / 30% reactive (removal for things that slip through). Every deck needs some of both - a pure reactive deck with no threats never wins, and a pure proactive deck with no interaction loses to combo."},
    {"instruction": "What are the most common deckbuilding mistakes in Legacy?", "input": "", "output": "1) Too many 3+ mana cards: Legacy rewards 0-2 mana efficiency. Every 3+ mana card needs extraordinary justification. 2) Not enough blue cards for Force of Will: if you play Force, you need 19+ blue cards. Check after sideboarding too. 3) Wrong fetchland configuration: your fetches should find your dual lands and basics. Mismatched fetches waste flexibility. 4) Too few or too many basics: 0 basics means Wasteland destroys you. 5+ basics means you flood on colorless in multi-color decks. 2-4 is usually right. 5) Sideboard cards that conflict with your maindeck: Null Rod in a deck with Lotus Petal, Leyline in a Murktide deck (actually Leyline only hits opponents, so this is fine). 6) Playing more than 60 cards without Yorion."},
]

deck_analysis = [
    {"instruction": "What are the warning signs that my Legacy deck needs updating?", "input": "", "output": "Red flags: 1) Your win rate dropped 5%+ over 20 matches without changing your play. 2) A new card was printed that directly hates your strategy (e.g., Bowmasters for small creature decks). 3) Your worst matchup became the most popular deck. 4) You consistently lose game 1 and rely on sideboard to compete. 5) Opponents consistently have the right answers for your threats (they metagamed against you). 6) A card in your deck feels dead in 30%+ of games. 7) New printings made a card in your deck strictly obsolete. Update process: change 1-2 flex slots and 2-3 sideboard slots. Do not overhaul the entire deck at once."},
    {"instruction": "How do I evaluate if my Legacy mana base is correct?", "input": "", "output": "Test these checkpoints: 1) Can you cast your turn-1 play in 90%+ of opening hands? (Need 14+ sources of that color). 2) Do you have 2-4 basics for Wasteland/Blood Moon protection? 3) Can you cast Force of Will (1 life + pitch) AND your threats in the same game? (Need sufficient blue sources and colored sources for threats). 4) Are your fetchlands configured correctly? Each fetch should find at least 2 dual land types. 5) Are you taking too much damage from your own mana base? Track life lost to fetches and shocks over 10 games. 6) Do you flood or screw on color more than 10% of games? If so, adjust basic/dual/fetch ratios."},
    {"instruction": "My deck has a 55% win rate overall but 30% against Oops All Spells. Is that acceptable?", "input": "", "output": "It depends on how often you face Oops. At 8.2% meta share, you face Oops roughly once every 12 matches. With a 30% win rate in that matchup, you lose that match 70% of the time. Expected impact on overall win rate: -0.7 x 0.082 = -5.7% reduction in overall win rate from that matchup alone. Your 55% overall already includes this drag. The question is whether dedicating more sideboard slots to improve the Oops matchup (4 Leyline of the Void) would improve your overall win rate by more than it costs in other matchups. If adding 4 Leyline brings Oops to 60% but weakens other matchups by 2%, the math might not favor the change. Calculate expected value per matchup before changing."},
    {"instruction": "How do I evaluate whether a new set will impact Legacy?", "input": "", "output": "Look for cards that meet Legacy's power bar: 1) Free spells or alternative costs (Force of Negation, Solitude). 2) Creatures with 3+ toughness that provide value on ETB (Bowmasters, Murktide). 3) Lands with powerful abilities (Urza's Saga). 4) Cards that slot directly into existing shells without deckbuilding cost. 5) New mechanics that circumvent existing interaction (energy bypasses countermagic). Most set releases add 0-2 Legacy-playable cards. Modern Horizons sets are exceptions: MH1 added ~10, MH2 added ~15, MH3 added ~10. Standard sets rarely contribute. Commander/supplemental sets occasionally have relevant cards (True-Name Nemesis from C13)."},
    {"instruction": "How do tournament results differ from league results in Legacy?", "input": "", "output": "MTGO League 5-0s: published weekly, represent the broadest metagame. Include both skilled players on tier 1 decks and lucky runs on fringe decks. Wizards curates published lists to show diversity, so meta percentages from 5-0s can be misleading. Challenge top 8s: 32+ player events, more competitive. Top 8 represents decks that won 5+ matches against strong fields. Better indicator of actual deck power. Showcase Qualifiers: highest stakes MTGO events, best players, most competitive metagame. Paper GPs/Opens: larger fields, potentially slower metagame adaptation, more rogue decks. The most reliable data comes from averaging Challenge top 8s over 4+ weeks."},
]

conversation = [
    {"instruction": "I just went 0-4 at a Legacy tournament. Should I switch decks?", "input": "", "output": "Not necessarily. 0-4 in a single tournament can happen with any deck due to variance. Before switching, ask:\n\n1) Were your losses due to bad matchups, bad draws, or bad play? If matchups: maybe your deck is poorly positioned in your local meta. If draws: variance, play more. If play: focus on improving, not switching.\n\n2) How many total Legacy matches have you played with this deck? If fewer than 30, you are still learning. Give it more time.\n\n3) Did you enjoy playing the deck? Enjoyment matters more than a single tournament result. Legacy is a long-term commitment.\n\n4) Review each loss specifically. Write down the key moments. Often you will find 2-3 decisions that cost you games.\n\nOnly switch if: you consistently (30+ matches) have a sub-45% win rate AND you have identified structural matchup problems that sideboarding cannot fix. One bad tournament is noise, not signal."},
    {"instruction": "How do I deal with tilt in Legacy?", "input": "", "output": "Legacy tilt is especially brutal because the format's complexity means mistakes compound. Tips:\n\n1) Take a breath between games. Literally. 10 seconds of breathing resets your mental state.\n\n2) Focus on the next decision, not the last mistake. You cannot undo a bad Brainstorm, but you can play the next turn optimally.\n\n3) If you just lost a match: stand up, get water, walk around for 2 minutes before the next round. Physical movement breaks the tilt cycle.\n\n4) Remember that every player, including world champions, makes mistakes and has losing streaks. One session does not define your skill.\n\n5) Avoid results-oriented thinking. A correct play that loses is still correct. An incorrect play that wins is still incorrect. Judge your play quality, not the outcome.\n\n6) If you are genuinely tilted after 3 rounds, consider dropping and playing casually. Forcing yourself through rounds while tilted just compounds bad decisions.\n\nLegacy is a marathon, not a sprint."},
    {"instruction": "Should I practice Legacy against AI or only against humans?", "input": "", "output": "Both have value:\n\nAI practice (goldfishing, simple bots): Best for: learning your own deck's sequencing, practicing opening hands, memorizing sideboard plans, and understanding your average goldfish speed. Goldfishing 20 hands teaches you more about your deck's consistency than 5 matches against humans. Weakness: AI does not play like humans, so you do not learn interaction timing.\n\nHuman practice: Best for: learning matchup dynamics, practicing Brainstorm decisions under pressure, sideboard evolution, and developing metagame intuition. You cannot learn Daze math or Force of Will decisions against AI. Weakness: slower, dependent on finding opponents.\n\nOptimal split: 30% goldfishing/AI (learn your deck mechanics), 70% human practice (learn the format). For your first 10 matches with a new deck, goldfish 80% of the time to learn sequencing before adding opponent interaction."},
    {"instruction": "What makes Legacy the best format in Magic?", "input": "", "output": "Legacy players will tell you: 1) Every card in Magic's history is available. The deepest card pool means the most interesting deckbuilding decisions. 2) Skill expression is unmatched. Brainstorm alone has hundreds of decision trees. The gap between a good and great Legacy player is wider than any other format. 3) No rotation. Your deck investment lasts forever. A deck built in 2015 (with updates) is still competitive in 2026. 4) Community. Legacy players are passionate, knowledgeable, and welcoming. The format's barrier to entry creates a self-selecting community of dedicated players. 5) Game diversity. With 54+ archetypes, every tournament round is different. You face combo, tempo, control, and prison all in one event. 6) History. Playing with Alpha cards alongside modern designs connects you to Magic's entire 30+ year history. Legacy is not just a format - it is Magic at its most complete."},
    {"instruction": "Convince me to try Legacy if I have never played an eternal format.", "input": "", "output": "Try Legacy because:\n\n1) You will play Magic at its most powerful. Cards that defined every era - Brainstorm, Force of Will, Lightning Bolt, Swords to Plowshares - all in one format.\n\n2) You do not need to spend $5000 to start. MTGO costs $300-500. Many stores allow proxies. Burn is $1500 in paper.\n\n3) The learning curve is steep but the payoff is enormous. Once you understand Legacy's interactions, every other format feels shallow by comparison.\n\n4) Your collection appreciates. Reserved List cards only go up. This is the only Magic format where your cards are an investment.\n\n5) The community will welcome you. Legacy players WANT more people to play the format. Ask questions, borrow decks, and people will help.\n\n6) Start with one deck and master it. You do not need to know every card on day 1. Brainstorm and Force of Will will teach you the rest.\n\nThe first time you Brainstorm in response to Thoughtseize to hide your best cards, you will understand why Legacy players never switch formats."},
]

board_state = [
    {"instruction": "Board state: I have 3 mana and Swords to Plowshares in hand. Opponent attacks with Emrakul, the Aeons Torn (protection from colored spells) via Sneak Attack. Can I do anything?", "input": "", "output": "Swords cannot target Emrakul (protection from colored spells). Your options: 1) If you have Karakas, tap it to bounce Emrakul (land ability, not a spell). 2) Sacrifice permanents to annihilator 6 (you lose 6 permanents but survive if you have more than 15 life). 3) Fog effects (Darkness costs 1B, prevents all combat damage this turn). 4) Flash in a creature that can block (but Emrakul has flying, so you need a flyer or reach creature). 5) Maze of Ith untaps and removes from combat (land ability, not a colored spell). Without Karakas or Maze, you are likely dead to 15 damage + annihilator 6."},
    {"instruction": "Board state: I have Natural Order in hand and 4 elves in play including Heritage Druid. Opponent has Force of Will and a blue card (I know from Thoughtseize). How do I play this?", "input": "", "output": "You need to either bait or play around Force. Options: 1) Cast a lesser threat first (Elvish Visionary, etc.) to bait Force, then Natural Order next turn. Risk: they save Force for NO. 2) Just cast Natural Order into Force. You lose NO and a sacrificed elf (2-for-2 plus Force's pitch = 3 cards from opponent). This leaves you with 3 elves and another draw step to find a second NO or GSZ. 3) If you have enough mana from Heritage Druid, cast multiple spells to force them to use Force on the wrong one. Heritage Druid taps 3 elves for GGG. Use GGG to cast NO (costs 2GG, need one more G from a land). If they Force, you still have elves and mana for Craterhoof via another path. Line 3 is best: deploy a threat THEN Natural Order. They must Force one; the other resolves."},
    {"instruction": "Board state: I am playing Doomsday. I just resolved Doomsday at 7 life. I have Ponder in hand and 1 Island untapped. Construct a pile.", "input": "", "output": "Available resources: Ponder in hand, 1 blue mana, 7 life (Doomsday cost half your life rounded up from starting life). Pile (top to bottom): 1) Brainstorm 2) LED (Lion's Eye Diamond) 3) Thassa's Oracle 4) Force of Will 5) A blue card (for Force pitch)\n\nSequence: Cast Ponder (U), see top 3: Brainstorm, LED, Oracle. Take Brainstorm (draw it). Island untapped. Need more mana. Cast Brainstorm (U from tapping Island): draw LED, Oracle, Force of Will. Put back 2 cards (does not matter, library has 2 left). Play LED (0). Cast Oracle... wait, Oracle costs UU. You have 0 mana and LED gives BBB or UUU. Crack LED for UUU, discarding hand (Force goes to graveyard). Cast Oracle for UU (1 mana remaining). Oracle ETB: devotion to blue = 2 (UU in Oracle's cost). Cards in library = 2. 2 >= 2 = you win!\n\nWait - you need to check: after drawing with Brainstorm and putting 2 back, library has 2 cards. Oracle checks on ETB. Devotion to blue = Oracle (UU in its mana cost) = 2. Library = 2. 2 >= 2. You win!"},
    {"instruction": "Board state: I have Batterskull equipped to a Germ token (4/4 vigilance lifelink). Opponent casts Kolaghan's Command choosing 'destroy an artifact' and 'deal 2 damage to any target.' What happens?", "input": "", "output": "Kolaghan's Command's two modes resolve in order: 1) Destroy target artifact: destroys Batterskull (it is an artifact). 2) Deal 2 damage to target: deals 2 to the Germ (or you, or another target). If Batterskull is destroyed, the Germ token is still a 0/0 creature (base stats with no equipment). It dies to state-based actions (0 toughness) before the 2 damage mode even matters. If opponent chose to deal 2 damage to you instead, Batterskull is still destroyed and the Germ dies as a 0/0. However - Batterskull has a return ability: pay 3 mana to return it to hand. If you have 3 mana, you can activate this in response to K-Command, saving Batterskull by bouncing it to hand (Germ dies either way since it becomes 0/0 when Batterskull leaves)."},
    {"instruction": "Board state: My opponent controls Narset, Parter of Veils (each opponent can draw only 1 card per turn). I have Sylvan Library in play. During my draw step, what happens?", "input": "", "output": "Your draw step: you draw your normal card for the turn (1 draw). Then Sylvan Library triggers: you may draw 2 additional cards. However, Narset prevents you from drawing more than 1 card per turn. Your normal draw already used your 1 allowed draw. Sylvan Library's 2 extra draws are replaced by nothing (you simply cannot draw). You drew 1 card total, and Sylvan Library's 'put 2 back or pay 8 life' still applies. Since you only drew 1 card this turn, you can choose to put 0 back and pay 0 life, or put 1 back (the card you drew). Narset completely shuts off Sylvan Library's advantage. To fix this: remove Narset first, then Library becomes a draw engine again."},
]

budget = [
    {"instruction": "What are the best budget sideboard cards for each color?", "input": "", "output": "White ($1-5): Swords to Plowshares ($3), Rest in Peace ($2), Deafening Silence ($1), Containment Priest ($3), Ethersworn Canonist ($2). Blue ($1-15): Flusterstorm ($12), Hydroblast ($2), Blue Elemental Blast ($2), Spell Pierce ($1), Mindbreak Trap ($5). Black ($1-10): Surgical Extraction ($5), Thoughtseize ($15), Massacre ($1), Plague Engineer ($3). Red ($1-5): Pyroblast ($2), Red Elemental Blast ($2), Meltdown ($1), Abrade ($1). Green ($1-15): Veil of Summer ($5), Force of Vigor ($15), Endurance ($35 - priciest but worth it), Collector Ouphe ($2). Colorless ($1-10): Grafdigger's Cage ($2), Pithing Needle ($1), Tormod's Crypt ($1), Relic of Progenitus ($2). Total cost for a versatile 15-card sideboard: $30-80."},
    {"instruction": "I want to build 2 Legacy decks that share as many cards as possible. What pair gives the best overlap?", "input": "", "output": "Best overlap pairs:\n\n1) Dimir Tempo + Doomsday: Share 4 Brainstorm, 4 Ponder, 4 Force of Will, 4 Daze, Underground Sea, Polluted Delta, fetchlands. ~24 cards overlap. Different threats and combo pieces.\n\n2) Izzet Delver + Sneak and Show: Share 4 Brainstorm, 4 Ponder, 4 Force of Will, Volcanic Island, Scalding Tarn, fetchlands, Lotus Petal. ~20 cards overlap. Different threats and combo vs tempo strategy.\n\n3) Red Stompy + Eldrazi: Share 4 Chalice of the Void, 4 Ancient Tomb, City of Traitors, basic Mountains (partial). ~12 cards overlap. Different creature suites.\n\n4) Burn + Red Stompy: Share Mountains, Simian Spirit Guide, some sideboard cards. ~8 cards overlap but very budget-friendly total.\n\nRecommendation: Dimir Tempo + Doomsday gives the most overlap and covers both fair and combo strategies for tournament flexibility."},
    {"instruction": "What Legacy cards are most likely to hold value if I quit the game?", "input": "", "output": "Ranked by resale confidence: 1) Reserved List duals: 95-100% resale. Underground Sea, Volcanic Island, etc. always have buyers and appreciate over time. 2) Reserved List combo pieces: 90-95% resale. Lion's Eye Diamond, Mox Diamond, City of Traitors. 3) Force of Will: 85-90% resale. High demand, occasional reprints cause temporary dips but always recovers. 4) Fetchlands: 80-90% resale. Used in every format, reprints cause dips but demand is permanent. 5) Modern Horizons mythics: 70-85% resale. Murktide, Bowmasters, Solitude hold value but risk future reprints. 6) Standard/Commander staples that see Legacy play: 60-80% resale. Prices are more volatile. If resale value matters, prioritize Reserved List first, then format-defining staples."},
]

# Write all
categories = [
    ("rules_qa.jsonl", rules),
    ("card_evaluation.jsonl", card_eval),
    ("deckbuilding_rationale.jsonl", deckbuilding),
    ("deck_analysis.jsonl", deck_analysis),
    ("conversation_flow.jsonl", conversation),
    ("board_state_analysis.jsonl", board_state),
    ("budget_substitutions.jsonl", budget),
]

for filename, data in categories:
    outpath = os.path.join(os.path.dirname(__file__), "..", "data", "training", filename)
    with open(outpath, "a", encoding="utf-8") as f:
        for pair in data:
            f.write(json.dumps(pair, ensure_ascii=False) + "\n")
    print(f"Appended {len(data)} pairs to {filename}")
