"""Generate conversation flow training data - Batch 2 (append)."""
import json
import os

pairs = [
    # === DECK BUILDING CONVERSATIONS (continued) ===
    {"instruction": "I want to build a deck around Urza's Saga. What are my options?", "input": "", "output": "Urza's Saga is one of the most versatile cards in Legacy. It creates Construct tokens that grow based on artifact count and tutors for 0-1 cost artifacts. Here are your options:\n\n1) Affinity/8-Cast: Full artifact deck with Thought Monitor, Emry, and maximum Construct sizes. Tier 2 at 2.4%.\n2) Painter: Saga tutors Grindstone (the combo piece) and makes Constructs for backup pressure. Tier 2 at 4.1%.\n3) Mystic Forge Combo: Saga finds key combo pieces like Sensei's Divining Top (wait, banned). Instead finds Grinding Station or other 1-drops.\n4) Death and Taxes: Some D&T builds splash Saga to tutor Pithing Needle, Retrofitter Foundry, or Shadowspear.\n5) Grixis/UR Control: Saga as a value land in a fair blue shell.\n\nSaga is in 22% of Legacy decks overall. What colors and strategy interest you?"},
    {"instruction": "I keep losing to graveyard decks. How do I fix my sideboard?", "input": "", "output": "The first question is: which graveyard decks are you losing to? They require different hate:\n\nVs Reanimator: Leyline of the Void (best, free), Surgical Extraction (targets specific creatures), Containment Priest (stops creatures entering without being cast).\n\nVs Dredge: Leyline of the Void (shuts off dredge entirely), Rest in Peace (same effect but costs 2 mana).\n\nVs Oops All Spells: Leyline of the Void (prevents the combo), Surgical Extraction (exile Thassa's Oracle).\n\nVs Doomsday: Surgical Extraction (exile Oracle or Doomsday from graveyard), Stifle (counter Oracle ETB).\n\nThe universal solution is 4 Leyline of the Void - it covers all of the above. If your deck uses its own graveyard (Murktide, delve), use Surgical Extraction or Endurance instead since Leyline would hurt you too. What deck are you playing?"},
    {"instruction": "My friend says I should play 4 Ponder in my Storm deck but I think Preordain is better there. Who is right?", "input": "", "output": "Your friend is right, and here is why: Ponder is better than Preordain in Storm for two critical reasons.\n\n1) Ponder sees 3 cards and can shuffle if all 3 are bad. In Storm, you are looking for very specific cards (Lion's Eye Diamond, Burning Wish, Dark Ritual) and the ability to shuffle away 3 blanks is much more valuable than Preordain's scry 2 draw 1.\n\n2) Ponder with a fetchland effectively sees 4 cards (3 from Ponder plus a fresh draw after shuffling). Storm needs to find combo pieces fast, and seeing more cards per cantrip is paramount.\n\n3) Ponder also lets you stack the top of your library for Ad Nauseam (you want low-cost cards on top to draw more). Preordain cannot stack the deck.\n\nThe one case for Preordain: if you have no fetchlands (some budget builds), Preordain's scry is better than Ponder's 3-card look without shuffle."},
    {"instruction": "Can you help me tune my Death and Taxes list for a combo-heavy meta?", "input": "", "output": "Absolutely. D&T's main weakness is combo, but you can shore it up significantly:\n\nMaindeck changes:\n- Run 4 Thalia, Guardian of Thraben (taxes every ritual and cantrip by 1)\n- Add 2 Spirit of the Labyrinth (shuts off Brainstorm and cantrip chains)\n- Consider 1-2 Ethersworn Canonist main (1 noncreature spell per turn wrecks Storm)\n- Ensure 4 Rishadan Port (deny mana so combo cannot reach critical mana thresholds)\n\nSideboard:\n- 3 Deafening Silence (1 noncreature spell per turn, devastating vs Storm and Oops)\n- 2 Mindbreak Trap (free counter when they cast 3+ spells)\n- 2 Containment Priest (stops Show and Tell, Reanimate, Sneak Attack)\n- 1 Surgical Extraction (targets specific combo pieces)\n\nThe goal is not to out-combo them but to slow them down enough that your creatures kill them first. What combo decks are you specifically facing?"},
    {"instruction": "I opened a Volcanic Island in a collection I bought. What deck should I build around it?", "input": "", "output": "A Volcanic Island opens up several great deck options:\n\n1) Izzet Delver (needs 2-3 Volcanic Island): Your opened copy is a great start. Add Delver, Murktide, Lightning Bolt, cantrips, Force of Will, Daze. Budget build possible with 1 real Volc + 1-2 Steam Vents. Cost to complete: $1500-2500.\n\n2) Sneak and Show (needs 1-2 Volcanic Island): Volcanic provides the UR base for Show and Tell + Sneak Attack. Single Volcanic is enough with Ancient Tomb and Lotus Petal handling the rest. Cost to complete: $1500-2000.\n\n3) Jeskai Stoneblade (needs 1-2 Volcanic Island + 2-3 Tundra): More expensive due to needing Tundra as well. Cost to complete: $2500-4000.\n\n4) Ruby Storm (needs 0-1 Volcanic Island): Mostly mono-red but a Volcanic Island enables blue sideboard cards. Cheapest option at $400-700 to complete.\n\nVolcanic Island is $500-700, so you have a $500+ head start. Which style interests you?"},
    {"instruction": "I am going to my first Legacy tournament this weekend. What should I know?", "input": "", "output": "Welcome to competitive Legacy! Here are the most important things:\n\n1) Know the top 5 decks: Dimir Tempo (14.6%), Ocelot Pride (8.5%), Oops (8.2%), Sneak and Show (6.7%), Izzet Delver (4.3%). You WILL face at least 2-3 of these.\n\n2) Mulligan decisions: Legacy mulligans are more punishing than other formats. Know what a keepable hand looks like for your deck and what you need to beat the popular matchups.\n\n3) Sideboard plan: Write out your sideboard plan for each top 5 matchup BEFORE the tournament. Know what comes in and what goes out.\n\n4) Play around Force of Will: 45% of decks play it. Do not run your best spell into open blue mana unless you have a backup plan.\n\n5) Watch for Leyline of the Void: 36% of decks start with it in the sideboard. If you are on a graveyard deck, assume it exists.\n\n6) Call a judge if unsure: Legacy has complex interactions. Judges are there to help. Never guess on a rules question.\n\nWhat deck are you planning to play?"},
    {"instruction": "I played against Dimir Tempo three rounds in a row and lost every time. What am I doing wrong?", "input": "", "output": "Dimir Tempo is the most played deck for a reason, and losing to it is common. Let me diagnose the problem:\n\n1) Are you playing into their Daze? If you tap out on turns 1-2, Daze punishes you for free. Play around it by making land drops and casting spells when you can pay the extra 1.\n\n2) Are you feeding their Bowmasters? Every cantrip you cast past the first draw triggers Bowmasters. If they have BB open, consider whether that Brainstorm is worth giving them a 1/1 and a ping.\n\n3) Are you using your removal correctly? Do not kill the Bowmasters 1/1 token - kill the Bowmasters itself. The Amass army grows with each trigger.\n\n4) Are you sideboarding correctly? Pyroblast kills Murktide Regent for 1 mana. Toxic Deluge clears their board. Hydroblast counters their spells.\n\n5) Are you on the right deck? Some decks simply have a bad Dimir Tempo matchup. If your deck folds to Thoughtseize + Force + Daze, consider switching to something that goes bigger (Lands, Sneak and Show).\n\nWhat deck are you playing? I can give specific advice."},

    # === CARD DISCUSSION CONVERSATIONS ===
    {"instruction": "Someone told me Brainstorm is bad and I should play Preordain instead. Are they right?", "input": "", "output": "They are almost certainly wrong, assuming you are playing fetchlands. Brainstorm + fetchland is the most powerful cantrip interaction in Magic's history. Here is why:\n\nBrainstorm alone: Draw 3, put back 2. Net effect: you see 3 new cards but keep the same hand size. Mediocre.\n\nBrainstorm + fetchland: Draw 3, put 2 bad cards on top, crack fetchland, shuffle them away. Net effect: you drew the best of 4 cards and permanently removed 2 bad cards from the top of your deck. Exceptional.\n\nPreordain: Scry 2 (look at 2 cards, put bad ones on bottom), draw 1. You see 3 cards total but can only bottom 2 of them. No shuffle synergy.\n\nThe ONLY case where Preordain is better: if you play zero fetchlands, no shuffle effects, and no library manipulation. In that case, Brainstorm's 2 cards put back on top are dead draws. But in Legacy, every blue deck plays 6-8 fetchlands, making this scenario irrelevant.\n\nBrainstorm is the best cantrip in Legacy. Anyone saying otherwise does not understand the fetchland interaction."},
    {"instruction": "Is Wasteland overpowered? Should it be banned?", "input": "", "output": "Wasteland is extremely powerful but should NOT be banned. Here is why it is actually healthy for the format:\n\n1) Wasteland keeps greedy mana bases in check. Without it, every deck would play 4+ colors with zero deckbuilding cost. Wasteland forces you to run basic lands, which is a real constraint.\n\n2) Wasteland enables non-blue strategies. Death and Taxes, Eldrazi, and Red Stompy all rely on mana denial to compete with cantrip-heavy blue decks. Without Wasteland, blue would be even more dominant.\n\n3) Wasteland is answerable. You can play around it by fetching basics, running extra lands, or using mana creatures. Smart deckbuilding and play can minimize Wasteland's impact.\n\n4) Wasteland enables interesting decisions. When to use it, what to target, and how to sequence your own lands around opponent's Wasteland are some of Legacy's most skill-testing decisions.\n\n48% of decks play Wasteland. If it were banned, the entire format would need to be rebalanced. It is a format pillar, not a problem card."},
    {"instruction": "Why was Deathrite Shaman banned? It seems like just a mana dork.", "input": "", "output": "Deathrite Shaman was far more than a mana dork. At the time of its ban in July 2018, it was in 57% of Legacy decks. Here is why it was broken:\n\n1) It was a 1-mana creature that produced any color of mana by exiling lands from graveyards. In a format full of fetchlands, there were always lands to exile. This enabled effortless 3-4 color decks.\n\n2) It gained 2 life by exiling instants/sorceries (relevant vs Burn and aggro).\n\n3) It drained 2 life by exiling creatures (a win condition in grindy games and graveyard hate).\n\n4) It had no deckbuilding cost - any deck with B or G could play it.\n\nThe result: 4-color midrange piles (Czech Pile) dominated the format because DRS fixed mana perfectly while providing utility. There was no reason NOT to play it. After the ban, the format diversified dramatically as 2-color tempo decks returned and mana bases required real choices again."},
    {"instruction": "What is the deal with the Reserved List? Why can't they just reprint dual lands?", "input": "", "output": "The Reserved List is a promise Wizards of the Coast made in 1996 never to reprint certain cards. It was created after the Chronicles set reprinted many Legends cards, tanking their secondary market value and angering collectors.\n\nThe Reserved List includes all original dual lands (Underground Sea, Volcanic Island, etc.), Black Lotus, the Moxen, and hundreds of other old cards. Wizards has stated repeatedly that they will honor this commitment indefinitely.\n\nFor Legacy, this means: dual lands will never become cheaper through reprints. The supply is fixed and decreasing (cards get lost, damaged, or locked in collections). This is the primary barrier to Legacy accessibility and why the format is expensive.\n\nThe community is split: competitive players want abolition of the Reserved List for accessibility. Collectors and investors want it maintained to protect their holdings. Wizards treats it as legally binding regardless of community opinion.\n\nPractical advice: buy duals if you can afford them (they appreciate in value), use shock lands if you cannot, and advocate for proxy-friendly events at your local store."},

    # === SPECIFIC DECK CONSULTATION ===
    {"instruction": "I want to build Lands but The Tabernacle at Pendrell Vale costs $5000. Is the deck playable without it?", "input": "", "output": "Lands is playable without Tabernacle but significantly weakened against creature-heavy strategies. Here is the honest assessment:\n\nWith Tabernacle: You have a land you can Crop Rotation for at instant speed that clears small creature boards (Elves, Goblins, D&T tokens) for free. It wins matchups single-handedly.\n\nWithout Tabernacle: You lose your best tool against go-wide creature strategies. Replacements like Pendrell Mists (4 mana enchantment) or Engineered Plague are much slower and less effective.\n\nThe practical path:\n1) Build Lands without Tabernacle (~$3000-4000 with other Reserved List cards).\n2) Play it and learn the deck. Tabernacle matters in maybe 20-30% of matchups.\n3) Save for Tabernacle over time. It holds/appreciates in value.\n4) In the meantime, use Crop Rotation to find Bojuka Bog, Karakas, or Ghost Quarter as utility lands instead.\n\nAlternatively, consider Selesnya Depths ($800-1200) which uses the same Dark Depths combo in a creature-based shell without needing Tabernacle at all."},
    {"instruction": "Can you design a Legacy deck that beats both Dimir Tempo and Oops All Spells?", "input": "", "output": "That is a tough ask because those two decks require very different answers. Dimir Tempo is a fair deck that grinds; Oops is an all-in combo. Here are decks that beat both:\n\n1) Sneak and Show: Favorable vs Dimir Tempo (Emrakul dodges their removal, annihilator is devastating). Against Oops, you race with Force of Will backup. Post-board, Leyline of the Void handles Oops while Pyroblast handles Dimir. Win rate: ~55-60% vs both.\n\n2) Lands: Favorable vs Dimir Tempo (Wasteland-proof, Maze of Ith, Punishing Fire). Against Oops, you rely on Bojuka Bog and sideboard Surgical Extraction. The Oops matchup is worse (maybe 40%), but Dimir is great (65%).\n\n3) Painter: Fast combo races Oops or disrupts with Chalice. Against Dimir, Red Elemental Blast effects with Painter naming blue are unconditional counters. Win rate: ~55% vs both.\n\nMy recommendation: Sneak and Show for the most balanced matchup spread against both. Want me to build the list?"},
    {"instruction": "I play Dimir Tempo but I want to make it more unique. What spicy tech could I add?", "input": "", "output": "Love the brewer's mindset! Here are some spicy inclusions that most Dimir Tempo players do not run:\n\n1) Subtlety (pitch for UU alternative): Puts a creature or planeswalker on top of their library instead of countering it. Surprise blowout when they tap out for a big threat.\n\n2) Grief (wait, banned) - never mind. How about Unmask? Free hand disruption by exiling a black card. Worse than Thoughtseize most of the time but free is free.\n\n3) Spell Snare: Counters 2-mana spells for U. Hits Bowmasters, Stoneforge Mystic, Counterbalance, Hymn to Tourach, Painter's Servant. Very meta-dependent.\n\n4) Vendilion Clique: Flash 3/1 flyer that sees opponent's hand and can strip a card. Provides information for your countermagic decisions.\n\n5) Brazen Borrower: Flash 3/1 flyer that bounces a permanent first. Handles resolved threats that Daze and Force missed.\n\n6) Bitterblossom: Grindy enchantment that creates a 1/1 flyer every turn. Excellent in the mirror and against control. The life loss is manageable in tempo.\n\nThe key to spicy tech: it should not weaken your core matchups. Test each addition against Ocelot Pride, Oops, and Sneak and Show before committing. What sounds interesting?"},
]

outpath = os.path.join(os.path.dirname(__file__), "..", "data", "training", "conversation_flow.jsonl")
with open(outpath, "a", encoding="utf-8") as f:
    for pair in pairs:
        f.write(json.dumps(pair, ensure_ascii=False) + "\n")

print(f"Appended {len(pairs)} pairs to {outpath}")
