"""Generate rules Q&A training data - Batch 3 (append). Focus on more Legacy interactions."""
import json
import os

pairs = [
    # === TURN STRUCTURE AND PRIORITY ===
    {"instruction": "What are the steps of a turn in Magic?", "input": "", "output": "A turn consists of these phases and steps in order: 1) Beginning Phase: Untap step (untap permanents, no priority), Upkeep step (triggers resolve, priority), Draw step (draw a card, priority). 2) Pre-combat Main Phase: Play lands, cast spells. 3) Combat Phase: Beginning of combat, Declare attackers, Declare blockers, Combat damage, End of combat. 4) Post-combat Main Phase: Play lands if you have not yet, cast spells. 5) Ending Phase: End step (end-of-turn triggers), Cleanup step (discard to hand size, damage wears off). Players get priority at each step except untap and cleanup (unless triggers happen)."},
    {"instruction": "When exactly does a miracle trigger happen?", "input": "", "output": "Miracle triggers when you draw a card IF it is the first card you draw in a turn. As soon as you draw the card and see it, you must immediately reveal it if you want to use miracle. The miracle trigger goes on the stack. You can respond to the trigger (including Brainstorming to put it back). When the trigger resolves, you may cast the spell for its miracle cost. If you put the card into your hand with other cards before revealing it, you have missed the miracle trigger. In Legacy, this is most relevant with Terminus (miracle cost W for a board wipe) and Entreat the Angels."},
    {"instruction": "Can I cast sorceries during my opponent's turn?", "input": "", "output": "Normally no - sorceries can only be cast during your own main phase when the stack is empty. However, some effects let you cast sorceries at other times: Omniscience lets you cast spells without paying mana costs (but does not change timing restrictions by itself). Teferi, Time Raveler lets you cast spells any time you could cast an instant. Quicken (rare in Legacy) gives the next sorcery flash. Cascade casts the cascaded spell immediately regardless of normal timing. Burning Wish finds a sorcery but you still cast it normally (during your turn)."},
    {"instruction": "What happens if two triggered abilities trigger at the same time?", "input": "", "output": "If multiple triggered abilities trigger simultaneously, the active player (whose turn it is) puts their triggers on the stack first in any order they choose, then the non-active player puts theirs on top in any order they choose. Since the stack resolves last-in-first-out, the non-active player's triggers resolve first. This matters in Legacy with simultaneous ETBs (Show and Tell putting two permanents in play) and combat triggers (annihilator and other attack triggers)."},
    {"instruction": "What is split second and how does it work?", "input": "", "output": "Split second means that while the spell is on the stack, players cannot cast spells or activate abilities that are not mana abilities. You can still trigger abilities (triggers still go on the stack) and activate mana abilities. In Legacy, the most relevant split second cards are Krosan Grip (destroys artifact or enchantment), Sudden Shock (2 damage), and Angel's Grace (you cannot lose this turn). Split second stops Force of Will, Brainstorm, and most countermagic from being cast in response. However, Stifle-like effects that are already on the stack can still counter triggered abilities."},
    {"instruction": "Can my opponent respond to me cracking a fetchland?", "input": "", "output": "Yes. Activating a fetchland (pay 1 life, sacrifice it) puts an activated ability on the stack. Your opponent gets priority before the search resolves. They can cast instants, activate abilities, or even Stifle the fetchland activation. Common responses: Orcish Bowmasters (flash in and ping you while you search), Vendilion Clique (flash in to check your hand before you shuffle), or Stifle (counter the search - you already sacrificed the land and paid life but get nothing). This is why timing your fetchland cracks matters in Legacy."},
    {"instruction": "What is the difference between a cost and an effect?", "input": "", "output": "Costs are paid when you cast a spell or activate an ability. They appear before the colon in activated abilities and in the mana cost or additional costs of spells. Costs cannot be responded to and cannot be prevented. Effects are what happen when the spell resolves or the ability resolves. Effects can be countered (by countering the spell/ability). Example: Lion's Eye Diamond - sacrificing it and discarding your hand is a COST (cannot be prevented). The 3 mana is the EFFECT. Example: Wasteland - tapping and sacrificing is the COST. Destroying a land is the EFFECT (can be Stifled)."},
    {"instruction": "How do replacement effects work?", "input": "", "output": "Replacement effects modify how an event happens rather than triggering after it. They use the words 'instead' or 'as.' Example: Leyline of the Void says 'if a card would be put into an opponent's graveyard, exile it instead.' The card never touches the graveyard - the exile replaces the graveyard movement. Dredge is also a replacement effect: instead of drawing, you mill and return the dredge card. If multiple replacement effects could apply to the same event, the affected player chooses which one to apply. Replacement effects cannot be responded to since they modify the event as it happens."},
    {"instruction": "What happens when a spell is countered?", "input": "", "output": "When a spell is countered, it is put into its owner's graveyard (not resolved). None of its effects happen. However, costs that were already paid are not refunded - mana is spent, cards are exiled for Force of Will, life is paid, artifacts are sacrificed for Lion's Eye Diamond. The spell simply fails to resolve. Exception: if a spell says 'this spell can't be countered' (like Abrupt Decay, Supreme Verdict, or Cavern of Souls creatures), counter spells still target it but fail to counter on resolution. The counter spell is still cast and counted for storm."},
    {"instruction": "Can I cast a spell with no legal targets?", "input": "", "output": "If a spell requires targets and there are no legal targets, you cannot cast it at all. You cannot cast Swords to Plowshares if there are no creatures on the battlefield. However, if a spell has targets but also has modes or effects that do not require targets, it can sometimes be cast even if one target is missing. For modal spells, you choose modes on casting and only need legal targets for the chosen modes. If a spell's only target becomes illegal before resolution (the creature is sacrificed in response), the spell fizzles and is countered by game rules."},

    # === SPECIFIC CARD INTERACTIONS (DEEP CUTS) ===
    {"instruction": "My opponent has Narset, Parter of Veils in play. Can I still cast Brainstorm?", "input": "", "output": "You can cast Brainstorm, but Narset says each opponent cannot draw more than one card each turn. Brainstorm says 'draw three cards.' With Narset in play, you draw 1 card (the first draw of the turn) and the other 2 draws are replaced with nothing. You still put 2 cards back on top. Net result: you draw 1 card and put 2 from your hand on top of your library. This is TERRIBLE - you end up with 1 fewer card in hand. Narset is one of the strongest anti-cantrip cards in Legacy."},
    {"instruction": "How does Surgical Extraction interact with split cards?", "input": "", "output": "Surgical Extraction exiles all copies of the named card from the opponent's hand, graveyard, and library. For split cards (like Fire // Ice), you choose one half when naming. However, since both halves are on the same physical card, exiling Fire also exiles Ice (they are one card). So Surgical Extraction on either half removes all copies of the complete split card. This is relevant for cards like Wear // Tear or Commit // Memory."},
    {"instruction": "If I Reanimate my opponent's creature, who controls it?", "input": "", "output": "You control it. Reanimate says 'put target creature card from a graveyard onto the battlefield under your control.' You can target creatures in any graveyard, including your opponent's. You lose life equal to that creature's mana value and the creature enters under your control. This is a common play in the Reanimator mirror: Reanimate your opponent's Griselbrand after it dies. The creature remembers nothing about its previous controller."},
    {"instruction": "Can Ensnaring Bridge stop Marit Lage from attacking?", "input": "", "output": "Yes, if you have 0 or very few cards in hand. Ensnaring Bridge prevents creatures with power greater than the number of cards in your hand from attacking. Marit Lage is a 20/20, so you need fewer than 20 cards in hand (always true). Wait - Ensnaring Bridge says 'greater than the number of cards in your hand.' With 0 cards in hand, creatures with power greater than 0 cannot attack. Marit Lage has power 20, which is greater than 0, so it CANNOT attack. Ensnaring Bridge with an empty hand stops Marit Lage. This is why Bridge is played in prison decks."},
    {"instruction": "Does Collector Ouphe stop Aether Vial?", "input": "", "output": "Yes. Collector Ouphe says activated abilities of artifacts cannot be activated. Aether Vial's ability to put a creature into play is an activated ability of an artifact. With Ouphe in play, Vial cannot be activated. This also stops Vial from gaining charge counters at your upkeep since... wait, the charge counter ability is a triggered ability, not activated. Ouphe stops the TAP ability (putting creatures in) but NOT the upkeep counter trigger. So Vial still gains counters but cannot be used to put creatures in play. Eventually the counters become too high to be useful."},
    {"instruction": "What happens if I cast Show and Tell and both players put in a planeswalker?", "input": "", "output": "Both planeswalkers enter the battlefield simultaneously. They are both in play. Neither player gets to activate their planeswalker first - the active player gets priority after Show and Tell finishes resolving. The active player can then activate their planeswalker (one loyalty ability per turn). The non-active player must wait until they get priority (typically their own turn) to activate theirs. If both planeswalkers have the same name, the legend rule applies: each player chooses one of their own to keep and puts the rest into the graveyard. But if they are different planeswalkers, both stay."},
    {"instruction": "How does Notion Thief interact with Brainstorm?", "input": "", "output": "Notion Thief says: if an opponent would draw a card except the first one they draw in each of their draw steps, instead that player skips that draw and you draw a card. When your opponent casts Brainstorm (draw 3 cards), the first draw happens normally, but the second and third draws are replaced: your opponent skips them and YOU draw 2 cards instead. Your opponent then puts 2 cards from their hand on top of their library as normal. Net result: you drew 2 extra cards, opponent drew 1 and put 2 back (losing 1 card from hand). Devastating."},
    {"instruction": "Can I use Crop Rotation at instant speed to find Dark Depths?", "input": "", "output": "Yes. Crop Rotation is an instant that sacrifices a land and searches for any land card. At instant speed, you can find Dark Depths (or Thespian's Stage, or any utility land). Common play: in response to opponent's attack, Crop Rotation sacrificing a land to find Maze of Ith and fog their attacker. Or at end of opponent's turn, Crop Rotation for Thespian's Stage, then on your turn copy Dark Depths for Marit Lage. Crop Rotation is one of the most versatile tutors in Legacy because lands are so powerful."},
    {"instruction": "Does Rest in Peace stop Dredge entirely?", "input": "", "output": "Not entirely, but it is devastating. Rest in Peace exiles cards that would go to the graveyard instead. This means: milled cards go to exile (no dredge targets), creatures that die go to exile (no Ichorid recursion), and Dread Return cannot be flashed back from exile. However, cards already in the graveyard when Rest in Peace resolves ALSO get exiled. The Dredge player cannot dredge because there are no cards with dredge in their graveyard (they were all exiled). The mechanic itself still works - they can replace a draw with dredge if they somehow get a dredge card in their graveyard, but Rest in Peace prevents that from happening. Dredge needs to destroy Rest in Peace or lose."},

    # === LAYERS AND INTERACTIONS ===
    {"instruction": "How does Blood Moon affect fetchlands already in play?", "input": "", "output": "Blood Moon changes all nonbasic lands into Mountains. They lose all their original abilities and land types and become Mountains. Fetchlands already in play become Mountains - they cannot be activated to search because they no longer have that ability. However, they CAN still tap for R (red mana) since they are Mountains. If Blood Moon is later removed, the fetchlands regain their original abilities and can be cracked normally. This is why it is critical to crack fetchlands for basic lands BEFORE Blood Moon resolves if you suspect it."},
    {"instruction": "If my opponent plays Chalice of the Void on 1, can I cast Engineered Explosives for X=1 to destroy it?", "input": "", "output": "This is tricky. If you cast Engineered Explosives with X=1, it has mana value 1 on the stack (X is 1). Chalice on 1 counters spells with mana value 1. So your EE gets countered. However, if you cast EE with X=0 (paying 0 mana), it has mana value 0 on the stack and enters with 0 charge counters. Chalice on 1 does not counter it. Then activate EE to destroy all nonland permanents with mana value 0. But wait - Chalice of the Void on the battlefield has mana value 0 (XX with X=0 on the battlefield). So EE on 0 destroys Chalice on 1! This is one of the most important rules interactions in Legacy."},
    {"instruction": "How do Flickerwisp and Aether Vial interact?", "input": "", "output": "Aether Vial with 3 charge counters can put Flickerwisp (mana value 3) into play at instant speed. Flickerwisp has an ETB that exiles target permanent and returns it at the beginning of the next end step. Common plays: 1) During opponent's end step, Vial in Flickerwisp to exile their best permanent. It returns during YOUR end step, effectively removing it for a full turn. 2) Vial in Flickerwisp during combat to exile an attacker (it returns tapped and without dealing damage). 3) Flicker your own Stoneforge Mystic to get another equipment tutor. The instant-speed deployment via Vial makes Flickerwisp extremely versatile."},
    {"instruction": "What happens if I Swords to Plowshares a creature with an ETB trigger on the stack?", "input": "", "output": "The ETB trigger is already on the stack and will still resolve even though the creature is no longer on the battlefield. In Magic, triggered abilities exist independently of their source once triggered. So if your opponent plays Thassa's Oracle with 0 cards in library, and you Swords to Plowshares Oracle in response to the ETB trigger, the Oracle is exiled and gains life for your opponent BUT the trigger still resolves and checks if devotion to blue is greater than or equal to cards in library. If the Doomsday player has 0 cards in library, they still win even though Oracle is gone. To stop Oracle, you need to counter the spell or the trigger, not remove the creature."},
    {"instruction": "Can I sacrifice a creature to multiple effects?", "input": "", "output": "No. Sacrificing is a cost, and you can only sacrifice a creature once. Once it leaves the battlefield, it no longer exists there to be sacrificed again. If you sacrifice a creature to activate Goblin Bombardment (deal 1 damage), you cannot also sacrifice it to Cabal Therapy (name a card). However, you CAN respond to a sacrifice ability by sacrificing the same creature to a different effect before the first one resolves. For example: opponent targets your creature with Diabolic Edict (you must sacrifice a creature). In response, you sacrifice it to Goblin Bombardment to get value before losing it. You still need to sacrifice another creature to Edict when it resolves, but at least you got Bombardment value."},
]

outpath = os.path.join(os.path.dirname(__file__), "..", "data", "training", "rules_qa.jsonl")
with open(outpath, "a", encoding="utf-8") as f:
    for pair in pairs:
        f.write(json.dumps(pair, ensure_ascii=False) + "\n")

print(f"Appended {len(pairs)} pairs to {outpath}")
