"""Generate training data - Final push batches. Get to 1500."""
import json
import os

# Each category gets a large batch of new unique pairs
rules = [
    {"instruction": "How does morph work in Legacy?", "input": "", "output": "Morph lets you cast a card face-down as a 2/2 creature for 3 generic mana. At any time you have priority, you may turn it face up by paying its morph cost. Turning face up does not use the stack and cannot be responded to. In Legacy, morph is rarely seen. The most relevant morph cards are Exalted Angel (old Legacy card) and occasionally Willbender (redirect target). The face-down 2/2 dies to basically everything in Legacy, making morph strategies unviable in a format this fast."},
    {"instruction": "What is the interaction between Containment Priest and Collected Company?", "input": "", "output": "Containment Priest says if a nontoken creature would enter the battlefield and it was not cast, exile it instead. Collected Company puts creatures from the top of your library onto the battlefield WITHOUT casting them. With Priest in play, creatures CoCo tries to put in play are exiled instead. However, Priest only stops OPPONENT's creatures if you control the Priest. If your OPPONENT has Priest and YOU cast CoCo, your creatures are exiled. If YOU control Priest and cast CoCo, Priest affects your own creatures too - they get exiled. Priest does not discriminate by controller."},
    {"instruction": "What is the interaction between Blood Moon and fetch lands in the graveyard?", "input": "", "output": "Blood Moon only affects lands on the battlefield. Fetchlands in the graveyard are not affected - they retain their original characteristics. This matters for Deathrite Shaman (banned but illustrative): DRS can exile a fetchland from a graveyard regardless of whether Blood Moon is in play because Blood Moon does not change cards in other zones. Similarly, Life from the Loam can return fetchlands from the graveyard to hand, and they are normal fetchlands when played (though they immediately become Mountains under Moon)."},
    {"instruction": "Can I use Stifle on a split second spell?", "input": "", "output": "Split second prevents players from casting spells or activating abilities while it is on the stack. However, Stifle counters activated or triggered ABILITIES, not spells. If the split second spell has a triggered ability (rare), you could not Stifle it because you cannot cast Stifle (a spell) while split second is on the stack. If a different triggered ability triggers while split second is on the stack, you still cannot cast Stifle to counter it. Split second effectively shuts off Stifle entirely while it is on the stack. You can only use mana abilities during split second."},
    {"instruction": "How does Chains of Mephistopheles work?", "input": "", "output": "Chains of Mephistopheles is one of the most confusing cards in Legacy. It creates a replacement effect: if a player would draw a card except the first in their draw step, they discard a card instead. If they cannot discard (empty hand), they mill a card instead of drawing. The effect: Brainstorm with Chains = draw 1 (normal first draw of step), then for draws 2 and 3, you discard 2 cards then draw 2. Net: you see new cards but at parity or card disadvantage. Cantrips become terrible. Chains is extremely rare (Reserved List, expensive) but devastates cantrip-heavy decks. It sees play in some Mono Black Pox lists."},
    {"instruction": "What happens when two replacement effects try to replace the same event?", "input": "", "output": "When multiple replacement effects could apply to the same event, the affected player or controller of the affected permanent chooses which replacement to apply first. After one applies, check if the other still applies to the modified event. Example: with both Leyline of the Void and Dredge in play, when you would draw: Dredge wants to replace the draw with mill+return. Leyline wants to exile cards that go to graveyard. You choose: dredge (mill 6, but each milled card is exiled by Leyline instead of going to graveyard). You get the dredge card back to hand, but the milled cards go to exile. Both effects apply."},
    {"instruction": "Can I sacrifice a creature with 0 toughness?", "input": "", "output": "It depends on timing. State-based actions (including destroying a creature with 0 toughness) are checked whenever a player would receive priority. If a creature has 0 toughness and you have priority, it dies before you can sacrifice it. However, if an effect gives a creature 0 toughness AND you can sacrifice in response (before SBAs are checked), you can sacrifice it. Example: Toxic Deluge gives -3/-3 to your 2/2. Before SBAs check, the 2/2 has -1/-1 (0 toughness). You cannot sacrifice it because Deluge's resolution is still happening and you do not have priority yet. Once Deluge finishes resolving, SBAs kill the 0-toughness creature before you get priority. To sacrifice, you need to do it BEFORE the -X/-X effect resolves."},
    {"instruction": "How does Phyrexian mana work?", "input": "", "output": "Phyrexian mana symbols (circle with a P) can be paid with either 1 mana of the appropriate color OR 2 life. Surgical Extraction costs B/P - pay B or 2 life. Gitaxian Probe cost U/P - pay U or 2 life (now banned). Mental Misstep cost U/P - pay U or 2 life (now banned). The life payment means any color deck can play these cards. The mana value includes Phyrexian mana at full value: Surgical Extraction has MV 1 (one B/P symbol). Dismember costs 1 B/P B/P and has MV 3, even if you pay 1 mana + 4 life. Chalice of the Void on 1 counters Surgical Extraction regardless of how you paid."},
    {"instruction": "What is Conspicuous Snoop and is it relevant in Legacy?", "input": "", "output": "Conspicuous Snoop is a 2-mana Goblin that lets you look at the top card of your library and cast Goblin spells from the top. If the top card is a Goblin, Snoop gains all activated abilities of that card. With Kiki-Jiki, Mirror Breaker on top (a Goblin with a copy ability), Snoop gains the ability to tap and create a copy of itself with haste. The copy also has the ability. Tap the copy to create another copy. Repeat infinitely for infinite hasty attackers. This combo occasionally appears in Legacy Goblins as an alternate win condition, though it is fragile and requires specific setup."},
    {"instruction": "How does provoke work and is it Legacy relevant?", "input": "", "output": "Provoke is a keyword that lets an attacking creature force a specific creature to block it. When a creature with provoke attacks, you may have target creature the defending player controls untap and block it if able. In Legacy, provoke is not competitively relevant. The only provoke card that occasionally sees play is Goblin Sharpshooter (which has a different but similarly aggressive ability). Provoke is from Legions block and has been replaced by more efficient combat manipulation in modern card design. Legacy combat is rarely about forced blocks - it is about evasion, removal, and combo kills."},
]

card_eval = [
    {"instruction": "Is Wasteland the best land in Legacy?", "input": "", "output": "It has the strongest argument. At 48% of decks - more than any other nonbasic - Wasteland defines Legacy deckbuilding. Every mana base must account for Wasteland: you run basics because of it, you fetch differently because of it, you choose your lands based on it. No other card shapes deckbuilding decisions across the entire format as broadly. The only competition is Underground Sea (the most played dual at 28%) or Polluted Delta (most played fetch at 38%). But neither of those forces opponents to change their entire mana base construction. Wasteland is format-defining in a way few cards have ever been."},
    {"instruction": "Is Leyline of the Void the most important sideboard card in Legacy?", "input": "", "output": "By the numbers, yes. Leyline is in 36% of Legacy sideboards, more than any other sideboard card. It shuts down: Reanimator (completely), Dredge (completely), Oops All Spells (mostly), Doomsday (partially), Storm with Past in Flames (partially), and Murktide Regent (reduces delve). The free starting cost (no mana if in opening hand) is critical because graveyard combo can win turn 1. No other sideboard card covers as many matchups as effectively for zero mana."},
    {"instruction": "Is Yorion, Sky Nomad worth the 80-card deckbuilding cost?", "input": "", "output": "In specific decks, yes. Yorion costs 3WU as a 4/5 flyer that blinks all nonland permanents you own on ETB. The 80-card requirement reduces consistency (40% chance of seeing a specific 4-of drops to 32%). But the guaranteed access to Yorion compensates: it is always available as a card in hand for 3 mana. In Death and Taxes, Yorion blinks Stoneforge Mystic (re-tutor equipment), Flickerwisp (re-exile a permanent), Solitude (re-exile a creature), and Bowmasters (re-trigger). The accumulated value from one Yorion ETB often wins the game. D&T's redundant hatebears minimize the consistency cost."},
    {"instruction": "Is Intuition Legacy-playable?", "input": "", "output": "Niche but yes. Intuition costs 2U and searches your library for 3 cards. Opponent chooses 1 for your hand, other 2 go to graveyard. In reanimator or graveyard strategies, this is a 3-mana tutor that puts cards exactly where you want them. Search for 3 copies of the same card: opponent gives you 1 and 2 go to graveyard, but you get what you wanted regardless. Or search for 3 different synergistic cards where any 1 in hand + 2 in graveyard is powerful. Intuition sees occasional play in combo and control decks that leverage the graveyard. At 3 mana and instant speed, it is reasonably costed for the effect."},
    {"instruction": "Is Carpet of Flowers Legacy-playable?", "input": "", "output": "As a sideboard card against blue decks, yes. Carpet of Flowers costs G and during each of your main phases, adds X mana of any color where X is the number of Islands opponent controls. Against Dimir Tempo with 3-4 Islands in play, Carpet generates 3-4 free mana every turn. This is absurd - it is better than any mana rock in the format against blue decks. It sees sideboard play in green-based decks (Maverick, Elves, Lands) specifically for blue matchups. Dead against non-blue decks, which is why it is sideboard only."},
    {"instruction": "Is Chalice of the Void or Blood Moon a better lock piece?", "input": "", "output": "Different roles. Chalice on 1 counters the most popular spells in Legacy (cantrips, removal, disruption) but does not affect anything costing 2+. Blood Moon changes all nonbasic lands to Mountains, potentially shutting off entire mana bases. Chalice is better against: cantrip-heavy decks (Delver, Control), combo relying on 1-mana spells (Storm rituals). Moon is better against: multi-color decks (cuts them off colors entirely), utility land decks (Lands, Urza's Saga strategies). Against mono-color or basic-heavy decks, Moon does nothing while Chalice always has targets. Most prison decks play both, but if forced to choose one, Chalice has broader applications."},
    {"instruction": "Is Submerge Legacy-playable?", "input": "", "output": "Niche sideboard card. Submerge costs 3UU normally or is free if an opponent controls a Forest and you control an Island. It puts target creature on top of its owner's library (not destroy, no graveyard). In matchups against green decks (Elves, Maverick, BUG), Submerge is free removal that wastes their draw step. It is not destroy (dodges indestructible) and not exile (they can reuse the creature, but it costs them a turn). It is too narrow for most sideboards but occasionally appears in blue decks facing green-heavy local metas."},
    {"instruction": "Is Predict Legacy-playable?", "input": "", "output": "Niche but clever. Predict costs 1U, names a card, mills the top card, and if you named correctly you draw 2. In Miracles with Sensei's Divining Top (now banned) or cantrip manipulation, you could stack your own library and Predict naming a card you knew was on top. Mill it (fueling the graveyard) and draw 2. Without Top, Predict requires Brainstorm to set up the top of your library. It sees occasional play in UW Control as a 2-mana instant-speed draw-2 that also fills the graveyard for escape or delve. Very fringe."},
    {"instruction": "Is Price of Progress the best Burn card in Legacy?", "input": "", "output": "It is the highest-ceiling burn spell. Lightning Bolt always deals 3. Price of Progress deals 2 per nonbasic land the opponent controls. Against Dimir Tempo with 4 nonbasics in play, Price deals 8 damage for 1R. Against Lands with 8+ nonbasics, it can deal 16+. Average damage across the Legacy field is roughly 6-8, making it the most efficient burn spell per mana. The floor is 0 (against mono-basic decks) but the ceiling is absurd. It is the reason budget mana bases with shock lands are especially punished - shocks take 2 life AND Price counts them as nonbasics."},
    {"instruction": "Is Snuff Out the best free black removal?", "input": "", "output": "It is the only free black removal (excluding evoke elementals). Snuff Out costs 4 life to cast for free if you control a Swamp (Underground Sea counts). It destroys a nonblack creature. Pros: 0 mana, instant speed, pairs well with Dimir Tempo's aggressive strategy. Cons: 4 life is steep against aggro (Burn, Ocelot), cannot hit black creatures (misses Bowmasters, the most played creature, which is black), and cannot hit Murktide (which is blue, not black, so Snuff DOES hit it). Snuff Out is in most Dimir Tempo lists as a 1-2 of for free removal alongside Fatal Push."},
]

deckbuilding = [
    {"instruction": "What cards should every blue Legacy sideboard include?", "input": "", "output": "The universal blue sideboard package: 2-3 Pyroblast (answers Murktide, counters Force, kills blue permanents), 2 Flusterstorm (anti-combo, counter wars), 2-3 Surgical Extraction (any deck can play it at 2 life, targets specific graveyard threats), 1-2 Hydroblast (anti-red in metas with Stompy or Burn). These 7-10 cards form the backbone that every blue sideboard should include. The remaining 5-8 slots are deck-specific: graveyard hate (Leyline), artifact hate (Force of Vigor), sweepers (Toxic Deluge), or matchup-specific cards."},
    {"instruction": "What is the optimal Force of Will count by archetype?", "input": "", "output": "4 copies: Tempo (Dimir, Delver), Combo (Storm, Show and Tell, Oops, Doomsday) - you NEED to see Force consistently. 3 copies: Control (some builds cut 1 Force for a more proactive card in grindy metas). 2 copies: Very rare, only if your deck has an alternative free interaction plan. 0 copies: Non-blue decks (D&T, Eldrazi, Red Stompy, Burn, Ocelot Pride). There is essentially no reason to play 1 Force - either you need the free interaction (play 4) or you do not (play 0). The 4-or-0 rule is one of Legacy's most consistent deckbuilding principles."},
    {"instruction": "When should I play Wasteland in my Legacy deck?", "input": "", "output": "Play 4 Wasteland when: your deck operates on 1-2 mana (Delver, D&T), you pair it with Daze for mana denial, or your strategy benefits from destroying specific lands (Lands uses it recursively). Play 2-3 Wasteland when: your deck needs some mana denial but also needs colored mana (some midrange builds). Play 0 Wasteland when: you need every land to produce colored mana (3+ color control), your spells cost 3+ mana consistently (you cannot afford to sacrifice a land), or your strategy does not benefit from mana denial (combo decks that need to reach their own mana threshold)."},
    {"instruction": "What makes a good 1-drop threat in Legacy?", "input": "", "output": "A Legacy-viable 1-drop creature needs at least one of: 1) Immediate value on ETB (Orcish Bowmasters triggers on opponent's draws). 2) Scaling power (Delver of Secrets flips to 3/2 flyer). 3) Mana generation (Heritage Druid taps 3 elves for GGG). 4) Disruption (Mother of Runes protects other creatures). 5) Evasion (Goblin Lackey puts goblins into play on combat damage). A 1-drop that is just a body (Savannah Lions, 2/1 for W) is not Legacy-playable because the body alone provides no strategic advantage. Every 1-drop slot is precious and must provide utility beyond just attacking."},
    {"instruction": "How do I decide between maindeck Surgical Extraction and Thoughtseize?", "input": "", "output": "Thoughtseize mainboard when: you want proactive disruption against all matchups (takes any nonland card), your deck is tempo or combo (stripping the best card before comboing or deploying threats). Surgical mainboard when: graveyard strategies are prevalent in your meta (15%+ graveyard combo), you want information AND disruption, or your deck is slower and the 2 life from Thoughtseize matters. Most Dimir Tempo plays 4 Thoughtseize main and 2 Surgical side. Some build play 1 Surgical main when graveyard combo exceeds 20% of their local meta. They serve different roles: Thoughtseize is broadest disruption, Surgical is targeted graveyard hate with information."},
    {"instruction": "How do I build a deck that beats both combo and fair strategies?", "input": "", "output": "The best approach is Dimir Tempo's model: 1) Play Force of Will and Daze (handles combo). 2) Play Thoughtseize (handles both by stripping the best card). 3) Play efficient threats that close games quickly (Murktide, Bowmasters). 4) Play Wasteland (handles fair decks' mana bases). 5) Play flexible removal (Snuff Out is free vs creatures). The key insight: you do not need dedicated combo hate or fair-deck hate. You need DISRUPTION that works against everything, plus a fast clock. Force of Will is the universal answer to combo. Wasteland + Daze is the universal answer to fair decks. Thoughtseize works against both. This is why Dimir Tempo is the most played deck."},
    {"instruction": "What is the role of each card in the Dimir Tempo core?", "input": "", "output": "4 Brainstorm: finds answers, sets up Delver flips, hides cards from Thoughtseize. 4 Ponder: additional card selection, shuffle away bad cards. 4 Force of Will: free countermagic, protects threats, stops combo. 4 Daze: free counter on turns 1-3, forces opponents to play off-curve. 4 Thoughtseize: proactive disruption, sees opponent's hand, strips best card. 4 Wasteland: mana denial, pairs with Daze, removes utility lands. 4 Orcish Bowmasters: punishes cantrips, flash threat, creates tokens. 3-4 Murktide Regent: primary finisher, large flyer, dodges Bolt. Every card serves a specific role in the tempo strategy. Removing any one of these 8 card types significantly weakens the deck."},
]

deck_analysis = [
    {"instruction": "What percentage of the Legacy metagame should I prepare for with my sideboard?", "input": "", "output": "Target the top 60-70% of the metagame with your sideboard. In the current meta: Dimir Tempo (14.6%), Ocelot Pride (8.5%), Oops (8.2%), Sneak and Show (6.7%), Izzet Delver (4.3%), Painter (4.1%), Lands (3.8%), TES (3.5%), Eldrazi (3.1%). That is 56.8% from just the top 9 decks. Have a sideboard plan for ALL of these. The remaining 43% is spread across 45+ archetypes at 1-2% each - you cannot prepare for all of them individually. Use versatile hate that covers multiple fringe decks (Leyline covers all graveyard, Pyroblast covers all blue)."},
    {"instruction": "Is Dimir Tempo likely to get a card banned?", "input": "", "output": "Based on historical patterns, Dimir Tempo is not currently at ban risk. At 14.6% meta share with a 52.7% win rate, it is the most popular deck but does not meet historical ban thresholds: DRS was at 57% representation when banned. Miracles with Top was at 15%+ with time issues. Ragavan era UR Delver was at 15-20% with a higher win rate. Dimir Tempo has no single card that is clearly broken - Bowmasters, Murktide, Thoughtseize, and Force are all strong but none is the format-warping element. The March 2026 B&R explicitly found Legacy healthy. A ban would require Dimir Tempo rising to 20%+ or win rate climbing above 55%."},
    {"instruction": "What would happen to the Legacy metagame if Force of Will were banned?", "input": "", "output": "Catastrophic format collapse. Force of Will is the safety valve that keeps combo in check. Without it: 1) Combo decks would win on turn 1-2 with no free interaction to stop them. Oops, Storm, Show and Tell would become oppressive. 2) Non-blue decks (D&T, Eldrazi) would become the only fair strategies since they use taxing effects instead of countermagic. 3) Daze alone is insufficient to police combo (only catches tapped-out plays). 4) The format would devolve into 'who combos faster' vs 'who plays the right prison piece.' Force of Will is not just a good card - it is the structural pillar that allows fair Magic to coexist with combo in Legacy. Banning it would end the format as we know it."},
    {"instruction": "How do I evaluate whether my local meta differs from the online meta?", "input": "", "output": "Track your local meta for 4-6 weeks by recording every opponent's deck. Then compare to MTGGoldfish's Legacy metagame page. Common differences: 1) Local metas have fewer combo decks (combo requires practice and confidence, paper players tend toward fair decks). 2) Local metas have more rogue decks (players invest in one deck and play it for years regardless of meta). 3) Local metas lag behind online trends by 2-4 weeks. 4) Local metas are more predictable (you know the 8-12 regular players and their decks). 5) Budget considerations shift local metas (fewer 4-Underground Sea Dimir lists, more Burn and budget options). Your sideboard should be tuned to YOUR local meta, not the MTGO meta."},
    {"instruction": "What is the expected win rate of a tier 1 Legacy deck with a skilled pilot?", "input": "", "output": "A skilled pilot on a tier 1 deck should expect: Overall: 55-60% win rate across all matchups over 50+ matches. Against the field at a tournament: 60-65% match win rate (5-1 or 4-1-1 at a typical 6-round event). Against specific bad matchups: 35-45% (still winnable through skill and sideboarding). Against specific good matchups: 65-75%. The difference between a skilled and average pilot on the same deck is approximately 5-10% win rate. This is why deck mastery matters more than deck choice - a 60% pilot on a tier 2 deck beats a 50% pilot on a tier 1 deck."},
]

conversation = [
    {"instruction": "What is the biggest misconception about Legacy?", "input": "", "output": "The biggest misconception is that Legacy is 'turn 1 combo format where nothing else matters.' In reality, Legacy is the most diverse and interactive format in Magic. Yes, combo EXISTS and can win turn 1, but: 1) Force of Will in 45% of decks checks combo. 2) The most played deck (Dimir Tempo) is a fair tempo strategy. 3) Creature combat, planeswalkers, and grinding are central to most games. 4) Combo represents about 35-40% of the meta, meaning 60-65% is fair Magic. The average Legacy game involves interactive decisions every turn, card selection through cantrips, and strategic resource management. It is not two ships passing in the night."},
    {"instruction": "How do I explain Legacy to someone who only plays Standard?", "input": "", "output": "Legacy is Standard but with every card ever printed and everything costs 1 mana. Imagine if your Standard deck could play the most efficient version of every effect: removal for 1 mana (Swords to Plowshares), countermagic for free (Force of Will), card draw for 1 mana (Brainstorm), and threats for 1-2 mana that would be banned in Standard. The result: games are faster, decisions are denser, and every turn matters from the very first. Think of it like chess vs checkers: Standard has simpler pieces moving on a simpler board. Legacy has more pieces, more possible moves, and more ways to win or lose on any given turn."},
    {"instruction": "Why do Legacy players love the format so much?", "input": "", "output": "Because Legacy offers what no other format can: 1) Intellectual depth - Brainstorm alone has more decision trees than most entire Standard formats. 2) Personal expression - with 54 archetypes, every player finds a deck that matches their personality. 3) History - playing with Alpha duals alongside modern cards connects you to Magic's entire history. 4) Mastery reward - the format rewards deep knowledge more than any other. A Legacy master consistently beats players on better decks through superior play. 5) Community - the shared barrier to entry creates a community of passionate, committed players who genuinely care about each other and the format. 6) Permanence - your deck never rotates. The skills, cards, and knowledge you build last forever."},
    {"instruction": "What would you tell someone who just lost their first 5 Legacy matches?", "input": "", "output": "Welcome to Legacy. Losing your first matches is NORMAL and expected. Here is why you should not be discouraged:\n\n1) Legacy has the steepest learning curve in Magic. Every opponent knows their deck intimately. You are competing against years of accumulated knowledge.\n\n2) Your losses are educational. Each one teaches you an interaction, a timing window, or a card you need to know. Write down what beat you.\n\n3) Brainstorm decisions take months to optimize. If you are playing blue, your cantrip skills will improve dramatically over the next 50 games.\n\n4) Sideboarding improves with experience. You will learn which cards to bring in once you see what opponents are doing.\n\n5) Every Legacy player went through this. The difference between you and them is 100-500 more games of practice.\n\nCommit to 30 more games with the same deck before evaluating. Legacy does not reveal its depth in 5 matches."},
    {"instruction": "What is the most important skill to develop for Legacy?", "input": "", "output": "Brainstorm timing and execution. Brainstorm is in 43% of Legacy decks and is cast multiple times per game. The difference between casting Brainstorm well and casting it poorly is the difference between winning and losing. Key Brainstorm skills: 1) When to cast (have a fetchland? what are you looking for? is now the right time?). 2) What to put back (context-dependent: hide from Thoughtseize, set up Delver, put back situational cards). 3) When to hold (no fetchland = no shuffle = bad Brainstorm). Master Brainstorm and you master Legacy. Everything else - Daze math, Force timing, sideboarding - is secondary to cantrip proficiency."},
]

board_state = [
    {"instruction": "Board state: I have Life from the Loam in hand and 3 Wastelands in graveyard. Opponent has 3 lands. Can I lock them out this turn?", "input": "", "output": "Cast Life from the Loam returning 3 Wastelands to hand. If you have Exploration in play (play 2 lands per turn): play Wasteland #1, activate to destroy opponent's land #1. Play Wasteland #2, activate to destroy land #2. You used both land drops. You cannot play Wasteland #3 this turn. Opponent has 1 land remaining. Next turn: dredge Loam, return Wastelands, repeat. Without Exploration (1 land drop): play 1 Wasteland, destroy 1 land. Opponent has 2 lands. Much slower lock. The Exploration + Loam + Wasteland engine is the heart of Lands' soft lock strategy."},
    {"instruction": "Board state: Opponent just resolved Omniscience and is casting spells for free. I have Flusterstorm in hand. Is it useful?", "input": "", "output": "Yes! Omniscience lets them cast spells for free, but Flusterstorm still works. Flusterstorm counters an instant or sorcery unless its controller pays 1 for EACH copy. Even with Omniscience, paying mana for Flusterstorm copies requires actually having and tapping mana. If opponent is casting everything for free via Omniscience and not tapping lands, they may not have mana available to pay for Flusterstorm copies. However - Omniscience says 'without paying its mana cost' but paying for Flusterstorm is an additional cost, not a mana cost... actually, Flusterstorm says 'pay 1' which is a cost they must pay with actual mana. If they have untapped lands, they can pay. If they used Omniscience for everything and never tapped lands, they might have full mana available. Flusterstorm is still useful but may not be sufficient alone."},
    {"instruction": "Board state: I control Thalia and Ethersworn Canonist. Opponent wants to cast Brainstorm then Ponder. What happens?", "input": "", "output": "Thalia makes noncreature spells cost 1 more. Ethersworn Canonist limits each player to 1 noncreature spell per turn. Opponent wants to cast Brainstorm (normally U, now 1U with Thalia). They can cast Brainstorm for 1U. Ethersworn Canonist then prevents them from casting Ponder (a second noncreature spell). They are limited to 1 noncreature spell per turn. This is the D&T dream: Thalia taxes the one spell they can cast, and Canonist prevents all subsequent spells. With both in play, the opponent can cast exactly 1 noncreature spell per turn at +1 mana cost. Devastating against cantrip-heavy and combo decks."},
    {"instruction": "Board state: I cast Burning Wish. In response, I crack Lion's Eye Diamond for 3 red mana. My hand is now empty. Burning Wish resolves. What can I get?", "input": "", "output": "This is the classic TES play. LED is cracked in response to Burning Wish, discarding your hand (which might have been empty anyway or contained cards you do not need). You gain RRR. Burning Wish resolves: search your sideboard for a sorcery card and put it in your hand. You can get Tendrils of Agony, Empty the Warrens, Past in Flames, or any other sorcery in your sideboard. Then you cast the sorcery using the RRR from LED plus any other mana floating. Tendrils costs 2BB, so you need BB from another source (Dark Ritual mana floating from earlier in the turn). The LED crack in response to Wish is the fundamental TES sequencing trick."},
    {"instruction": "Board state: My opponent has an empty library and 1 card in hand. I have Surgical Extraction. Can I win?", "input": "", "output": "If their 1 card in hand is their last card and their library is empty, they will lose on their next draw step (cannot draw from an empty library = game loss). You do not need to do anything - just pass the turn and they lose. Surgical Extraction is unnecessary here. However, if they might have an instant-speed win (like casting Thassa's Oracle from hand before their draw step), you should consider: can you stop it? If they cast Oracle with 0 cards in library and devotion to blue >= 0, they win. If you have Force of Will, counter Oracle. If not, Surgical in response to Oracle's ETB trigger targeting... Surgical targets a card in graveyard, not a trigger. Surgical cannot stop Oracle. You need a counterspell or Stifle for the trigger."},
]

budget = [
    {"instruction": "What is the total investment needed to play Legacy at each competitive level?", "input": "", "output": "Casual/FNM (proxy-friendly): $50-200. Buy sleeves, basics, and cheap staples. Proxy the rest. Functional at full power. MTGO Competitive: $300-600 for a full deck. Play leagues and challenges at the highest level. Paper competitive (budget): $1000-2000. Oops, Burn, Eldrazi, or shock-land versions of blue decks. 90-95% power. Paper competitive (full): $3000-6000. Real dual lands, complete sideboard, optimal list. 100% power. Paper competitive (pimp): $10,000+. Full foils, Beta duals, judge promos. Same power as $3000-6000 but prettier. The biggest jump in competitiveness is from $0 to $1000 (first real deck). The jump from $3000 to $6000 is marginal (3-4 Underground Sea vs 2 + shock lands)."},
    {"instruction": "If I could only buy 5 Legacy cards to start, what should they be?", "input": "", "output": "The 5 cards that go in the most decks and hold value best: 1) Force of Will ($80-100): goes in every blue deck, non-negotiable. 2) Polluted Delta ($30-40): most versatile fetchland, finds Island and Swamp types. 3) Wasteland ($25-35): goes in 48% of decks, defines the format. 4) Brainstorm ($3-5): goes in 43% of decks, best cantrip ever. 5) Ponder ($3-5): goes in 38% of decks, second best cantrip. Total: ~$150-185. These 5 cards are the foundation of most Legacy decks and together form the core of Dimir Tempo, Izzet Delver, Sneak and Show, Doomsday, and many more. Every dollar spent here transfers to future deck purchases."},
    {"instruction": "Is it smarter to buy one expensive deck or two budget decks?", "input": "", "output": "Two budget decks, for three reasons: 1) Metagame flexibility: with two decks, you can choose the better-positioned one each week. One deck means you are stuck even in a bad meta. 2) Learning: playing two different strategies teaches you the format faster. Understanding both sides of a matchup makes you better at both. 3) Risk diversification: if a card in one deck gets banned, you still have the other. Recommended budget pair: Oops All Spells ($1100) + Death and Taxes ($1500) = $2600 for a tier 1 combo deck and a tier 2 fair deck with zero card overlap and maximum matchup coverage."},
]

# Write all
categories = [
    ("rules_qa.jsonl", rules),
    ("card_evaluation.jsonl", card_eval),
    ("deckbuilding_rationale.jsonl", deckbuilding),
    ("deck_analysis.jsonl", deck_analysis),
    ("conversation_flow.jsonl", conversation),
    ("board_state_analysis.jsonl", board_state),
    ("budget_substitutions.jsonl", budget),
]

for filename, data in categories:
    outpath = os.path.join(os.path.dirname(__file__), "..", "data", "training", filename)
    with open(outpath, "a", encoding="utf-8") as f:
        for pair in data:
            f.write(json.dumps(pair, ensure_ascii=False) + "\n")
    print(f"Appended {len(data)} pairs to {filename}")
