"""Generate training data - Mega batch 6. Continue scaling toward 1500."""
import json
import os

rules = [
    {"instruction": "What is flash and when can I cast flash creatures?", "input": "", "output": "Flash allows you to cast a creature at any time you could cast an instant - during your opponent's turn, in response to spells, during combat, etc. In Legacy, flash creatures are powerful because they dodge sorcery-speed removal and enable surprise blocks. Key flash creatures: Orcish Bowmasters (punishes cantrips at instant speed), Brazen Borrower (bounces a permanent then attacks), Endurance (graveyard hate on a body), Solitude (removal on a body), Containment Priest (stops creatures entering without being cast)."},
    {"instruction": "What is the difference between 'cast' and 'put into play'?", "input": "", "output": "Cast means you go through the normal process of paying mana costs (or alternative costs), putting the spell on the stack, and resolving it. Put into play means the card goes directly from one zone to the battlefield without being cast. Show and Tell PUTS permanents into play. Reanimate PUTS a creature into play. Aether Vial PUTS creatures into play. This distinction matters because: Chalice of the Void only counters CAST spells, Containment Priest exiles creatures that were not CAST, and 'when you cast' triggers only happen on CAST, not put into play. Emrakul's extra turn trigger says 'when you cast' so Sneak Attack does not give an extra turn."},
    {"instruction": "What is the layer system and when does it matter in Legacy?", "input": "", "output": "The layer system determines how continuous effects interact. There are 7 layers applied in order: 1) Copy effects, 2) Control-changing, 3) Text-changing, 4) Type-changing, 5) Color-changing, 6) Ability adding/removing, 7) Power/toughness. This matters in Legacy most with Blood Moon (layer 4 changes land types, removing abilities in layer 6) and Painter's Servant (layer 5 adds color). Since type-changing (layer 4) happens before ability-removing (layer 6), Blood Moon first makes lands Mountains, then they lose their original abilities. Painter operates in layer 5, so it applies after type changes but before ability changes."},
    {"instruction": "How does the Stifle + fetchland interaction work exactly?", "input": "", "output": "Fetchland activation: tap, pay 1 life, sacrifice this land: search your library for a [type] land and put it onto the battlefield. The sacrifice and life payment are COSTS (paid immediately). The search is the EFFECT (goes on the stack). When you Stifle the fetchland ability, the ability is countered. The fetchland was already sacrificed (cost) and life was already paid (cost), but the search does not happen. Net result: opponent loses the fetchland, loses 1 life, and gets no land. This is a 1-mana Stone Rain + 1 life drain. Devastating tempo play."},
    {"instruction": "Can I respond to the Dredge replacement effect?", "input": "", "output": "No. Dredge is a replacement effect, not a triggered ability. Replacement effects do not use the stack. When a player would draw a card and chooses to dredge instead, the dredge happens immediately as part of the draw replacement. You cannot respond between the decision to dredge and the milling/return. This is why Dredge is so hard to interact with - the graveyard fills without any window for opponents to respond. The only interaction points are: before the draw (remove the dredge card from graveyard with Surgical or Endurance), or after the dredge (respond to triggered abilities from milled cards like Narcomoeba)."},
    {"instruction": "What happens when I Wasteland a land that was just played?", "input": "", "output": "You can Wasteland any nonbasic land at any time you have priority, including a land that was just played this turn. The land enters the battlefield and the active player gets priority. If they play a fetchland, you can Wasteland it before they crack it (they lose both the fetchland and the Wasteland target). However, mana abilities do not use the stack, so if they tap the land for mana in response to Wasteland, they get the mana before it is destroyed. You cannot prevent them from getting at least one use of mana from it."},
    {"instruction": "What is the timing for Leyline of the Void at the start of the game?", "input": "", "output": "Leyline of the Void can begin the game in play if it is in your opening hand. This happens before any player takes any game action - before mulligans are decided, before any spells can be cast. The Leyline is simply in play from the start. It affects the opponent's graveyard immediately: any card that would go to their graveyard from the first turn onward is exiled instead. Against Oops All Spells, a turn-0 Leyline means their Balustrade Spy mills their library into exile, not the graveyard, and Narcomoeba does not trigger (it triggers from graveyard only). This is why Leyline is the #1 hate card."},
    {"instruction": "Can my opponent use Karakas on a creature I put into play with Show and Tell?", "input": "", "output": "Yes, but not immediately. Show and Tell resolves with all permanents entering simultaneously. After Show and Tell finishes resolving, the active player gets priority. If it is your turn and you cast Show and Tell, YOU get priority first. You could activate your own abilities before passing priority. Then your opponent gets priority and can activate Karakas to bounce your legendary creature. If it is somehow their turn and they get priority first, they can Karakas immediately. The takeaway: on your turn, you get one window of priority before they can Karakas. Use it wisely (attack with Emrakul via Sneak Attack, etc)."},
    {"instruction": "What happens if both players have Orcish Bowmasters in play and one player casts Brainstorm?", "input": "", "output": "When a player casts Brainstorm (draw 3 cards), both Bowmasters trigger for each card drawn beyond the first. The Brainstorm caster draws 3 cards: the 2nd and 3rd draws trigger the opposing Bowmasters (2 triggers) AND the caster's own Bowmasters does NOT trigger (it only triggers on opponents' draws). So the opponent gets 2 Bowmasters triggers (2 damage, Army grows by 2). If the Brainstorm caster also had drawn a card earlier that turn (draw step), the first Brainstorm draw is the 2nd draw of the turn, meaning all 3 Brainstorm draws trigger opponent's Bowmasters (3 triggers). This is why Brainstorm against Bowmasters is so painful."},
    {"instruction": "How does Dark Depths' sacrifice work as a state-based action?", "input": "", "output": "Dark Depths has the ability: when Dark Depths has no ice counters on it, sacrifice it. This is NOT a state-based action - it is a triggered ability. When the last counter is removed (by Thespian's Stage copying it with 0 counters, or by Vampire Hexmage removing all counters), the trigger goes on the stack. Players can respond to this trigger. When it resolves, you sacrifice Dark Depths and create Marit Lage, a 20/20 black Avatar creature token with flying and indestructible. You CAN respond: Stifle the trigger (Depths stays with 0 counters but no Marit Lage), Wasteland the Depths before the trigger resolves (no Depths to sacrifice, trigger fizzles... actually, you sacrifice it as the trigger resolves, so Wastelanding in response means it is already gone and the trigger still creates Marit Lage. Wait - the trigger says 'sacrifice it' so if Depths is gone, you cannot sacrifice it, but you still create the token. Actually, re-reading: the ability says sacrifice AND create. If you cannot sacrifice (already gone), you still create the token. So Wasteland does not stop Marit Lage)."},
]

card_eval = [
    {"instruction": "Is Daze Legacy-playable?", "input": "", "output": "Yes, Daze is one of the defining cards of Legacy. For its alternative cost of returning an Island to your hand, you counter a spell unless the opponent pays 1. Daze is in 27% of Legacy decks. It is at its best on the play in the first 2-3 turns when opponents tap out. Combined with Wasteland (destroy the land they would use to pay), Daze becomes a hard counter. It is worse in long games when opponents have surplus mana. Best in: Delver, tempo. Worst in: control, combo."},
    {"instruction": "Is Orcish Bowmasters the best creature in Legacy?", "input": "", "output": "It has a strong case. Bowmasters is in 29% of decks - the most played creature in Legacy. It has flash (instant-speed deployment), triggers on every opponent card draw beyond the first (punishing cantrips), creates a growing Orc Army token, and costs just 1B. It reshuffled the entire metagame when printed: Elves and small-creature strategies collapsed, cantrip timing became a strategic decision, and every black deck gained a premium threat. The only argument against it being the best: Murktide Regent closes games faster and dodges Bolt, while Bowmasters is more of a value engine."},
    {"instruction": "Is Hymn to Tourach Legacy-playable?", "input": "", "output": "Yes, in the right shells. Hymn to Tourach costs BB and forces the opponent to discard 2 cards at random. The random discard is both its strength (can hit any card including lands) and weakness (might hit irrelevant cards). It is devastating on turn 1 with Dark Ritual or turn 2 normally, stripping 2 cards when hands are small. It sees play in Pox, Mono Black, and some BW builds. The double-black cost limits it to heavily black decks. Hymn has declined because Thoughtseize's surgical precision is often better than random 2-for-1."},
    {"instruction": "Is Mox Opal Legacy-playable?", "input": "", "output": "Yes, in artifact-heavy decks. Mox Opal costs 0 and taps for any color with metalcraft (3+ artifacts). In 8-Cast, Affinity, and artifact combo decks, metalcraft is trivially achieved on turn 1 (artifact lands + 0-cost artifacts). A free mana source in these decks is absurdly powerful. Outside dedicated artifact decks, metalcraft is too unreliable. Mox Opal is in about 14% of Legacy decks, concentrated entirely in artifact strategies. It is one of the best fast mana sources in the format."},
    {"instruction": "Is Grief Legacy-playable?", "input": "", "output": "Grief WAS Legacy-playable and was banned in 2024. For 2BB or by pitching a black card, Grief was a 3/2 menace with an ETB that Thoughtseized the opponent. The broken interaction was Grief + Ephemerate: turn 1, pitch Grief for free, Thoughtseize them, Ephemerate Grief (blink it, dodging the evoke sacrifice), Thoughtseize them again. On your opponent's upkeep, Ephemerate rebounds and Thoughtseizes a third time. This left the opponent with 4 fewer cards by turn 2 while you had a 3/2. It was banned for creating unacceptable non-games."},
    {"instruction": "Is Aether Vial Legacy-playable?", "input": "", "output": "Yes, it is the backbone of Death and Taxes and several other creature-based strategies. Aether Vial costs 1 and puts creatures into play at instant speed without paying mana, bypassing counterspells (Daze, Force of Will, Chalice). It gains a charge counter each upkeep, matching your creature curve. At 2 counters it puts in Thalia, Stoneforge, Phyrexian Revoker. At 3 it puts in Flickerwisp, Recruiter, Skyclave Apparition. The instant-speed deployment creates combat tricks and EOT value that no other card enables."},
    {"instruction": "Is Blood Moon Legacy-playable?", "input": "", "output": "Yes, Blood Moon is a format-defining prison piece. For 2R, all nonbasic lands become Mountains. In a format where most decks run 15+ nonbasic lands, Blood Moon effectively turns off the opponent's mana base. It is best in mono-red decks (Red Stompy, Painter) that only need Mountains anyway. It is in about 10-15% of Legacy decks mainboard or sideboard. The card single-handedly wins games against greedy multi-color decks that did not fetch basics early enough."},
    {"instruction": "Is Crop Rotation Legacy-playable?", "input": "", "output": "Yes, in Lands and some other land-focused strategies. Crop Rotation is a 1-mana green instant that sacrifices a land to tutor any land card directly into play. This is enormously powerful in Legacy because lands are powerful: Dark Depths (20/20 combo), Thespian's Stage (copy combo lands), Bojuka Bog (graveyard hate), Karakas (bounce legends), Maze of Ith (fog attackers), Wasteland (destroy lands), Tabernacle (kill creatures). Crop Rotation is an instant-speed tutor for any of these effects at just 1 mana."},
    {"instruction": "Is Collected Company Legacy-playable?", "input": "", "output": "Barely, and in very specific shells. Collected Company costs 3G and looks at the top 6 cards, putting up to 2 creatures with mana value 3 or less onto the battlefield. At 4 mana, it competes with Natural Order (which gets ANY green creature including Craterhoof). CoCo is better when you want creature density and instant-speed deployment, worse when you want a specific finisher. It sees occasional play in Maverick and GW creature decks but is not a Legacy staple. The 4-mana cost and randomness work against it in a format that demands precision."},
    {"instruction": "Is The One Ring Legacy-playable?", "input": "", "output": "Yes. The One Ring costs 4 mana and provides: indestructible and protection from everything until your next turn (survives a full turn cycle safely), and an activated ability to draw cards (tap, put a burden counter, draw cards equal to burden counters). The card advantage is absurd - drawing 1, then 2, then 3 cards per turn. The life loss from burden counters eventually kills you, but prison decks lock the opponent before that matters. It is in about 13% of Legacy decks, primarily in Red Stompy, Mystic Forge, and Eldrazi."},
]

deckbuilding = [
    {"instruction": "How many win conditions does a control deck need?", "input": "", "output": "Typically 2-6, depending on how redundant they are. Jeskai Control might run 2 Monastery Mentor and 1-2 Entreat the Angels - enough to find one via cantrips. Beanstalk Control wins through accumulated value from 4 Up the Beanstalk and does not need dedicated win conditions. Lands wins with 2 Dark Depths + 2 Thespian's Stage (the combo IS the win condition). The key: cantrips let you find a single win condition reliably, so you do not need many. Every slot spent on a win condition is a slot not spent on answers."},
    {"instruction": "Why do some Legacy decks play Mishra's Bauble?", "input": "", "output": "Mishra's Bauble costs 0 mana and draws a card at the beginning of the next upkeep (delayed draw). It fills multiple roles: 1) Free artifact for Urza's Saga Constructs and metalcraft. 2) Contributes to delirium (artifact type in graveyard) for Dragon's Rage Channeler. 3) Fuels delve for Murktide Regent. 4) Lets you see the top card of any library (information). 5) It is a free spell for storm count. The card does almost nothing individually, but its zero cost and synergies make it powerful in specific shells."},
    {"instruction": "Why does every Legacy combo deck play some form of protection?", "input": "", "output": "Force of Will is in 45% of Legacy decks. If your combo resolves, you win, but 45% of the time your opponent has a free counterspell ready. Without protection, your combo is countered almost half the time. Protection options: Force of Will (counter their Force), Pact of Negation (free counter on combo turn), Veil of Summer (stops blue and black interaction for G), Thoughtseize (strip their Force before comboing), Silence (prevent all spells for W), Defense Grid (spells cost 3 more on opponent's turn). Every competitive combo deck runs 4-8 protection pieces."},
    {"instruction": "What is a transformational sideboard and when should I use one?", "input": "", "output": "A transformational sideboard changes your deck's strategy entirely post-board. Example: Doomsday bringing in a Show and Tell package so opponents who sided in graveyard hate face a completely different combo. Storm bringing in a creature beatdown plan (Young Pyromancer, Monastery Mentor) so opponents with anti-storm hate (Mindbreak Trap, Deafening Silence) face irrelevant sideboard cards. Transformational sideboards work best when: 1) your game 1 strategy has a specific hate card that blanks it, 2) the transformation dodges that hate entirely, and 3) you have enough sideboard slots (usually 8-10). The risk is inconsistency from having two half-strategies."},
    {"instruction": "Why do Legacy Delver decks play fewer lands than other formats?", "input": "", "output": "Legacy Delver decks typically run 18-19 lands compared to 22-24 in Modern or Standard. This works because: 1) 8 cantrips (Brainstorm + Ponder) let you keep 1-land hands and find the second land reliably. 2) Spells cost 0-2 mana, so you rarely need more than 3 lands in play. 3) Daze returns a land to hand, effectively letting you 'replay' it. 4) Wasteland is a land that you WANT to sacrifice. Playing fewer lands maximizes spell density, which means more threats and interaction per game. The cantrip engine compensates for the low land count."},
    {"instruction": "How do I choose between main-decking removal vs counterspells?", "input": "", "output": "Consider your strategy and the metagame: 1) Tempo decks: prioritize counterspells (Daze, Force of Will) over removal because you want to protect your threats and deny opponent's plays. Run 2-4 removal as flex. 2) Control decks: balance both - you need removal for resolved threats and counterspells for stack interaction. 3) Creature matchups: removal is better (Swords to Plowshares, Lightning Bolt). 4) Combo matchups: counterspells are better (Force of Will, Daze). Since Legacy is roughly 40% combo, having 4 Force of Will mainboard is almost mandatory for blue decks. Then add removal based on how many creatures you expect to face."},
    {"instruction": "What is the role of Preordain vs Consider in Legacy?", "input": "", "output": "Both are cantrips that cost U. Preordain scrys 2 then draws 1 (see 3 cards, can bottom 2). Consider surveys 1 (look at top card, may put in graveyard) then draws 1 (see 2 cards, can mill 1). Preordain is better for card SELECTION (see more cards, choose better). Consider is better for GRAVEYARD FUELING (instant speed, puts a card in graveyard for Murktide delve, delirium, or Cabal Therapy). In Dimir Tempo, Consider is sometimes preferred because the instant speed and graveyard synergy outweigh Preordain's deeper selection. In combo, Preordain is always better."},
    {"instruction": "Why do some decks play a single copy of a card?", "input": "", "output": "One-ofs in Legacy serve specific purposes: 1) Tutor targets: Green Sun's Zenith decks play 1-of creatures for each situation (1 Collector Ouphe, 1 Endurance, 1 Dryad Arbor). 2) Legendary cards: Karakas is legendary, so multiples are dead. Run 1. 3) Sideboard tech: 1-of Massacre in sideboard is enough when you can find it with cantrips. 4) Wish targets: Burning Wish's sideboard has 1-ofs for each situation. The principle: in a cantrip-heavy format, 1-ofs are effectively more than 1 copy because Brainstorm and Ponder find them."},
    {"instruction": "How do I decide between playing aggressive or controlling with a tempo deck?", "input": "", "output": "The decision depends on your role in each matchup: 1) Against combo: be aggressive. Deploy a threat early and protect it with countermagic. You are the clock. 2) Against aggro: be controlling. Remove their threats, stabilize, then deploy your own. 3) Against control: be aggressive early (under their shields) then transition to protecting what you have. 4) Against prison: depends on their lock. If Chalice is on 1, you cannot cantrip - be aggressive with existing threats. If Blood Moon is out, adapt your mana usage. The hallmark of a skilled tempo pilot is recognizing your role and adjusting mid-game."},
]

deck_analysis_pairs = [
    {"instruction": "Analyze the Legacy metagame for someone who plays Red Stompy.", "input": "", "output": "Red Stompy sits at 2.7% meta share. Here is how the current meta looks from your perspective:\n\nFavorable (about 25% of field): Izzet Delver (Chalice on 1 wrecks them), Burn (Blood Moon is irrelevant but Chalice + threats outrace), Infect (Chalice on 1 stops pump spells).\n\nEven (about 35%): Dimir Tempo (they have Thoughtseize + Force for your lock pieces, but a resolved Blood Moon or Chalice is devastating), Death and Taxes (Thalia does not help against artifacts, but they can go under your setup), Ocelot Pride (creature deck that does not rely on cantrips, but Chalice still helps).\n\nUnfavorable (about 40%): Sneak and Show (combo costs 3-4, dodges Chalice), Oops (Force of Will through Chalice, combo before you lock), Lands (Wasteland-proof, goes over your threats), 8-Cast (artifact deck that does not care about Blood Moon).\n\nSideboard priorities: Force of Vigor answers are essential. Bring extra threats against blue decks that board in Force of Vigor."},
    {"instruction": "Analyze this decklist for weaknesses: 4 Delver of Secrets, 4 Murktide Regent, 4 Lightning Bolt, 4 Brainstorm, 4 Ponder, 4 Force of Will, 4 Daze, 4 Wasteland, 4 Scalding Tarn, 3 Volcanic Island, 1 Island, 1 Mountain", "input": "", "output": "This is Izzet Delver. Weaknesses I see:\n\n1) No Thoughtseize or hand disruption: you have no proactive disruption against combo. Your only interaction is Daze and Force of Will, which are reactive. Dimir Tempo has Thoughtseize for a reason.\n\n2) No Orcish Bowmasters: the most played creature in Legacy, and you are not running it. This means you have less game against cantrip-heavy opponents and lose the Bowmasters mirror advantage.\n\n3) Only 18 lands with 3 Volcanic Island and 4 Wasteland: this means 7 of your 18 lands do not produce blue mana. Combined with Daze bouncing Islands, you may struggle to cast Force of Will (needs UU from hand if paying normally).\n\n4) Basic Mountain over a 2nd Island: you are more vulnerable to Wasteland with only 1 basic Island.\n\nSuggested improvements: consider adding Thoughtseize by splashing black (becomes Dimir Tempo), or at minimum, play Surgical Extraction and Flusterstorm in sideboard for combo matchups."},
    {"instruction": "Is Aluren positioned to continue its success after winning the Showcase Qualifier?", "input": "", "output": "Short-term (2-4 weeks): Yes, Aluren is well-positioned. Its 1.2% meta share means opponents do not prepare for it. The deck's combo-control hybrid nature means it has game against both fair and combo decks. The Showcase Qualifier win proves it can take down competitive events.\n\nMedium-term (1-3 months): Risk increases. After a high-profile win, more players will study Aluren and learn to sideboard against it. Surgical Extraction on Acererak and Leyline of the Void are effective hate that is already in most sideboards for other reasons.\n\nLong-term: Aluren will settle back to a 1-2% meta deck that occasionally spikes events. Its strength is in surprise and the skill of its pilots, not raw power. The deck rewards deep format knowledge and is hard to play optimally, which limits its adoption.\n\nRecommendation: if you already know how to play Aluren, this is a great time to run it. If you are considering learning it, be aware the window of surprise advantage may close as the meta adjusts."},
    {"instruction": "How has the Legacy metagame changed since the Entomb ban?", "input": "", "output": "The November 2025 Entomb ban had several cascading effects:\n\n1) Reanimator dropped from tier 1 (~8%) to tier 2 (~2%). Without turn-1 Entomb into Reanimate, the deck is a turn slower and less consistent.\n\n2) Oops All Spells rose from tier 2 to tier 1 (now 8.2%). It absorbed the 'fastest combo' role that Reanimator left behind. Players who wanted a turn-1 combo moved to Oops.\n\n3) Sneak and Show rose slightly (now 6.7%). Another beneficiary of the 'cheat big things into play' niche.\n\n4) Leyline of the Void stayed at 36% despite Reanimator declining. This is because Oops, Dredge, and Doomsday still exist as graveyard targets.\n\n5) Dimir Tempo rose to 14.6% as the top deck. With Reanimator's decline, one of Dimir's worst matchups became less common.\n\n6) Overall combo diversity increased. Instead of one dominant combo deck (Reanimator), the combo share is spread across Oops, S&T, TES, Doomsday, Painter, Mystic Forge, and Aluren."},
    {"instruction": "Compare the current Legacy meta to the 2021-2022 MH2 era.", "input": "", "output": "Key differences:\n\n2021-2022 (MH2 era): UR Delver dominated at 15-20% with Ragavan, DRC, Murktide, and Expressive Iteration. The format was 'Delver vs. everything else.' Ragavan on turn 1 generating mana and cards was oppressive. Initiative creatures from CLB created White Stompy. Uro piles were the main control strategy.\n\n2025-2026 (current): Dimir Tempo leads at 14.6% - similar share but the deck is FAIR. No Ragavan (banned), no Expressive Iteration (banned). Orcish Bowmasters (LTR 2023) replaced DRC as the flex creature. Energy cards from MH3 created viable non-blue aggro (Ocelot Pride 8.5%). Combo is more diverse with 8+ viable archetypes.\n\nThe format is healthier now. The 2021 era had one overwhelmingly dominant deck (UR Delver). The current era has Dimir Tempo as the best deck but with 54 competitive archetypes and no single deck above 53% win rate. More strategies are viable, more cards have been printed, and bans have opened design space."},
]

conversation = [
    {"instruction": "I am thinking about buying into Legacy. Convince me it is worth it.", "input": "", "output": "Here is why Legacy is worth the investment:\n\n1) The best gameplay in Magic. Legacy has the deepest card pool, the highest skill ceiling, and the most diverse metagame. Every game involves meaningful decisions from turn 1.\n\n2) Your deck never rotates. A Legacy deck bought today will be legal forever (barring specific card bans). Standard decks become worthless every 2 years. Legacy decks are permanent.\n\n3) Financial appreciation. Reserved List cards (dual lands, LED) only go up in value. Your Underground Seas will be worth more in 5 years than today. Legacy is the only Magic format where your collection consistently appreciates.\n\n4) Community. Legacy players are the most passionate and knowledgeable in Magic. The community is tight-knit, welcoming to new players, and deeply invested in the format's health.\n\n5) Accessibility is improving. MTGO lets you play for $300-500. Many stores allow proxies. You do not need $5000 on day one.\n\n6) Unmatched variety. 54 competitive archetypes mean you can always find something new to play or play against. No two weeks of Legacy feel the same."},
    {"instruction": "Walk me through the thought process of building a Legacy sideboard from scratch.", "input": "", "output": "Step-by-step sideboard construction:\n\n1) List your worst 5-8 matchups. For Dimir Tempo: Lands, Oops, Storm, Sneak and Show, Red Stompy, Ocelot Pride.\n\n2) For each matchup, identify the 1-2 cards that would improve it most. Lands: Blood Moon or Surgical on Loam. Oops: Leyline of the Void. Storm: Flusterstorm. Sneak and Show: Pyroblast. Red Stompy: Force of Vigor. Ocelot: Toxic Deluge.\n\n3) Find overlap. Leyline covers Oops AND Dredge AND Doomsday. Pyroblast covers S&T AND Delver mirrors. Flusterstorm covers Storm AND counter wars. Maximize cards that help in multiple matchups.\n\n4) Allocate slots. Start with your most common bad matchups. If Oops is 8.2% and you face it every other tournament, 4 Leylines is justified. If Dredge is 1.1%, 0 dedicated Dredge hate is fine (Leyline covers it anyway).\n\n5) Final 15: 4 Leyline of the Void, 2 Flusterstorm, 2 Pyroblast, 2 Hydroblast, 2 Toxic Deluge, 2 Null Rod, 1 Surgical Extraction. Every slot improves at least 2 matchups.\n\n6) Test. Play 10 matches with sideboard, adjust based on what you actually board in/out."},
    {"instruction": "My opponent just revealed Leyline of the Void from their opening hand. I am on Doomsday. What do I do?", "input": "", "output": "Do not panic. Leyline is painful but not game over for Doomsday:\n\n1) Your win condition (Thassa's Oracle) checks LIBRARY SIZE, not graveyard. Oracle says 'if X is greater than or equal to cards in library' where X is devotion to blue. Leyline does not affect this.\n\n2) The problem: your cantrips send cards to exile instead of graveyard, so you cannot use graveyard-based pile navigation. But you can still cast Doomsday (it resolves normally), and draw through your 5-card pile with cantrips.\n\n3) Your pile: needs to draw through itself using only draw spells, not graveyard interaction. Example pile: Brainstorm, Ponder, Oracle, Force of Will, blue card. Cast Brainstorm (draw Ponder, Oracle, Force, put 2 back), cast Ponder (see remaining cards, draw Oracle), cast Oracle with 0 cards in library.\n\n4) Alternatively: find and cast Force of Vigor (pitch green card) to destroy Leyline first, then proceed with a normal graveyard-enabled pile.\n\nThe key: Leyline slows you down by 1-2 turns but does not prevent the kill. Stay calm and construct your pile carefully."},
    {"instruction": "What questions should I ask myself before every Legacy game?", "input": "", "output": "Pre-game mental checklist:\n\n1) What deck is my opponent on? (If game 1, infer from their first plays. If game 2-3, you know.)\n\n2) What is their fastest possible kill? (Turn 1 for Oops, turn 2-3 for Storm, turn 3-4 for fair decks.) This sets your urgency level.\n\n3) What is MY role in this matchup? (Aggressor, controller, or combo player?) This determines whether you deploy threats or hold interaction.\n\n4) What card in their deck do I lose to? (Emrakul, Blood Moon, Chalice, etc.) This tells you what to Force of Will.\n\n5) What is my mulligan threshold? (Keep any hand with Force against combo. Keep any hand with 2 lands + cantrip against fair.)\n\n6) What is my sideboard plan? (Know BEFORE you sit down what comes in and what goes out.)\n\n7) What is their sideboard plan against me? (Are they bringing in Leyline? Pyroblast? Chalice? Adjust your play accordingly.)\n\nAsking these questions before every game takes 30 seconds and dramatically improves your decision-making."},
]

board_state = [
    {"instruction": "Board state: I am playing Dimir Tempo. I have Murktide Regent (6/6) and opponent is at 6 life with Swords to Plowshares in hand (I know from Thoughtseize). Should I attack?", "input": "", "output": "If you attack, opponent Swords your Murktide, exiling it and gaining 6 life (goes to 12). You lose your threat and they stabilize. If you do NOT attack, you hold Murktide as a blocker and threat while developing your board further. Better line: deploy another threat first (Bowmasters, Barrowgoyf) to force them to choose which to Swords. Then attack with the surviving threat. If you only have Murktide, consider: is the opponent deploying their own threats? If they have nothing, wait. If they are building a board, you may need to force the Swords now and rely on future topdecks. Context matters, but usually do not walk Murktide into known Swords without a backup plan."},
    {"instruction": "Board state: It is game 2 against Oops All Spells. I mulliganed to 6 and have Leyline of the Void, Force of Will, Brainstorm, Ponder, Island, Polluted Delta. Should I keep?", "input": "", "output": "Absolutely snap keep. This is the dream hand against Oops: Leyline of the Void starts in play (completely shuts off their combo), Force of Will protects the Leyline from Chain of Vapor or bounce effects, and Brainstorm + Ponder find you a threat to kill them with. With Leyline in play, they literally cannot win through their normal gameplan. They need to find artifact/enchantment removal for Leyline, and you have Force to stop that. Island + Polluted Delta provides mana. This 6-card hand is better than most 7-card hands. 10/10."},
    {"instruction": "Board state: Opponent casts Natural Order sacrificing a mana elf, searching for Craterhoof Behemoth. They have 5 other creatures in play. Can I survive?", "input": "", "output": "Craterhoof Behemoth enters and gives all their creatures +X/+X and trample where X is the number of creatures they control. With 5 creatures + Craterhoof = 6 creatures, everything gets +6/+6 and trample. A typical Elves board of five 1/1 elves becomes five 7/7 tramplers plus a 11/11 Craterhoof = 46 damage with trample. You probably cannot survive this through blocking. Your options: 1) Counter Natural Order with Force of Will. 2) Kill the sacrifice target in response (but they already sacrificed as a cost). 3) Swords to Plowshares Craterhoof before the trigger resolves... wait, the +X/+X is an ETB trigger that goes on the stack. You CAN respond by removing Craterhoof, which means X = 5 instead of 6. Still likely lethal. Your best bet was countering Natural Order."},
    {"instruction": "Board state: I am playing Storm (TES). My opponent has Thalia, Guardian of Thraben in play. How much extra mana do I need to combo?", "input": "", "output": "Thalia adds 1 to every noncreature spell. Your typical combo sequence costs: Dark Ritual (B+1=1B), Rite of Flame (R+1=1R), Lion's Eye Diamond (0+1=1), Burning Wish (1R+1=2R), Tendrils of Agony (2BB+1=3BB). Each spell costs 1 more. If you cast 5 spells, that is 5 extra mana needed. A normal TES kill needs about 4-5 mana to start; with Thalia, you need 9-10 mana. This is very difficult but not impossible. Lines: 1) Use Burning Wish for Pulverize (destroy all artifacts, but Thalia is a creature, not an artifact). 2) Use Grapeshot or Lightning Bolt effect to kill Thalia first. 3) Generate enough extra mana through additional rituals. The best play is usually to kill Thalia with your first spell (Abrupt Decay costs 1BG+1=2BG with Thalia) then combo normally."},
    {"instruction": "Board state: Both players have Orcish Bowmasters in play. I want to cast Brainstorm. What happens?", "input": "", "output": "When you cast Brainstorm, you draw 3 cards. Your opponent's Bowmasters triggers for each card you draw beyond the first draw of the turn. If this is your first draw action (before draw step or you are in your draw step), the first Brainstorm draw is normal, draws 2 and 3 trigger opponent's Bowmasters twice. If you already drew for turn, all 3 Brainstorm draws trigger (3 times). Your OWN Bowmasters does NOT trigger because it only triggers on OPPONENT's draws, not yours. So: opponent gets 2-3 triggers (2-3 damage to you or your creatures, Army grows by 2-3). This is why Brainstorm timing against Bowmasters is critical - sometimes it is correct to NOT cantrip into opposing Bowmasters."},
]

budget = [
    {"instruction": "What Legacy deck gives the best value for the money?", "input": "", "output": "Oops All Spells at ~$1100 offers the best power-to-price ratio. It is a tier 1 deck (8.2% meta share, ~53% win rate) that costs less than most Standard decks. Force of Will ($320-400 for a set) is the biggest expense, and those transfer to any blue deck you build later. The rest of the deck (Lotus Petal, Dark Ritual, Balustrade Spy, Narcomoeba, etc.) is cheap. No dual lands, no Reserved List cards beyond Force. Dollar-for-dollar, no other Legacy deck comes close."},
    {"instruction": "I have a complete Modern Burn deck. How much does it cost to convert to Legacy Burn?", "input": "", "output": "Very cheap! Legacy Burn shares most cards with Modern Burn. You already have: Lightning Bolt, Eidolon of the Great Revel, Goblin Guide, Monastery Swiftspear, Searing Blaze, Lava Spike, Rift Bolt. New cards needed for Legacy: 4 Chain Lightning ($2 each = $8), 4 Price of Progress ($3 each = $12), 4 Fireblast ($2 each = $8). Total upgrade cost: about $30-50. The most expensive addition might be a set of fetchlands if you do not already own them ($80-160 for a budget set). Legacy Burn is one of the cheapest format transitions in Magic."},
    {"instruction": "Should I buy dual lands or Force of Will first?", "input": "", "output": "Force of Will first, for three reasons: 1) Force of Will goes in EVERY blue deck. Dual lands are deck-specific (Underground Sea only goes in UB decks). 2) Force of Will is not on the Reserved List and gets occasional reprints, but demand keeps the price steady at $80-100. Buying now is fine. 3) You can play functional Legacy with shock lands instead of duals, but you CANNOT play functional Legacy without Force of Will - there is no substitute. Exception: if you play a non-blue deck (D&T, Eldrazi, Red Stompy), you do not need Force at all. In that case, buy your deck's specific staples first."},
    {"instruction": "How do I build a Legacy collection over 12 months on a $200/month budget?", "input": "", "output": "12-month plan ($2400 total):\n\nMonth 1-2 ($400): 4 Force of Will. Your most important purchase.\nMonth 3 ($200): 8 fetchlands (budget options like Flood Plain/Bad River + 2 premium fetches).\nMonth 4 ($200): 4 Brainstorm, 4 Ponder, 4 Wasteland, 4 Daze, common staples.\nMonth 5-6 ($400): 1-2 dual lands of your primary color. Choose based on your target deck.\nMonth 7 ($200): Deck-specific cards (Bowmasters, Murktide, Thoughtseize, etc.).\nMonth 8 ($200): Complete your sideboard staples (Leyline, Surgical, Pyroblast, etc.).\nMonth 9-10 ($400): 1-2 more dual lands to complete your mana base.\nMonth 11-12 ($400): Second deck or premium upgrades (premium fetchlands, extra duals).\n\nBy month 6 you have a functional deck. By month 12 you have a fully powered deck with sideboard flexibility. Reserved List purchases (duals) in months 5-6 and 9-10 appreciate over time."},
]

# Write all categories
categories = [
    ("rules_qa.jsonl", rules),
    ("card_evaluation.jsonl", card_eval),
    ("deckbuilding_rationale.jsonl", deckbuilding),
    ("deck_analysis.jsonl", deck_analysis_pairs),
    ("conversation_flow.jsonl", conversation),
    ("board_state_analysis.jsonl", board_state),
    ("budget_substitutions.jsonl", budget),
]

for filename, data in categories:
    outpath = os.path.join(os.path.dirname(__file__), "..", "data", "training", filename)
    with open(outpath, "a", encoding="utf-8") as f:
        for pair in data:
            f.write(json.dumps(pair, ensure_ascii=False) + "\n")
    print(f"Appended {len(data)} pairs to {filename}")
