"""Generate budget substitution training data."""
import json
import os

pairs = [
    # === DUAL LAND SUBSTITUTIONS ===
    {"instruction": "What is a budget replacement for Underground Sea?", "input": "", "output": "Watery Grave from Ravnica is the best budget replacement for Underground Sea. It enters untapped if you pay 2 life, providing the same UB mana fixing. The trade-off is meaningful: 2 life per untapped use adds up against aggressive decks, and you take 6+ damage from lands in a typical game. Against Burn, this can be the difference between winning and losing. In a slower meta, Watery Grave is very functional. Underground Sea costs $600-800 while Watery Grave is under $15."},
    {"instruction": "What is a budget replacement for Volcanic Island?", "input": "", "output": "Steam Vents is the budget replacement for Volcanic Island. Same trade-off as all shock lands: 2 life per untapped use. In Izzet Delver, where you fetch aggressively and often need UR on turns 1-2, the life cost adds up to 4-8 damage from lands. This is worse against Burn and aggressive Ocelot Pride builds but acceptable against combo and control. Volcanic Island is $500-700 while Steam Vents is under $15."},
    {"instruction": "What is a budget replacement for Tropical Island?", "input": "", "output": "Breeding Pool replaces Tropical Island. Since Tropical Island is usually a splash dual (1-2 copies), the life cost is less impactful than replacing your primary dual. In Infect, where you need UG on turn 1-2, the 2 life matters more since you are often at low life from your own Gitaxian Probes and fetchlands. Tropical Island is $400-600 while Breeding Pool is under $15."},
    {"instruction": "What is a budget replacement for Tundra?", "input": "", "output": "Hallowed Fountain replaces Tundra. In UW control decks, the life cost is less relevant since you plan to go long and can afford to enter tapped occasionally in the late game. In tempo builds where you need WU on turn 2, entering tapped can be devastating. Tundra is $300-500 while Hallowed Fountain is under $10."},
    {"instruction": "Can I play fetchable triomes instead of dual lands?", "input": "", "output": "Triomes like Zagoth Triome or Raffine's Tower provide three colors and are fetchable, but they always enter tapped. In Legacy tempo decks, entering tapped on turns 1-3 is usually game-losing because you fall behind on Daze math and cannot deploy threats on curve. Triomes are acceptable in control decks as 1-of utility lands. They are NOT acceptable replacements for dual lands in tempo or combo decks."},
    {"instruction": "What is a budget replacement for Bayou?", "input": "", "output": "Overgrown Tomb replaces Bayou. In Nic Fit or BG midrange, the life cost is manageable since these decks run Veteran Explorer to ramp. In Elves, where Bayou often provides the only black source for sideboard Thoughtseize, Overgrown Tomb works but the 2 life cost cuts into the aggressive gameplan. Bayou is $300-500 while Overgrown Tomb is under $15."},

    # === EXPENSIVE NON-LAND SUBSTITUTIONS ===
    {"instruction": "What is a budget replacement for Force of Will?", "input": "", "output": "There is no true replacement for Force of Will. It is the only card in Legacy that can counter any spell for free at any time. Force of Negation is the closest alternative but only works on the opponent's turn and only hits noncreature spells. Subtlety only hits creatures and planeswalkers. If you cannot afford Force of Will ($80-100 each), consider playing a non-blue deck like Death and Taxes, Eldrazi, Red Stompy, or Burn that does not need it."},
    {"instruction": "What is a budget replacement for Wasteland?", "input": "", "output": "Ghost Quarter and Field of Ruin are budget alternatives to Wasteland, but both give the opponent a basic land, dramatically reducing the mana denial effect. Wasteland destroys a land with no compensation, which is what makes it format-defining. If you must substitute, Ghost Quarter is better than Field of Ruin because it does not require 2 mana. But honestly, Wasteland at $25-35 is one of the more affordable Legacy staples."},
    {"instruction": "What is a budget replacement for Lion's Eye Diamond?", "input": "", "output": "There is no replacement for Lion's Eye Diamond in combo decks. LED provides 3 free mana at instant speed, which is unique and irreplaceable in Storm and Dredge. Without LED, Storm cannot reliably go off, and Dredge loses its explosive starts. If you cannot afford LED ($300-400 each), consider Storm variants that use fewer copies or switch to Ruby Storm which does not use LED at all."},
    {"instruction": "What is a budget replacement for Mox Diamond?", "input": "", "output": "Chrome Mox is the closest alternative. Instead of discarding a land, you imprint a nonland card. The trade-off is that Chrome Mox costs you a spell instead of a land, which is worse in most decks since spells are more valuable. In Lands specifically, Mox Diamond is irreplaceable because discarding a land is an upside with Life from the Loam. Mox Diamond is $400-500 while Chrome Mox is $50-70."},
    {"instruction": "What is a budget replacement for The Tabernacle at Pendrell Vale?", "input": "", "output": "Pendrell Mists is a 4-mana enchantment with the same effect as Tabernacle. The problem is that 4 mana is enormously slower than a free land, and it can be countered or destroyed by enchantment removal. In Lands, where you can Crop Rotation for Tabernacle at instant speed, there is simply no replacement. Tabernacle is $5000+ and is the reason Lands is the most expensive Legacy deck. If you cannot afford it, consider Engineered Plague or Massacre as partial substitutes for the anti-creature role."},
    {"instruction": "What is a budget replacement for Gaea's Cradle?", "input": "", "output": "There is no replacement for Gaea's Cradle in Elves or Cradle Control. The card generates mana equal to your creature count for free, often producing 5-10 mana. Growing Rites of Itlimoc from Ixalan is the closest but costs 3 mana and needs to flip. In Elves, the deck is significantly weaker without Cradle. Cradle is $800-1000 each. If budget is a concern, consider Cloudpost Ramp as an alternative deck with a similar big-mana strategy at much lower cost."},

    # === BUDGET DECK RECOMMENDATIONS ===
    {"instruction": "What is the cheapest competitive Legacy deck?", "input": "", "output": "Oops All Spells at approximately $1100 is the cheapest tier 1 Legacy deck. It runs zero dual lands, and its most expensive cards are Force of Will and some sideboard staples. Burn at approximately $1500 is another budget option that avoids dual lands entirely. Belcher at approximately $1200 is similarly affordable. All three decks can win tournaments despite their low cost."},
    {"instruction": "Can I play competitive Legacy on a budget?", "input": "", "output": "Yes, several competitive decks cost under $2000. Oops All Spells ($1100), Burn ($1500), Belcher ($1200), and Dredge ($2000 with LED) are all tournament-viable. Red Stompy ($2500-3000 without Fiery Confluence) avoids dual lands. Eldrazi ($2100) uses only colorless lands. The key is choosing a deck whose expensive cards are staples you will use forever, and avoiding Reserved List cards you cannot afford."},
    {"instruction": "What is the cheapest way to build Dimir Tempo?", "input": "", "output": "The minimum viable Dimir Tempo build replaces Underground Sea with Watery Grave and cuts some expensive sideboard cards. This brings the cost from $5000 down to approximately $1500-2000. The 2-life-per-use cost from Watery Grave reduces your win rate by a few percentage points against aggressive decks but is functional against combo and control. Force of Will ($80-100 each) is the single biggest non-land expense and is not replaceable."},
    {"instruction": "How do I build a budget mana base for a two-color Legacy deck?", "input": "", "output": "Replace dual lands with the corresponding shock land (Watery Grave for Underground Sea, etc.). Run 3-4 basics to protect against Wasteland. Keep all fetchlands since they are $20-40 each and essential for Brainstorm. Consider running 1-2 slow fetches (Flood Plain for UW decks) to save on expensive Zendikar fetches. Total mana base cost drops from $2000-3000 to $200-400 with this approach."},

    # === TRADE-OFF ANALYSIS ===
    {"instruction": "How much worse is a shock land than a dual land in Legacy?", "input": "", "output": "In practice, replacing all dual lands with shock lands reduces your win rate by approximately 3-5%. The 2 life per untapped use costs you 4-10 life per game from lands alone, which is critical against Burn (where every point matters), Ocelot Pride (fast aggro), and Dimir Tempo (which can Bolt or Bowmasters you for remaining life). Against combo decks that do not care about your life total, the difference is negligible. The biggest risk is against Price of Progress, which deals double damage for each nonbasic land you control."},
    {"instruction": "Is it worth buying dual lands for Legacy?", "input": "", "output": "Dual lands are on the Reserved List and can never be reprinted, so they hold or increase in value over time. If you plan to play Legacy long-term, buying duals is both a gameplay investment and a financial one. Start with 2-3 copies of your primary dual and upgrade over time. Many players begin with shock lands and buy one dual at a time. The difference in gameplay quality is real but not insurmountable."},
    {"instruction": "What Reserved List cards are essential vs optional in Legacy?", "input": "", "output": "Essential: Dual lands are needed for competitive multicolor decks and have no close substitutes. Optional: Lion's Eye Diamond (only in Storm and Dredge), Mox Diamond (only in Lands and some Stompy decks), City of Traitors (Ancient Tomb is a non-Reserved alternative for most decks), Gaea's Cradle (only in Elves and Cradle Control). The Tabernacle at Pendrell Vale is only in Lands and costs more than some cars. Focus your Reserved List budget on dual lands first."},
    {"instruction": "What are the best budget-friendly sideboard cards?", "input": "", "output": "Many powerful Legacy sideboard cards are very affordable. Pyroblast and Hydroblast ($1-3 each), Surgical Extraction ($5-8), Mindbreak Trap ($5), Flusterstorm ($10-15), Deafening Silence ($1), Null Rod ($15-20), and Grafdigger's Cage ($2) are all cheap and highly effective. Leyline of the Void ($5-10) is the most played sideboard card in the format and costs almost nothing. Expensive sideboard cards like Endurance ($30-40) and Force of Vigor ($15-20) have budget alternatives."},
    {"instruction": "Give me a budget version of Izzet Delver.", "input": "", "output": "Replace 2-3 Volcanic Island ($500-700 each) with 2-3 Steam Vents ($12). Keep 1 Volcanic Island if you can afford one for Wasteland resilience. Replace expensive sideboard cards: Endurance with Grafdigger's Cage, Subtlety with Spell Pierce. Keep 4 Force of Will (non-negotiable), 4 Wasteland (affordable at $30), and all fetchlands. Total savings: approximately $1500-2000. Win rate drops 2-3% mainly in aggressive matchups where shock land damage matters."},
]

outpath = os.path.join(os.path.dirname(__file__), "..", "data", "training", "budget_substitutions.jsonl")
with open(outpath, "w", encoding="utf-8") as f:
    for pair in pairs:
        f.write(json.dumps(pair, ensure_ascii=False) + "\n")

print(f"Written {len(pairs)} pairs to {outpath}")
