"""Generate conversation flow training data - multi-turn deck building dialogues."""
import json
import os

pairs = [
    # === PLAY STYLE INTERVIEWS ===
    {"instruction": "I like controlling the game and winning slowly. What Legacy deck should I consider?", "input": "", "output": "Great question! There are several strong control options in Legacy right now. Beanstalk Control is the most popular at 2.3% meta share - it uses Up the Beanstalk to generate card advantage off pitch spells like Force of Will and Solitude, then grinds opponents out with removal and countermagic. Jeskai Control is another option with Lightning Bolt and Swords to Plowshares for removal plus planeswalkers for inevitability. If you want something truly unique, Lands controls the game entirely through land abilities - Wasteland recursion, Maze of Ith, and Punishing Fire. What appeals to you more: traditional countermagic control, or something more unconventional?"},
    {"instruction": "I want to play combo but I do not want to lose to a single Force of Will. What are my options?", "input": "", "output": "Smart thinking. The combo decks most resilient to Force of Will are: 1) The EPIC Storm (TES) - Burning Wish gives you multiple combo routes, and you can bait Force with a less important spell then go off. 2) Doomsday - you construct your pile to play around Force by including your own countermagic in the 5 cards. 3) Painter - you have Goblin Welder to recur combo pieces that get countered, plus Red Elemental Blast becomes an unconditional counter with Painter naming blue. 4) Aluren - the combo is repeatable, so a single Force only delays you one turn. What is your experience level with combo? Some of these require more skill than others."},
    {"instruction": "I just started playing Legacy and have a small budget. What should I build?", "input": "", "output": "Welcome to Legacy! Here are the best budget entry points: Oops All Spells (~$1100) is a tier 1 combo deck with zero dual lands. It can win on turn 1 and teaches you about Legacy's interaction patterns (Force of Will, graveyard hate). Burn (~$1500) is straightforward and teaches you about Legacy's speed and life total management. Red Stompy (~$2500) teaches you about prison strategies and lock pieces. All three are tournament-competitive. Which play style appeals to you: fast combo, aggressive burn, or disruptive prison?"},
    {"instruction": "I used to play Modern Izzet Murktide. What is the closest Legacy deck?", "input": "", "output": "You will feel right at home with Izzet Delver in Legacy! It plays Murktide Regent, Dragon's Rage Channeler (in some builds), Lightning Bolt, and cantrips - all familiar from Modern. The key Legacy additions are Force of Will (free counterspell), Daze (free counter by returning an Island), Wasteland (land destruction), and Brainstorm (the best cantrip ever printed). The deck is currently tier 2 at 4.3% meta share. Dimir Tempo (UB instead of UR) is the tier 1 version that trades Bolt for Thoughtseize and Bowmasters. Would you like to start with UR for familiarity, or jump to UB for power?"},
    {"instruction": "I want to play a deck that nobody expects. Something that wins tournaments but is under 2% of the meta.", "input": "", "output": "Love the rogue deck mindset! Here are some sleeper picks: Aluren (1.2%) just won the Legacy Showcase Qualifier - it is a combo-control hybrid where opponents rarely know how to sideboard. Cradle Control (2.3%) uses Gaea's Cradle for absurd mana generation with a Green Sun's Zenith toolbox. Stiflenought (0.1%) puts a 12/12 trample on the board turn 1-2 and protects it with Force. Esper Vial (0.2%) showed up in recent Challenge top 8s. The advantage of rogue decks is that opponents make more mistakes because they do not know your deck's key cards. What colors or play style interest you?"},

    # === DECK BUILDING CONVERSATIONS ===
    {"instruction": "I want to build Dimir Tempo. What do I need?", "input": "", "output": "Here is the core shell for Dimir Tempo:\n\nThreats (12): 4 Orcish Bowmasters, 4 Murktide Regent, 4 Tamiyo Inquisitive Student (or Barrowgoyf)\n\nCantrips (8): 4 Brainstorm, 4 Ponder\n\nDisruption (12): 4 Force of Will, 4 Daze, 4 Thoughtseize\n\nRemoval (4): 2 Fatal Push, 2 Snuff Out\n\nLands (19): 4 Polluted Delta, 4 Misty Rainforest, 3 Underground Sea, 4 Wasteland, 2 Island, 1 Swamp, 1 Undercity Sewers\n\nSideboard: 4 Leyline of the Void, 2 Surgical Extraction, 2 Hydroblast, 2 Flusterstorm, 2 Null Rod, 2 Toxic Deluge, 1 Massacre\n\nTotal cost: ~$5000 with real duals, ~$2000 with Watery Grave substitutions. Would you like me to go through the card choices or discuss budget options?"},
    {"instruction": "Build me a deck that beats Dimir Tempo consistently.", "input": "", "output": "The best Dimir Tempo killers right now:\n\n1) Lands (strong favorable): Wasteland-proof mana base, Maze of Ith blanks Murktide and Bowmasters, Punishing Fire grinds out small threats, and Dark Depths threatens a 20/20 they cannot remove. Main drawback: $8000+ cost and weak to fast combo.\n\n2) Sneak and Show (favorable): Emrakul dodges all their removal and annihilator devastates their board. They need Force + Daze to stop you, and you have your own Force backup. Cost: $4000-5000.\n\n3) Ocelot Pride Midrange (close but favorable post-board): Goes wide past their one-for-one removal, does not rely on cantrips so Bowmasters is less impactful. Cost: $2500.\n\nWhich of these interests you? I can build a specific list."},
    {"instruction": "I have 4 Force of Will, 4 Brainstorm, 4 Ponder, and some fetchlands. What Legacy decks can I build with this core?", "input": "", "output": "That is an excellent starting point! Force of Will + cantrips is the foundation of every blue Legacy deck. Here is what you can build, roughly ordered by additional investment needed:\n\n1) Dimir Tempo: Add Bowmasters, Murktide, Thoughtseize, Daze, Underground Sea. (~$1500-3000 additional)\n2) Izzet Delver: Add Murktide, Lightning Bolt, Daze, Volcanic Island. (~$1500-2500 additional)\n3) Sneak and Show: Add Show and Tell, Sneak Attack, Emrakul, Atraxa, Ancient Tomb, Lotus Petal. (~$1500-2000 additional)\n4) Doomsday: Add Doomsday, Dark Ritual, Thassa's Oracle, Daze, Underground Sea. (~$1000-2000 additional)\n5) Stiflenought: Add Stifle, Phyrexian Dreadnought, Daze, Dress Down. (~$500-1000 additional)\n\nWhat is your budget for additional cards, and what play style do you prefer?"},
    {"instruction": "I pulled an Ocelot Pride and Guide of Souls from MH3. Can I build a deck around them?", "input": "", "output": "Absolutely! You have the core of the second most popular deck in Legacy - Ocelot Pride Midrange at 8.5% meta share. Here is the build:\n\nEnergy Package: 4 Ocelot Pride, 4 Guide of Souls, 4 Ajani Nacatl Pariah, 4 Amped Raptor\n\nRemoval: 4 Swords to Plowshares, 4 Solitude\n\nSupport: 4 Phelia Exuberant Shepherd, 2-4 Broadside Bombardiers\n\nLands: Arid Mesa, Marsh Flats, Windswept Heath, Plains, Mountain, Plateau (or Sacred Foundry)\n\nSideboard: Containment Priest, Mindbreak Trap, Deafening Silence, Meltdown, Surgical Extraction\n\nThis deck is relatively budget-friendly at $2500 with real Plateau, or $2200 with Sacred Foundry. The energy cards themselves are $10-30 each. It does not need Force of Will or Brainstorm, making it one of the cheapest tier 1 options. Want me to optimize the list for your local meta?"},
    {"instruction": "What if I cut the Dazes from my Dimir Tempo list for more removal?", "input": "", "output": "That is a common consideration but usually wrong for Dimir Tempo. Here is why Daze is so important:\n\n1) Free interaction on the play: Turn 1 Delver, opponent plays a spell, Daze it - you are up a threat and a counter for zero mana.\n2) Paired with Wasteland: Wasteland their land, then Daze their spell - they cannot pay the 1 because you destroyed their mana source.\n3) Tempo defines the archetype: Without Daze, you are a midrange deck pretending to be tempo. Midrange is worse at the Dimir shell than pure tempo.\n4) Combo protection: Daze protects your threats in the first 2-3 turns when it matters most.\n\nThat said, Daze IS correct to cut post-sideboard in grindy matchups where games go long and opponents have plenty of mana. Board out 1-2 Dazes against midrange and control, keep all 4 against combo. What matchup were you concerned about?"},
    {"instruction": "I keep losing to Chalice of the Void on 1. What should I change?", "input": "", "output": "Chalice on 1 is brutal against cantrip-heavy decks. Here are your options:\n\nIn-deck solutions: Force of Vigor (destroys Chalice for free by pitching a green card), Engineered Explosives on 0 (destroys Chalice when it has 0 charge counters, costs 0 so Chalice does not counter it - wait, Chalice on 1 does not stop EE on 0), Abrupt Decay (cannot be countered, destroys CMC 3 or less).\n\nDeck choice solutions: Switch to a deck where 1-mana spells are not critical. Sneak and Show (combo costs 3-4), Lands (operates through land abilities), Ocelot Pride (creature-based, most threats cost 2+).\n\nSideboard plan: Bring in all your Chalice answers and cut your worst 1-mana spells. Typical: +2 Force of Vigor, +1 Engineered Explosives, -2 Ponder, -1 Thoughtseize.\n\nWhich deck are you playing? I can give specific advice."},

    # === ITERATIVE REFINEMENT ===
    {"instruction": "My Izzet Delver list keeps losing to Orcish Bowmasters. How do I adjust?", "input": "", "output": "Bowmasters punishes your cantrips and kills your small creatures. Here are adjustments:\n\n1) Threat selection: Play Murktide Regent (survives Bowmasters trigger and blocks the 1/1), cut Dragon's Rage Channeler (dies to the ping). Consider Ethereal Forager or Tolarian Terror as additional Bolt-proof threats.\n\n2) Cantrip timing: Fetch and Brainstorm on your own turn only when necessary. Avoid end-of-turn Brainstorm against open BB mana - they will flash in Bowmasters in response.\n\n3) Removal: Ensure you have ways to kill Bowmasters: Lightning Bolt, Unholy Heat (if running delirium), or Pyroblast if they are the UB version.\n\n4) Consider switching to Dimir: If Bowmasters is everywhere in your meta, playing your own Bowmasters is better than trying to beat them. The UB shell handles the mirror better.\n\nWhat does your current list look like?"},
    {"instruction": "I want to add Uro, Titan of Nature's Wrath to my control deck. Is it worth the green splash?", "input": "", "output": "Uro is an excellent grindy card but the green splash has real costs:\n\nPros: Uro gains 3 life (matters vs aggro), draws a card, ramps, and escapes as a 6/6. In long games, Uro is nearly unbeatable card advantage.\n\nCons: Adding green requires Tropical Island ($400-600) and green fetches, stretching the mana base. More nonbasics means more vulnerability to Wasteland and Blood Moon. You also need enough green cards for the splash to be worthwhile (Endurance, Veil of Summer in sideboard).\n\nVerdict: If your meta is heavy on fair midrange and control, Uro is excellent. If your meta is combo-heavy, the splash weakens your mana base for a card you may never have time to cast. What does your local meta look like?"},
    {"instruction": "Should I play Ponder or Preordain as my second cantrip?", "input": "", "output": "Ponder in almost every case. Ponder looks at 3 cards and can shuffle them away with a fetchland if all 3 are bad, effectively seeing 4 cards. Preordain scrys 2 then draws 1, seeing only 3 cards with no shuffle option.\n\nPonder is better because: 1) It finds specific cards faster (important for combo and sideboard hate). 2) The shuffle option with fetchlands is extremely powerful. 3) It sets up Delver of Secrets flips by putting an instant/sorcery on top.\n\nPreordain is better only when: 1) You have very few fetchlands (no shuffle synergy). 2) Your deck does not play Delver. 3) You need the scry to filter away truly dead cards.\n\nIn Legacy, the answer is Ponder 99% of the time since every blue deck runs fetchlands."},

    # === META DISCUSSION ===
    {"instruction": "The Legacy metagame just shifted after a ban. How do I adapt my deck?", "input": "", "output": "When bans happen, follow this process:\n\n1) Identify the power vacuum: What decks were kept in check by the banned card? Those decks will rise. When Entomb was banned, Reanimator dropped and Oops All Spells filled the fast combo niche.\n\n2) Check your matchup spread: If the rising decks are bad matchups for you, adjust your sideboard or switch decks. If they are good matchups, your deck just got better.\n\n3) Watch the first week of results: MTGO Challenges adapt fastest. Check MTGGoldfish for the new meta percentages before making changes.\n\n4) Adjust sideboard first: Do not overhaul your main deck based on one week of data. Sideboard changes are low-risk and can be reversed.\n\n5) Give it 3-4 weeks: The meta usually stabilizes after a month. Knee-jerk reactions often target last week's boogeyman while missing the actual new best deck.\n\nWhat ban are you adapting to?"},
    {"instruction": "A new set just came out. How do I evaluate which cards might be Legacy-playable?", "input": "", "output": "Legacy card evaluation checklist:\n\n1) Mana cost: Is it 0-2 mana? Cards above 2 mana need to be exceptional (Murktide at UU with delve, True-Name Nemesis at 1UU). 3+ mana cards need to end the game or provide overwhelming value.\n\n2) Free or alternative cost: Can it be cast without paying mana? Force of Negation, Solitude, Endurance all see play because of pitch costs.\n\n3) Does it pass the Bolt test? For creatures, does it survive Lightning Bolt (3+ toughness) or provide value even if Bolted (ETB effect)?\n\n4) Does it fit an existing shell? Cards that slot into Delver, Show and Tell, D&T, or Stompy have a home immediately. Cards that need a new deck built around them rarely make it.\n\n5) Does it compare favorably to what it replaces? Barrowgoyf replaced Tarmogoyf because it grows larger more efficiently. If the new card is not better than what already exists, it will not see play.\n\nWhat cards are you evaluating?"},
    {"instruction": "My local meta is 30% Dimir Tempo, 20% combo, 20% Ocelot, 15% Stompy, 15% other. What should I play?", "input": "", "output": "With 30% Dimir Tempo, you want a deck that is favorable in that matchup since you will face it almost every round. Here is my analysis:\n\nBest choice: Lands. Very favorable vs Dimir Tempo (your biggest matchup), even vs Ocelot, acceptable vs Stompy (depends on build), weak vs combo. Sideboard heavily for combo (4 Leyline of the Void, 2 Surgical). Expected win rate: 55-60% in this field.\n\nSecond choice: Sneak and Show. Favorable vs Dimir and Stompy, even vs Ocelot, races combo. More consistent matchup spread. Expected: 53-57%.\n\nThird choice: Play Dimir Tempo yourself and win the mirror through skill and sideboard preparation. At 30% mirror, the player who knows the matchup better wins more. Expected: 50-55%.\n\nAvoid: Burn (Bowmasters everywhere), Elves (Bowmasters and combo both destroy you), pure control (too slow for combo-heavy field).\n\nWant me to build a specific list optimized for this meta?"},

    # === SPECIFIC CARD DISCUSSION ===
    {"instruction": "Tell me about Brainstorm. Why is it the best card in Legacy?", "input": "", "output": "Brainstorm is a 1-mana instant that draws 3 cards and puts 2 back on top of your library. On its own, this is mediocre - you see 3 cards but keep the same number. What makes Brainstorm broken in Legacy is fetchlands.\n\nThe Brainstorm + fetchland interaction: Cast Brainstorm, draw 3 new cards, put 2 bad cards on top, then crack a fetchland to shuffle those bad cards away. You effectively drew the best card out of 4 for 1 mana at instant speed.\n\nAdditional uses: Hide important cards from Thoughtseize by putting them on top of your library. Put back a card you want to cast next turn. Set up Counterbalance or Delver of Secrets flips by choosing what goes on top.\n\nBrainstorm is in 43% of Legacy decks. It is the single card that defines Legacy as a format. Playing blue in Legacy without Brainstorm requires a very good reason."},
    {"instruction": "Is Force of Will actually good or just necessary?", "input": "", "output": "Both. Force of Will is a bad card in terms of card economy - you spend 2 cards (Force + pitch) to counter 1 card. In a fair, grindy game, this card disadvantage is real and painful.\n\nBut Force of Will is NECESSARY because without it, combo decks would dominate Legacy. Imagine a format where Storm, Oops All Spells, and Show and Tell have no free countermagic to worry about. Turn-1 kills would be the norm, and fair Magic would be unplayable.\n\nForce is GOOD in specific contexts: protecting your own combo turn, stopping a game-winning spell, and in matchups where the tempo of the free counter matters more than the card disadvantage. Against combo, Force is excellent. Against midrange, it is often sideboarded out.\n\nThe skill of Legacy is knowing WHEN to Force. Forcing a Tarmogoyf is usually wrong. Forcing a Show and Tell is usually right. The decision point is: does this spell win the game if it resolves?"},
    {"instruction": "Why do people say Legacy is a Brainstorm format?", "input": "", "output": "Because Brainstorm shapes every aspect of Legacy deckbuilding and gameplay:\n\n1) Deckbuilding: Every blue deck runs 4 Brainstorm and 8+ fetchlands to maximize the Brainstorm-shuffle interaction. This constrains mana bases toward fetchland-heavy configurations.\n\n2) Card selection: Brainstorm means blue decks see more of their library than non-blue decks, finding answers and threats more consistently. This is why blue dominates Legacy.\n\n3) Matchup knowledge: Because Brainstorm finds specific cards reliably, Legacy rewards knowing exactly which card matters in each matchup. A Brainstorm pilot who knows to find Surgical Extraction against Doomsday will win more than one who Brainstorms blindly.\n\n4) Anti-Brainstorm strategies: Non-blue decks must either be fast enough that Brainstorm does not matter (combo, aggro), or disruptive enough to prevent Brainstorm from being effective (Chalice on 1, Narset Parter of Veils, Spirit of the Labyrinth).\n\n5) The counterplay: Orcish Bowmasters punishes Brainstorm's card draw, which is why Bowmasters reshaped Legacy."},
]

outpath = os.path.join(os.path.dirname(__file__), "..", "data", "training", "conversation_flow.jsonl")
with open(outpath, "w", encoding="utf-8") as f:
    for pair in pairs:
        f.write(json.dumps(pair, ensure_ascii=False) + "\n")

print(f"Written {len(pairs)} pairs to {outpath}")
