"""Generate training data - Mega batch 7. Push toward 1500 with heavy expansion across all categories."""
import json
import os

rules = [
    {"instruction": "How does Wasteland interact with fetch lands the opponent controls?", "input": "", "output": "You can Wasteland an opponent's uncracked fetchland, destroying it before they can search. They lose the land and get nothing. If they crack the fetchland in response to Wasteland, they pay 1 life and search normally while Wasteland's target becomes illegal and the ability fizzles. The correct play is usually to Wasteland during their upkeep or in response to them tapping out, when they might not have priority to crack it first. However, mana abilities (including fetchland activations) can be activated at any time with priority, so they can always respond."},
    {"instruction": "What is the interaction between Thespian's Stage and Vesuva?", "input": "", "output": "Thespian's Stage copies a land by paying 2 and tapping. Vesuva enters as a copy of any land already in play. Both can copy Dark Depths for the Marit Lage combo. The key difference: Stage copies at instant speed (activated ability) while Vesuva copies only on entry. Stage is better because you can hold it and activate at the best moment. With Dark Depths in play, Stage copies it, enters as a Dark Depths with 0 ice counters (Stage had none), triggering the sacrifice and creating Marit Lage."},
    {"instruction": "Can I use Surgical Extraction on a card that is on the stack?", "input": "", "output": "No. Surgical Extraction targets a card in a graveyard, not on the stack. You can only Surgical a card after it has resolved (if it is an instant or sorcery that went to the graveyard) or after a permanent has been destroyed and gone to the graveyard. If your opponent casts Dark Ritual, you cannot Surgical it while it is on the stack. You must wait until it resolves and goes to the graveyard, then Surgical in response to their next spell. Against Doomsday, wait until Doomsday goes to the graveyard after resolving, then Surgical the Oracle from the 5-card pile they just made."},
    {"instruction": "How does Trinisphere work with alternative costs?", "input": "", "output": "Trinisphere makes all spells cost at least 3 mana to cast. This applies AFTER all other cost modifications. Force of Will's alternative cost is exile a blue card + 1 life. With Trinisphere, the total cost must be at least 3, so Force of Will costs exile a blue card + 1 life + 3 mana. Daze's alternative cost is return an Island. With Trinisphere, Daze costs return an Island + 3 mana. Even free spells like Lotus Petal (0 mana) cost 3 mana to cast. Trinisphere is devastating against Legacy's efficient spell base and is a key prison piece in Red Stompy."},
    {"instruction": "What happens if I exile a card with Imprint but the Imprinted card later leaves exile?", "input": "", "output": "Once a card is imprinted (e.g., Chrome Mox), removing it from exile does not change Chrome Mox's function. Imprint creates a link between the artifact and the exiled card. If the exiled card somehow leaves exile (very rare), Chrome Mox no longer has an imprinted card and cannot produce mana. In practice, this almost never happens because cards in exile are extremely difficult to move. The relevant Legacy interaction: if you imprint a card on Chrome Mox and your opponent casts Pull from Eternity to return the imprinted card to the graveyard, Chrome Mox stops producing mana."},
    {"instruction": "Can you cast a spell during the cleanup step?", "input": "", "output": "Normally no. The cleanup step is when you discard to hand size and damage wears off. Players do not normally receive priority during cleanup. However, if a triggered ability triggers during cleanup (e.g., Madness triggers from discarding), the triggered ability goes on the stack, and players DO receive priority. After resolving everything, there is another cleanup step. This means if you have Madness cards and discard to hand size, you can cast them. In Legacy, this is rare but relevant with Faithless Looting discarding Madness cards."},
    {"instruction": "What is the difference between a spell and a permanent?", "input": "", "output": "A spell exists only on the stack while being cast. Once it resolves, if it is a permanent type (creature, artifact, enchantment, planeswalker, land), it becomes a permanent on the battlefield. If it is an instant or sorcery, it goes to the graveyard after resolving. A card is a 'spell' only while on the stack. Force of Will counters SPELLS, not permanents. Abrupt Decay destroys PERMANENTS, not spells. This is why you cannot Force of Will a creature that is already in play - it is no longer a spell. Conversely, you cannot Abrupt Decay a spell on the stack - it is not yet a permanent."},
    {"instruction": "How does Griselbrand's activated ability work?", "input": "", "output": "Griselbrand has: Pay 7 life: Draw 7 cards. This is an activated ability that can be activated at instant speed any number of times as long as you have 7+ life and Griselbrand is in play. After Reanimating Griselbrand (costing 8 life, leaving you at ~12 life), you can activate once to draw 7 (going to 5 life), finding more reanimation spells, countermagic, and threats. If you started at 20 and Reanimate cost 8 (going to 12), you activate twice to draw 14 cards (going to -2... wait, you would die at 0). At 12 life, you activate once (12-7=5 life, draw 7). The life management is critical."},
    {"instruction": "Does Pithing Needle stop triggered abilities?", "input": "", "output": "No. Pithing Needle prevents activated abilities of the named card from being activated. Triggered abilities still trigger normally. Example: naming Aether Vial with Needle prevents the tap ability (putting creatures in play) but does NOT prevent the upkeep trigger (gaining a charge counter). Naming Orcish Bowmasters with Needle does nothing useful because Bowmasters' ability is triggered (when opponent draws), not activated. Naming Thespian's Stage prevents the copy activation (stops the Dark Depths combo). Always name activated abilities, not triggered ones."},
    {"instruction": "What is the interaction between Daze and Spell Pierce?", "input": "", "output": "Both are conditional counterspells. Daze counters unless opponent pays 1 (your cost: return an Island). Spell Pierce counters noncreature spells unless opponent pays 2 (your cost: U). They can be used together for layered disruption: cast Spell Pierce first, if they pay 2, then Daze, and they need another 1 mana (total 3 extra mana to resolve one spell). Or vice versa. Against a turn-2 Show and Tell with opponent having 3 mana, Daze forces them to use their extra mana, then Spell Pierce catches them with no mana left."},
    {"instruction": "How does the Monarch mechanic work in Legacy?", "input": "", "output": "The Monarch is a game designation: at the beginning of your end step, if you are the Monarch, you draw an extra card. You become the Monarch when a card says so (Palace Jailer, Court of Grace) or when a creature deals combat damage to the current Monarch. In Legacy, Monarch is most relevant in Death and Taxes (Palace Jailer exiles a creature and makes you Monarch). The extra card per turn is powerful card advantage. Opponents must attack you with a creature to steal Monarch, which conflicts with blocking strategies. If no creature deals damage to you, you draw an extra card every turn indefinitely."},
    {"instruction": "Can I Stifle a planeswalker's loyalty ability?", "input": "", "output": "No. Planeswalker loyalty abilities are activated abilities, not triggered abilities. Stifle counters triggered abilities and activated abilities. Wait - Stifle says 'counter target activated or triggered ability.' So yes, you CAN Stifle a planeswalker loyalty ability! The loyalty cost (adding or removing counters) is paid as a cost and is not refunded. So if your opponent activates Jace the Mind Sculptor's +2 (gaining 2 loyalty counters), you can Stifle the ability. Jace already gained the counters (cost paid) but the effect (look at top card, put on top or bottom) does not happen. This is a powerful but uncommon play."},
    {"instruction": "What happens when a player controls no lands and has cards in hand that cost mana?", "input": "", "output": "They are effectively locked out until they draw a land or have an alternative way to generate mana. Cards like Lotus Petal, Chrome Mox, Elvish Spirit Guide, and Simian Spirit Guide produce mana without lands. Daze and Force of Will can be cast without mana using alternative costs. In Legacy, the Wasteland + Daze combination can create this scenario: destroy their only land with Wasteland, then Daze any spell they try to cast. If they cannot find another land or free mana, they are soft-locked. This is why running 2-4 basic lands is essential - basics cannot be Wastelanded."},
    {"instruction": "Does Emrakul's protection from colored spells prevent Jace from bouncing it?", "input": "", "output": "Jace the Mind Sculptor's -1 ability says 'return target creature to its owner's hand.' This is an ability of a permanent (Jace), not a spell. Protection from colored SPELLS does not protect against abilities of colored permanents. However, Jace IS a blue permanent. Protection prevents damage, enchanting, blocking, and TARGETING from sources with the protected quality. Since Jace's ability targets Emrakul and Jace is a colored permanent... wait. Protection from colored SPELLS specifically means spells, not permanents or abilities. Jace's ability is not a spell. So Jace CAN bounce Emrakul with the -1. This is why Show and Tell decks fear resolved Jace."},
]

card_eval = [
    {"instruction": "Is Stifle Legacy-playable?", "input": "", "output": "Situationally yes. Stifle costs U and counters any activated or triggered ability. It counters fetchland activations (1-mana Stone Rain), Storm triggers (stops all copies), cascade triggers, and ETB effects. It was a staple in RUG Delver alongside Wasteland for mana denial. In the current meta, Stifle is less common because Dimir Tempo prefers Thoughtseize for proactive disruption. But in Stiflenought (Stifle + Phyrexian Dreadnought), it is essential. Meta-dependent card that shines when opponents rely on activated/triggered abilities."},
    {"instruction": "Is Punishing Fire Legacy-playable?", "input": "", "output": "Yes, specifically in Lands. Punishing Fire costs 1R for 2 damage to any target. With Grove of the Burnwillows (which gains the opponent 1 life when tapped for mana), you can return Punishing Fire from the graveyard to your hand whenever an opponent gains life. This creates an infinite loop: tap Grove (opponent gains 1 life), return Fire, cast Fire (deal 2 damage). This grinds out any creature-based strategy over time. The combo sees play almost exclusively in Lands where Grove is a natural mana source."},
    {"instruction": "Is Surgical Extraction Legacy-playable?", "input": "", "output": "Yes, it is one of the most played sideboard cards at 25% of decks. Surgical costs 0 mana (2 life via Phyrexian mana) and exiles all copies of a named card from opponent's hand, graveyard, and library. Key targets: Thassa's Oracle (kills Doomsday and Oops), Life from the Loam (cripples Lands), Reanimate targets (stops Reanimator), Show and Tell (leaves them with creatures they cannot cheat). The 0 mana cost means you can use it while tapped out. The hand and library exile provides information and removes future threats."},
    {"instruction": "Is Delver of Secrets still Legacy-playable in 2026?", "input": "", "output": "Yes, but less than its peak. Delver of Secrets is technically a 1-mana creature that flips into a 3/2 flyer - an excellent rate. In Izzet Delver (4.3% meta), it remains the namesake threat. However, Dimir Tempo (14.6%) has largely moved away from Delver in favor of Barrowgoyf and Tamiyo, which provide more consistent value without requiring the coin-flip of Delver's upkeep trigger. Delver is still Legacy-playable but is no longer the default 1-drop in the best blue tempo deck."},
    {"instruction": "Is Endurance Legacy-playable?", "input": "", "output": "Yes, as both maindeck and sideboard card. Endurance is a 3/4 reach for 1GG or pitch a green card for free. The ETB shuffles a target player's graveyard into their library. This serves as: instant-speed graveyard hate (disrupts Reanimator, Dredge, Doomsday piles), a flash blocker (3/4 reach blocks Murktide Regent for a turn), a green pitch for Force of Vigor, and a Green Sun's Zenith target. At 8% of decks, it is the premier green sideboard card and sometimes makes the main in BUG and Bant builds."},
    {"instruction": "Is Veil of Summer Legacy-playable?", "input": "", "output": "Yes, as a powerful sideboard card. For G, Veil of Summer makes you and your spells uncounterable by blue or black spells, prevents you from being targeted by blue or black spells, and draws a card if an opponent has cast a blue or black spell this turn. In Legacy, where blue (Force of Will, Daze) and black (Thoughtseize, Fatal Push) dominate interaction, Veil shuts down an entire turn of disruption for 1 mana while replacing itself. It is the green equivalent of Pyroblast but broader."},
    {"instruction": "Is Monastery Swiftspear Legacy-playable?", "input": "", "output": "Only in Burn. Swiftspear is a 1/2 haste with prowess for R. In Burn, it attacks for 1 immediately and grows with each burn spell cast (prowess triggers). A typical Burn turn: Swiftspear, Bolt, Bolt = Swiftspear attacks for 3 (base 1 + 2 prowess) plus 6 from Bolts = 9 damage. Outside of Burn, the 1/2 body is too fragile for Legacy (dies to Bowmasters' ping) and lacks the card advantage or utility that Legacy creatures need."},
    {"instruction": "Is Sylvan Library Legacy-playable?", "input": "", "output": "Yes, it is one of the best card advantage engines in Legacy. For 1G, Sylvan Library lets you draw 2 extra cards during your draw step, then choose to put any back (or keep for 4 life each). This is effectively Ancestral Recall every turn with a life cost. In green midrange and control decks, Library dominates long games by providing unmatched card selection. It is harder to remove than creatures (enchantment, not vulnerable to Bowmasters or Bolt) and does not require mana to activate each turn. It is in about 5-8% of Legacy decks, primarily in green-based fair strategies."},
    {"instruction": "Is Pact of Negation Legacy-playable?", "input": "", "output": "Yes, in combo decks. Pact of Negation costs 0 mana to counter a spell, with the upkeep cost of paying 3UU or losing the game. In combo decks that win on the turn they cast Pact, the upkeep cost never comes due. Oops All Spells uses it to protect the combo turn. Storm uses it as backup protection. Show and Tell uses it to force through the combo. It is NOT playable in fair decks because the upkeep cost of 5 mana is untenable in a deck that plans to survive to next turn. Pact is strictly a same-turn-win protection spell."},
    {"instruction": "Is Chrome Mox Legacy-playable?", "input": "", "output": "Yes, in prison and combo decks. Chrome Mox costs 0 and taps for any color of the imprinted card's colors. The imprint cost (exile a nonland, nonartifact card from hand) is significant card disadvantage, but the free mana enables turn-1 lock pieces (Blood Moon, Chalice, Trinisphere) that win the game outright. It is in Red Stompy, some Painter builds, and occasional combo lists. Not playable in fair decks where card advantage matters more than speed. Chrome Mox at $50-70 is a budget alternative to Mox Diamond ($400-500)."},
    {"instruction": "Is Green Sun's Zenith Legacy-playable?", "input": "", "output": "Yes, it is the backbone of green toolbox strategies. GSZ costs XG and searches your library for a green creature with mana value X or less and puts it directly onto the battlefield. For X=0, it finds Dryad Arbor (free mana dork). For X=2, it finds Collector Ouphe or Gaddock Teeg. For X=3, it finds Knight of the Reliquary or Endurance. For X=5+, it finds Craterhoof Behemoth. The toolbox flexibility in one card is unmatched. GSZ then shuffles into your library, not the graveyard, so you can draw it again. It is in Elves, Maverick, Cradle Control, and Nic Fit."},
]

deckbuilding = [
    {"instruction": "Why does Dimir Tempo play Undercity Sewers?", "input": "", "output": "Undercity Sewers is a surveil land that enters tapped and surveys 1 (look at top card, may put in graveyard) when it enters. In Dimir Tempo, the surveil fuels Murktide Regent delve and provides card selection. It is typically a 1-of that you fetch with Polluted Delta when you do not need an untapped land this turn. The tapped entry is a real cost, so you only fetch it when you can afford to lose a turn of tempo."},
    {"instruction": "Why does Sneak and Show not play Daze?", "input": "", "output": "Sneak and Show needs to reach 3-4 mana to combo (Show and Tell costs 2U, Sneak Attack costs 3R). Daze requires returning an Island, which sets you back a land drop and delays the combo by a turn. The deck already plays Force of Will for free protection, and its mana needs (Ancient Tomb, Lotus Petal) are optimized for reaching combo mana fast. Daze would be anti-synergistic: you want MORE mana, not less. Sneak and Show plays defensive countermagic (Force, Flusterstorm) instead of tempo-positive countermagic (Daze)."},
    {"instruction": "Why does Painter play Imperial Recruiter?", "input": "", "output": "Imperial Recruiter is a 1/1 for 2R that tutors any creature with power 2 or less to your hand. In Painter, this finds: Painter's Servant (1/3, the combo piece), Goblin Welder (1/1, artifact recursion), Goblin Engineer (1/1, artifact tutor), and Magus of the Moon (2/2, Blood Moon on a body). Recruiter turns every creature in the deck into a toolbox target. The 2R cost is manageable with Ancient Tomb. It is a critical consistency piece that finds whichever half of the combo you are missing."},
    {"instruction": "Why do some Dimir Tempo lists play Barrowgoyf over Tarmogoyf?", "input": "", "output": "Barrowgoyf from MH3 counts card types in your graveyard only, not both graveyards. This is better with Leyline of the Void (which exiles opponent's cards, shrinking their graveyard and thus old Tarmogoyf). Barrowgoyf also has a self-mill ability that fuels its own growth and Murktide's delve. In the current meta where 36% of decks play Leyline, Barrowgoyf is more reliable than Tarmogoyf. The trade-off: Barrowgoyf cannot grow from opponent's card types, making it slightly smaller in games without graveyard hate."},
    {"instruction": "Why does Eldrazi play Thought-Knot Seer over other 4-drops?", "input": "", "output": "Thought-Knot Seer is a 4/4 for 3C (3 colorless + 1 colorless from Eldrazi Temple = castable turn 2) that exiles a card from the opponent's hand on ETB. This combines disruption and a threat in one card. The hand exile is better than Thoughtseize in some ways: it exiles (no graveyard interactions) and takes any nonland card. The 'draw a card when it leaves' downside is acceptable because the 4/4 body often trades favorably in combat. No other 4-drop provides this combination of disruption and clock for a colorless deck."},
    {"instruction": "Why does Burn play Price of Progress?", "input": "", "output": "Price of Progress deals 2 damage per nonbasic land the opponent controls. In Legacy, most decks run 15-18 nonbasic lands. Against a typical Dimir Tempo mana base with 3 Underground Sea, 4 Wasteland, and 4 fetchlands in play (some cracked), Price of Progress often deals 6-10 damage for just 1R. This is the most efficient burn spell in Legacy against multi-color decks. Against mono-color decks with many basics (Burn mirror, Red Stompy), Price is much weaker. It is why budget Legacy mana bases with shock lands are especially vulnerable to Burn."},
    {"instruction": "Why does D&T play Skyclave Apparition?", "input": "", "output": "Skyclave Apparition is a 2/2 for 1WW that exiles a nonland, nontoken permanent with mana value 4 or less when it enters. In Legacy, this hits almost everything: Murktide Regent (MV 7... wait, Murktide has MV 7 but delve reduces the COST, not the mana value. Murktide has MV 7, so Apparition cannot exile it). It DOES hit: Orcish Bowmasters (MV 2), Delver (MV 1), Painter's Servant (MV 2), Chalice of the Void (MV 0 on battlefield), Up the Beanstalk (MV 2). When Apparition leaves, opponent gets a token. Flickerwisp can exile Apparition to reset the trigger, permanently exiling the target."},
    {"instruction": "Why do Legacy decks rarely play creatures that cost 4 or more mana?", "input": "", "output": "Legacy's speed demands mana efficiency. By turn 4, combo decks have already won or been stopped, tempo decks have a threat + multiple disruption pieces deployed, and prison decks have 2-3 lock pieces in play. A 4-mana creature that just attacks is too slow. The exceptions prove the rule: Murktide Regent costs UU with delve (effectively 2 mana), Emrakul is cheated into play (never cast for 15), Thought-Knot Seer disrupts on ETB, and Karn the Great Creator is a toolbox. Every 4+ mana card in Legacy must either be cheated into play or provide game-altering value on ETB."},
    {"instruction": "How do you decide between Thoughtseize and Cabal Therapy?", "input": "", "output": "Thoughtseize costs B and lets you see the opponent's hand and take any nonland card. Guaranteed information and targeted disruption. Cabal Therapy costs B and you NAME a card without seeing their hand. If correct, they discard all copies. It has flashback by sacrificing a creature. Thoughtseize is better when: you do not know what the opponent has, you need reliable disruption, and you have no sacrifice fodder. Cabal Therapy is better when: you have seen their hand (from Probe or prior Thoughtseize), you have expendable creatures (Elves, Veteran Explorer in Nic Fit), and you want to strip multiple copies. Most decks play Thoughtseize for reliability."},
]

deck_analysis = [
    {"instruction": "How do I evaluate whether a new deck archetype will stick in Legacy or fade away?", "input": "", "output": "Look for these signals: 1) Multiple independent players achieving results (not just one pilot's pet deck). 2) The deck attacks a real metagame weakness, not just a theoretical one. 3) Core cards are genuinely powerful in Legacy's context (pass the Bolt test, survive Bowmasters, interact with combo). 4) The deck has a plan for the top 3 metagame decks. 5) It maintains results over 4+ weeks of data. Red flags: reliance on opponent's lack of familiarity (surprise factor wears off), single card dependence that folds to one removal spell, and poor combo matchup without sideboard improvement. Ocelot Pride stuck because energy cards are genuinely powerful; many MH3 experiments faded because they were worse than existing options."},
    {"instruction": "What does it mean when a deck has a 'transformational sideboard'?", "input": "", "output": "A transformational sideboard changes the deck's primary strategy post-board to dodge specific hate. Classic example: Storm siding into Young Pyromancer beatdown when opponents bring in anti-storm cards (Mindbreak Trap, Deafening Silence). The opponent's hate becomes dead cards while you attack with a creature plan they were not prepared for. Modern example: Doomsday siding into a Show and Tell package when opponents bring in graveyard hate and Surgical Extraction. Requirements: 8-10 sideboard slots for the transformation, enough overlap in mana base to support both plans, and opponents actually bringing in narrow hate that the transformation dodges."},
    {"instruction": "What is a meta deck vs a rogue deck in Legacy?", "input": "", "output": "A meta deck is an established archetype with a known decklist, documented matchup spreads, and regular top finishes. The top 20 decks by meta share are 'meta decks.' Players prepare their sideboards for these. A rogue deck is an unconventional strategy that falls outside the expected metagame. It might be a completely new archetype, an unusual combination of existing cards, or a forgotten strategy making a comeback. Rogue decks benefit from surprise: opponents do not know how to mulligan, sideboard, or sequence against them. The downside: rogue decks are often rogue for a reason - they may have structural weaknesses that meta decks have already solved."},
    {"instruction": "How do I track my Legacy results to improve?", "input": "", "output": "Create a spreadsheet or use an app with these columns: Date, Opponent Deck, Game 1 Result, Game 2 Result, Game 3 Result, Match Result, Notes on key decisions. Track at least 30 matches for statistical significance. Analyze: 1) Overall win rate (target 55%+). 2) Per-archetype win rates (identify your best and worst matchups). 3) Game 1 vs games 2-3 win rate (if game 1 is much worse, your maindeck needs adjustment; if games 2-3 are worse, your sideboard needs work). 4) Play vs draw win rate (some decks are much better on the play). 5) Mulligan win rate (are you mulliganing correctly?). Review notes from losses to find patterns of mistakes."},
    {"instruction": "What are the key differences between paper Legacy and MTGO Legacy?", "input": "", "output": "Metagame differences: MTGO tends to have more combo and less fair midrange because combo is easier to execute with automated rules enforcement. Paper has more creature-based decks and fewer complex combos because physical play is slower. MTGO adapts to meta shifts faster (daily leagues provide immediate data) while paper metas lag by 1-2 weeks. Card availability: MTGO is cheaper so more players can play tier 1 decks; paper has more budget and rogue decks. Play patterns: MTGO has chess clocks (25 minutes per player) so slow decks like Miracles and Lands are penalized. Paper has 50-minute rounds for the match, favoring decks that go to time (Lands, D&T). Skill expression: MTGO removes all bluffing and body language (cannot represent Daze by pausing before passing priority... well, you can hold priority deliberately)."},
    {"instruction": "Should I register a deck I have practiced 100+ matches with or the theoretically best deck I have played 5 times?", "input": "", "output": "Always register the deck you know. Legacy rewards format knowledge and deck mastery more than any other format. A player with 100 matches on a tier 2 deck will outperform a player with 5 matches on a tier 1 deck because: 1) You know every sideboard plan by heart. 2) You recognize key decision points instantly. 3) You know your mulligan thresholds precisely. 4) You play faster and more confidently, making fewer mistakes. 5) You have seen edge cases and unusual board states that new pilots miss. The competitive edge from deck mastery is estimated at 5-10% win rate over an equally skilled but less experienced pilot."},
]

conversation = [
    {"instruction": "What should I do between rounds at a Legacy tournament?", "input": "", "output": "Between rounds: 1) Write down your opponent's deck and any unusual cards you saw. This helps future matchup preparation. 2) Review the match: what decisions could you have made differently? 3) Eat and hydrate. Tournaments are long and mental fatigue causes mistakes. 4) Check standings if available - knowing your likely opponents helps plan ahead. 5) Do NOT obsess over a loss. Reset mentally for the next match. 6) If time permits, watch a match involving a deck you might face to scout their list. 7) Review your sideboard plan for the most likely next-round opponent. The players who perform best at tournaments are the ones who stay focused and mentally fresh throughout the day."},
    {"instruction": "My friend and I want to playtest Legacy but we only own two decks. How do we get the most out of testing?", "input": "", "output": "Maximize two-deck testing with this structure:\n\n1) Play 10 pre-board games. Track who wins each one. This establishes your game 1 matchup.\n\n2) Develop sideboard plans for both sides. Write them down.\n\n3) Play 10 post-board games. Track results. Compare to game 1 results.\n\n4) Switch decks and repeat. Playing both sides teaches you what the opponent is trying to do, which improves your play when you switch back.\n\n5) After 20+ games each way, discuss: what were the key cards? What lines won the most? What sideboard cards overperformed or underperformed?\n\n6) Adjust decklists and repeat.\n\nEven with just 2 decks, this deep matchup knowledge is more valuable than superficial experience across 10 decks. You will know this matchup better than anyone at a tournament."},
    {"instruction": "I want to build a Legacy gauntlet for testing. What decks should I include?", "input": "", "output": "A minimum viable Legacy gauntlet covers the top macro-strategies:\n\n1) Dimir Tempo (tier 1 tempo, 14.6%): the deck to beat\n2) Oops All Spells (tier 1 fast combo, 8.2%): tests your combo interaction\n3) Sneak and Show (tier 1 midrange combo, 6.7%): tests your ability to stop resolved permanents\n4) Ocelot Pride (tier 1 aggro/midrange, 8.5%): tests your creature interaction\n5) Red Stompy (tier 2 prison, 2.7%): tests your ability to play through Chalice and Blood Moon\n6) Death and Taxes (tier 2 hatebears, 2.0%): tests your ability to fight through taxes\n\nThese 6 decks cover: tempo, fast combo, midrange combo, aggro, prison, and hatebears - representing ~42% of the total metagame. If your deck has positive matchups against all 6, it is well-positioned."},
    {"instruction": "How do I learn to play Brainstorm correctly?", "input": "", "output": "Brainstorm mastery comes in stages:\n\nStage 1 (beginner): Cast Brainstorm, put back 2 bad cards, crack fetchland. This is correct 80% of the time.\n\nStage 2 (intermediate): Think before casting. Ask: do I have a fetchland? What am I looking for? Is now the right time? Hold Brainstorm if you do not have a shuffle effect.\n\nStage 3 (advanced): Consider what to put back in the context of the matchup. Against Thoughtseize, put important cards on TOP (they cannot take them). Consider putting back cards that are good later but not now (a sweeper you do not need yet).\n\nStage 4 (expert): Brainstorm in response to specific triggers. Brainstorm in response to Thoughtseize to hide cards. Brainstorm before your draw step to set up Delver flips. Brainstorm to put back a card you want to Daze (return Island, draw the card you put back).\n\nThe difference between a good and great Legacy player is often just Brainstorm decisions. Play 100+ games focusing specifically on Brainstorm timing before moving on to other skills."},
    {"instruction": "What is the etiquette for Legacy tournaments?", "input": "", "output": "Legacy community norms:\n\n1) Be friendly and discuss games after the match. Legacy players love talking about the format.\n\n2) Announce triggers clearly, especially Bowmasters, Delver flips, and Vial counters. Missing triggers in competitive play can result in judge calls.\n\n3) Do not slow play. Legacy has complex board states but players are expected to play at a reasonable pace. If you are thinking for a long time, say so.\n\n4) Shuffle your opponent's deck after they search. This is standard procedure.\n\n5) Call a judge if you are unsure about a rules interaction. Judges are neutral arbiters and calling one is NOT rude.\n\n6) Do not scoop early if your opponent needs practice playing through a win. Many players appreciate seeing the combo or kill in action.\n\n7) If playing with proxies (at stores that allow them), make sure they are clearly readable and distinguishable. Good proxy etiquette means your opponent can easily read your cards."},
]

board_state = [
    {"instruction": "Board state: I have Chalice of the Void on 1 and my opponent just cast Abrupt Decay targeting it. Can I counter Abrupt Decay?", "input": "", "output": "No. Abrupt Decay has 'this spell can't be countered' which means no counter effect works against it. Additionally, even though Abrupt Decay has mana value 2 (not 1), so your Chalice on 1 would not have countered it anyway. Your Chalice is going to be destroyed. The only ways to protect against Abrupt Decay are: 1) prevent it from being cast (Thoughtseize it, Thalia taxes it), 2) give your permanent hexproof or shroud (Sterling Grove protects enchantments), 3) sacrifice the targeted permanent in response for value. Against Abrupt Decay specifically, proactive disruption is the only reliable answer."},
    {"instruction": "Board state: My opponent has Solitary Confinement in play (prevent all damage, skip draw step, shroud). I cannot target them or deal damage. How do I win?", "input": "", "output": "Solitary Confinement prevents damage and gives shroud (cannot be targeted), but it requires discarding a card at upkeep and the controller skips their draw step. Options: 1) Wait. If they cannot draw cards, they will eventually run out of cards to discard and Confinement is sacrificed. Enchantress draws cards from enchantments to sustain it, so you need to disrupt their draw engine. 2) Destroy Confinement: it has shroud so targeted removal fails. Use non-targeting removal: Engineered Explosives on 3, Oblivion Stone, Council's Judgment, or Cryptic Command's bounce mode. 3) Force them to sacrifice: Liliana of the Veil's -2 makes them sacrifice a permanent (you choose which eventually empties their board). 4) Win without damage: Tendrils of Agony causes LOSS OF LIFE, not damage. Confinement prevents damage but not life loss. Storm can win through Confinement!"},
    {"instruction": "Board state: I control a flipped Delver (3/2 flyer). Opponent controls Orcish Bowmasters (1/1) and Orc Army (2/2). I have Lightning Bolt in hand. What is the best attack/removal sequence?", "input": "", "output": "Key decision: what to Bolt. Option A: Bolt Bowmasters (kills the 1/1). Army stays as 2/2. Attack with Delver for 3 (opponent goes to -3 if they block with Army and Delver dies, or takes 3 if they do not block). Option B: Bolt the Army (2 damage does not kill a 2/2... wait, Army has 2 toughness, Bolt does 3, Army dies). Army dies, Bowmasters stays as 1/1. Attack with Delver for 3 (opponent blocks with 1/1 Bowmasters, your 3/2 kills their 1/1, you take 0). Option C: Bolt opponent's face for 3, attack for 3 = 6 damage total but their board stays.\n\nBest line: Bolt Bowmasters first (kill the value engine that triggers on every cantrip). Then attack with Delver into the 2/2 Army - they can block (trade: Delver dies, Army dies) or take 3. Killing Bowmasters is priority #1 because it generates value every turn you cantrip."},
    {"instruction": "Board state: I am playing Lands. I have Exploration, 3 lands in play, and Life from the Loam plus Wasteland plus Ghost Quarter in hand. Opponent has 2 nonbasic lands. Can I destroy both this turn?", "input": "", "output": "Yes! With Exploration, you can play 2 lands per turn. Sequence: 1) Play Wasteland from hand (land drop 1 of 2 via Exploration). 2) Activate Wasteland, sacrificing it, destroying opponent's first nonbasic. 3) Play Ghost Quarter from hand (land drop 2 of 2). 4) Activate Ghost Quarter, sacrificing it, destroying opponent's second nonbasic (they search for a basic). You destroyed both nonbasics. Ghost Quarter gives them a basic, but Wasteland does not. Next turn, dredge Life from the Loam to return Wasteland + Ghost Quarter + another land to hand, and do it again. With Exploration, you destroy 2 lands per turn indefinitely."},
    {"instruction": "Board state: Both players are in topdeck mode (no cards in hand). I have 3 lands. Opponent has a Jace the Mind Sculptor at 6 loyalty. What am I hoping to draw?", "input": "", "output": "You need to kill Jace immediately or you lose to the +2 every turn (opponent controls your draws). Best topdecks: 1) Orcish Bowmasters (flash in, ping Jace for 1, attack for 1 next turn = slow but possible). 2) Lightning Bolt (3 damage to Jace, goes to 3 loyalty, need another bolt). 3) Murktide Regent (if graveyard has 5+ cards, cast for UU, attack Jace for 3+, need another attack). 4) Council's Judgment (exiles Jace for 1WW). 5) Abrupt Decay (destroys permanent MV 3 or less... Jace is MV 4, cannot be Decayed). 6) Wasteland (does not help vs Jace). 7) Any creature with 7+ power to kill Jace in one attack (rare in topdeck mode). You are in a very bad position. Jace in topdeck mode is nearly game over because the +2 controls what you draw."},
]

budget = [
    {"instruction": "What is the cheapest path from zero to a complete Legacy collection?", "input": "", "output": "The cheapest path starts MTGO and transitions to paper:\n\nMonth 1-3 (MTGO, $300): Rent or buy a budget MTGO deck (Oops $100, Burn $50). Play 50+ leagues to learn the format.\n\nMonth 4-6 (Paper entry, $500): Buy Burn in paper ($1500) or Oops ($1100). These share zero cards with your MTGO deck, but you now have paper Legacy.\n\nMonth 7-12 (Upgrade, $200/month): Buy Force of Will ($400), fetchlands ($200), and save for your first dual land.\n\nMonth 13-18 (Second deck, $200/month): Build Dimir Tempo with 1-2 real Underground Seas + shock lands for the rest.\n\nMonth 19-24 (Complete, $200/month): Fill out dual lands, acquire sideboard staples, build a third deck.\n\nTotal 2-year investment: ~$5000 for 2-3 competitive paper decks + MTGO account. Reserved List purchases appreciate, so your collection value actually increases over time."},
    {"instruction": "Rank the Legacy dual lands by importance for a new player.", "input": "", "output": "Ranked by how many decks use them:\n\n1) Underground Sea ($600-800): Goes in Dimir Tempo (14.6%), Doomsday, Storm, Reanimator, BUG decks. The #1 most played dual.\n2) Volcanic Island ($500-700): Goes in Izzet Delver (4.3%), Sneak and Show (6.7%), Jeskai, UR decks.\n3) Tundra ($300-500): Goes in UW Control, Miracles, Stoneblade, D&T splash.\n4) Tropical Island ($400-600): Goes in Infect, RUG builds, Aluren, BUG splash.\n5) Bayou ($300-500): Goes in Elves, BUG, Nic Fit, Aluren.\n6) Badlands ($200-400): Goes in Reanimator, BR builds.\n7) Plateau ($200-350): Goes in Painter, Boros Initiative.\n8) Scrubland ($200-400): Goes in D&T BW, Deadguy Ale.\n9) Savannah ($200-400): Goes in Maverick, Enchantress.\n10) Taiga ($200-400): Goes in Lands (1-of), RUG builds.\n\nBuy Underground Sea first if you want to play blue-black. Buy Volcanic Island if you want to play blue-red."},
    {"instruction": "Is it worth buying MTGO cards or should I just rent?", "input": "", "output": "Depends on how long you plan to play:\n\nRenting (Cardhoarder, Manatraders): $20-50/month for access to any deck. Best for: trying multiple decks, short-term play, testing before buying paper. Downside: ongoing cost, must return cards when subscription ends.\n\nBuying: $300-600 one-time for a full deck. Best for: committed players who play weekly, long-term value (cards retain 80-90% resale value). Downside: capital locked up, one deck unless you buy more.\n\nMath: renting at $30/month x 12 months = $360/year. Buying Dimir Tempo at $450 and selling after a year at $380 = $70 net cost. Buying is cheaper after ~6 months of play. But renting lets you try different decks.\n\nRecommendation: rent for the first 2-3 months while you find your deck, then buy once you commit."},
    {"instruction": "My entire Legacy budget is $200. What can I build?", "input": "", "output": "$200 is extremely tight for paper Legacy but you have options:\n\n1) Ruby Storm (~$200-300): Mono-red storm with Ruby Medallion, Birgi, Bonus Round. No Force of Will, no dual lands, no fetchlands. Competitive at tier 3 level. The cheapest functional Legacy combo deck.\n\n2) Mono Red Burn (budget version, ~$200): Skip Goblin Guide ($10 each), Eidolon ($8 each), and fetchlands. Replace with Monastery Swiftspear, Searing Blood, and Mountains. Functional but weaker.\n\n3) Proxy the rest: If your LGS allows proxies, $200 buys the non-proxy cards (sleeves, basic lands, cheap staples) and you proxy the expensive ones. This is the most competitive option.\n\n4) MTGO: $200 buys a full competitive MTGO deck (Burn $50, Oops $100, Ruby Storm $50) with money left for league entries.\n\nHonest answer: $200 in paper Legacy is very limiting. MTGO or proxy events are your best options at this budget."},
    {"instruction": "I want to foil out my Legacy deck. Which cards should I prioritize for foils?", "input": "", "output": "Prioritize by visibility and pimp factor:\n\n1) Basic lands: You play them every game and foil basics are cheap ($2-5). Full art or snow-covered foils look stunning.\n2) Dual lands: Judge promos or Beta duals are the ultimate flex, but expensive ($1000+). Skip unless you have deep pockets.\n3) Forces of Will: Alliances foils are iconic but warped (old foiling process). EMA or Double Masters foils are more playable.\n4) Cantrips (Brainstorm, Ponder): You cast these every game. Foil Brainstorm from Mercadian Masques is a classic.\n5) Your namesake creature (Delver, Bowmasters): The card that represents your deck.\n\nDo NOT foil: sideboard cards (only seen games 2-3), lands you fetch away quickly (fetchlands barely stay in play), or cards that rotate in and out of your list with meta shifts. Foil the cards that DEFINE your deck and that you will own for years."},
]

# Write all
categories = [
    ("rules_qa.jsonl", rules),
    ("card_evaluation.jsonl", card_eval),
    ("deckbuilding_rationale.jsonl", deckbuilding),
    ("deck_analysis.jsonl", deck_analysis),
    ("conversation_flow.jsonl", conversation),
    ("board_state_analysis.jsonl", board_state),
    ("budget_substitutions.jsonl", budget),
]

for filename, data in categories:
    outpath = os.path.join(os.path.dirname(__file__), "..", "data", "training", filename)
    with open(outpath, "a", encoding="utf-8") as f:
        for pair in data:
            f.write(json.dumps(pair, ensure_ascii=False) + "\n")
    print(f"Appended {len(data)} pairs to {filename}")
