"""Generate training data - Mega batch 8. Continue toward 1500."""
import json
import os

rules = [
    {"instruction": "How does cascade work step by step?", "input": "", "output": "When you cast a spell with cascade: 1) The cascade trigger goes on the stack above the spell. 2) Exile cards from the top of your library one at a time until you exile a nonland card with mana value less than the cascading spell. 3) You may cast that card without paying its mana cost. 4) Put all other exiled cards on the bottom of your library in a random order. Important: the cascaded spell resolves BEFORE the original spell because it goes on top of the stack. Cascade cannot find cards with equal or higher mana value. Suspend cards with no mana cost (like Ancestral Vision, MV 0) can be cascaded into because 0 is less than any positive number."},
    {"instruction": "What is the cascade suspend trick in Legacy?", "input": "", "output": "Suspend cards like Ancestral Vision and Crashing Footfalls have no mana cost (mana value 0) and can only be cast by suspend or other effects that let you cast them without paying. Cascade spells exile until hitting a card with lower MV, and MV 0 is lower than anything. So Shardless Agent (MV 3) cascading into Ancestral Vision casts it for free (draw 3 cards) without waiting for suspend. This is the basis of Cascade Crash (Crashing Footfalls = 2 free 4/4 Rhinos) and older Shardless BUG (Agent into Ancestral Vision)."},
    {"instruction": "Can I cast an instant during the resolution of another spell?", "input": "", "output": "No. While a spell is resolving, no player has priority and no spells or abilities can be cast or activated (except mana abilities). You must wait until the spell finishes resolving completely, then the active player gets priority. For example, during Show and Tell resolution, you cannot cast an instant between permanents entering play. Everything enters simultaneously, then players get priority. Similarly, while Brainstorm is resolving (drawing 3, putting 2 back), you cannot crack a fetchland in the middle."},
    {"instruction": "How does Emrakul's extra turn trigger work with Sneak Attack?", "input": "", "output": "Emrakul, the Aeons Torn says 'when you CAST Emrakul, take an extra turn after this one.' This is a cast trigger, meaning it triggers only when Emrakul is cast from hand by paying mana. Sneak Attack puts Emrakul onto the battlefield without casting it. Therefore, Sneak Attack does NOT give you an extra turn. Show and Tell also puts Emrakul into play without casting, so no extra turn. The extra turn only happens when you actually spend 15 mana to cast Emrakul from hand (extremely rare in Legacy)."},
    {"instruction": "What happens if I control two Orcish Bowmasters and my opponent draws a card?", "input": "", "output": "Each Bowmasters has its own triggered ability that triggers independently. When your opponent draws a card beyond their first of the turn, BOTH Bowmasters trigger. Each trigger amasses Orcs 1 (creating a 1/1 or adding a counter to an existing Army) and deals 1 damage to any target. So with two Bowmasters, each extra draw produces: 2 damage, Army grows by 2. Against a Brainstorm (3 draws), if it is the first draw action: draws 2 and 3 trigger both Bowmasters = 4 triggers = 4 damage, Army grows by 4. Doubled Bowmasters is devastating against cantrip-heavy decks."},
    {"instruction": "How does Lurrus of the Dream-Den's companion restriction work?", "input": "", "output": "Lurrus was a companion that required your starting deck to contain no permanent cards with mana value 3 or more. The companion mechanic was errata'd in 2020: you must pay 3 generic mana to move your companion from outside the game to your hand before casting it normally. Lurrus was banned in Legacy because the restriction was too easy to meet (most Legacy permanents cost 0-2 mana) and the guaranteed card advantage (recast a permanent from graveyard each turn) was too powerful. Yorion (80-card restriction) survives because the deckbuilding cost is more significant."},
    {"instruction": "What is the difference between hexproof, shroud, and protection?", "input": "", "output": "Hexproof: cannot be targeted by opponents' spells and abilities. You CAN target your own hexproof permanent. Shroud: cannot be targeted by ANY spells or abilities, including your own. You cannot equip, enchant, or buff a creature with shroud. Protection from [quality]: cannot be Damaged, Enchanted/Equipped, Blocked, or Targeted by sources of the named quality (DEBT). Protection is the strongest because it prevents damage too, not just targeting. Example: True-Name Nemesis (protection from a player) > hexproof because it also cannot be damaged or blocked by that player. All three can be bypassed by non-targeting effects (Toxic Deluge, Terminus, Liliana sacrifice)."},
    {"instruction": "What happens when you copy a spell with storm?", "input": "", "output": "Storm creates copies of the spell for each other spell cast before it that turn. Copies are put directly on the stack - they are NOT cast. This means: copies do not increase the storm count (they are not cast), copies cannot be cascaded (cascade triggers on cast), and copies cannot be countered by Chalice of the Void (Chalice counters cast spells with the matching MV). However, copies CAN be countered by regular counterspells (Force of Will, Flusterstorm). Flusterstorm is particularly good because its own storm creates copies that can counter each storm copy individually."},
    {"instruction": "What is the legend rule and how does it apply to both players?", "input": "", "output": "The legend rule says: if a player controls two or more legendary permanents with the same name, that player chooses one to keep and puts the rest in the graveyard. Crucially, this only applies to permanents YOU control. If you and your opponent both control a Karakas, both stay in play because each player controls only one. If Show and Tell puts your Emrakul and their Emrakul into play, both stay (different controllers). The legend rule only forces a choice when one player controls multiple of the same legend."},
    {"instruction": "Can abilities be activated while a player is searching their library?", "input": "", "output": "No. While a player is searching their library (from a fetchland, tutor, etc.), no player has priority. The searching player finds a card (or fails to find) and the effect finishes resolving. Only then do players get priority again. You cannot activate abilities or cast spells while someone is searching. However, note that the sacrifice of a fetchland happens as a COST before the search begins. So the fetchland is already in the graveyard during the search. If you need to respond to a fetchland activation, you must do so before the ability resolves (before the search starts), not during."},
    {"instruction": "What is a replacement effect vs a triggered ability?", "input": "", "output": "Replacement effects change HOW an event happens. They use 'instead' or 'as' and do not use the stack. Example: Leyline of the Void - cards go to exile INSTEAD of the graveyard. You cannot respond because the event is simply changed as it happens. Triggered abilities respond to events AFTER they happen. They use 'when', 'whenever', or 'at' and go on the stack (can be responded to). Example: Orcish Bowmasters - WHENEVER an opponent draws, trigger. The draw happens, then the trigger goes on the stack. Key difference: you can respond to triggers (Stifle them, kill the creature) but you cannot respond to replacement effects."},
    {"instruction": "How does priority work in a multiplayer Legacy game?", "input": "", "output": "In multiplayer Legacy (rare but exists in some formats), priority passes in turn order starting with the active player. After the active player passes, the next player in turn order gets priority, and so on. All players must pass in succession with an empty stack for the phase/step to end. A spell resolves only after all players pass priority in succession with it on top of the stack. This means the player immediately after the caster gets to respond first, but all players eventually get the chance. In 2-player Legacy (the norm), it is simply active player then non-active player."},
]

card_eval = [
    {"instruction": "Is Thoughtseize or Inquisition of Kozilek better in Legacy?", "input": "", "output": "Thoughtseize is significantly better. Inquisition of Kozilek hits nonland cards with MV 3 or less, which misses many critical Legacy targets: Force of Will (MV 5), Murktide Regent (MV 7), Show and Tell (MV 3... actually IoK does hit MV 3 or less, so Show and Tell IS hit). However, IoK misses Emrakul, Omniscience, Sneak Attack (MV 4), Force of Will, Force of Negation (MV 3, IS hit). The life cost of Thoughtseize (2 life) is worth the ability to hit ANY nonland card. Legacy staples like Force of Will and expensive combo pieces are too important to miss."},
    {"instruction": "Is Lightning Bolt or Chain Lightning better in Legacy Burn?", "input": "", "output": "Lightning Bolt is better overall because it is an instant (can respond to threats, deal damage at end of turn). Chain Lightning is a sorcery that deals 3 damage for R but the opponent can copy it for RR (rarely relevant in Legacy since they would rather not take 3). Burn plays 4 of BOTH because it needs maximum damage density. If forced to choose, Bolt wins: instant speed matters against creatures (kill Bowmasters in response to its trigger) and for end-of-turn damage (represent Bolt to force opponent into suboptimal plays). Chain Lightning is the 5th-8th copy of Bolt, which is still excellent."},
    {"instruction": "Is Swords to Plowshares or Path to Exile better in Legacy?", "input": "", "output": "Swords to Plowshares is dramatically better. Both cost W and exile a creature, but Swords gives the opponent life while Path gives them a land. In Legacy, life is nearly irrelevant (games are decided by board state and card quality, not life totals). But giving an opponent a land is devastating: it counteracts your Wasteland strategy, helps them cast spells through Daze, and ramps them toward their combo turn. Path to Exile is barely playable in Legacy specifically because the land ramp downside is too severe. Swords is in 21% of Legacy decks; Path is in less than 1%."},
    {"instruction": "Is Kolaghan's Command Legacy-playable?", "input": "", "output": "Marginally. Kolaghan's Command costs 1BR and has 4 modes (choose 2): deal 2 damage to any target, return a creature from graveyard to hand, opponent discards, destroy an artifact. In Legacy, 3 mana for a 2-for-1 is acceptable but not exceptional. It was strong in Czech Pile (2017-2018) where 4-color decks could cast it easily. Currently, it sees occasional play in Grixis and Rakdos builds. The artifact destruction mode is relevant against Chalice, Vial, and Urza's Saga tokens. The main limitation: 3 mana is a lot in Legacy, and more focused 1-2 mana answers often do the job better."},
    {"instruction": "Is Retrofitter Foundry Legacy-playable?", "input": "", "output": "Yes, in specific shells. Retrofitter Foundry costs 1 and can be tutored by Urza's Saga. Its activated abilities create a 1/1 Servo for 3, upgrade a Servo to a 1/1 Thopter (flying) for 1, or upgrade a Thopter to a 4/4 Construct for 1. In combination with Urza's Saga Constructs and free tokens, it provides a repeatable token engine that generates board presence without spending cards. It is best in Azorius Artifacts, D&T (with Stoneforge for equipment synergy), and UW Control with Saga. Not a standalone powerhouse but an excellent Saga tutor target."},
    {"instruction": "Is Dress Down Legacy-playable?", "input": "", "output": "Yes, as a sideboard card and occasionally maindeck. Dress Down costs 1U and removes all abilities from all creatures until end of turn, then sacrifices itself. Key interactions: 1) Enables Phyrexian Dreadnought (enters as a 12/12 with no drawback). 2) Blanks Orcish Bowmasters (no trigger), Thalia (no tax), True-Name Nemesis (no protection), Murktide Regent (loses flying, still big). 3) Draws a card (ETB cantrip). The 2-mana instant-speed ability blanking is powerful in creature-heavy matchups. The self-sacrifice means it is a one-turn effect."},
    {"instruction": "Is Back to Basics Legacy-playable?", "input": "", "output": "Yes, as a powerful sideboard and occasional maindeck enchantment. Back to Basics costs 2U and prevents all nonbasic lands from untapping. Against decks with 15+ nonbasics (most Legacy decks), this effectively locks them out of casting spells. Unlike Blood Moon (which changes land types), Back to Basics just keeps them tapped. The opponent can still tap them for mana before they would untap, but each nonbasic only gets one use then stays tapped forever. Best in mono-blue decks that run many basic Islands. At 3 mana, it is slower than Blood Moon but blue decks can protect it with Force of Will."},
    {"instruction": "Is Meltdown Legacy-playable?", "input": "", "output": "Yes, as a sideboard card against artifact strategies. Meltdown costs XR and destroys each artifact with mana value X or less. For X=1 (1R total), it destroys Chalice of the Void (MV 0 on battlefield), Aether Vial (MV 1), Lotus Petal (MV 0), and Mishra's Bauble (MV 0). For X=0 (just R), it destroys all 0-cost artifacts. It is a mass artifact sweeper that scales as needed. It sees play in red sideboards as a flexible answer to artifact-heavy strategies. The sorcery speed is a limitation but the mass destruction compensates."},
    {"instruction": "Is Force of Vigor the best artifact/enchantment hate in Legacy?", "input": "", "output": "It is the best FREE artifact/enchantment hate. For 2GG or by pitching a green card, Force of Vigor destroys up to 2 artifacts and/or enchantments. The free pitch cost is critical: it answers Chalice of the Void (which counters Nature's Claim at MV 1), destroys 2 targets for 1 card (2-for-1 or 3-for-2 including the pitch), and can be cast while tapped out. It is the premium answer to Blood Moon, Chalice, Ensnaring Bridge, The One Ring, and any double-lock board. The downside: requires a green card to pitch, so only green decks play it. Non-green decks use Engineered Explosives or Prismatic Ending instead."},
    {"instruction": "Is Null Rod Legacy-playable?", "input": "", "output": "Yes. Null Rod costs 2 and says activated abilities of artifacts cannot be activated. This shuts off: Aether Vial (no creatures), Grindstone (no combo), LED (no mana), Lotus Petal (no mana), Sensei's Divining Top (banned but illustrative), Urza's Saga tokens (no equip), and any artifact mana. It does NOT stop triggered abilities or static abilities, and it does not affect non-artifact permanents. It is devastating against Painter, 8-Cast, Affinity, Mystic Forge, and any deck reliant on artifact activations. Be careful not to play it in decks with your own artifact activations."},
]

deckbuilding = [
    {"instruction": "How do I evaluate whether to include a new card in my Legacy deck?", "input": "", "output": "Ask these questions: 1) Is it more efficient than what it replaces? Card must do the same job better or do a unique job that justifies the slot. 2) Does it survive the format's interaction? Creatures need 3+ toughness (Bolt test, Bowmasters test) or provide value on ETB. 3) Does it work with your deck's engine? In cantrip decks, cards should be blue (for Force of Will pitch). In Chalice decks, cards should not cost the Chalice number. 4) Is it good in multiple matchups? Narrow cards belong in sideboards. Maindeck cards should be useful in 60%+ of games. 5) What do you cut? Every addition requires a cut. If you cannot identify a card that is worse, the new card probably does not make it."},
    {"instruction": "Why do competitive Legacy players rarely change more than 2-3 cards between tournaments?", "input": "", "output": "Legacy decks are highly optimized over years of play. Each card slot has been tested and justified. Changing more than 2-3 cards at once makes it impossible to tell which change helped or hurt. Competitive players: 1) Change 1-2 mainboard flex slots based on expected metagame (swap removal spells, adjust threat mix). 2) Change 2-3 sideboard slots based on what they expect to face. 3) Keep the core 50-52 mainboard cards and 10-12 sideboard cards stable. The disciplined approach means you learn your deck deeply and attribute wins/losses to play decisions rather than deck construction variance."},
    {"instruction": "What is the ideal ratio of threats to interaction in a Legacy deck?", "input": "", "output": "Depends on strategy: Tempo (Dimir Delver): ~12 threats, ~16 interaction, ~8 cantrips, ~19 lands. You want enough threats to pressure but mostly disruption. Control (Beanstalk): ~4-8 win conditions, ~20 interaction, ~8 cantrips, ~24 lands. Win conditions are sparse because cantrips find them. Combo (Storm): ~6-8 combo pieces, ~8 protection, ~12 cantrips + rituals, ~15 lands. Most of the deck IS the combo. Prison (Red Stompy): ~8-12 threats, ~8-12 lock pieces, ~8 fast mana, ~20 lands. Lock pieces are both threats and interaction. The common thread: cantrips let you run fewer of any category because you find what you need."},
    {"instruction": "What makes a good sideboard card in Legacy?", "input": "", "output": "The best sideboard cards share these qualities: 1) High impact when drawn: Leyline of the Void single-handedly wins the graveyard matchup. 2) Broad applicability: Pyroblast hits Murktide AND counters Force AND kills Jace - useful against multiple blue decks. 3) Low mana cost: you need to deploy hate before the opponent executes their plan. Free cards (Leyline, Force of Vigor, Mindbreak Trap) are premium. 4) Does not hurt your own strategy: Null Rod in a deck with artifact mana is a nonbo. Leyline in a Murktide deck exiles your own graveyard... wait, Leyline only affects opponents. 5) Not already mainboard: if a card is good enough for maindeck, it should be there. Sideboard cards are specifically for targeted matchups where they dramatically improve your win rate."},
    {"instruction": "When should I play Flusterstorm vs Spell Pierce?", "input": "", "output": "Flusterstorm (U): counters target instant or sorcery unless its controller pays 1 for each copy (storm copies = your storm count). Best against: Storm (your Flusterstorm has storm too, creating enough copies to counter every Storm spell), counter wars (multiple copies counter multiple countermagic), and any stack-heavy matchup. Spell Pierce (U): counters target noncreature spell unless they pay 2. Best against: fair decks where opponents tap low (they often cannot pay 2 early), any noncreature spell. Choose Flusterstorm when: you expect Storm or counter-heavy matchups. Choose Spell Pierce when: you want to catch planeswalkers, enchantments (Up the Beanstalk), and sorceries (Show and Tell). Many players run a split for flexibility."},
    {"instruction": "Why do some Legacy players run a split of 2 Pyroblast and 2 Red Elemental Blast?", "input": "", "output": "Functionally they are almost identical: both cost R to counter a blue spell or destroy a blue permanent. The split is to play around two cards: 1) Meddling Mage: if opponent names Pyroblast, your Red Elemental Blasts still work (different card names). 2) Surgical Extraction: if opponent Surgicals your Pyroblast, your REBs survive. 3) Cabal Therapy: if named, only half your copies are hit. The strategic diversification costs nothing (both cards do the same thing) but protects against narrow hate that names specific cards. This is a Legacy-specific optimization that reflects the format's attention to detail."},
    {"instruction": "What is a 'cantrip' in Legacy and why are they so important?", "input": "", "output": "A cantrip is a spell that replaces itself by drawing a card (or providing card selection). Legacy cantrips: Brainstorm (U, draw 3 put back 2), Ponder (U, look at 3 with shuffle option), Preordain (U, scry 2 draw 1), Consider (U, surveil 1 draw 1). Cantrips are the backbone of blue Legacy because they: 1) Find specific answers (Surgical vs combo, Swords vs creatures). 2) Smooth draws (keep 1-land hands and find the second). 3) Fuel Delver flips, delirium, and delve. 4) Provide shuffle effects with fetchlands. 5) Cost only 1 mana, fitting into any turn. Without cantrips, Legacy decks would be at the mercy of random draws. With them, blue decks effectively play with a 40-card deck because they see so many more cards."},
]

conversation = [
    {"instruction": "What is the most satisfying play in Legacy?", "input": "", "output": "Every Legacy player has their own answer, but the community favorites are:\n\n1) Brainstorm in response to Thoughtseize: hide your 2 best cards on top of your library, then the opponent sees a hand of your worst cards. Pure skill expression.\n\n2) Turn 1 kill: Any deck that wins on turn 1 (Oops, Belcher, Storm) produces an electrifying moment. Laying out the combo and watching the opponent realize they are dead is Legacy at its most dramatic.\n\n3) Natural Order into Craterhoof for lethal: sacrificing a tiny 1/1 elf and replacing it with a 5/5 that gives your 8 other elves +9/+9 trample for a 70+ damage attack.\n\n4) Perfect Doomsday pile: constructing a 5-card pile that plays through opponent's disruption, draws through itself, and wins with Oracle. The intellectual satisfaction is unmatched.\n\n5) Flipping Delver on turn 2: the iconic Legacy moment. Revealing Brainstorm or Force of Will and attacking for 3 in the air.\n\nWhat is yours?"},
    {"instruction": "My local game store is starting a Legacy night. How do I help grow the community?", "input": "", "output": "Growing a Legacy community takes effort but pays off:\n\n1) Advocate for proxy-friendly events. The #1 barrier to Legacy is cost. Allowing proxies lets players try the format without $3000+ investment.\n\n2) Lend decks. If you own multiple Legacy decks, let new players borrow one. One good experience hooks them.\n\n3) Teach while you play. Explain interactions, suggest plays, and do not punish new player mistakes harshly. Legacy has a steep learning curve and new players need encouragement.\n\n4) Start a Discord or group chat for your local Legacy players. Coordinate events, share decklists, and discuss the meta.\n\n5) Record and share your matches (with permission). Content helps attract players who are Legacy-curious.\n\n6) Be consistent. Show up every week. Community events die when attendance is unreliable.\n\n7) Run beginner-friendly events with simplified rules (maybe best-of-1 with premade decks) to introduce the format.\n\nThe Legacy community is the best in Magic because the players care deeply about the format. Be part of that tradition."},
    {"instruction": "What should I read to get better at Legacy?", "input": "", "output": "Essential reading and watching:\n\n1) Articles: MTGGoldfish's 'This Week in Legacy' (weekly meta analysis), Legacy articles on ChannelFireball and TCGPlayer by Reid Duke, Anuraag Das, and others.\n\n2) Primers: The Source (mtgsalvation.com) has dedicated threads for every archetype maintained over years. Read the primer for YOUR deck cover to cover.\n\n3) Videos: Phil Gallagher (PhilGallagher on YouTube) plays and explains Legacy matches. AnziD streams Legacy on Twitch with excellent commentary. Julian Knab provides high-level Storm content.\n\n4) Books: 'LLMs in Production' covers the AI aspects of building Legacy tools (this project's course textbook).\n\n5) Reddit: r/MTGLegacy is active with meta discussion, deck help, and card evaluation.\n\n6) Discord: Multiple Legacy Discord servers for specific archetypes and general discussion.\n\nThe fastest improvement comes from playing + reviewing your own matches. But reading and watching helps you learn what good play looks like before you can execute it yourself."},
    {"instruction": "I am about to play my first Legacy game ever. What is the one most important thing to remember?", "input": "", "output": "Fetch basic lands first.\n\nSeriously. The single most impactful advice for a new Legacy player is: when you crack a fetchland turn 1, get a basic Island (or whatever basic your deck needs) instead of a dual land. Here is why:\n\n1) 48% of Legacy decks play Wasteland. If your only land is a dual land, they destroy it and you have nothing.\n\n2) Blood Moon (in 10-15% of decks) turns all nonbasics into Mountains. A basic Island still works under Blood Moon.\n\n3) You can always fetch the dual later when you need both colors.\n\nThe number of games lost by new Legacy players because they fetched Underground Sea turn 1 and got Wastelanded is incalculable. Fetch. Basic. First. Everything else can be learned over time, but this one habit will immediately improve your win rate."},
]

board_state = [
    {"instruction": "Board state: I have a resolved Aluren in play (can cast creatures MV 3 or less for free). I have Acererak the Archlich in hand. Walk me through the kill.", "input": "", "output": "With Aluren in play, cast Acererak (MV 3) for free. Acererak's ETB triggers: you may venture into a dungeon. Choose Lost Mine of Phandelver. Go to room 1 (gain 1 life... actually you want to NOT complete the dungeon). Re-read: Acererak says 'when Acererak enters, if you have NOT completed a dungeon, return Acererak to its owner's hand.' Since you have not completed a dungeon yet, Acererak bounces to hand. Cast Acererak again (free with Aluren). Again, you have not completed the dungeon, so it bounces. But wait - each entry DOES progress the dungeon. After entering enough times, you will complete Lost Mine. The last room deals 1 damage to each opponent. But you need to loop through multiple dungeon completions for lethal. Each complete dungeon run = 1 damage + other effects. You loop until opponent is dead. It takes about 20 loops for 20 damage."},
    {"instruction": "Board state: I have Helm of Obedience and Rest in Peace in play. How does the combo work?", "input": "", "output": "Helm of Obedience costs X and taps: opponent puts cards from top of library into graveyard until a creature card or X cards are put there, then you gain control of that creature. With Rest in Peace in play, cards that would go to the graveyard are exiled instead. Activate Helm for X=1. Opponent reveals the top card: it would go to the graveyard, but Rest in Peace exiles it instead. Since it was exiled and NOT put into the graveyard, the condition 'until a creature card or X cards are put into the graveyard' is never satisfied. The ability continues indefinitely, exiling the opponent's ENTIRE library. They lose on their next draw step. This combo wins at instant speed for just 1 mana activation cost (X=1 plus tapping Helm)."},
    {"instruction": "Board state: My opponent plays Terminus for its miracle cost (W). Can I save my creatures?", "input": "", "output": "Terminus is a sorcery that puts all creatures on the bottom of their owners' libraries. When miracle is revealed, the trigger goes on the stack. You can respond to the miracle trigger (before they cast Terminus) or to the spell itself (after they cast it for W). Your options: 1) Bounce your own creatures to hand (Karakas for legends, Ephemerate exiles and returns later). 2) Sacrifice your creatures for value before Terminus resolves (to Goblin Bombardment, Cabal Therapy flashback, etc.). 3) Counter Terminus (Force of Will, Daze - but it only costs W so Daze is less effective). 4) Stifle the miracle trigger (they cannot cast it for W, must pay full 4WW). Note: Terminus puts creatures on the BOTTOM of libraries, not the graveyard, so sacrifice is the only way to get death/graveyard triggers."},
    {"instruction": "Board state: I have Food Chain in play and Misthollow Griffin in hand. Walk me through generating infinite mana.", "input": "", "output": "Food Chain: exile a creature you control, add mana equal to that creature's mana value +1 (only for creature spells). Misthollow Griffin (MV 4, flying 3/3) can be cast from exile.\n\n1) Cast Misthollow Griffin from hand for 3U (4 mana).\n2) Exile Griffin to Food Chain: get 5 mana (MV 4 + 1) of any one color, usable only for creature spells.\n3) Cast Griffin from exile for 3U (paying 4 of the 5 mana). Net: +1 mana.\n4) Exile Griffin again: get 5 mana. Cast Griffin: spend 4. Net: +1 more mana.\n5) Repeat infinitely. Each loop nets +1 mana for creature spells.\n\nWith infinite creature mana, cast Walking Ballista for X=infinite. Ballista enters with infinite +1/+1 counters. Remove counters to deal 1 damage each to opponent for infinite damage. Alternative: cast Thassa's Oracle with infinite devotion to blue for the win."},
    {"instruction": "Board state: Opponent at 20 life. I have 7 goblins in play including Goblin Ringleader and Muxus. I just drew Goblin Lackey. Can I kill them?", "input": "", "output": "You have 7 goblins for a total attack of approximately 7-12 power depending on lords and specific creatures. That is not lethal from 20 in one swing unless you have Goblin Chieftain (+1/+1 lord) or multiple lords. However, Goblin Lackey has a special ability: whenever it deals combat damage to a player, put a Goblin from your hand into play. If Lackey connects (1 damage), you could put a powerful goblin into play for free. But you just drew Lackey, so it has summoning sickness and cannot attack this turn.\n\nBetter question: can you attack with your 7 goblins for enough damage? 7 creatures with average power 1-2 = 7-14 damage. Not lethal from 20. You need another turn or a pump effect. If one of your goblins is Goblin Chieftain (lord giving +1/+1 and haste), your 7 goblins attack for ~14-21 damage. With 2 lords, easily lethal. Without lords, you need 2 combat steps."},
]

budget = [
    {"instruction": "What Legacy staples are likely to be reprinted and drop in price?", "input": "", "output": "Likely to be reprinted (buy later): Force of Will (reprinted in Eternal Masters, Double Masters - expect future reprints), Orcish Bowmasters (only in LTR, due for a reprint soon), Murktide Regent (MH2, will be reprinted eventually), fetchlands (reprinted periodically, wait for the next cycle), Surgical Extraction (multiple reprints, buy during a reprint window).\n\nWill NEVER be reprinted (buy now): All Reserved List cards - dual lands, Lion's Eye Diamond, Mox Diamond, City of Traitors, Gaea's Cradle, The Tabernacle. These only go up in price.\n\nUncertain: Modern Horizons mythics (Solitude, Endurance) may appear in supplemental products. Wasteland has been reprinted (Tempest, Eternal Masters) but is cheap enough that reprints matter less.\n\nStrategy: buy Reserved List first (appreciating asset), wait for reprint windows on everything else."},
    {"instruction": "What is the total cost of playing Legacy for one year on MTGO vs paper?", "input": "", "output": "MTGO annual cost:\n- Deck purchase: $300-500 (one-time, recoverable at 80-90%)\n- League entries: 10 tix/league x 2/week x 52 weeks = ~$1040\n- Prizes offset: winning 3+ matches averages ~5 tix back per league = -$520\n- Net annual MTGO cost: ~$500-800 (plus recoverable deck value)\n\nPaper annual cost:\n- Deck purchase: $1500-5000+ (one-time, recoverable at 70-100% for RL cards)\n- Event entries: $10-15/week x 52 = ~$520-780\n- Card updates: $50-100/year for new printings\n- Net annual paper cost: $570-880 ongoing (plus initial deck investment)\n\nVerdict: MTGO is cheaper to START but ongoing costs are similar. Paper requires a larger upfront investment but Reserved List cards appreciate. The optimal strategy is both: MTGO for volume practice, paper for local community and the tactile experience."},
    {"instruction": "Are there any Legacy cards that are good long-term financial investments?", "input": "", "output": "Reserved List cards are the only reliable MTG investment:\n\n1) Dual lands: Underground Sea has gone from $200 (2015) to $600-800 (2026). Consistent 15-20% annual appreciation.\n2) Lion's Eye Diamond: $50 (2015) to $300-400 (2026). Storm and Dredge demand keeps it rising.\n3) Mox Diamond: $100 (2015) to $400-500 (2026). Used in Lands and prison decks.\n4) Gaea's Cradle: $200 (2015) to $800-1000 (2026). Commander demand adds to Legacy demand.\n5) City of Traitors: $100 (2015) to $300-400 (2026). Used in every Stompy and Eldrazi deck.\n\nNon-Reserved cards are NOT good investments because reprints crash prices. Force of Will dropped from $100 to $40 after Eternal Masters, then recovered to $80. The volatility is too high.\n\nIf you want to invest in Magic, buy Reserved List Legacy staples. They are the only cards with guaranteed scarcity and consistent demand."},
]

# Write all
categories = [
    ("rules_qa.jsonl", rules),
    ("card_evaluation.jsonl", card_eval),
    ("deckbuilding_rationale.jsonl", deckbuilding),
    ("conversation_flow.jsonl", conversation),
    ("board_state_analysis.jsonl", board_state),
    ("budget_substitutions.jsonl", budget),
]

for filename, data in categories:
    outpath = os.path.join(os.path.dirname(__file__), "..", "data", "training", filename)
    with open(outpath, "a", encoding="utf-8") as f:
        for pair in data:
            f.write(json.dumps(pair, ensure_ascii=False) + "\n")
    print(f"Appended {len(data)} pairs to {filename}")
