"""Generate deck analysis training data - Batch 3 (append). More archetype IDs, meta positioning, and sideboard plans."""
import json
import os

pairs = [
    # === MORE ARCHETYPE IDENTIFICATION ===
    {"instruction": "Identify this deck: 4 Glistener Elf, 4 Blighted Agent, 4 Invigorate, 4 Berserk, 4 Brainstorm, 4 Force of Will, 4 Daze, Tropical Island, fetchlands", "input": "", "output": "This is Infect, a tier 3 aggro-combo deck at 0.4% meta share. Glistener Elf and Blighted Agent are infect creatures that kill with 10 poison instead of 20 damage. Invigorate (+4/+4 for free if opponent controls a Forest) and Berserk (double power, trample) combine for massive pump spells that one-shot opponents. The blue shell (Brainstorm, Force, Daze) provides protection. Infect can kill as early as turn 2 but is fragile against removal-heavy decks."},
    {"instruction": "Identify this deck: 4 Price of Progress, 4 Lightning Bolt, 4 Chain Lightning, 4 Eidolon of the Great Revel, 4 Goblin Guide, 4 Monastery Swiftspear, Mountains", "input": "", "output": "This is Burn, a fringe aggro deck at 0.3% meta share. Every card deals direct damage to the opponent's face. Price of Progress deals double damage for each nonbasic land the opponent controls (devastating in Legacy where most decks run 15+ nonbasics). Eidolon punishes every spell costing 3 or less. The deck aims to deal 20 damage by turn 3-4 with no interaction. Budget-friendly at ~$1500."},
    {"instruction": "Identify this deck: 4 Veteran Explorer, 4 Cabal Therapy, 4 Green Sun's Zenith, Phyrexian Tower, various big creatures and planeswalkers", "input": "", "output": "This is Nic Fit, a fringe midrange-ramp deck. Veteran Explorer dies (often sacrificed to Phyrexian Tower or Cabal Therapy) and both players search for 2 basic lands. But Nic Fit benefits more from the ramp because it plays expensive threats like Primeval Titan, Uro, or planeswalkers that opponents' low-curve decks cannot match. Cabal Therapy provides hand disruption and a sacrifice outlet for Explorer. GSZ tutors silver bullets. The deck is a meta predator against fair blue decks but weak to combo."},
    {"instruction": "Identify this deck: 4 Enchantress's Presence, 4 Argothian Enchantress, 4 Solitary Confinement, 4 Sterling Grove, Elephant Grass, various enchantments", "input": "", "output": "This is Enchantress, a fringe combo-prison deck at 0.2% meta share. Argothian Enchantress and Enchantress's Presence draw a card whenever you cast an enchantment, creating a draw engine. Solitary Confinement prevents all damage and targeting (you discard a card each upkeep, sustained by Enchantress draws). Sterling Grove gives shroud to other enchantments and tutors. The deck creates an impenetrable prison where the opponent cannot deal damage or target you."},
    {"instruction": "Identify this deck: 4 Urza's Saga, 4 Nettlecyst, 4 Thought Monitor, 4 Emry Lurker of the Loch, 4 Mox Opal, 4 Chalice of the Void, artifact lands", "input": "", "output": "This is Affinity Stompy (also called 8-Cast), a tier 2 artifact aggro-prison deck at 2.4% meta share. Urza's Saga creates growing Construct tokens and tutors for 0-1 cost artifacts. Thought Monitor draws 2 cards with affinity for artifacts. Emry recurs artifacts from the graveyard. Mox Opal provides free mana with metalcraft. Chalice on 1 locks out cantrips. The deck floods the board with artifacts for both aggressive and prison angles."},
    {"instruction": "Identify this deck: 4 Ruby Medallion, 4 Birgi God of Storytelling, 4 Bonus Round, rituals, Past in Flames, Grapeshot", "input": "", "output": "This is Ruby Storm, a tier 3 mono-red storm deck at 0.4% meta share. Ruby Medallion reduces all red spells by 1, and Birgi adds R whenever you cast a spell. With both in play, red spells cost 2 less and generate 1 mana, making most rituals and cantrips mana-positive. Bonus Round copies each instant and sorcery, doubling your spells. Past in Flames gives flashback to all instants and sorceries in the graveyard. The kill is Grapeshot with massive storm count. Budget-friendly at ~$300 with no dual lands or LEDs."},
    {"instruction": "Identify this deck: 4 Cloudpost, 4 Glimmerpost, Primeval Titan, Ugin the Spirit Dragon, 4 Crop Rotation, Expedition Map", "input": "", "output": "This is Cloudpost Ramp (also called 12-Post), a tier 3 big-mana deck at 1% meta share. Cloudpost taps for mana equal to the number of Loci in play. With 4 Cloudpost and 4 Glimmerpost, each Cloudpost taps for 8 mana. Crop Rotation and Expedition Map tutor for Loci. Primeval Titan finds 2 more Loci on ETB. The end game is casting Ugin, Emrakul, or other enormous threats with 15+ mana. The deck is weak to Wasteland and Blood Moon."},

    # === MORE STRENGTHS/WEAKNESSES ===
    {"instruction": "What are the strengths and weaknesses of Aluren?", "input": "", "output": "Strengths: Combo-control hybrid that grinds effectively even without the combo, opponents rarely know how to sideboard against it (1.2% meta share means low preparation), the combo (Aluren + Acererak) is compact and hard to interact with once Aluren resolves, and it recently won the Legacy Showcase Qualifier proving its viability. Weaknesses: Aluren costs 4 mana (slow by Legacy standards), the combo requires keeping creatures alive (vulnerable to Swords and Bowmasters), and graveyard hate incidentally hurts Cabal Therapy flashback."},
    {"instruction": "What are the strengths and weaknesses of Izzet Delver?", "input": "", "output": "Strengths: Lightning Bolt provides reach that Dimir Tempo lacks (can finish games when opponent stabilizes), Pyroblast in the sideboard is excellent in blue mirrors, and the deck is a proven archetype with over a decade of optimization. Weaknesses: Orcish Bowmasters punishes cantrips and kills DRC/Delver pre-flip, Thoughtseize from Dimir is more versatile than Lightning Bolt against combo, and Volcanic Island is more expensive than Underground Sea. At 4.3% vs Dimir's 14.6%, the meta has spoken."},
    {"instruction": "What are the strengths and weaknesses of Mono Black Midrange?", "input": "", "output": "Strengths: Thoughtseize + Hymn to Tourach strips the opponent's hand, Bowmasters + Dark Confidant provide card advantage (though Bob is less common now), Sheoldred's Edict handles True-Name Nemesis and hexproof, and the mono-colored mana base is immune to Wasteland (all Swamps). Weaknesses: No countermagic means combo decks can go off unimpeded, no free interaction (no Force of Will), limited card selection without cantrips, and the deck is slow to close games."},
    {"instruction": "What are the strengths and weaknesses of Boros Initiative?", "input": "", "output": "Strengths: Caves of Chaos Adventurer provides the Initiative (a powerful dungeon mechanic), Solitude is free removal, Chalice of the Void locks out cantrips, and the creature quality is high (Archon of Emeria taxes and stops extra lands). Weaknesses: No card selection (no cantrips), inconsistent draws without Brainstorm, weak to combo that goes under Chalice (Show and Tell costs 3), and the deck relies on specific draws (fast mana + lock piece + threat) to function."},

    # === COMPREHENSIVE SIDEBOARD PLANS ===
    {"instruction": "How should Ocelot Pride Midrange sideboard against Dimir Tempo?", "input": "", "output": "In: +2 Mindbreak Trap (insurance against their Force of Will chains), +1 Containment Priest (if they run Snuff Out), +2 removal for Murktide (Path to Exile or similar). Out: -2 Solitude (Dimir has few must-exile targets), -1 Broadside Bombardiers (too slow in this matchup), -2 flexible slots. Key: your energy engine outgrinds their one-for-one removal. Do not overboard. Keep your curve low and flood the board. Bowmasters is their best card against you - prioritize killing it."},
    {"instruction": "How should Sneak and Show sideboard against combo decks?", "input": "", "output": "Against Storm: +2 Flusterstorm, +2 Pyroblast. Out: -2 Sneak Attack (too slow), -2 flex. Counter their combo, your combo is faster. Against Oops: +4 Leyline of the Void. Out: -2 Sneak Attack, -2 Ponder. Leyline stops their combo, you race without it. Against Doomsday: +2 Pyroblast, +2 Surgical Extraction. Out: -2 Sneak Attack, -2 flex. Counter Doomsday or Surgical their Oracle. General principle: keep Show and Tell + Force of Will + Emrakul as your core. Sneak Attack is your weakest card against combo since it costs 4 mana."},
    {"instruction": "How should Storm (TES) sideboard against Leyline of the Void decks?", "input": "", "output": "Leyline shuts off Past in Flames but does not stop your main combo. Adjust your lines: use Burning Wish for Tendrils directly instead of Past in Flames. Bring in: +2 Abrupt Decay or Chain of Vapor (bounce/destroy Leyline), +1 Pulverize if available. Cut: -2 Past in Flames (dead with Leyline), -1 flex. Key insight: you can still win through Leyline by going Ritual + Ritual + LED + Burning Wish for Tendrils. Leyline is disruptive but not a hard lock against TES like it is against Dredge."},
    {"instruction": "How should Elves sideboard against Red Stompy?", "input": "", "output": "This is a terrible matchup. Blood Moon shuts off Gaea's Cradle, Chalice on 1 stops most of your 1-mana elves, and Fury wipes your board. Bring in: +3 Force of Vigor (destroy Blood Moon and Chalice for free), +2 Thoughtseize (strip lock pieces before they deploy), +1 Progenitus (Natural Order target that dodges everything). Cut: -3 Glimpse of Nature (too slow, countered by Chalice), -2 Heritage Druid (less explosive without Glimpse), -1 flex. Your best hope is Force of Vigor on their turn-1 Chalice followed by a fast Craterhoof turn."},
    {"instruction": "Give me a general sideboard guide for Legacy.", "input": "", "output": "Universal Legacy sideboard principles:\n\n1) Against combo: bring in Leyline of the Void (graveyard), Flusterstorm/Mindbreak Trap (storm), Force of Will stays in (never board out Force vs combo).\n\n2) Against tempo/Delver: bring in Pyroblast (kills Murktide, counters Force), Toxic Deluge (sweeper), extra removal. Board out Daze (they play around it) and narrow counters.\n\n3) Against prison/Stompy: bring in Force of Vigor (destroys Chalice and Blood Moon), artifact hate. Board out creature removal (they have few creatures that matter).\n\n4) Against control: bring in planeswalkers and card advantage that beats countermagic. Board out removal and fast interaction (Daze).\n\n5) Against creature decks: bring in sweepers (Deluge, Terminus). Board out narrow counters.\n\nAlways check your blue card count after boarding if you play Force of Will. Never drop below 19 blue cards."},

    # === META POSITIONING AND DECK CHOICE ===
    {"instruction": "The online metagame shifted to 20% Ocelot Pride. How do I adjust?", "input": "", "output": "20% Ocelot means you face it roughly every other round. Adjustments: 1) Main deck: run sweepers like Toxic Deluge if your deck supports it. 2) Sideboard: add 2-3 dedicated Ocelot answers: Toxic Deluge, Massacre (free vs white), Engineered Explosives on 1. 3) Deck choice: Lands is naturally favored (Maze of Ith, Tabernacle, Punishing Fire). Dimir Tempo with Deluge is solid. Storm does not care about creatures and races them. 4) Avoid: slow control without sweepers, creature decks that get outvalued by energy engines."},
    {"instruction": "I want to play a tournament next week but have never played Legacy. What is the fastest competitive deck to learn?", "input": "", "output": "Burn is the fastest to learn. The strategy is straightforward: point damage at the opponent's face. Count to 20 with Lightning Bolt, Chain Lightning, Eidolon, Price of Progress. The decision trees are simpler than Brainstorm-based decks. Budget-friendly at ~$1500.\n\nSecond choice: Eldrazi. Deploy Chalice on 1, play big creatures, attack. Fewer decisions than blue decks. No Brainstorm or fetchland sequencing to learn.\n\nAvoid for your first tournament: Doomsday (most complex deck in Legacy), Storm (requires extensive format knowledge for sequencing), Lands (unique strategy with many lines), Dimir Tempo (Brainstorm decisions take months to optimize). Pick a proactive deck where your plan is clear regardless of what the opponent does."},
    {"instruction": "What Legacy deck has the highest skill ceiling?", "input": "", "output": "Doomsday has the highest skill ceiling in Legacy. Constructing the correct 5-card pile requires: knowing your opponent's possible interaction, calculating available mana and life, choosing between multiple pile configurations, and adjusting on the fly if disrupted mid-pile. Top Doomsday players have significantly higher win rates than average pilots.\n\nOther high-ceiling decks: Lands (complex land sequencing, many utility land choices per turn), The EPIC Storm (sequencing rituals, reading opponent's disruption, alternate kill paths), Death and Taxes (intricate Aether Vial and Flickerwisp timing). Low-ceiling decks: Burn (linear), Oops All Spells (few decisions), Eldrazi (straightforward)."},
    {"instruction": "Rank the tier 1 decks by difficulty to play correctly.", "input": "", "output": "From hardest to easiest:\n\n1) Dimir Tempo (hardest tier 1): Brainstorm decisions, Daze math, Thoughtseize timing, when to be aggressive vs defensive, when to Force vs hold, fetchland sequencing. Hundreds of micro-decisions per game.\n\n2) Sneak and Show: Sequencing combo pieces, knowing when to go for it vs wait for protection, reading opponent's hand for Force of Will, mulligan decisions for combo hands.\n\n3) Ocelot Pride Midrange: Combat math with tokens and energy, sequencing threats for maximum value, sideboard decisions without cantrips to find answers.\n\n4) Oops All Spells (easiest tier 1): Find mana + spy creature, cast it, win. Mulligan decisions are the main skill expression. Games are very short and decision-light. The difficulty is in knowing when to go for it and when opponent's have free interaction."},
]

outpath = os.path.join(os.path.dirname(__file__), "..", "data", "training", "deck_analysis.jsonl")
with open(outpath, "a", encoding="utf-8") as f:
    for pair in pairs:
        f.write(json.dumps(pair, ensure_ascii=False) + "\n")

print(f"Appended {len(pairs)} pairs to {outpath}")
