"""Generate deck analysis training data - Batch 2 (append)."""
import json
import os

pairs = [
    # === MORE ARCHETYPE IDENTIFICATION ===
    {"instruction": "Identify this deck archetype: 4 Goblin Lackey, 4 Goblin Matron, 4 Goblin Ringleader, 4 Muxus Goblin Grandee, 4 Aether Vial, 4 Cavern of Souls, 4 Wasteland", "input": "", "output": "This is Goblins, a tribal aggro-combo deck that is currently fringe at 0.4% meta share. Goblin Lackey cheats creatures into play on combat damage, Matron tutors, Ringleader refuels, and Muxus provides an explosive turn by putting multiple goblins into play at once. Aether Vial and Cavern of Souls make the tribal package uncounterable. The deck has struggled since Orcish Bowmasters entered the format, killing most goblins on sight."},
    {"instruction": "Identify this deck archetype: 4 Leyline of the Void, 4 Helm of Obedience, 4 Thoughtseize, 4 Dark Ritual, 4 Swords to Plowshares, Scrubland, Wasteland", "input": "", "output": "This is BW Helm Combo (also called Orzhov Helm). The two-card combo is Leyline of the Void in play plus Helm of Obedience activated for 1: since cards cannot go to the graveyard (exiled instead), Helm keeps going until the opponent's entire library is exiled. Dark Ritual accelerates Helm, Thoughtseize clears disruption, and Swords to Plowshares provides removal. The deck doubles as a graveyard hate strategy since Leyline shuts down Reanimator and Dredge naturally."},
    {"instruction": "Identify this deck archetype: 4 Stoneforge Mystic, 1 Batterskull, 1 Kaldra Compleat, 4 Brainstorm, 4 Ponder, 4 Force of Will, 4 Swords to Plowshares, 3 Tundra, 2 Volcanic Island", "input": "", "output": "This is Jeskai Stoneblade, a fair blue control-midrange deck. Stoneforge Mystic tutors equipment (Batterskull for grindy matchups, Kaldra Compleat for an evasive threat) while the UWR shell provides Swords to Plowshares, Force of Will, and cantrips. The Volcanic Island splash gives access to Lightning Bolt and sideboard Pyroblast. Stoneblade is currently tier 3 at about 2% meta share."},
    {"instruction": "Identify this deck archetype: 4 Stifle, 4 Phyrexian Dreadnought, 4 Brainstorm, 4 Ponder, 4 Force of Will, 4 Daze, 2 Dress Down", "input": "", "output": "This is Stiflenought, a fringe tempo-combo deck. Stifle counters Phyrexian Dreadnought's sacrifice trigger, leaving a 12/12 trample in play for 1 mana. Dress Down removes all abilities so Dreadnought enters without its drawback. The blue cantrip and Force of Will shell protects the combo while Daze provides tempo. It is a glass cannon that wins fast but folds to removal-heavy decks."},
    {"instruction": "Identify this deck archetype: 4 High Tide, 4 Time Spiral, 4 Brainstorm, 4 Ponder, 4 Force of Will, 4 Merchant Scroll, 1 Brain Freeze, 1 Blue Sun's Zenith", "input": "", "output": "This is High Tide, a historic mono-blue combo deck. High Tide doubles the mana each Island produces, and Time Spiral untaps all lands while refilling your hand, generating massive mana and cards. Merchant Scroll tutors for combo pieces. Brain Freeze wins by generating a lethal storm count. The deck requires Candelabra of Tawnos (very expensive Reserved List) in optimal builds and is rarely seen in modern Legacy."},
    {"instruction": "Identify this deck archetype: 4 Aluren, 4 Cavern Harpy, 2 Acererak the Archlich, 4 Brainstorm, 4 Force of Will, 4 Cabal Therapy, 3 Bayou, 2 Underground Sea, 2 Tropical Island", "input": "", "output": "This is Aluren, a combo-control deck at 1.2% meta share that recently won the Legacy Showcase Qualifier. Aluren lets you cast creatures with mana value 3 or less for free. Acererak the Archlich loops infinitely with Aluren since it returns to your hand when you choose not to complete a dungeon. Cavern Harpy bounces itself for the same loop with other ETB creatures. The BUG shell provides disruption through Force and Cabal Therapy."},
    {"instruction": "Identify this deck archetype: 4 Mystic Forge, 4 Grim Monolith, 4 The One Ring, 4 Karn the Great Creator, 4 Chalice of the Void, 4 Ancient Tomb, 4 City of Traitors", "input": "", "output": "This is Mystic Forge Combo, a tier 2 artifact combo deck at 3.0% meta share. Mystic Forge lets you play artifacts from the top of your library, and with cost reducers like Grim Monolith generating mana, you can chain through your entire deck. Karn the Great Creator provides a wishboard of artifact silver bullets. Chalice of the Void on 1 locks out cantrip decks while you assemble the combo."},
    {"instruction": "Identify this deck archetype: 4 Smallpox, 4 Liliana of the Veil, 4 Hymn to Tourach, 4 Wasteland, 4 Mishra's Factory, 14 Swamp", "input": "", "output": "This is Pox (also called Smallpox or Mono Black Pox), a tier 3 resource denial deck at about 2% meta share. Smallpox, Hymn to Tourach, and Liliana strip the opponent of cards, creatures, and lands simultaneously. Wasteland adds mana denial. The deck wins slowly through Mishra's Factory beatdown and planeswalker ultimates while the opponent has nothing. It thrives against fair decks but struggles against combo that does not care about resources."},
    {"instruction": "Identify this deck archetype: 4 Hive Mind, 4 Show and Tell, 4 Pact of the Titan, 4 Summoner's Pact, 4 Slaughter Pact, 4 Force of Will, 4 Brainstorm, 4 Ponder", "input": "", "output": "This is Hive Mind, a historic combo deck. Show and Tell puts Hive Mind into play, then you cast any Pact spell. Hive Mind copies it for each opponent, and on their next upkeep they must pay the Pact cost or lose the game. Since Pact of the Titan costs 0 to cast but 4 mana on upkeep, and most opponents cannot pay multiple Pact costs simultaneously, this is usually lethal. The deck is rare in modern Legacy."},

    # === MORE STRENGTHS AND WEAKNESSES ===
    {"instruction": "What are the strengths and weaknesses of The EPIC Storm?", "input": "", "output": "Strengths: Burning Wish provides unmatched flexibility through a wishboard of sorceries, can win through disruption with multiple combo routes (Tendrils, Empty the Warrens, Past in Flames), turn 2-3 goldfish speed, and experienced pilots can navigate through hate. Weaknesses: Chalice on 1 stops most of the deck, Leyline of the Void shuts off Past in Flames, Thalia taxes every spell by 1, and the deck requires exceptional sequencing skills to play optimally."},
    {"instruction": "What are the strengths and weaknesses of Painter?", "input": "", "output": "Strengths: Fast two-card combo (turn 2-3), Goblin Welder provides artifact recursion, Red Elemental Blast becomes unconditional with Painter naming blue, Chalice of the Void disrupts cantrip decks, and the deck has a strong backup plan of grindy artifact value. Weaknesses: Null Rod and Collector Ouphe shut off Grindstone, Surgical Extraction on either combo piece is devastating, and the deck is soft to Force of Will on the combo turn."},
    {"instruction": "What are the strengths and weaknesses of Eldrazi?", "input": "", "output": "Strengths: Turn-1 Chalice on 1 wins many games alone, creatures are individually powerful and hard to remove efficiently, the colorless mana base dodges Blood Moon and Wasteland (somewhat), and Thought-Knot Seer provides hand disruption. Weaknesses: Chalice only stops 1-mana spells (Show and Tell costs 3), the deck lacks card advantage and runs out of gas, and it struggles against combo decks that go over the top."},
    {"instruction": "What are the strengths and weaknesses of Doomsday?", "input": "", "output": "Strengths: The most compact combo in Legacy (one card resolving wins), protected by the full Force + Daze + cantrip blue shell, kills are deterministic once the pile is constructed correctly, and post-board transformational plans are possible. Weaknesses: Doomsday costs BBB (hard to cast through Wasteland), life total matters (you pay half life), wrong pile construction is unrecoverable, and the deck demands exceptional format knowledge."},
    {"instruction": "What are the strengths and weaknesses of Red Stompy?", "input": "", "output": "Strengths: Turn-1 lock pieces (Blood Moon, Chalice, Trinisphere) can shut out entire decks, does not need dual lands, The One Ring provides card advantage, and the deck punishes greedy multi-color mana bases. Weaknesses: Inconsistent draws (needs fast mana plus lock piece), weak to Force of Will and Force of Vigor, creature threats are mediocre without lock pieces, and Eldrazi does the prison plan better with bigger creatures."},

    # === DETAILED META POSITIONING ===
    {"instruction": "What is the best deck to play in a combo-heavy metagame?", "input": "", "output": "Dimir Tempo is the safest choice: Thoughtseize + Force of Will + Daze is the best anti-combo package and the clock from Murktide and Bowmasters finishes games before combo rebuilds. Izzet Delver adds Lightning Bolt for reach. Death and Taxes with Thalia and hatebears can slow combo enough to win. If you want to play combo yourself, Painter has both a fast combo and Chalice to disrupt opposing combos."},
    {"instruction": "What is the best deck to play in a fair-heavy metagame?", "input": "", "output": "Combo decks thrive when the meta is fair. Sneak and Show beats most fair decks by resolving a single Show and Tell. Storm punishes opponents who board out disruption for creature interaction. Lands grinds out fair decks with Wasteland recursion and Marit Lage. Oops All Spells can steal games before fair decks deploy their value engines. When everyone is trying to play fair Magic, doing something unfair is rewarded."},
    {"instruction": "What is the best deck to play in a prison-heavy metagame?", "input": "", "output": "Decks that operate through Chalice of the Void and Blood Moon are best. Sneak and Show (combo costs 3-4 mana, dodges Chalice on 1), Lands (operates entirely through land abilities that Chalice cannot touch), and Ocelot Pride (creature-based plan that does not rely on cantrips). Force of Vigor in the sideboard is essential to handle Chalice and Blood Moon. Avoid Delver-style decks that are neutered by Chalice on 1."},
    {"instruction": "How should I metagame for a local Legacy event?", "input": "", "output": "At local events, the metagame is smaller and more predictable than MTGO. Talk to other players to learn what they play. If your store has 3 Delver players, board heavily for tempo. If there are 2 combo players, bring extra hate. Local metas often lag behind online trends by weeks, so check if recent innovations have reached your area. Play a deck you know well over a theoretically better choice you are learning."},
    {"instruction": "How should I metagame for an MTGO Legacy Challenge?", "input": "", "output": "MTGO Challenges reflect the online metagame which currently skews toward Dimir Tempo (14.6%), Ocelot Pride (8.5%), and Oops (8.2%). Prepare for these three plus Storm, Sneak and Show, and Painter. The online meta adapts faster than paper, so check the latest 5-0 lists on MTGGoldfish before registering. Versatile sideboards that cover multiple matchups are more important than narrow hate for one deck."},

    # === FULL SIDEBOARD PLANS ===
    {"instruction": "Give me a complete sideboard plan for Dimir Tempo against the top 5 decks.", "input": "", "output": "vs Dimir Tempo mirror: +2 Hydroblast, +1 Toxic Deluge, -2 Daze, -1 Wasteland. Daze is bad in the mirror when both players expect it. vs Ocelot Pride: +2 Toxic Deluge, +1 Hydroblast, -2 Daze, -1 Snuff Out. Sweepers are essential against their go-wide plan. vs Oops: +4 Leyline of the Void, +2 Surgical Extraction, -4 Wasteland, -2 Snuff Out. Graveyard hate is everything, removal is useless. vs Sneak and Show: +2 Flusterstorm, +2 Surgical, -2 Wasteland, -2 Snuff Out. Counter their combo and Surgical Emrakul. vs Painter: +2 Null Rod, +1 Toxic Deluge, -2 Daze, -1 Thoughtseize. Null Rod stops Grindstone, Deluge clears the board."},
    {"instruction": "Give me a complete sideboard plan for Sneak and Show against the top 5 decks.", "input": "", "output": "vs Dimir Tempo: +2 Pyroblast, +1 Veil of Summer, -2 Sneak Attack, -1 Lotus Petal. Pyroblast counters Force and kills Murktide. vs Ocelot Pride: +2 Kozilek's Return, +1 Sneak Attack, -2 Force of Will, -1 Ponder. Sweeper handles their board, and they lack free countermagic so Force is less essential. vs Oops: +4 Leyline of the Void, -2 Sneak Attack, -2 Ponder. Leyline stops their combo, and you race them without it. vs Lands: +2 Blood Moon, +2 Pyroblast, -2 Sneak Attack, -2 Daze. Blood Moon destroys their mana base. vs Storm: +2 Flusterstorm, +2 Pyroblast, -3 Sneak Attack, -1 Emrakul. Counter-heavy plan, Sneak Attack is too slow."},
    {"instruction": "How does a typical Dimir Tempo sideboard look?", "input": "", "output": "A well-constructed Dimir Tempo sideboard typically contains: 3-4 Leyline of the Void (graveyard combo), 2 Surgical Extraction (targeted graveyard hate), 2 Hydroblast (anti-red, mirror), 2 Flusterstorm (anti-combo, counter wars), 2 Null Rod or Force of Vigor (anti-artifacts), 1-2 Toxic Deluge (sweeper for go-wide decks and True-Name Nemesis), 1 Massacre or additional removal. The exact configuration shifts weekly based on expected metagame."},
]

outpath = os.path.join(os.path.dirname(__file__), "..", "data", "training", "deck_analysis.jsonl")
with open(outpath, "a", encoding="utf-8") as f:
    for pair in pairs:
        f.write(json.dumps(pair, ensure_ascii=False) + "\n")

print(f"Appended {len(pairs)} pairs to {outpath}")
