"""Generate training data - Mega batch 5. Large expansion across all categories to push toward 1500."""
import json
import os

rules = [
    {"instruction": "What is a mana ability and why does it matter?", "input": "", "output": "A mana ability is an activated ability that produces mana, does not target, and is not a loyalty ability. Mana abilities do not use the stack and cannot be responded to. This matters because cards like Deathrite Shaman's first ability and Lion's Eye Diamond are mana abilities - once activated, opponents cannot stop them. Tapping a land for mana is also a mana ability. You can always tap lands for mana in response to any spell or ability without your opponent being able to prevent it."},
    {"instruction": "Can I cast Lightning Bolt targeting my own creature?", "input": "", "output": "Yes. Lightning Bolt says 'any target' which includes your own creatures, your opponent, or yourself. You might want to target your own creature to: prevent an opponent from gaining life from Swords to Plowshares (sacrifice it to damage instead), trigger a 'when damaged' ability, or put a card in your graveyard for Tarmogoyf or delve. Targeting yourself is also legal if you need to reduce your own life total for Death's Shadow."},
    {"instruction": "What happens when a creature with undying dies?", "input": "", "output": "Undying triggers when a creature without a +1/+1 counter dies. It returns to the battlefield with a +1/+1 counter. If a creature already has a +1/+1 counter when it dies, undying does not trigger. With Leyline of the Void, the creature is exiled instead of going to the graveyard, and undying does not trigger (it never 'died' in the graveyard sense). Young Wolf and Geralf's Messenger are the most common undying creatures in Legacy."},
    {"instruction": "How does Chalice of the Void interact with X spells?", "input": "", "output": "Chalice of the Void counters spells with a specific mana value. For spells with X in their cost, X is the chosen value while on the stack. Engineered Explosives cast with X=2 has mana value 2 on the stack and is countered by Chalice on 2. But when an X spell is anywhere other than the stack (hand, library, graveyard), X is 0. So Chalice on 0 does NOT counter an Explosives cast for X=2 because Chalice checks mana value on the stack (which is 2, not 0)."},
    {"instruction": "What is state-based action and when do they happen?", "input": "", "output": "State-based actions are game rules that are checked whenever a player would receive priority. They include: a creature with 0 or less toughness is destroyed, a player with 0 or less life loses the game, a creature with lethal damage is destroyed, a player who drew from an empty library loses, the legend rule (keep one, put the rest in graveyard), and a token that left the battlefield ceases to exist. Players cannot respond to state-based actions because no player has priority when they happen. Multiple SBAs are processed simultaneously."},
    {"instruction": "How does protection work? What does DEBT stand for?", "input": "", "output": "Protection prevents four things, remembered by the acronym DEBT: Damage from sources with the protected quality, Enchanting/Equipping by sources with the quality, Blocking by creatures with the quality, Targeting by spells and abilities from sources with the quality. Protection does NOT prevent non-targeting effects (Toxic Deluge, Terminus, Liliana's sacrifice), board-wide effects, or being affected by abilities that do not target. Emrakul has protection from colored spells, so it cannot be targeted by Swords to Plowshares (colored spell) but CAN be bounced by Karakas (land ability, not a spell)."},
    {"instruction": "What is phasing and how does it differ from exile?", "input": "", "output": "Phasing causes a permanent to phase out (become treated as if it does not exist) and phase back in at the beginning of its controller's next untap step. Unlike exile, phasing does not trigger ETB or LTB abilities, does not remove counters or auras, and the permanent remembers everything about its previous state. Teferi's Protection phases out all your permanents for a turn of invulnerability. In Legacy, phasing is most relevant on Teferi, Time Raveler's bounce effect and some newer cards."},
    {"instruction": "Can multiple Chalice of the Void be in play at different values?", "input": "", "output": "Yes. You can have Chalice on 1 and Chalice on 0 in play simultaneously. Each Chalice independently triggers when a spell with the matching mana value is cast. With both, all 0-cost AND 1-cost spells are countered. You can even have two Chalice on 1 - both trigger, but the spell is only countered once (the second trigger does nothing extra). This redundancy matters against Force of Vigor: if they destroy one Chalice, the other still functions."},
    {"instruction": "What happens if I control two legendary permanents with the same name?", "input": "", "output": "The legend rule is a state-based action: if you control two or more legendary permanents with the same name, you choose one to keep and put the rest into your owner's graveyard. This happens immediately and cannot be responded to. In Legacy, this matters with Karakas (you can play a second to trigger a 'dies' ability on the first), and with Show and Tell (if both players put in the same legendary creature, each keeps their own copy since they are controlled by different players - the legend rule only applies to permanents you control)."},
    {"instruction": "How does infect work with pump spells?", "input": "", "output": "Infect creatures deal damage to players as poison counters instead of reducing life. A player with 10 or more poison counters loses the game. Pump spells add to the damage: Glistener Elf (1/1 infect) with Invigorate (+4/+4) is a 5/5 that deals 5 poison. Berserk doubles its power to 10, dealing lethal 10 poison in one hit. This means Infect can kill on turn 2: turn 1 Glistener Elf, turn 2 Invigorate (free) + Berserk (G) = 10 poison. The defending player only needs to prevent this once, which is why Infect is a glass cannon."},
    {"instruction": "Can a spell be both countered and resolved?", "input": "", "output": "No. A spell either resolves (its effects happen) or it is countered (it goes to the graveyard with no effect). Once a spell is countered, it cannot resolve. However, there is a special case: 'this spell can't be countered' means counter effects still target it but fail. The spell resolves normally. Abrupt Decay, Supreme Verdict, and creatures cast through Cavern of Souls have this property. You can still cast Force of Will targeting them (it is a legal action), but the counter effect does nothing."},
    {"instruction": "What is the interaction between Wasteland and Urza's Saga?", "input": "", "output": "Urza's Saga is a land with chapter abilities. On chapter III, it searches for a 0-1 cost artifact, then as a state-based action, it is sacrificed (it is a Saga that has completed its chapters). You can Wasteland Urza's Saga at any time since it is a nonbasic land. If you Wasteland it before chapter III triggers, the controller does not get the artifact tutor. If you wait until chapter III is on the stack and then Wasteland it, the Saga is destroyed but the chapter III ability still resolves (abilities are independent of their source). The optimal Wasteland timing is before the chapter III upkeep trigger."},
    {"instruction": "How does Dredge as a mechanic work step by step?", "input": "", "output": "Dredge N is a replacement effect on cards in the graveyard. When you would draw a card, if a card with dredge is in your graveyard, you may replace that draw with: mill N cards from the top of your library into your graveyard, then return the dredge card from your graveyard to your hand. This is not drawing a card - it is replacing the draw. It does not trigger 'whenever you draw' abilities. You can dredge during any card draw: your draw step, Brainstorm's draws, or triggered draws. If your library has fewer than N cards, you cannot choose to dredge (you would lose for drawing from an empty library, but dredge replaces the draw so you lose instead from milling)."},
]

card_eval = [
    {"instruction": "Is Ancient Tomb Legacy-playable?", "input": "", "output": "Yes, it is one of the most important lands in Legacy. Ancient Tomb taps for 2 colorless mana at the cost of 2 life. It enables turn-1 plays that normally cost 2 mana: Chalice of the Void on 1, Painter's Servant, and many others. It is in 33% of Legacy decks. The 2 life per use adds up, but prison and combo decks plan to end the game before life totals matter. Ancient Tomb is the enabler for every Stompy, Eldrazi, and artifact strategy."},
    {"instruction": "Is Preordain Legacy-playable?", "input": "", "output": "Marginally. Preordain is the third-best cantrip in Legacy after Brainstorm and Ponder, and most decks only need 8 cantrips (4+4). It sees play as cantrips 9-10 in combo decks that need maximum card selection (some Storm builds, some Doomsday lists) and in decks without fetchlands where Ponder's shuffle is less valuable. It costs U to scry 2 then draw 1. The scry-before-draw sequencing is decent but seeing only 3 cards vs Ponder's 4 (with shuffle) is a real downside."},
    {"instruction": "Is Urza's Saga Legacy-playable?", "input": "", "output": "Yes, it is one of the most impactful Modern Horizons 2 additions to Legacy. Urza's Saga is in 22% of decks. As a land, it costs zero deck slots (replaces a land). Chapter I and II create Construct tokens that grow with artifact count. Chapter III tutors for any 0-1 mana artifact (Pithing Needle, Shadowspear, Aether Spellbomb, etc.). It provides both a threat and a tutor on a land. The downside is vulnerability to Wasteland and Blood Moon, and it self-destructs after chapter III."},
    {"instruction": "Is Karakas Legacy-playable?", "input": "", "output": "Yes. Karakas is a legendary land that taps for W and has an ability to return target legendary creature to its owner's hand. It is in 21% of Legacy decks. It bounces opposing Emrakul, Atraxa, Thalia, and any other legend for free. It protects your own legends from removal (return Thalia to hand in response to Swords). It costs no mana and no card to activate. The only cost is that it is a nonbasic land (vulnerable to Wasteland) and legendary (second copy is dead). Every white deck should consider Karakas."},
    {"instruction": "Is True-Name Nemesis Legacy-playable?", "input": "", "output": "Yes, though less dominant than it once was. True-Name Nemesis is a 3/1 for 1UU with protection from the chosen player. It cannot be targeted, damaged, blocked, or enchanted by that player. This makes it essentially unremovable through normal means. Answers: Toxic Deluge, Terminus, sacrifice effects, Council's Judgment. At 3 mana it is slow for Legacy, but the unkillable clock is valuable in grindy matchups. It has declined because Bowmasters and faster threats have made 3-mana creatures less appealing."},
    {"instruction": "Is Entomb Legacy-playable?", "input": "", "output": "Entomb WAS extremely Legacy-playable but was banned in November 2025. For B at instant speed, it put any card from your library into your graveyard. This enabled turn-1 kills with Reanimate: turn 1 Entomb for Griselbrand, Reanimate it, draw 14 cards, win. The card was too efficient as a combo enabler with zero deckbuilding cost. Post-ban, Reanimator still exists but uses slower discard outlets like Faithful Mending."},
    {"instruction": "Is Up the Beanstalk Legacy-playable?", "input": "", "output": "Yes. Up the Beanstalk is a 2-mana enchantment that draws a card on ETB and draws again whenever you cast a spell with mana value 5 or greater. In Legacy, Force of Will (MV 5), Solitude (MV 5), Fury (MV 5), and Subtlety (MV 5) all trigger it even when cast for free alternative costs. This turns pitch spells into cantrips. Beanstalk Control at 2.3% meta share is built entirely around this interaction."},
    {"instruction": "Is Walking Ballista Legacy-playable?", "input": "", "output": "In specific shells, yes. Walking Ballista costs XX and enters with X +1/+1 counters, with an ability to remove a counter to deal 1 damage to any target. At face value, this is too slow and expensive for Legacy. But as a combo kill condition, it is perfect: with infinite mana from Food Chain, Auriok Salvagers + LED, or Mystic Forge loops, Ballista kills by entering with infinite counters. It is also tutorable by Karn, the Great Creator from the sideboard. As a standalone card, it is not Legacy-playable; as a combo piece, it is excellent."},
    {"instruction": "Is Narset, Parter of Veils Legacy-playable?", "input": "", "output": "Situationally yes. Narset costs 1UU, has a static ability that prevents opponents from drawing more than one card per turn (shuts off Brainstorm, Ponder, Sylvan Library, Glimpse of Nature), and a -2 to look at top 4 and take a noncreature, nonland card. Against cantrip-heavy decks, Narset is devastating. Against combo or non-blue decks, the passive is less relevant. She sees sideboard play in UW/UWR control as a meta-dependent card. The 3 mana cost is her biggest limitation."},
    {"instruction": "Is Expressive Iteration Legacy-playable?", "input": "", "output": "It WAS extremely Legacy-playable and was banned in March 2023. For UR, you looked at the top 3 cards, put one in hand, one in exile (playable this turn), and one on the bottom. This was effectively draw-2 for 2 mana with card selection. It was in every UR and URx deck and gave Delver too-efficient card advantage. After the ban, Delver decks lost their best card advantage spell and had to adapt with less efficient options."},
]

deckbuilding = [
    {"instruction": "Why does every Delver variant play exactly 4 Brainstorm and 4 Ponder?", "input": "", "output": "Brainstorm and Ponder are the foundation of every blue Legacy deck. They provide: consistency (find the right answer for any matchup), Delver flip setup (put an instant/sorcery on top), graveyard fueling (fetchland cracks after Brainstorm fill the graveyard for Murktide delve), and protection setup (find Force of Will when needed). Playing fewer than 4 of either reduces the deck's most powerful advantage: seeing more cards than the opponent. There is no reasonable argument for cutting cantrips in a Delver deck."},
    {"instruction": "Why does Lands play Maze of Ith?", "input": "", "output": "Maze of Ith untaps an attacking creature and prevents all combat damage it deals and receives. In Lands, this serves as free repeatable creature removal that does not cost a card or mana. Against Delver's Murktide Regent, Maze neutralizes it every turn indefinitely. The self-targeting trick (attack with Knight of the Reliquary, Maze your own Knight) effectively gives your creatures vigilance. Maze is findable by Crop Rotation at instant speed."},
    {"instruction": "Why does Storm play Ponder over Preordain as the second cantrip?", "input": "", "output": "Ponder sees 3 cards and can shuffle if all 3 are bad, effectively seeing 4 cards with a fetchland. In Storm, you are looking for very specific combo pieces (LED, Burning Wish, rituals) and the ability to shuffle away 3 blanks is critical. Ponder also sets up the top of your library for Ad Nauseam (you want low-cost cards on top). Storm needs to find its pieces by turn 2-3, and Ponder's deeper card selection achieves this better than Preordain's scry 2."},
    {"instruction": "Why do some Dimir Tempo lists play Snuff Out?", "input": "", "output": "Snuff Out costs 4 life to cast for free if you control a Swamp (Underground Sea counts). This gives Dimir Tempo a zero-mana removal spell, allowing you to deploy threats AND remove opposing creatures in the same turn. It is particularly strong against Murktide Regent (which dodges Lightning Bolt). The 4-life cost is significant against aggressive decks but acceptable in matchups where board control matters more than life total. Most lists play 1-2 copies."},
    {"instruction": "Why do prison decks play fast mana but tempo decks do not?", "input": "", "output": "Prison decks need to deploy lock pieces (Chalice, Blood Moon, Trinisphere) on turn 1 to be effective. A turn-2 Blood Moon is dramatically weaker because the opponent has already fetched their basics. Fast mana (Ancient Tomb, City of Traitors, Lotus Petal, Chrome Mox) enables these critical turn-1 plays. Tempo decks do not need fast mana because their spells cost 0-2 mana naturally, and fast mana does not help cast cantrips or Daze more efficiently. Tempo decks want colored mana sources, not colorless acceleration."},
    {"instruction": "Why does Death and Taxes play a high number of utility lands?", "input": "", "output": "D&T leverages Aether Vial for creature deployment, freeing its mana for land abilities. This means lands like Rishadan Port (tap opponent's land), Wasteland (destroy nonbasic), Karakas (bounce legends), Mishra's Factory (2/2 creature land), and Flagstones of Trokair (fetch Plains when destroyed) all provide value without competing with creature casting. No other Legacy deck can play 8+ utility lands because no other deck has Vial reducing the need for mana from lands."},
    {"instruction": "Why do most Legacy sideboards include exactly 15 cards?", "input": "", "output": "The maximum sideboard size is 15 cards. Playing fewer than 15 is almost always wrong because you are giving up free options. Each sideboard slot should improve at least one matchup by being better than the weakest maindeck card in that matchup. Even if your last few slots are marginal, they are still better than having no option. The only argument for fewer than 15: if you literally cannot think of a card that improves any matchup, which is essentially impossible given Legacy's card pool."},
    {"instruction": "Why does every Legacy deck run exactly 60 cards in the main?", "input": "", "output": "Every card above 60 reduces your probability of drawing your best cards. Mathematical proof: with a 4-of in 60 cards, you see it in your opening 7 with ~40% probability. At 61 cards, it drops slightly. At 65, meaningfully. The cumulative effect across all your key cards (Force of Will, Brainstorm, your best threat, your best answer) is a significant consistency reduction. Legacy rewards consistency because you need specific cards for specific matchups. The only exception is Yorion companion (80 cards), where the guaranteed companion justifies the cost."},
    {"instruction": "What makes Wasteland better in some decks than others?", "input": "", "output": "Wasteland is best in decks that: 1) Operate on fewer lands (Delver at 18-19 lands can afford to sacrifice one; Control at 25 cannot). 2) Have mana denial synergy (Daze + Wasteland is devastating when combined). 3) Run cheap spells that function after Wasting their own land. 4) Do not need every land to produce colored mana (colorless from Wasteland is acceptable when your spells cost 1). Wasteland is worst in: control decks that need every land drop, combo decks that need colored mana for their combo, and 3+ color decks where every land needs to fix mana."},
]

deck_analysis = [
    {"instruction": "My Dimir Tempo deck went 5-0 in a league. How do I know if my list is good or if I just got lucky?", "input": "", "output": "A single 5-0 does not prove a list is good - variance in 5 rounds is high. To evaluate your list objectively: 1) Track results over 20+ matches minimum. A 60%+ win rate over 20 matches is statistically significant. 2) Analyze your losses - were they due to matchup problems (structural) or play mistakes (fixable)? 3) Compare your list to successful published lists - where do you differ and why? 4) Check if your 5-0 opponents were on unusual decks (beating 5 fringe decks is easier than beating 5 tier 1 decks). 5) Repeat the 5-0 before concluding the list is optimal. Consistent results beat any single good finish."},
    {"instruction": "What does it mean when a deck is 'well-positioned in the metagame'?", "input": "", "output": "A well-positioned deck has favorable matchups against the most commonly played decks. For example, if Dimir Tempo is 14.6% of the meta and your deck beats it 60% of the time, that alone gives you a significant edge over the field. Well-positioned means: 1) positive win rates against the top 3-5 decks by meta share, 2) no auto-loss matchups among the top 10, and 3) sideboard cards that improve your weaker matchups. A deck can be powerful but poorly positioned (Elves is strong but auto-loses to Bowmasters)."},
    {"instruction": "How do I read a Legacy metagame breakdown?", "input": "", "output": "Key things to look at: 1) Top deck by meta share - this is what you will face most often, prepare for it. 2) Combined archetype categories - is the meta combo-heavy, fair-heavy, or balanced? This determines whether you need more countermagic or more removal. 3) Underrepresented strategies with high win rates - these are opportunities for brewers. 4) Sideboard hate prevalence - if 36% play Leyline of the Void, graveyard decks face hate in 1/3 of matches. 5) Recent trends - is a deck rising or falling? Rising decks mean more hate will appear; falling decks mean less hate."},
    {"instruction": "What are the signs that a Legacy deck is about to get a card banned?", "input": "", "output": "Historical patterns suggest bans happen when: 1) One deck exceeds 15-20% meta share for multiple months (DRS was 57%, Top-Miracles was 15%+). 2) A card has no meaningful counterplay or deckbuilding cost (DRS was in every BGx deck for free). 3) Play patterns are unfun or slow (Sensei's Divining Top caused time issues). 4) Win rate significantly exceeds 55% across large samples. 5) The B&R announcement specifically names a deck as concerning. Current Legacy (April 2026) has Dimir Tempo at 14.6% with a 52.7% win rate - concerning but not yet ban-worthy per Wizards' analysis."},
    {"instruction": "How do I evaluate tournament results to find emerging decks?", "input": "", "output": "Focus on these signals: 1) A deck that was not in the top 20 suddenly has multiple top 8 finishes. 2) A known archetype appears with significant card changes (new tech). 3) Multiple independent players on the same unusual strategy (not just one player's pet deck). 4) The deck beats the current top meta decks (check their reported matchups). Best sources: MTGGoldfish's 5-0 league decklists (broadest sample), Challenge top 8s (competitive sample), and Showcase Qualifiers (highest stakes). The April 2026 Showcase Qualifier was won by Aluren - worth watching if it repeats."},
    {"instruction": "What does a healthy Legacy metagame look like?", "input": "", "output": "A healthy Legacy metagame has: 1) No single deck above 55% win rate. 2) Top deck at 10-15% meta share (not 20%+). 3) Multiple viable strategies across combo, tempo, control, and prison. 4) Diverse tournament top 8s (not the same 2-3 decks repeatedly). 5) At least 30+ distinct competitive archetypes. 6) No card that is format-warping (present in 50%+ of decks with no deckbuilding cost). The current April 2026 meta meets all these criteria: 54 archetypes, Dimir Tempo at 14.6% / 52.7% WR, all macro-strategies viable, diverse top 8s."},
    {"instruction": "How do I know when to switch Legacy decks?", "input": "", "output": "Consider switching when: 1) Your win rate over 30+ matches drops below 50% and you have identified the cause as structural (bad matchup spread) rather than play errors. 2) Your deck's worst matchup becomes the most popular deck (e.g., you play Elves and Bowmasters decks rise to 30%+). 3) A ban hits your deck's key card. 4) You have plateaued after months of practice and want new challenges. Do NOT switch: after a single bad tournament, after losing to variance, or because a different deck won a single event. Legacy rewards deep knowledge of one deck. Switching too often means you never master anything."},
]

conversation = [
    {"instruction": "What is the best way to learn Legacy?", "input": "", "output": "The optimal learning path:\n\n1) Choose ONE deck and commit to it for at least 50 matches. Switching decks delays learning.\n\n2) Learn your deck inside out: goldfish 20+ hands, write down your sideboard plans, know your matchup percentages.\n\n3) Learn the top 10 opposing decks: know their key cards, how they win, what they sideboard, and what their tells are.\n\n4) Study Brainstorm: if you play blue, learning when and how to Brainstorm is the single highest-impact skill. Watch expert players and notice when they Brainstorm vs hold it.\n\n5) Play on MTGO for volume. Paper events are great for practice but MTGO provides 10x the match volume.\n\n6) Watch content: streamers explain their decisions in real-time. Pause and think about what you would do before seeing their play.\n\n7) Review your own games: what did you miss? What could you have played differently? The best players constantly self-critique.\n\nThe biggest mistake new players make is trying to learn the entire format at once instead of mastering one deck first."},
    {"instruction": "I just lost a match where my opponent played cards I have never seen before. How do I handle unknown decks?", "input": "", "output": "Unknown decks are common in Legacy with 54+ archetypes. Here is how to handle them:\n\n1) Identify the macro-strategy: are they combo (trying to win in one big turn), tempo (cheap threats + disruption), control (answering everything), or prison (lock pieces)? This tells you your general approach.\n\n2) Look for format staples: if they play Force of Will, they are blue and interactive. If they play Ancient Tomb, they are prison/stompy. If they play Dark Ritual, they are combo.\n\n3) Default to safe play: keep Force of Will for anything that looks game-winning. Do not use Wasteland on random lands unless you are sure.\n\n4) Ask after the match: Legacy players are generally happy to explain their deck. Learn what it does so you are prepared next time.\n\n5) After the tournament, look up the deck on MTGGoldfish or the archetype guide. Add it to your mental database of 'decks I know.'\n\nThe advantage of experience: after playing Legacy for a year, you will recognize almost every deck from the first 1-2 cards played."},
    {"instruction": "I drew Brainstorm but I have no fetchland. Should I still cast it?", "input": "", "output": "Usually no, unless you have a specific reason. Brainstorm without a shuffle effect (fetchland, Ponder) means you put 2 cards on top and draw them over the next 2 turns. This is called a 'Brainstorm lock' - you already know your next 2 draws and they are the cards you did not want.\n\nCast Brainstorm without a fetch when: 1) You are about to die and need to see 3 new cards RIGHT NOW. 2) You need to hide a card from Thoughtseize (put it on top before they see your hand). 3) You have another shuffle effect coming (Ponder next turn). 4) You want to put a card on top for Counterbalance or Delver flip.\n\nOtherwise, hold Brainstorm until you have a fetchland available. The power of Brainstorm is the shuffle, and casting it without one wastes most of its value."},
    {"instruction": "Explain the Legacy metagame clock: what determines how fast decks need to be.", "input": "", "output": "The Legacy metagame clock is set by the fastest combo decks:\n\n1) Oops All Spells can win turn 1. This means every deck needs a plan for turn 1 interaction (Force of Will, Daze) or risk dying before playing.\n\n2) Storm and Sneak and Show reliably win turns 2-3. This sets the 'goldfish clock' - if your deck cannot either win or meaningfully interact by turn 3, it is too slow.\n\n3) Dimir Tempo deploys threats turn 1-2 and applies disruption + pressure simultaneously. Fair decks must match this efficiency or be run over.\n\nConsequences: Legacy decks are hyper-efficient because anything slow gets killed by combo. This is why 1-mana spells dominate, why free counterspells are essential, and why 4+ mana cards need to win the game immediately. The metagame clock also explains why control is viable: it trades speed for inevitability, using free countermagic to survive the early turns."},
    {"instruction": "My opponent mulliganed to 5 cards. How does that change my strategy?", "input": "", "output": "Your opponent mulliganing to 5 means they kept a focused hand with a specific plan. Adjust accordingly:\n\n1) If they are combo: they likely kept a hand that can combo but has minimal protection. Be aggressive with disruption - Thoughtseize them immediately. Their 5 cards might be exactly the combo with no backup.\n\n2) If they are fair: they are behind on resources. Press your card advantage. Every 1-for-1 trade favors you because they have fewer cards. Do not let them stabilize.\n\n3) If they are prison: they might have kept a hand with a lock piece and fast mana. Be ready with Force of Will for their turn 1 play - a 5-card prison hand is all-in on one lock piece.\n\n4) General: do not mulligan your own hand aggressively just because they mulliganed. Your 7 cards beats their 5 in almost any scenario. Keep a reasonable hand and ride the card advantage."},
]

board_state = [
    {"instruction": "Board state: I control Blood Moon. Opponent plays Boseiju, Who Endures (channel ability from hand). Can they destroy Blood Moon?", "input": "", "output": "Yes. Boseiju's channel ability is activated from the hand, not from the battlefield. Blood Moon only affects nonbasic lands ON THE BATTLEFIELD. Boseiju's channel says 'discard this card: destroy target artifact, enchantment, or nonbasic land an opponent controls.' This is a hand ability, not a land ability, so Blood Moon does not interfere. The opponent discards Boseiju from hand and destroys Blood Moon. This is one of the few ways to answer Blood Moon from under Blood Moon."},
    {"instruction": "Board state: My opponent controls Omniscience. They start casting spells for free. Can I do anything?", "input": "", "output": "Omniscience lets them cast spells for free, but each spell still goes on the stack and you get priority to respond. You can: 1) Force of Will their most important spell. 2) Flusterstorm their key instant or sorcery (storm copies counter all the things). 3) Stifle a critical triggered ability. 4) If you have Karakas, bounce their legendary creature after it enters. 5) If you have your own Show and Tell in hand and Omniscience puts in a creature, Show and Tell your own threat. The key: even with Omniscience, they still use the stack. You are not helpless if you held up interaction."},
    {"instruction": "Board state: I have 2 creatures. Opponent casts Toxic Deluge paying X=3. In response, can I save my creatures with Ephemerate?", "input": "", "output": "Yes, partially. Ephemerate exiles one creature you control and returns it at the next end step. Cast Ephemerate targeting your best creature in response to Toxic Deluge. Your creature is exiled (safe from Deluge). Toxic Deluge resolves, giving all creatures -3/-3 - your other creature dies if it has 3 or less toughness. At the next end step, your Ephemerated creature returns to the battlefield fresh. You saved one creature from a board wipe. Note: Ephemerate has rebound, so next upkeep you can do it again for free."},
    {"instruction": "Board state: Opponent has Thalia (noncreature spells cost 1 more) and Spirit of the Labyrinth (each player may draw only 1 card per turn). How do I fight through this?", "input": "", "output": "This is a devastating D&T lock. Your cantrips cost 2 instead of 1, and drawing extra cards is impossible (Brainstorm draws only 1). Priorities: 1) Kill Spirit of the Labyrinth first - it prevents cantripping entirely. Use a removal spell (Swords for W+1, Bolt for R+1, Push for B+1 with Thalia tax). 2) Then kill Thalia to restore normal spell costs. 3) If you cannot remove either, deploy a threat that does not require cantrips (flash in Bowmasters) and try to race. 4) Toxic Deluge at 1BB+1 (Thalia tax) = 2BB clears both. This is the cleanest answer but costs 4 mana + life."},
    {"instruction": "Board state: I have Show and Tell in hand but opponent has Containment Priest in hand (I know from Gitaxian Probe). Should I still cast Show and Tell?", "input": "", "output": "No, or at least not without a plan. If you cast Show and Tell, opponent puts Containment Priest into play. Priest says: if a nontoken creature would enter the battlefield and it was not cast, exile it. Your Emrakul/Atraxa enters via Show and Tell (not cast), so it gets exiled. You put in a 15-mana creature, they exile it for free.\n\nBetter lines: 1) Use Sneak Attack instead (you can respond to Priest's ETB by Sneaking in Emrakul before Priest settles). Wait, Priest's replacement effect applies immediately. 2) Counter or remove Priest first. 3) Put in a non-creature permanent (Omniscience, Sneak Attack enchantment) since Priest only stops creatures. 4) Wait until they use Priest for another purpose or side it out."},
    {"instruction": "Board state: I am at 1 life playing Storm. I need to win this turn or die. I have Dark Ritual, LED, Burning Wish, Brainstorm, and 1 Swamp.", "input": "", "output": "You can win! Sequence: 1) Swamp, cast Dark Ritual (BBB in pool, storm 1). 2) Cast Brainstorm (draw 3, put 2 back, storm 2). This finds more gas if available. 3) Cast Lion's Eye Diamond (0 mana, storm 3). 4) Cast Burning Wish, hold priority. 5) Crack LED for BBB in response (discard hand, pool now BBB + whatever remains from Ritual, storm still 3). 6) Burning Wish resolves, get Tendrils of Agony from sideboard. 7) Cast Tendrils (storm 4 now, Tendrils makes 4 copies = 5 total = 10 drain). 8) Wait - that is only 10 damage if opponent is at 20. You need storm 9 for lethal. With only these 5 cards, storm count is 5 (Ritual, Brainstorm, LED, Wish, Tendrils = 5 spells). Tendrils creates 5 copies + original = 12 life drain total. If opponent is at 12 or less, you win!"},
]

# Write all categories
categories = [
    ("rules_qa.jsonl", rules),
    ("card_evaluation.jsonl", card_eval),
    ("deckbuilding_rationale.jsonl", deckbuilding),
    ("deck_analysis.jsonl", deck_analysis),
    ("conversation_flow.jsonl", conversation),
    ("board_state_analysis.jsonl", board_state),
]

for filename, data in categories:
    outpath = os.path.join(os.path.dirname(__file__), "..", "data", "training", filename)
    with open(outpath, "a", encoding="utf-8") as f:
        for pair in data:
            f.write(json.dumps(pair, ensure_ascii=False) + "\n")
    print(f"Appended {len(data)} pairs to {filename}")
