"""Generate budget substitution training data - Batch 2 (append)."""
import json
import os

pairs = [
    # More dual land subs
    {"instruction": "What is a budget replacement for Badlands?", "input": "", "output": "Blood Crypt replaces Badlands. In Reanimator, the 2 life per untapped use is risky since Reanimate already costs life equal to the creature's mana value. Fetching Blood Crypt untapped plus Reanimating Griselbrand costs 10 life total. Consider entering it tapped when possible. Badlands is $200-400 while Blood Crypt is under $15."},
    {"instruction": "What is a budget replacement for Savannah?", "input": "", "output": "Temple Garden replaces Savannah. In Maverick and Enchantress, the 2 life is manageable since these decks gain life incidentally (Knight of the Reliquary blocks well, Enchantress gains life). Savannah is $200-400 while Temple Garden is under $10."},
    {"instruction": "What is a budget replacement for Plateau?", "input": "", "output": "Sacred Foundry replaces Plateau. In Painter, where Plateau provides the white splash for sideboard cards, the life cost is minimal since you only fetch it occasionally. In Boros Initiative, where you need WR consistently, the repeated 2 life adds up against aggressive decks. Plateau is $200-350 while Sacred Foundry is under $15."},
    {"instruction": "What is a budget replacement for Scrubland?", "input": "", "output": "Godless Shrine replaces Scrubland. In Death and Taxes BW builds, the life cost matters more since D&T games often go long and life total becomes relevant. However, D&T typically only runs 1-2 dual lands with the rest being Plains and utility lands, so the impact is limited. Scrubland is $200-400 while Godless Shrine is under $10."},
    {"instruction": "What is a budget replacement for Taiga?", "input": "", "output": "Stomping Ground replaces Taiga. In Lands, Taiga is usually a 1-of that Crop Rotation can find, so the 2 life cost is a single event. In Punishing Maverick, the life cost is more relevant since you fetch it repeatedly. Taiga is $200-400 while Stomping Ground is under $15."},

    # More expensive non-land subs
    {"instruction": "What is a budget replacement for Uro, Titan of Nature's Wrath?", "input": "", "output": "There is no direct replacement for Uro's combination of life gain, card draw, ramp, and recursive threat. Ice-Fang Coatl provides a flash deathtouch body that draws a card for UG but lacks the recursion and ramp. Sylvan Library provides card advantage for G but costs life instead of gaining it. In practice, cutting Uro weakens the grindy long-game plan significantly. Uro is $30-40 each."},
    {"instruction": "What is a budget replacement for Jace, the Mind Sculptor?", "input": "", "output": "Narset, Parter of Veils costs half the mana (1UU vs 2UU) and provides card selection while shutting off opponent card draw, but lacks Jace's bounce ability and ultimate. Teferi, Time Raveler at 1WU bounces permanents and draws cards but requires white. For pure control decks, neither fully replaces Jace's ability to brainstorm every turn and threaten an ultimate. Jace is $30-50 each."},
    {"instruction": "What is a budget replacement for Sylvan Library?", "input": "", "output": "There is no good replacement for Sylvan Library's combination of card selection and card advantage for just 2 mana. Mirri's Guile provides the top-3 look for G but does not draw extra cards. Courser of Kruphix reveals the top card and gains life but costs 3. In green midrange decks, Sylvan Library is a $25-35 card that is worth the investment. No substitute provides the same power level."},
    {"instruction": "What is a budget replacement for Stoneforge Mystic?", "input": "", "output": "There is no functional replacement for Stoneforge Mystic's ability to tutor equipment and cheat it into play for 1W. Steelshaper's Gift tutors equipment to hand for W but does not put it into play. Puresteel Paladin draws cards from equipment but costs WW and needs metalcraft. Without Stoneforge, equipment strategies are not competitive in Legacy. Stoneforge is $15-25 each and one of the more affordable Legacy staples."},
    {"instruction": "What is a budget replacement for Dark Confidant?", "input": "", "output": "Phyrexian Arena draws an extra card per turn for 3 mana instead of 2 but lacks the creature body. Night's Whisper draws 2 for 2 mana as a one-shot effect. In practice, Dark Confidant has been largely replaced by Orcish Bowmasters in the current meta anyway, so the question is less relevant than it used to be. Dark Confidant is $10-15 each."},

    # Budget deck builds
    {"instruction": "Give me a budget version of Death and Taxes.", "input": "", "output": "D&T is already one of the more affordable Legacy decks since it is mostly mono-white. Skip the 1-2 Scrubland/Karakas splash (save $400-800). Run basic Plains instead. Replace Rishadan Port ($80 each) with additional Wastelands or Ghost Quarters if needed. The core of Thalia, Stoneforge Mystic, Aether Vial, Flickerwisp, and Swords to Plowshares is all affordable. Total budget build: $800-1200 vs $2500-3500 optimal."},
    {"instruction": "Give me a budget version of Painter.", "input": "", "output": "Painter's core combo pieces (Painter's Servant $25, Grindstone $25) are affordable. Ancient Tomb ($30) is the main mana investment. Skip City of Traitors ($300 each) and replace with more basic Mountains and Simian Spirit Guide. Replace Imperial Recruiter ($30 each) with Goblin Matron ($1). The deck functions well on a budget since the combo only needs 2 specific artifacts. Total budget: $400-700 vs $2500 optimal."},
    {"instruction": "Give me a budget version of Storm.", "input": "", "output": "The most expensive Storm cards are Lion's Eye Diamond ($300-400 each, need 4). Ruby Storm avoids LED entirely, using Birgi and Ruby Medallion instead with Bonus Round. It costs approximately $200-400 total. For traditional Storm (TES/ANT), there is no replacement for LED. Consider starting with Ruby Storm to learn combo sequencing, then upgrading to TES/ANT when you acquire LEDs."},
    {"instruction": "Give me a budget version of Lands.", "input": "", "output": "Lands is extremely difficult to budget. The Tabernacle at Pendrell Vale ($5000+), Mox Diamond ($400-500 each), and dual lands are all core to the strategy. A budget version cutting Tabernacle, replacing Mox Diamond with Chrome Mox, and using Stomping Ground for Taiga costs $1500-2000 but is significantly weaker. Consider Selesnya Depths ($800-1200) as a budget alternative that uses the same Dark Depths combo without the expensive land-based control elements."},
    {"instruction": "What is the upgrade path from Burn to a more competitive Legacy deck?", "input": "", "output": "From Burn ($1500), the natural upgrade is Red Stompy ($2500) since you already own Mountains, and both decks play aggressive red strategies. Blood Moon, Chalice of the Void, and Ancient Tomb are the main investments. From there, acquiring Volcanic Islands lets you pivot to Izzet Delver by adding cantrips, Force of Will, and Delver of Secrets. This progression goes: Burn -> Red Stompy -> Izzet Delver over $1500 -> $2500 -> $4000."},
    {"instruction": "What is the upgrade path from Oops All Spells to other combo decks?", "input": "", "output": "From Oops ($1100), the shared cards (Force of Will, Lotus Petal, Dark Ritual, Pact of Negation) transfer to several combo decks. Adding Burning Wish and more rituals transitions toward Storm ($2500-5000 depending on LED). Adding Show and Tell and big creatures transitions to Sneak and Show ($4000-5000). The Force of Will set ($320-400) is the biggest shared investment and transfers to any blue deck."},

    # Trade-off analysis
    {"instruction": "What are the hidden costs of playing budget replacements in Legacy?", "input": "", "output": "Beyond the obvious (2 life from shock lands, narrower alternatives), budget replacements have hidden costs: you telegraph to experienced opponents that you are on a budget build, which changes their Wasteland targeting decisions. Shock lands are vulnerable to Price of Progress (double damage per nonbasic) which is more punishing than against dual lands. Budget cards also cannot be found by certain tutors that specify basic land types. The psychological factor of opponents adjusting play based on seeing shock lands is real at competitive events."},
    {"instruction": "Is it better to proxy or play budget substitutions?", "input": "", "output": "It depends on the event. Many local game stores allow proxies for Legacy events, which lets you play the optimal list. MTGO does not use proxies but cards are much cheaper ($300-650 for most decks). For competitive events (SCG Opens, Grand Prix), proxies are not allowed and you need real cards or budget substitutions. If your LGS allows proxies, absolutely use them to learn the deck at full power, then acquire real cards over time for larger events."},
    {"instruction": "Which Legacy staples hold their value best?", "input": "", "output": "Reserved List cards (dual lands, Lion's Eye Diamond, Mox Diamond, City of Traitors, Gaea's Cradle) only go up in value since they can never be reprinted. Force of Will holds value due to constant demand despite reprints. Fetchlands (Polluted Delta, Scalding Tarn) hold value well with periodic dips around reprints. Modern Horizons mythics (Murktide Regent, Orcish Bowmasters, Solitude) are volatile and drop after reprints. Buy Reserved List first since they appreciate, and MH cards last since they depreciate."},
    {"instruction": "Should I buy into Legacy or play on MTGO?", "input": "", "output": "MTGO is the best way to start: full decks cost $300-650 (vs $1000-8000+ paper), leagues fire constantly, and you can sell cards back at 80-90% value if you quit. Paper Legacy is a long-term investment where Reserved List cards appreciate over time. The ideal path is: start on MTGO to learn the format and find your deck, then slowly acquire paper cards for local events. Many serious Legacy players maintain both a paper collection and an MTGO account."},
]

outpath = os.path.join(os.path.dirname(__file__), "..", "data", "training", "budget_substitutions.jsonl")
with open(outpath, "a", encoding="utf-8") as f:
    for pair in pairs:
        f.write(json.dumps(pair, ensure_ascii=False) + "\n")

print(f"Appended {len(pairs)} pairs to {outpath}")
