"""Generate training data - Batch 4 multi-category. Conversation, board state, budget, and more of everything."""
import json
import os

# === CONVERSATION FLOW ===
conversation = [
    {"instruction": "I have $3000 to spend on Legacy. What is the best use of that money?", "input": "", "output": "With $3000 you have several strong options:\n\n1) Full-power Ocelot Pride Midrange (~$2500): Tier 1 deck, no dual lands needed, competitive immediately. Leaves $500 for future upgrades or sideboard tuning.\n\n2) Dimir Tempo with 2 Underground Sea + shock lands (~$2800): Get 2 real duals and fill the rest with Watery Grave. Functional at ~95% power. Upgrade to 3-4 Seas over time.\n\n3) Sneak and Show (~$3000 with careful buying): Ancient Tomb, Show and Tell, Emrakul, Force of Will, cantrips, Lotus Petal. Skip the expensive Volcanic Islands initially.\n\n4) Death and Taxes + Painter (~$2500 combined): Two competitive decks that share no cards, giving you metagame flexibility.\n\nMy recommendation: start with Ocelot Pride or Dimir Tempo. Both are tier 1, teach Legacy fundamentals, and their staples (Force of Will, fetchlands, Bowmasters) transfer to many other decks. What play style do you prefer?"},
    {"instruction": "How do I prepare for a specific matchup I keep losing to?", "input": "", "output": "Follow this process:\n\n1) Identify WHY you are losing. Record your games or write notes. Are you losing to a specific card (Chalice, Blood Moon)? A specific game state (they combo before you can interact)? Or general card quality (they out-value you)?\n\n2) Study the opposing deck. Read the archetype guide, understand their key cards, know their sideboard plan against you.\n\n3) Adjust your sideboard. Dedicate 2-3 slots to your problem matchup. Bring in cards that directly answer their strategy.\n\n4) Practice the matchup. Goldfish against their deck, play test games, learn the key decision points.\n\n5) Adjust your play patterns. Maybe you are fetching wrong, Brainstorming at the wrong time, or using Force of Will on the wrong target.\n\n6) Consider if the matchup is fixable. Some matchups are structurally terrible (Elves vs Bowmasters). If you cannot fix it with sideboard and play changes, accept it and focus on your good matchups.\n\nWhat matchup are you struggling with?"},
    {"instruction": "My deck went 3-2 at a tournament. Two losses were to combo. How do I improve?", "input": "", "output": "3-2 is a solid start! Two combo losses suggests your disruption package or sideboard needs adjustment:\n\n1) Check your maindeck interaction: Do you have 4 Force of Will? If not, that is problem #1. Are you running Thoughtseize or other proactive disruption? Against combo, reactive answers (Daze, Counterspell) are worse than proactive ones (Thoughtseize strips the combo piece before they can use it).\n\n2) Check your sideboard: How many anti-combo cards do you have? With combo at ~40% of the meta, you want 5-7 sideboard slots dedicated to combo. Leyline of the Void (4), Flusterstorm (2), and Surgical Extraction (1) cover most bases.\n\n3) Check your sideboard execution: Were you boarding correctly? Bring in ALL your combo hate, cut your weakest cards (usually creature removal against creatureless combo).\n\n4) Check your play: Against combo, your #1 priority is disruption, #2 is clock. Deploy a threat AND hold up interaction. Do not tap out without Force backup.\n\nWhat combo decks beat you, and what were the key moments?"},
    {"instruction": "I want to switch from Standard to Legacy. What should I know?", "input": "", "output": "The biggest differences from Standard:\n\n1) Speed: Legacy games are often decided by turn 3-4. Turn-1 plays define the game. If your deck does not do something powerful by turn 2, you are behind.\n\n2) Free spells: Force of Will, Daze, and pitch elementals (Solitude, Endurance) mean you are NEVER safe just because your opponent is tapped out. Always consider what free interaction they might have.\n\n3) Brainstorm changes everything: 43% of decks play it. Card selection is so good that Legacy games feel like both players always have the right answer. This is because they often do.\n\n4) The mana is perfect but fragile: Dual lands and fetchlands give flawless mana, but Wasteland and Blood Moon punish it. Always fetch basics early.\n\n5) Sideboard matters more: With 54+ archetypes, your sideboard plan is different every round. Know your sideboard plans BEFORE the tournament.\n\n6) Life total matters less: 20 life is often irrelevant because combo kills you regardless and fair decks end games through board state, not damage racing. The exception is Burn.\n\nThe format is incredibly deep and rewarding. Welcome!"},
    {"instruction": "Can you explain what a Daze check is?", "input": "", "output": "A Daze check is a play pattern where you cast a less important spell first to see if your opponent has Daze before committing your key spell.\n\nExample: You have Delver of Secrets and Murktide Regent in hand, opponent has 1 untapped Island. Cast Delver first (the less important spell). If they Daze it, they bounced their Island - now they have ZERO lands and cannot interact with Murktide next turn. If they do not Daze, Delver resolves and you still have Murktide for later.\n\nThe concept: you are testing (checking) whether they have Daze by offering a bait spell. If they bite, you won the exchange. If they do not, your bait spell still resolved.\n\nAdvanced: experienced players know about Daze checks and may hold Daze for the more important spell. This creates a layer of mind games - do you lead with the card you want to resolve, or the bait? This is one of the deepest strategic elements in Legacy."},
    {"instruction": "My friend says Legacy is dying. Is that true?", "input": "", "output": "No, Legacy is not dying, but it is evolving. The facts:\n\n1) MTGO Legacy leagues fire constantly with healthy participation. The weekly Challenge events draw 32+ players and Showcase Qualifiers draw hundreds.\n\n2) Paper Legacy has challenges due to Reserved List card prices, but local events thrive at stores that allow proxies.\n\n3) The format receives active attention from Wizards with regular B&R updates. The March 2026 announcement specifically analyzed Legacy health.\n\n4) Viewership for Legacy content on YouTube and Twitch is strong. Creators like Phil Gallagher, AnziD, and others have active communities.\n\n5) MH3 and recent sets continue to print Legacy-impactful cards, keeping the format fresh.\n\nThe main barrier is cost, not player interest. Legacy has the most devoted player base of any format because the gameplay is unmatched. Proxy events, MTGO, and community organizations keep it accessible despite Reserved List prices."},
    {"instruction": "What are the most common mistakes new Legacy players make?", "input": "", "output": "The top mistakes:\n\n1) Brainstorming without a shuffle effect. If you cannot crack a fetchland after Brainstorm, you lock yourself with 2 bad cards on top.\n\n2) Using Force of Will on the wrong spell. Do not Force a creature when you should Force the combo piece. Always ask: does this spell win the game if it resolves?\n\n3) Not playing around Daze. If your opponent has an untapped Island and you tap out for a key spell, you deserve to get Dazed.\n\n4) Fetching wrong. Fetching dual land on turn 1 instead of basic when you expect Wasteland is a common error that costs games.\n\n5) Sideboarding incorrectly. Bringing in too many narrow cards or cutting core engine pieces (do not cut Brainstorm unless absolutely necessary).\n\n6) Not knowing opponent's deck. Legacy has 54+ archetypes. If you do not know what your opponent is doing, you cannot make correct decisions.\n\n7) Playing too slowly. Legacy rewards tight, efficient play. Every mana and card matters from turn 1. Durdle and you lose."},
    {"instruction": "How does the London Mulligan work in Legacy?", "input": "", "output": "The London Mulligan: draw 7 cards, decide keep or mulligan. If you mulligan, draw 7 again, then put 1 card on the bottom of your library. Mulligan to 6: draw 7, put 1 on bottom (keep 6). Mulligan to 5: draw 7, put 2 on bottom (keep 5). And so on.\n\nLegacy-specific considerations: 1) Combo decks mulligan aggressively because a 5-card hand with the combo is better than a 7-card hand without it. 2) Tempo decks keep loose hands more often because cantrips fix bad draws. 3) Hands with Brainstorm + fetchland can keep almost anything since Brainstorm sees 3 more cards. 4) Against unknown opponents game 1, keep hands that interact (Force of Will) over hands that are powerful but fragile. 5) After sideboard, you know the matchup - mulligan toward your hate cards."},
]

# === BOARD STATE ANALYSIS ===
board_state = [
    {"instruction": "Board state: I have Stoneforge Mystic in play with Batterskull in hand. Opponent has Kolaghan's Command in hand (I know from Thoughtseize). Should I activate Stoneforge?", "input": "", "output": "Yes, activate Stoneforge to put Batterskull into play now. Kolaghan's Command can destroy an artifact AND force a discard. If you wait and keep Batterskull in hand, K-Command can make you discard Batterskull AND destroy something else. If you put Batterskull into play, K-Command can still destroy it, but at least it does not also strip another card from your hand. Worst case: they K-Command destroying Batterskull + something else, and Batterskull goes to graveyard where you can return it to hand (Batterskull has a bounce ability). By playing it now, you get at least one attack/block and force them to use K-Command defensively."},
    {"instruction": "Board state: I am playing D&T. I have Aether Vial on 2 and Flickerwisp in hand. Opponent attacks with Murktide Regent (7/7). How do I handle this?", "input": "", "output": "You cannot Vial in Flickerwisp because it costs 3, not 2 (Vial has 2 counters). If you had Vial on 3, you could Flickerwisp the Murktide before damage to exile it until end step. With Vial on 2, check what 2-cost creatures you have in hand: Stoneforge Mystic (tutor Batterskull to block next turn), Thalia (does not help here), Phyrexian Revoker (name Murktide? No, it does not have activated abilities). Best play: take the 7 damage, tick Vial to 3, and next attack you can Flickerwisp the Murktide. Alternatively, if you have Swords to Plowshares, cast it targeting Murktide."},
    {"instruction": "Board state: I am at 4 life playing Reanimator. I have Reanimate and Griselbrand in graveyard. Should I Reanimate it?", "input": "", "output": "Reanimate Griselbrand costs life equal to its mana value: 8. You are at 4 life. Reanimating Griselbrand puts you to -4 life and you die before gaining any value. DO NOT Reanimate Griselbrand here. Your options: 1) Reanimate a cheaper creature if one exists in a graveyard (Archon of Cruelty costs 8 too, so same problem). 2) Use Animate Dead or Exhume instead (they do not cost life). 3) Find a way to gain life first. 4) Wait until your life total can sustain the Reanimate cost. Life management is critical in Reanimator."},
    {"instruction": "Board state: My opponent cast Thoughtseize. My hand is: Force of Will, Brainstorm, Ponder, Murktide Regent, Underground Sea. What do they take?", "input": "", "output": "From the opponent's perspective, they are choosing what hurts you most. Force of Will is the correct take in most scenarios because: 1) It is your only free interaction - without it, they can combo or deploy threats freely. 2) Brainstorm and Ponder will find more cards, but Force is unique. 3) Murktide is a threat but can be answered by removal later.\n\nHowever, if the opponent is on combo (Storm, Show and Tell), they take Force 100% of the time. If they are on fair blue, they might take Murktide since it is your best threat and they plan to grind. If they are on aggro, they might take Murktide to prevent being raced.\n\nAs the player being Thoughtseized: after they take Force, immediately Brainstorm to hide your best remaining card(s) on top of your library where Thoughtseize cannot touch them. This is a key response pattern."},
    {"instruction": "Board state: I have Thalia Guardian of Thraben in play. Opponent has 3 mana available. Can they cast Brainstorm + Ponder this turn?", "input": "", "output": "With Thalia in play, noncreature spells cost 1 more. Brainstorm normally costs U, now costs 1U (2 mana). Ponder normally costs U, now costs 1U (2 mana). With 3 mana, the opponent can cast either Brainstorm OR Ponder, but not both (2 + 2 = 4 mana needed). Thalia effectively cuts their cantrip output in half. This is why Thalia is so strong against cantrip decks: they can no longer efficiently chain cantrips to find answers."},
    {"instruction": "Board state: Opponent has Ancient Tomb, City of Traitors, and Chalice of the Void on 1. They play a second Chalice on 0. What does this lock out?", "input": "", "output": "Chalice on 1 counters all spells with mana value 1: Brainstorm, Ponder, Swords to Plowshares, Lightning Bolt, Thoughtseize, Daze, Delver, and most 1-mana interaction. Chalice on 0 counters all spells with mana value 0: Lotus Petal, Mox Opal, Mishra's Bauble, Engineered Explosives (cast for X=0), Chrome Mox, and Mox Diamond. Together, they lock out everything costing 0 or 1. Your opponent still has access to 2+ mana spells: Force of Will (5), Show and Tell (3), Murktide Regent (2 with delve). Focus your game plan on 2+ mana spells and use Force of Vigor (free by pitching green) to destroy the Chalices."},
    {"instruction": "Board state: I am playing TES. I have 5 mana, Ad Nauseam in hand, and I am at 14 life. Is it safe to cast Ad Nauseam?", "input": "", "output": "Ad Nauseam reveals cards from the top of your library and puts them into your hand, losing life equal to each card's mana value. You stop whenever you choose. At 14 life, you can safely reveal approximately 10-14 cards (average mana value in TES is about 1.0-1.2). This should give you enough rituals, LED, and Burning Wish to kill. Key risks: revealing expensive spells back-to-back (Burning Wish at MV 2, Force of Will at MV 5 could cost 7 life in 2 reveals). Stop when you have enough mana + storm for lethal Tendrils. Safe threshold: stop when you are at 4-5 life remaining to avoid dying to your own Storm next turn. 14 life is a comfortable Ad Nauseam."},
    {"instruction": "Board state: I have Dark Depths with 0 ice counters and Thespian's Stage. Opponent has Wasteland untapped. What is my line?", "input": "", "output": "If you activate Thespian's Stage to copy Dark Depths while opponent has Wasteland untapped, they can respond to the activation by Wastelanding either Dark Depths or Thespian's Stage. If they Wasteland the Stage, the copy ability fizzles and you have no Stage and still a Depths with 0 counters. If they Wasteland Dark Depths, the copy ability still resolves (it was already on the stack) and Stage becomes a copy of Dark Depths with 0 counters, creating Marit Lage.\n\nBest line: activate Stage targeting Dark Depths. If they Wasteland Depths in response, you still get Marit Lage (Stage copies the last known state). If they Wasteland Stage, you lose but can recover with Crop Rotation or Life from the Loam. If they Wasteland before you activate, you lost your window. Act during their end step to minimize their response window."},
    {"instruction": "Board state: Opponent has True-Name Nemesis (protection from me). I need to remove it. What are my options?", "input": "", "output": "True-Name Nemesis has protection from you, which means you cannot target it, deal damage to it, block it, or enchant it. Options that work:\n\n1) Non-targeting removal: Toxic Deluge (-X/-X to all creatures, does not target), Terminus (tuck all creatures, does not target), Council's Judgment (opponents vote, does not target), Supreme Verdict (destroy all, does not target).\n\n2) Sacrifice effects: Liliana of the Veil -2 (opponent sacrifices), Diabolic Edict (opponent sacrifices), Sheoldred's Edict.\n\n3) Mass bounce: Cyclonic Rift overloaded (does not target when overloaded).\n\n4) Race it: TNN is a 3/1, dealing 3 per turn. If you have a faster clock, just race and ignore it.\n\nThe most played answer is Toxic Deluge (13% of decks) since it handles TNN and anything else for variable cost. Terminus is next best in UW decks."},
    {"instruction": "Board state: I have Brainstorm and 2 fetchlands in play, no other cards in hand. Should I crack a fetch first or Brainstorm first?", "input": "", "output": "Brainstorm first, then crack fetch. Here is why:\n\n1) Cast Brainstorm: draw 3 cards, put 2 bad ones on top.\n2) Crack fetchland: shuffle away the 2 bad cards.\n3) You kept the best of 4 cards (3 drawn + eventual draw) and have 1 fetchland remaining for the next Brainstorm.\n\nIf you crack fetch first, you waste a shuffle effect. Then after Brainstorm, you put 2 bad cards on top and only have 1 fetch left to shuffle (instead of 2). You would draw 1 bad card before shuffling the second away.\n\nException: if you need a specific color of mana RIGHT NOW to cast Brainstorm (e.g., you need U and only have a fetchland), then fetch first to get an Island, then Brainstorm. But if you already have U available, always Brainstorm first."},
]

# === MORE BUDGET SUBSTITUTIONS ===
budget = [
    {"instruction": "Give me a complete budget Legacy collection for under $500 that lets me play multiple decks.", "input": "", "output": "For $500, focus on mono-colored and colorless decks:\n\n1) Burn core ($200): 4 Lightning Bolt, 4 Chain Lightning, 4 Eidolon of the Great Revel, 4 Goblin Guide, 4 Monastery Swiftspear, 4 Price of Progress, 4 Lava Spike, 4 Rift Bolt, Mountains.\n\n2) Red Stompy shell ($250 additional): 4 Chalice of the Void ($20 each), 4 Ancient Tomb ($30 each), 4 Blood Moon ($10 each), Chrome Mox.\n\nShared cards: Mountains, Simian Spirit Guide, Fiery Confluence. The Burn shell and Red Stompy shell share $100+ of cards.\n\nFuture upgrades: These red staples (Chalice, Ancient Tomb, Blood Moon) also go into Eldrazi, Painter, and other prison decks. You are building a collection foundation, not a dead end."},
    {"instruction": "What is the cheapest way to build a Force of Will deck?", "input": "", "output": "Force of Will is $80-100 each, so 4 copies cost $320-400. The cheapest deck that uses Force:\n\n1) Oops All Spells (~$1100): 4 Force of Will is the single biggest expense. The rest is Lotus Petal ($20 each), Pact of Negation ($15 each), and commons/uncommons. No dual lands.\n\n2) Stiflenought (~$800): Force of Will, Stifle, Phyrexian Dreadnought, Daze, Brainstorm, Ponder. No dual lands (run basics + fetchlands). The combo is dirt cheap, Force is the expensive part.\n\n3) Mono Blue Control (~$700): Back to Basics lock, Force of Will, counterspells, basic Islands. No dual lands needed.\n\nIn all cases, Force of Will at $320-400 is 30-50% of the deck cost. But Force transfers to every blue deck in Legacy, so it is the single best investment for a Legacy player."},
    {"instruction": "How do I prioritize Legacy card purchases over time?", "input": "", "output": "Priority order for building a Legacy collection:\n\n1) Fetchlands ($20-40 each): Go in every deck. Buy a playset of Polluted Delta and Flooded Strand or Misty Rainforest first.\n\n2) Force of Will ($80-100 each): Goes in every blue deck. The single most important Legacy staple.\n\n3) Brainstorm + Ponder ($1-5 each): Dirt cheap, play 4 of each immediately.\n\n4) Your first dual land ($300-600): Buy 1 copy of your deck's primary dual. This is both a gameplay upgrade and a financial investment (Reserved List appreciates).\n\n5) Deck-specific staples: Wasteland ($30), Thoughtseize ($15), Lightning Bolt ($3), Swords to Plowshares ($3).\n\n6) Sideboard staples: Leyline of the Void ($5), Surgical Extraction ($5), Pyroblast ($2).\n\n7) Additional dual lands: Buy 1 more every few months.\n\nThe key: buy Reserved List cards when possible since they only go up. Buy non-Reserved staples after reprints when prices dip."},
    {"instruction": "Can I build competitive Legacy using only cards from Modern?", "input": "", "output": "Partially. Many Legacy staples are Modern-legal: Lightning Bolt, Thoughtseize, fetchlands, Chalice of the Void, Ancient Tomb (actually not Modern-legal), most creatures. But critical Legacy cards are NOT Modern-legal: Force of Will, Brainstorm, Ponder, Daze, Wasteland, Swords to Plowshares, Dark Ritual, dual lands, Show and Tell, Reanimate, Lion's Eye Diamond.\n\nDecks you CAN build from mostly Modern cards: Burn (90% overlap), Eldrazi (70% overlap - needs Ancient Tomb, City of Traitors), Death's Shadow (60% overlap).\n\nDecks you CANNOT: Anything blue (needs Brainstorm, Force, Daze), combo (needs format-specific cards), Lands (entirely Legacy-only cards).\n\nThe honest answer: Legacy is a different format. Trying to build Legacy from Modern cards produces a Modern deck playing in Legacy, not a Legacy deck."},
    {"instruction": "What are the best free-to-play ways to practice Legacy?", "input": "", "output": "Several options:\n\n1) Cockatrice: Free desktop client. Build any deck with no cost. Active Legacy community. Quality of opponents varies.\n\n2) Moxfield Playtest: Free goldfishing (no opponent). Practice opening hands, sequencing, and mulligan decisions.\n\n3) XMage: Free open-source client with rules enforcement. Smaller community than Cockatrice but better for learning rules.\n\n4) MTG Forge: Free single-player against AI. Good for learning card interactions.\n\n5) Watch streams and videos: Phil Gallagher, AnziD, Julian Knab, and others stream Legacy on Twitch and YouTube. Watching expert play teaches decision-making.\n\n6) MTGO rental services (nearly free): Services like Cardhoarder let you rent MTGO cards. Rent a Legacy deck for $20-30/month and play in leagues and tournaments.\n\nThe best approach: goldfish on Moxfield to learn your deck, watch streams to learn the format, then play on Cockatrice or MTGO rental to test against real opponents."},
    {"instruction": "How much does it cost to play Legacy on MTGO?", "input": "", "output": "MTGO Legacy is dramatically cheaper than paper:\n\nDeck costs (MTGO tix): Oops All Spells ~100 tix ($100), Burn ~50 tix, Dimir Tempo ~350-450 tix, Sneak and Show ~300-400 tix, Lands ~400-500 tix, Painter ~200-300 tix.\n\nEntry fees: Leagues cost 10 tix for 5 matches. Challenges cost 30 tix with prize support. Preliminary events cost 20 tix.\n\nResale value: MTGO cards can be sold back through bots at 80-90% of purchase price. If you quit, you recover most of your investment.\n\nMonthly cost: If you play 2-3 leagues per week, expect 20-30 tix in entry fees. Prize payouts offset this if you win 3+ matches per league.\n\nBottom line: $300-500 gets you a competitive MTGO Legacy deck with minimal ongoing cost. Compare to $3000-8000 for paper. MTGO is by far the most accessible way to play competitive Legacy."},
]

# Write all three files
for category, data, filename in [
    ("conversation_flow", conversation, "conversation_flow.jsonl"),
    ("board_state_analysis", board_state, "board_state_analysis.jsonl"),
    ("budget_substitutions", budget, "budget_substitutions.jsonl"),
]:
    outpath = os.path.join(os.path.dirname(__file__), "..", "data", "training", filename)
    with open(outpath, "a", encoding="utf-8") as f:
        for pair in data:
            f.write(json.dumps(pair, ensure_ascii=False) + "\n")
    print(f"Appended {len(data)} pairs to {filename}")

