"""Generate deckbuilding rationale training data - Batch 2 (append)."""
import json
import os

pairs = [
    # === MORE CARD-IN-DECK RATIONALE (covering more archetypes) ===
    # Beanstalk Control
    {"instruction": "Why does Beanstalk Control play Up the Beanstalk?", "input": "", "output": "Up the Beanstalk is a 2-mana enchantment that draws a card whenever you cast a spell with mana value 5 or greater. In Legacy, Force of Will (MV 5), Solitude (MV 5), Fury (MV 5), and Subtlety (MV 5) all trigger it even when cast for their free alternative costs. This turns pitch spells into cantrips, generating absurd card advantage while doing things you already wanted to do."},
    {"instruction": "Why does Beanstalk Control play Solitude?", "input": "", "output": "Solitude is a free removal spell that exiles a creature by pitching a white card. In Beanstalk, it also triggers Up the Beanstalk to draw a card, making the pitch cost less painful. The 3/2 lifelink body is relevant when evoked and blinked with Ephemerate, gaining 3 life and exiling another creature. It handles problematic threats like Murktide Regent and True-Name Nemesis that dodge other removal."},
    # Reanimator
    {"instruction": "Why does Reanimator play Reanimate over other reanimation spells?", "input": "", "output": "Reanimate costs just 1 black mana, making it the cheapest and fastest reanimation spell. The life cost equal to the target creature's mana value is steep (8 for Griselbrand, 7 for Archon of Cruelty) but irrelevant when the reanimated creature immediately takes over the game. At 1 mana, Reanimate can be cast through Daze and Thalia while still leaving mana for protection."},
    {"instruction": "Why does Reanimator play Archon of Cruelty?", "input": "", "output": "Archon of Cruelty has an ETB that forces the opponent to sacrifice a creature or planeswalker, discard a card, and lose 3 life, while you draw a card and gain 3 life. This 6-for-1 swing on entry is devastating even if Archon is immediately removed. Unlike Griselbrand, Archon cannot be exiled by Karakas (it is not legendary) and provides value regardless of your life total."},
    {"instruction": "Why did Reanimator decline after the Entomb ban?", "input": "", "output": "Entomb was a 1-mana instant that put any creature directly into the graveyard, enabling turn-1 Entomb into turn-1 Reanimate kills. Without it, Reanimator must use slower discard outlets like Faithful Mending or Careful Study, which cost 2 mana and require drawing the creature first. This extra turn of setup gives opponents time to find Surgical Extraction, Force of Will, or graveyard hate."},
    # Elves
    {"instruction": "Why does Elves play Glimpse of Nature?", "input": "", "output": "Glimpse of Nature turns every creature cast into a cantrip for the rest of the turn, drawing a card per creature. With Heritage Druid providing mana from untapped elves and Nettle Sentinel untapping on each green spell, Elves can chain 5-10 creatures in a single turn, drawing into Natural Order or Craterhoof Behemoth for the kill. Glimpse is the engine that turns a pile of 1-mana creatures into a combo deck."},
    {"instruction": "Why does Elves play Natural Order?", "input": "", "output": "Natural Order sacrifices a green creature to tutor any green creature directly into play. In Elves, this means sacrificing a 1-mana elf to get Craterhoof Behemoth, which gives all your creatures +X/+X and trample where X is your creature count. With 5+ elves in play, this is typically a one-shot kill. Natural Order also finds silver bullets like Endurance or Collector Ouphe from the toolbox."},
    # Dredge
    {"instruction": "Why does Dredge play Lion's Eye Diamond?", "input": "", "output": "LED is the best card in Dredge because discarding your hand is an UPSIDE - it puts dredge cards into the graveyard where you want them. Cracking LED in response to a draw effect lets you dredge on the next draw while also generating 3 mana for Faithless Looting flashback or other spells. Turn-1 LED into draw spell is the explosive start that makes Dredge competitive."},
    {"instruction": "Why does Dredge play Ichorid?", "input": "", "output": "Ichorid returns from the graveyard to the battlefield for free at the beginning of your upkeep by exiling a black creature card. Since Dredge fills the graveyard with creatures naturally, Ichorid provides a recurring threat that costs zero mana and zero cards from hand. Multiple Ichorids coming back every turn create inevitability even through removal."},
    # Red Stompy
    {"instruction": "Why does Red Stompy play Blood Moon?", "input": "", "output": "Blood Moon turns all nonbasic lands into Mountains, shutting off dual lands, fetchlands, Wasteland, Urza's Saga, Dark Depths, and utility lands. In a format where most decks run 15+ nonbasics, Blood Moon effectively locks opponents out of casting their spells. Red Stompy only needs Mountains, so Blood Moon does not affect its own mana base at all."},
    {"instruction": "Why does Red Stompy play The One Ring?", "input": "", "output": "The One Ring provides protection from everything for a turn (buying time to set up locks) and draws increasing numbers of cards each turn. In a prison deck that aims to stop the opponent from playing, The One Ring provides the card advantage needed to find more lock pieces and threats. The cumulative life loss is acceptable because the opponent should be locked out by then."},
    {"instruction": "Why does Red Stompy play Chrome Mox?", "input": "", "output": "Chrome Mox provides turn-1 acceleration by imprinting a nonartifact, nonland card. Combined with Ancient Tomb or City of Traitors, Chrome Mox enables turn-1 Blood Moon, turn-1 Chalice of the Void on 1, or turn-1 Trinisphere. The card disadvantage of imprinting is acceptable because a resolved turn-1 lock piece often wins the game by itself."},
    # Aluren
    {"instruction": "Why does Aluren play Acererak the Archlich?", "input": "", "output": "Acererak the Archlich costs 3 mana, so it can be cast for free with Aluren. When Acererak enters the battlefield, you choose to not complete the dungeon, which returns Acererak to your hand. This creates an infinite loop: cast Acererak for free, fail dungeon, return to hand, repeat. Each iteration progresses you through a dungeon, eventually dealing lethal damage through Lost Mine of Phandelver's drain room."},
    # Cloudpost
    {"instruction": "Why does Cloudpost Ramp play Glimmerpost?", "input": "", "output": "Glimmerpost gains 1 life for each Locus you control when it enters, but more importantly it is a Locus that makes Cloudpost tap for more mana. With Cloudpost tapping for mana equal to Loci count, each Glimmerpost effectively adds 1 mana to every Cloudpost. Two Cloudposts and a Glimmerpost means each Cloudpost taps for 3 mana - 6 total from two lands."},
    # Stiflenought
    {"instruction": "Why does Stiflenought play Phyrexian Dreadnought?", "input": "", "output": "Phyrexian Dreadnought is a 12/12 trample for just 1 colorless mana, with a drawback that you must sacrifice 12 power of creatures when it enters or sacrifice it. With Stifle countering the ETB trigger, or Dress Down removing all abilities, you get a 12/12 on turn 1-2 for practically no cost. A 12/12 trample kills in two attacks and survives every damage-based removal in the format."},
    # Food Chain
    {"instruction": "Why does Food Chain play Misthollow Griffin?", "input": "", "output": "Misthollow Griffin can be cast from exile, which is unique in Magic. Food Chain exiles a creature to generate mana equal to its mana value plus 1 (but only for creature spells). Exile Griffin to Food Chain for 5 mana, recast Griffin from exile for 4 mana, net +1 mana each cycle. This creates infinite mana for creature spells, enabling Walking Ballista for infinite damage."},

    # === MORE MATCHUP REASONING ===
    {"instruction": "Why is Storm favored against Death and Taxes?", "input": "", "output": "D&T has no free counterspells to stop the combo turn. Thalia taxes Storm's spells by 1 each, but Storm can remove Thalia with a bounce spell or simply generate enough mana to pay through the tax. D&T's clock is too slow to kill before Storm goes off on turns 3-4, and Rishadan Port tapping one land is insufficient disruption against a deck that generates 10+ mana in a single turn."},
    {"instruction": "Why is Doomsday harder to play than other combo decks?", "input": "", "output": "Doomsday requires you to construct a 5-card pile that wins through whatever disruption the opponent might have, accounting for cards in hand, mana available, and cards you need to draw through. Different matchups require different piles (play around Surgical, play around Force of Will, play around Stifle). A wrong pile construction means you lose with no recourse. Other combo decks just need to find pieces and cast them."},
    {"instruction": "Why does Merfolk struggle in the current metagame?", "input": "", "output": "Orcish Bowmasters in 29% of decks is devastating against a deck full of 2-toughness creatures. Bowmasters kills Lord of Atlantis on sight and punishes every cantrip Merfolk casts. The deck also lacks free countermagic beyond Force of Will, making it weaker against combo than Delver variants. True-Name Nemesis is the one bright spot but costs 3 mana in a deck that wants to curve out with lords."},
    {"instruction": "Why is Ocelot Pride Midrange strong against creature decks?", "input": "", "output": "Ocelot Pride creates tokens on every non-combat damage trigger, so Lightning Bolt, Bowmasters pings, and Guide of Souls drain all generate extra bodies. The deck goes wide faster than most creature strategies can manage, and Swords to Plowshares plus Solitude handle any individual large threat. Against decks like D&T or Elves, Ocelot simply out-values them in creature combat."},
    {"instruction": "Why does Infect have polarized matchups?", "input": "", "output": "Infect wins by dealing just 10 poison with pump spells on an unblocked infect creature, which can happen as early as turn 2. Against decks without removal (combo, some prison), this is virtually unbeatable speed. But against decks with efficient removal (Swords to Plowshares, Lightning Bolt, Orcish Bowmasters), killing the infect creature in response to a pump spell is a devastating blowout that wastes multiple cards."},

    # === MORE MANA BASE AND CONSTRUCTION ===
    {"instruction": "How do you build a mana base for a three-color Legacy deck?", "input": "", "output": "Start with 4 fetchlands that find both your primary and secondary duals (e.g., Polluted Delta in UBx). Run 3-4 of your primary dual land, 1-2 of your secondary dual, and 2-3 basics (at least one of each primary color). Add 4 Wasteland if your deck is tempo-oriented. Total lands typically 18-20 for tempo, 22-24 for midrange. The key is ensuring 14+ sources of your primary color for turn-1 plays and 10+ of each secondary color."},
    {"instruction": "When should a Legacy deck play Ancient Tomb?", "input": "", "output": "Ancient Tomb belongs in decks that benefit from 2 colorless mana on turn 1 and can tolerate the 2 life per tap. This means prison decks (Chalice, Trinisphere, Blood Moon), artifact combo (Mystic Forge, Painter), Eldrazi (creatures cost 2+), and Show and Tell variants. It does NOT belong in tempo decks that need colored mana for cantrips or control decks that need every life point. The 2 life per use adds up fast."},
    {"instruction": "Why do some decks play City of Traitors over Ancient Tomb?", "input": "", "output": "City of Traitors provides 2 colorless mana without the 2 life cost, which matters in Eldrazi and prison decks that activate it many times. The downside is that it is sacrificed when you play another land, so it is better in decks that want to deploy one big play early (turn-1 Chalice + creature) rather than sustained mana production. Many decks play a split of both to maximize explosive starts."},
    {"instruction": "How many lands should a combo deck play?", "input": "", "output": "Combo decks typically play 14-18 lands depending on their mana curve and acceleration. Storm plays 14-15 with rituals providing the rest. Sneak and Show plays 16-18 with Lotus Petal and Ancient Tomb. Oops plays 0 (by design). Doomsday plays 16-17 with Dark Ritual. The key is having enough mana to cast your combo pieces on turns 2-3 while maximizing spell density for consistency."},
    {"instruction": "What is the correct fetchland configuration for Dimir Tempo?", "input": "", "output": "Most Dimir Tempo lists play 8 fetchlands: 4 Polluted Delta (finds Underground Sea and both basics) plus 4 Misty Rainforest, Flooded Strand, or Scalding Tarn (any blue fetch that finds Island). The second set of fetches is chosen based on splash potential: Misty for green sideboard cards, Scalding Tarn for Volcanic Island splash, Flooded Strand for Tundra splash. All 8 find basic Island, which is the most important basic."},

    # === MORE SIDEBOARD STRATEGY ===
    {"instruction": "How should I sideboard against Eldrazi?", "input": "", "output": "Chalice of the Void on 1 is their key card, so bring in cards that cost 0 or 2+ mana. Force of Vigor destroys Chalice for free. Engineered Explosives on 0 catches Chalice. Keep your big threats (Murktide survives anything Eldrazi throws at it). Cut low-impact 1-mana spells that get countered by Chalice. The matchup is about resolving threats through Chalice and going bigger than their creatures."},
    {"instruction": "How should I sideboard against Lands?", "input": "", "output": "Blood Moon effects are the best answer to Lands since their entire strategy is built on nonbasic lands. Surgical Extraction on Life from the Loam shuts down their recursion engine. Dress Down prevents Thespian's Stage from copying Dark Depths. Price of Progress deals massive damage against a deck with 30+ nonbasic lands. Cut your Dazes (they have few spells to counter) and creature removal (they have few creatures)."},
    {"instruction": "How should I sideboard against Ocelot Pride?", "input": "", "output": "Bring in sweepers like Toxic Deluge (kills through Solitude protection) and Massacre (free against white). Engineered Explosives on 1 catches most of their threats. Keep Orcish Bowmasters (excellent against their token generation). Cut Daze (they have enough mana to pay) and narrow countermagic. The goal is to go bigger with card advantage and sweepers rather than trying to one-for-one their value engine."},
    {"instruction": "How should I sideboard against Doomsday?", "input": "", "output": "Keep all countermagic (Force, Daze, Flusterstorm). Bring in Surgical Extraction (exile Doomsday from graveyard after they cast it, or target Thassa's Oracle). Stifle the Oracle ETB trigger if you play it. Thoughtseize is excellent since stripping Doomsday itself prevents the combo. The key is preventing Doomsday from resolving or disrupting the pile execution afterward."},
    {"instruction": "When should I bring in Mindbreak Trap?", "input": "", "output": "Mindbreak Trap is best against Storm and Oops All Spells because it exiles spells for free when the opponent has cast 3+ spells this turn (which both decks do every combo turn). It cannot be countered by Flusterstorm since it is exiled rather than countered. Bring it in against any deck that chains multiple spells in a single turn. It is dead against fair decks that cast one spell per turn."},
    {"instruction": "When should I bring in Null Rod or Collector Ouphe?", "input": "", "output": "Null Rod and Collector Ouphe shut off all activated abilities of artifacts. Bring them in against Painter (stops Grindstone activation), 8-Cast and Affinity (stops Urza's Saga, artifact mana), Mystic Forge (stops the Forge itself), and any deck heavily reliant on artifact mana (Lion's Eye Diamond, Lotus Petal, Chrome Mox). Be careful not to board them in when your own deck uses artifact mana."},
    {"instruction": "How do I use Force of Vigor effectively?", "input": "", "output": "Force of Vigor destroys two artifacts and/or enchantments for free by pitching a green card. It is devastating against Chalice of the Void (on 1 and 2), Urza's Saga and its Construct tokens, Blood Moon, Ensnaring Bridge, and The One Ring. The two-for-one aspect makes it better than Nature's Claim in matchups where the opponent has multiple problematic artifacts or enchantments. Always pitch it rather than hard-casting if possible."},

    # === DECK CONSTRUCTION PRINCIPLES ===
    {"instruction": "What is the 60-card rule in Legacy deck construction?", "input": "", "output": "Legacy decks must have a minimum of 60 cards in the main deck and up to 15 in the sideboard. While you can play more than 60, virtually every competitive deck plays exactly 60 because more cards reduces consistency - you are less likely to draw your best cards. The only exception is Yorion companion decks that play 80 cards, accepting reduced consistency for the companion advantage."},
    {"instruction": "How do I choose between a 60-card and 80-card build?", "input": "", "output": "Play 80 cards only with Yorion, Sky Nomad as companion, and only if your deck has enough blink targets to justify Yorion's ETB. Death and Taxes (Yorion BW), Beanstalk Control (Yorion builds), and some Bant builds use 80 cards. The 20 extra cards reduce consistency but Yorion's guaranteed value compensates. If your deck does not have strong ETB creatures to blink, 60 cards is strictly better."},
    {"instruction": "How do I decide which cards to play 4 copies of?", "input": "", "output": "Play 4 copies of cards you want to see in every opening hand and every game. In Dimir Tempo, that means 4 Brainstorm, 4 Ponder, 4 Force of Will, 4 Daze, 4 Wasteland, 4 Bowmasters. Play 3 copies of cards that are great but occasionally redundant (3 Murktide, 3 Thoughtseize). Play 1-2 copies of situational cards or legends (1 Karakas, 2 Snuff Out). The cantrips help find your 1-2 ofs when needed."},
    {"instruction": "What does a well-constructed Legacy deck curve look like?", "input": "", "output": "Tempo decks peak at 1-2 mana: 20+ spells at 0-1 mana, 8-12 at 2 mana, 2-4 at 3+ mana. Control decks are flatter: 10-12 at 1 mana, 8-10 at 2, 4-6 at 3, 2-4 at 4+. Combo decks are bimodal: many 0-1 mana spells (rituals, cantrips) and a few high-impact 3-4 mana payoffs. Prison decks spike at 0 and 3: fast mana (0) into lock pieces (3). Legacy is defined by mana efficiency - 4+ mana spells need to be game-winning to justify their slot."},

    # === ARCHETYPE SELECTION GUIDANCE ===
    {"instruction": "I like controlling the board and winning with inevitability. What Legacy deck should I play?", "input": "", "output": "Beanstalk Control or Jeskai Control are your best options. Beanstalk generates card advantage through Up the Beanstalk triggers on pitch spells, plays sweepers and removal, and wins through accumulated value. Jeskai Control uses Swords to Plowshares, Lightning Bolt, countermagic, and planeswalkers to grind opponents out. Lands is another option if you want a non-traditional control deck that operates entirely through lands."},
    {"instruction": "I like fast, aggressive decks that win before the opponent sets up. What Legacy deck should I play?", "input": "", "output": "For combo speed: Oops All Spells can win turn 1, Storm and Doomsday win turns 2-3, Sneak and Show wins turns 2-3. For aggressive creature speed: Ocelot Pride Midrange deploys efficient threats from turn 1 and overwhelms quickly, Burn goes face from turn 1. For tempo aggression: Dimir Tempo and Izzet Delver deploy cheap threats and protect them with free countermagic while denying opponent's mana."},
    {"instruction": "I want to play a deck that taxes and disrupts the opponent. What Legacy deck should I play?", "input": "", "output": "Death and Taxes is the premier tax deck: Thalia taxes spells, Rishadan Port and Wasteland tax mana, and Aether Vial lets you deploy creatures while keeping tax mana open. Red Stompy provides artifact-based prison with Chalice of the Void, Blood Moon, and Trinisphere. Eldrazi combines Chalice prison with large aggressive creatures. All three specialize in preventing the opponent from playing their game."},
    {"instruction": "I have a small budget. What competitive Legacy deck can I build?", "input": "", "output": "Oops All Spells at $1100 is the cheapest tier 1 deck - zero dual lands needed. Burn at $1500 is a consistent performer with no expensive Reserved List cards. Belcher at $1200 is similar to Oops in strategy and price. Red Stompy at $2500 avoids dual lands and uses Ancient Tomb as its main investment. Eldrazi at $2100 is all colorless. All five can win tournaments and serve as entry points into Legacy."},
    {"instruction": "I want to play a unique brew in Legacy. How do I approach it?", "input": "", "output": "Start by identifying a meta weakness: if 14.6% of the field is Dimir Tempo, build something that beats UB. Study underplayed archetypes with high win rates (Aluren won the Showcase Qualifier at only 1.2% meta share). Use established Legacy shells as foundations (cantrip + Force of Will, Ancient Tomb + Chalice, Green Sun's Zenith toolbox) and add your unique angle. Test extensively against tier 1 decks before committing - a brew that loses to the top 3 decks is just a bad deck."},

    # === CARD QUANTITY DECISIONS ===
    {"instruction": "How many copies of Wasteland should I play?", "input": "", "output": "4 copies in tempo decks (Delver, D&T) where mana denial is core strategy. 4 in Lands where Wasteland recursion with Loam is the primary gameplan. 2-3 in midrange decks that want it but cannot afford too many colorless sources. 0 in combo decks that need every land to produce colored mana and cannot afford to sacrifice a land drop for mana denial. 0 in control decks that need to hit land drops every turn."},
    {"instruction": "How many copies of Thoughtseize should I play?", "input": "", "output": "4 copies in Dimir Tempo where proactive disruption is essential. 3-4 in combo decks that need to clear the way for their combo turn. 2-3 in midrange decks as a flexible disruption spell. 0 in most blue control decks that prefer reactive answers (countermagic). The life cost matters against aggro, so some players trim to 2-3 post-board against Burn or Ocelot Pride. Thoughtseize is best when you know what to take, so format knowledge increases its value."},
    {"instruction": "How many copies of Orcish Bowmasters should I play?", "input": "", "output": "4 copies in any black deck that can cast it reliably. Bowmasters is the most played creature in Legacy at 29% of decks because it punishes cantrips (43% of decks play Brainstorm), provides a flash threat, and creates tokens for board presence. The only reason to play fewer is if your deck cannot reliably produce BB by turn 2, or if your strategy does not benefit from creature-based interaction."},
    {"instruction": "How many copies of Swords to Plowshares should I play?", "input": "", "output": "4 copies in creature-heavy matchups and control decks. 2-3 in tempo decks that also run other removal. 0 in combo decks that do not care about opposing creatures. Swords is the best creature removal spell ever printed at 1 mana instant exile, but the life gain for the opponent can be relevant against combo where every point of reach matters. Some players trim Swords against combo-heavy fields."},
]

outpath = os.path.join(os.path.dirname(__file__), "..", "data", "training", "deckbuilding_rationale.jsonl")
# Append to existing file
with open(outpath, "a", encoding="utf-8") as f:
    for pair in pairs:
        f.write(json.dumps(pair, ensure_ascii=False) + "\n")

print(f"Appended {len(pairs)} pairs to {outpath}")
