"""Generate rules Q&A training data - Batch 2 (append)."""
import json
import os

pairs = [
    # === MORE LEGACY-SPECIFIC INTERACTIONS ===
    {"instruction": "Can I Stifle a fetchland activation?", "input": "", "output": "Yes. Fetchland activations are activated abilities that go on the stack. Stifle counters the ability, so the fetchland is sacrificed (as part of the cost) but you do not search for a land. This is a devastating tempo play in Legacy because your opponent loses both the fetchland AND the land drop they expected. Stifle on a fetchland is a 1-mana Stone Rain."},
    {"instruction": "Can I Stifle the storm trigger?", "input": "", "output": "Yes. Storm is a triggered ability that triggers when the spell with storm is cast. When Tendrils of Agony is cast with a storm count of 10, the storm trigger goes on the stack creating 10 copies. You can Stifle the storm trigger itself before the copies are created, leaving only the original spell on the stack. This turns a lethal Tendrils into a single 2-life drain."},
    {"instruction": "Does Orcish Bowmasters trigger once or three times off Brainstorm?", "input": "", "output": "Three times. Brainstorm says 'draw three cards' which means three separate card draw events. Orcish Bowmasters triggers on each card drawn beyond the first each turn. If Brainstorm is the first draw effect of the turn, the first card drawn is the normal draw, and the second and third trigger Bowmasters twice. If the opponent already drew for turn, all three Brainstorm draws trigger Bowmasters. Each trigger creates a 1/1 Orc Army and deals 1 damage."},
    {"instruction": "Can I respond to a Thespian's Stage copying Dark Depths?", "input": "", "output": "Yes, but timing matters. Thespian's Stage's copy ability goes on the stack. You can respond by destroying Stage or Depths before the ability resolves. Once the ability resolves, Stage becomes a copy of Dark Depths with zero ice counters (the counters are not copied). The state-based action of having zero counters then triggers, sacrificing it to create Marit Lage. You can respond to the sacrifice trigger with removal, but once Marit Lage is created, it is a 20/20 indestructible that is very hard to answer."},
    {"instruction": "How does Daze interact with Thalia, Guardian of Thraben?", "input": "", "output": "Thalia makes noncreature spells cost 1 more. Daze has an alternative cost of returning an Island to your hand instead of paying its mana cost of U. However, Thalia adds 1 to the total cost regardless of how you pay. So to cast Daze via its alternative cost with Thalia in play, you must return an Island AND pay 1 mana. This effectively makes Daze not free against Death and Taxes, significantly weakening it."},
    {"instruction": "Can I activate Wasteland targeting my own land?", "input": "", "output": "Yes. Wasteland says 'destroy target nonbasic land' with no restriction on controller. You can target your own nonbasic land. This is sometimes correct: if your opponent controls Blood Moon, your nonbasic lands are Mountains. You can Wasteland your own 'Mountain' before it would be useful, or in response to a Price of Progress to reduce the damage. It also puts a land in the graveyard for Deathrite Shaman or threshold."},
    {"instruction": "If my opponent plays Show and Tell, can I put a Karakas into play and bounce their creature?", "input": "", "output": "Not immediately. Show and Tell has each player put a permanent into play simultaneously. Both Karakas and their Emrakul enter at the same time. You do not get priority to activate Karakas until after Show and Tell finishes resolving. At that point, you CAN tap Karakas to bounce their legendary creature. So yes, you can bounce Emrakul with Karakas off Show and Tell, but only after everything has entered play."},
    {"instruction": "Does Chalice of the Void on 0 counter Lotus Petal?", "input": "", "output": "Yes. Lotus Petal has a mana cost of {0}, so its mana value is 0. Chalice of the Void with 0 charge counters counters all spells with mana value 0. This includes Lotus Petal, Mox Opal, Mishra's Bauble, Engineered Explosives cast for X=0, and any other 0-cost spell. Chalice on 0 is an important play against artifact-heavy decks and Oops All Spells."},
    {"instruction": "Can I cast Force of Negation during my own turn for free?", "input": "", "output": "No. Force of Negation's alternative cost (exile a blue card) can only be used if it is not your turn. During your own turn, you must pay the full mana cost of 1UU. This is the key difference between Force of Negation and Force of Will. Force of Will can be cast for free on any turn by paying 1 life and exiling a blue card. Force of Negation is primarily a defensive card."},
    {"instruction": "How does Surgical Extraction work against Doomsday?", "input": "", "output": "Surgical Extraction can be devastating against Doomsday but timing is critical. After Doomsday resolves, the opponent has a 5-card library. If any of those 5 cards end up in the graveyard (from cantrips, fetchlands, or Doomsday itself putting the rest of the library into the graveyard), you can Surgical them. The best target is usually Thassa's Oracle - if you exile all copies of Oracle, the Doomsday player has no win condition in their pile. However, skilled Doomsday pilots construct piles that play around Surgical by including alternative win conditions."},
    {"instruction": "Does Emrakul's protection from colored spells stop Swords to Plowshares?", "input": "", "output": "Yes. Emrakul, the Aeons Torn has protection from colored spells. Swords to Plowshares is a white spell (colored), so it cannot target Emrakul. Protection prevents damage, enchanting/equipping, blocking, and targeting by sources of the protected quality. Since Swords is a colored spell trying to target Emrakul, it is an illegal target. To remove Emrakul, you need colorless removal (All Is Dust, Engineered Explosives), abilities of permanents already in play (Maze of Ith, Karakas for legendary), or sacrifice effects (Liliana of the Veil's -2)."},
    {"instruction": "Can I counter a spell that was cast with Cavern of Souls mana?", "input": "", "output": "If the spell is a creature spell of the named type AND was cast using mana from Cavern of Souls, it cannot be countered. Cavern of Souls says the creature spell can't be countered. However, you CAN still counter the creature if: 1) It was not the named creature type. 2) The mana from Cavern was not used (they used other lands). 3) You use an effect that does not counter but removes it (exile with Containment Priest, or bounce with Karakas after it enters). Chalice of the Void also cannot counter a Cavern-protected creature."},
    {"instruction": "How does Counterbalance work?", "input": "", "output": "Counterbalance is an enchantment that triggers whenever an opponent casts a spell. You reveal the top card of your library. If the revealed card has the same mana value as the spell, that spell is countered. With Sensei's Divining Top (now banned), you could arrange the top of your library to always have the right mana value ready. Without Top, Counterbalance relies on cantrips like Brainstorm and Ponder to set up the top card. It is strongest against decks with concentrated mana costs (like Legacy decks full of 1-mana spells)."},
    {"instruction": "What happens if I cast Terminus for its miracle cost?", "input": "", "output": "If Terminus is the first card you draw in a turn, you may reveal it and cast it for its miracle cost of W instead of its regular cost of 4WW. Miracle is a triggered ability that triggers when you draw the card (if it is the first draw of the turn). You reveal it, then get the option to cast it for the miracle cost as the trigger resolves. At W for a wrath that puts all creatures on the bottom of libraries (not destroy, avoiding indestructible), miracle Terminus is the most efficient board wipe in Legacy."},
    {"instruction": "Can I respond to an Aether Vial activation?", "input": "", "output": "Yes. Aether Vial's activated ability ('tap: put a creature card with mana value equal to the number of charge counters from your hand onto the battlefield') goes on the stack. You get priority to respond. However, you do not know which creature they will put into play until the ability resolves, because the creature is chosen on resolution, not on activation. You can counter the Vial activation with Stifle, or you can destroy the Vial in response (but the activation is already on the stack and will still resolve)."},
    {"instruction": "How does Dress Down interact with Phyrexian Dreadnought?", "input": "", "output": "Dress Down removes all abilities from creatures. If you cast Phyrexian Dreadnought while Dress Down is in play, Dreadnought enters the battlefield as a 12/12 with no abilities. Its sacrifice trigger never happens because it does not have the ability that creates the trigger. At end of turn, Dress Down sacrifices itself (it has 'at the beginning of the end step, sacrifice this'). When Dress Down leaves, Dreadnought regains its ability, but the ETB trigger does not retroactively trigger. You have a 12/12 permanently."},
    {"instruction": "Can Flickerwisp exile a token?", "input": "", "output": "Yes, Flickerwisp can target and exile a token. However, when the token is exiled, it ceases to exist as a state-based action. At the beginning of the next end step, Flickerwisp tries to return it to the battlefield, but it no longer exists in exile. The token is permanently removed from the game. This makes Flickerwisp excellent removal for Marit Lage tokens, Construct tokens from Urza's Saga, and Army tokens from Orcish Bowmasters."},
    {"instruction": "Does Life from the Loam's dredge ability work from exile?", "input": "", "output": "No. Dredge is a replacement effect that only works when Life from the Loam is in your graveyard. When you would draw a card, you may instead mill 3 cards and return Loam from your graveyard to your hand. If Loam is in exile (from Surgical Extraction, Rest in Peace, or Leyline of the Void), you cannot dredge it. This is why Surgical Extraction targeting Life from the Loam is so devastating against Lands - it removes the entire recursion engine."},
    {"instruction": "How does Snuff Out work?", "input": "", "output": "Snuff Out is an instant that costs 3B normally, but has an alternative cost of paying 4 life if you control a Swamp. Since Underground Sea has the Swamp land type, you can pay 4 life to cast Snuff Out for free in Dimir Tempo. This makes it a zero-mana removal spell at the cost of life, similar to how Force of Will trades life and a card for free interaction. It destroys a nonblack creature, so it does not hit Bowmasters or other black creatures."},
    {"instruction": "What happens if both players put an Omniscience into play off Show and Tell?", "input": "", "output": "Both players now have Omniscience in play. Omniscience lets you cast spells from your hand without paying their mana costs. The active player (whoever's turn it is) gets priority first after Show and Tell resolves, so they get to cast free spells first. This is usually whoever cast the Show and Tell. However, both players can respond to each other's free spells. In practice, if both players have Omniscience, the game becomes about who has the better cards in hand and who gets to go first."},

    # === MORE COMBAT AND TIMING ===
    {"instruction": "When exactly can I activate Maze of Ith during combat?", "input": "", "output": "You can activate Maze of Ith at any point during combat after attackers are declared. The most common timing is during the declare blockers step or after blockers are declared. Maze untaps the creature and removes it from combat, preventing all combat damage it would deal and receive. A key trick in Lands: attack with your own Knight of the Reliquary, then Maze of Ith your own Knight - it deals no combat damage but is untapped, letting you activate Knight's ability again. This effectively gives Knight of the Reliquary vigilance."},
    {"instruction": "Can I cast Brainstorm in response to my opponent's Thoughtseize?", "input": "", "output": "Yes. When your opponent casts Thoughtseize targeting you, you get priority before it resolves. You can cast Brainstorm in response, drawing 3 cards and putting 2 back on top of your library. Your opponent then sees your hand (which now contains the 1 new card you kept, minus the 2 you hid on top). You effectively hid your 2 best cards from Thoughtseize. This is one of the most important Brainstorm tricks in Legacy."},
    {"instruction": "My opponent activates Rishadan Port targeting my only Island during my upkeep. Can I tap it for mana in response?", "input": "", "output": "Yes. Rishadan Port's ability goes on the stack. Before it resolves, you have priority and can tap your Island for U. The mana goes into your mana pool. When Port's ability resolves, it taps your Island (which is already tapped - no additional effect). You have U in your pool but no untapped lands. This mana must be used before the current phase ends or it empties. This is important for casting instant-speed spells like Brainstorm during your upkeep in response to Port."},
    {"instruction": "My opponent casts Tendrils of Agony with storm count 9 (10 copies total). Can I Mindbreak Trap it?", "input": "", "output": "Yes, and this is the ideal scenario for Mindbreak Trap. Your opponent cast at least 3 spells this turn (storm count 9 means 9 prior spells), so Mindbreak Trap can be cast for free by exiling it. Mindbreak Trap exiles any number of target spells. You can target ALL the Tendrils copies on the stack (the original plus all 9 storm copies). This exiles the entire Tendrils and all copies, preventing all drain. This is why Mindbreak Trap is the premium anti-Storm sideboard card."},
    {"instruction": "Can I use Karakas to bounce my own Thalia to save her from removal?", "input": "", "output": "Yes. Thalia, Guardian of Thraben is a legendary creature, so Karakas can target her. If your opponent casts a removal spell (like Swords to Plowshares) targeting Thalia, you can respond by activating Karakas to return Thalia to your hand. The removal spell fizzles because its target is no longer on the battlefield. Next turn, you can replay Thalia. This is a common play in Death and Taxes to protect key creatures."},

    # === KEYWORD AND ABILITY INTERACTIONS ===
    {"instruction": "How does True-Name Nemesis work? Can anything kill it?", "input": "", "output": "True-Name Nemesis has protection from the chosen player. This means the chosen player cannot target it, deal damage to it, block it, or attach anything to it. It is effectively unblockable and unkillable by that player through normal means. Ways to kill it: board wipes that do not target (Toxic Deluge, Terminus, Council's Judgment, Massacre), sacrifice effects (Liliana of the Veil's -2, Diabolic Edict), and effects from other players in multiplayer. Toxic Deluge is the most played answer because it gives -X/-X which bypasses protection."},
    {"instruction": "Does Solitude's evoke trigger use the stack?", "input": "", "output": "Yes. When you cast Solitude for its evoke cost (exile a white card from hand), both the ETB exile trigger and the evoke sacrifice trigger go on the stack. You choose the order. If you put the sacrifice trigger on the stack first and the exile trigger on top, the exile resolves first (removing an opponent's creature) and then Solitude is sacrificed. With Ephemerate, you can respond to the sacrifice trigger by blinking Solitude, which creates a new object that is no longer affected by the sacrifice trigger. This lets you keep Solitude and get two exile triggers."},
    {"instruction": "How does cascade work with spells that cost 0?", "input": "", "output": "Cascade exiles cards until you hit a nonland card with lower mana value than the cascade spell, then you may cast it for free. A spell with mana value 3 cascading into a 0-cost spell is legal (0 is less than 3). This is how Shardless Agent (MV 3) cascades into Ancestral Vision (MV 0, suspended) or Crashing Footfalls (MV 0, suspended). The suspend spells cannot be cast from hand normally but cascade lets you cast them for free. However, Chalice of the Void on 0 will counter the cascaded 0-cost spell."},
    {"instruction": "What is the interaction between Painter's Servant and Grindstone?", "input": "", "output": "Painter's Servant makes all cards in all zones the chosen color (in addition to their other colors). Grindstone mills 2 cards and repeats if they share a color. With Painter naming any color, every card in the opponent's library is that color, so every pair of milled cards shares a color. Grindstone repeats until the entire library is milled. This is a two-card instant-win combo that only requires Painter in play and Grindstone activation (3 mana: 2 to activate Grindstone, 1 has already been spent on Painter)."},
    {"instruction": "How does annihilator work? Can I sacrifice tokens?", "input": "", "output": "Annihilator is a triggered ability that triggers when the creature attacks. Annihilator 6 (Emrakul) means the defending player must sacrifice 6 permanents when Emrakul attacks. Yes, you can sacrifice tokens. You can also sacrifice lands, enchantments, artifacts, planeswalkers - any permanents. The defending player chooses which permanents to sacrifice. This often means sacrificing your entire board. Annihilator triggers go on the stack before blockers are declared, so the permanents are sacrificed before you even get to block."},
    {"instruction": "What is the difference between hexproof and shroud?", "input": "", "output": "Hexproof means the permanent cannot be targeted by spells or abilities your opponents control. YOU can still target it with your own spells (equip, enchant, buff). Shroud means the permanent cannot be targeted by ANY spells or abilities, including yours. You cannot equip or enchant a creature with shroud. In Legacy, hexproof is more common on newer cards. True-Name Nemesis has protection (stronger than hexproof against the chosen player). Nimble Mongoose has shroud (you cannot buff it). For removal, both require non-targeting answers like board wipes or sacrifice effects."},
    {"instruction": "How does Deathrite Shaman's mana ability work?", "input": "", "output": "Deathrite Shaman has three activated abilities, but notably its first ability (exile a land card from a graveyard, add one mana of any color) IS a mana ability. Mana abilities do not use the stack and cannot be responded to. This means once DRS is untapped, your opponent cannot prevent you from exiling a fetchland and making mana. DRS was banned in Legacy because a 1-mana creature that taps for mana, drains life, and gains life with no deckbuilding cost was too ubiquitous."},
    {"instruction": "Can I cast Veil of Summer in response to Thoughtseize?", "input": "", "output": "Yes, and this is one of the best uses. Thoughtseize targets you, and Veil of Summer says you and spells you control cannot be the target of blue or black spells this turn. Thoughtseize is a black spell, so it loses its target and is countered by game rules (illegal target). Additionally, Veil draws you a card since the opponent cast a blue or black spell this turn. Veil of Summer for G effectively counters Thoughtseize and draws a card. This is why green sideboard cards are so valuable in Legacy."},
    {"instruction": "How does Sylvan Library work with fetchlands?", "input": "", "output": "Sylvan Library triggers at the beginning of your draw step. You draw two extra cards, then choose to put two cards from your hand on top of your library (those drawn this turn) or pay 4 life for each you keep. The key interaction: if you crack a fetchland or Brainstorm before your draw step trigger resolves, the library is shuffled. After drawing with Sylvan, you have seen more cards and can make better decisions. However, you must reveal and pay life for any extra cards you keep - there is no way to avoid the 4 life per card. With Brainstorm, you can Brainstorm in response to Sylvan's trigger, effectively selecting the best 4 cards from 6 seen."},

    # === MORE MANA AND COST RULES ===
    {"instruction": "How does delve work with Murktide Regent?", "input": "", "output": "Delve lets you exile cards from your graveyard to pay for generic mana in the spell's cost. Murktide Regent costs 5UU. The UU must be paid with blue mana, but the 5 generic can be paid by exiling 5 cards from your graveyard. With a full graveyard (common after cantrips and fetchlands), Murktide often costs just UU. Murktide enters with a +1/+1 counter for each instant and sorcery exiled to cast it, so exiling 5 instants/sorceries makes it a 7/7 (base 3/3 plus 4 counters, since one card might be a land). In practice, Murktide is often a 6/6 to 8/8 for 2 mana."},
    {"instruction": "Can I crack Lion's Eye Diamond in response to Brainstorm?", "input": "", "output": "Yes. This is a key LED interaction. You cast Brainstorm, and while Brainstorm is on the stack, you activate Lion's Eye Diamond (which is a mana ability and does not use the stack). You discard your hand and add 3 mana. Then Brainstorm resolves: you draw 3 cards (a fresh hand since you discarded) and put 2 back on top. This effectively turns LED into 3 mana plus a fresh look at 3 cards, discarding the cards you did not want anyway."},
    {"instruction": "What is the converted mana cost of a card cast with an X cost?", "input": "", "output": "On the stack, X is whatever value was chosen. So Engineered Explosives cast with X=2 has mana value 2 on the stack. On the battlefield, in the graveyard, in exile, or in the library, X is always 0. So Engineered Explosives on the battlefield has mana value 0 regardless of how many colors were spent to cast it. Chalice of the Void with 2 counters on the battlefield has mana value 0 (XX on the battlefield means X=0). This is why Engineered Explosives set to 0 can destroy Chalice of the Void (both have mana value 0 on the battlefield)."},
    {"instruction": "How does Thalia's tax interact with cascade?", "input": "", "output": "Thalia, Guardian of Thraben makes noncreature spells cost 1 more. Cascade lets you cast the cascaded spell without paying its mana cost. However, Thalia's tax is an additional cost, not part of the mana cost. You must still pay the additional 1 from Thalia even when casting a spell for free via cascade. So cascading into a noncreature spell with Thalia in play costs 1 mana. This can be relevant when cascading with no mana available."},
    {"instruction": "What happens if I cast a spell and my opponent casts Daze, but I want to pay the 1?", "input": "", "output": "When Daze's ability triggers (counter unless you pay 1), you choose whether to pay 1 mana. If you have 1 mana available, you can pay it and your spell is not countered. Daze returns to your opponent's hand as part of its cost, so they have already bounced their Island regardless of whether you pay. If you cannot pay 1, your spell is countered. The key Daze math is: does my opponent have enough mana to pay for Daze? Count their untapped lands minus the spell they are casting. If they have 1+ extra mana, Daze is much worse."},

    # === ZONE AND TIMING RULES ===
    {"instruction": "Can I Surgical Extraction a card in response to a Reanimate targeting it?", "input": "", "output": "Yes. Reanimate targets a creature card in a graveyard. With the Reanimate spell on the stack, you can cast Surgical Extraction (paying 2 life, Phyrexian mana) targeting the same creature card. Surgical resolves first, exiling the creature and all other copies from graveyard, hand, and library. When Reanimate tries to resolve, its target no longer exists in the graveyard, so it fizzles (is countered by game rules). The Reanimate player does not lose life since the spell did not resolve."},
    {"instruction": "If a creature dies with Leyline of the Void in play, where does it go?", "input": "", "output": "Exile. Leyline of the Void says 'if a card would be put into an opponent's graveyard from anywhere, exile it instead.' This is a replacement effect that changes the destination. The card never touches the graveyard, so no graveyard triggers happen. Dies triggers (like 'when this creature dies') DO still trigger because 'dies' means 'is put into a graveyard from the battlefield' and the replacement effect changes the zone but the game still considers the creature to have died. However, the card is in exile, not the graveyard, so it cannot be returned from the graveyard."},
    {"instruction": "What is the difference between 'destroy' and 'exile'?", "input": "", "output": "Destroy puts a permanent into the graveyard. It can be prevented by indestructible and regeneration. The card goes to the graveyard where it can be returned with Reanimate, Life from the Loam, etc. Exile removes a card from the game entirely (the exile zone). It cannot be prevented by indestructible. Exiled cards generally cannot be recovered (except cards like Misthollow Griffin that explicitly say they can be cast from exile). In Legacy, exile-based removal (Swords to Plowshares, Solitude) is preferred because it prevents graveyard recursion and handles indestructible creatures."},
    {"instruction": "Can I cast instants during my opponent's end step?", "input": "", "output": "Yes. During each end step, the active player gets priority first, then the non-active player. This is a common time to cast instants because: 1) It is the last chance to use mana before your turn (any unspent mana empties). 2) Sorcery-speed threats cannot be deployed in response. 3) Flash creatures deployed here have pseudo-haste since they can attack on your upcoming turn. Brainstorming at end of opponent's turn is a classic Legacy play that maximizes information before your draw step."},
    {"instruction": "What happens when both players pass priority with nothing on the stack?", "input": "", "output": "The current phase or step ends and the game moves to the next one. If both players pass priority with an empty stack during the main phase, the turn moves to the beginning of combat. If both pass during the end step, the turn ends and the next player's turn begins. The active player always gets priority first at the start of each step and phase. This is the fundamental flow of Magic: players alternate getting priority until both pass, then the game advances."},
]

outpath = os.path.join(os.path.dirname(__file__), "..", "data", "training", "rules_qa.jsonl")
with open(outpath, "a", encoding="utf-8") as f:
    for pair in pairs:
        f.write(json.dumps(pair, ensure_ascii=False) + "\n")

print(f"Appended {len(pairs)} pairs to {outpath}")
