"""Generate deckbuilding rationale training data."""
import json
import os

pairs = [
    # === WHY CARDS ARE IN SPECIFIC DECKS ===
    {"instruction": "Why does Dimir Tempo play Orcish Bowmasters?", "input": "", "output": "Orcish Bowmasters punishes every cantrip the opponent casts, creating a 1/1 army token and pinging a target for each card drawn beyond the first. In a format where 43% of decks play Brainstorm and 38% play Ponder, Bowmasters generates massive incidental value. It also has flash, making it a surprise blocker or end-of-turn threat that dodges sorcery-speed removal."},
    {"instruction": "Why does Dimir Tempo play Thoughtseize over other discard?", "input": "", "output": "Thoughtseize hits any nonland card for just one mana and one life, making it the most versatile hand disruption in Legacy. Unlike Hymn to Tourach (random) or Duress (noncreature only), Thoughtseize lets you surgically remove the opponent's best card regardless of type. The life cost is minimal in a tempo deck that plans to win before life totals matter."},
    {"instruction": "Why does Dimir Tempo play Daze?", "input": "", "output": "Daze is a free counterspell that lets you deploy threats while holding up interaction. In Dimir Tempo, you might play a turn-1 Delver or turn-2 Murktide and still counter the opponent's response by returning an Island. The tempo gain is enormous early game, and paired with Wasteland, it often catches opponents who can't afford to pay the extra mana."},
    {"instruction": "Why does Dimir Tempo play Murktide Regent?", "input": "", "output": "Murktide Regent is often a 6/6 or larger flyer for just UU after delving away graveyard cards. It dodges Lightning Bolt, demands premium removal like Swords to Plowshares, and closes games in 2-3 attacks. The delve cost is easy to fuel in a deck full of cantrips and fetchlands that naturally fill the graveyard."},
    {"instruction": "Why does Sneak and Show play Lotus Petal?", "input": "", "output": "Lotus Petal enables turn-1 or turn-2 Show and Tell by providing free mana acceleration. With Petal, the deck can cast Show and Tell as early as turn 1 (land + Petal + Ancient Tomb) or reliably on turn 2 through Daze. It also helps cast Sneak Attack on curve or protect the combo with Force of Will while tapped out."},
    {"instruction": "Why does Sneak and Show play both Emrakul and Atraxa?", "input": "", "output": "Emrakul, the Aeons Torn is the best Sneak Attack target because it gets an extra turn on cast and has annihilator 6, often winning in one attack. Atraxa, Grand Unifier is the best Show and Tell target because her ETB draws 7+ cards, providing overwhelming card advantage even if she is immediately answered. Having both gives the deck flexibility to choose the right threat for each situation."},
    {"instruction": "Why does Sneak and Show play Force of Will?", "input": "", "output": "Force of Will protects the combo turn. When you tap out for Show and Tell or Sneak Attack, you need free countermagic to stop the opponent's Force of Will or other disruption. Without Force backup, the combo is too fragile against the 45% of decks that play their own Force of Will."},
    {"instruction": "Why does Lands play Exploration?", "input": "", "output": "Exploration allows playing two lands per turn for just one green mana. This enables devastating plays like turn-1 Exploration into two lands, then turn-2 Wasteland plus recur with Life from the Loam to destroy two opponent lands per turn. It also accelerates the Dark Depths combo by getting both Depths and Thespian's Stage into play faster."},
    {"instruction": "Why does Lands play Life from the Loam?", "input": "", "output": "Life from the Loam is the engine that makes the entire Lands strategy work. Its dredge 3 fills the graveyard with lands that can be returned to hand, and it recurs Wasteland for repeated mana denial. Combined with Exploration, it creates a soft lock where you destroy an opponent's land every turn while never running out of your own."},
    {"instruction": "Why does Lands play The Tabernacle at Pendrell Vale?", "input": "", "output": "Tabernacle forces every creature to pay 1 mana during its controller's upkeep or be destroyed. Against creature-based decks like Elves, Goblins, or Death and Taxes, this is devastating because they cannot afford to keep their entire board alive. Lands can tutor for it with Crop Rotation and does not care about the upkeep cost since it runs very few creatures."},
    {"instruction": "Why does The EPIC Storm play Burning Wish?", "input": "", "output": "Burning Wish tutors for any sorcery from the sideboard, giving TES enormous flexibility. The sideboard contains situational win conditions (Tendrils of Agony, Empty the Warrens), removal (Pulverize), card draw (Past in Flames), and hate answers. This toolbox approach makes TES more resilient than other Storm variants because it can adapt mid-combo."},
    {"instruction": "Why does Storm play Lion's Eye Diamond?", "input": "", "output": "Lion's Eye Diamond provides 3 mana of any color for free by discarding your hand. In Storm, you cast it alongside Infernal Tutor (which benefits from an empty hand via hellbent) or crack it in response to Burning Wish. The 3 free mana dramatically increases storm count and total mana available for the kill turn."},
    {"instruction": "Why does Death and Taxes play Aether Vial?", "input": "", "output": "Aether Vial lets D&T put creatures into play at instant speed without paying mana, bypassing both Daze and Thalia's own tax on noncreature spells. It effectively gives every creature flash, enabling surprise blocks with Flickerwisp or end-of-turn Stoneforge Mystic. It also frees up mana for Rishadan Port and Wasteland activations."},
    {"instruction": "Why does Death and Taxes play Thalia, Guardian of Thraben?", "input": "", "output": "Thalia makes every noncreature spell cost 1 more, which is devastating in Legacy where most spells cost 0-2 mana. Brainstorm becomes 2 mana, Force of Will's alternative cost adds 1, and combo decks need extra mana for every ritual and cantrip. She is a 2/1 first striker that attacks well and demands immediate removal."},
    {"instruction": "Why does Death and Taxes play Rishadan Port?", "input": "", "output": "Rishadan Port taps an opponent's land during their upkeep, effectively keeping them one mana behind every turn. Combined with Wasteland and Thalia, this creates a crushing mana denial package that prevents opponents from casting their spells on curve. D&T can afford this because Aether Vial provides mana-free creature deployment."},
    {"instruction": "Why does Painter play Goblin Welder?", "input": "", "output": "Goblin Welder swaps artifacts between the graveyard and battlefield at instant speed. If Grindstone or Painter's Servant is destroyed, Welder can bring it back immediately by sacrificing a cheap artifact. It also enables value plays like recurring Ichor Wellspring for card draw."},
    {"instruction": "Why does Painter play Red Elemental Blast effects?", "input": "", "output": "When Painter's Servant is in play naming blue, every permanent and spell becomes blue. This means Red Elemental Blast and Pyroblast can counter ANY spell and destroy ANY permanent for just one red mana, transforming narrow sideboard cards into unconditional interaction."},
    {"instruction": "Why does Oops All Spells play zero lands?", "input": "", "output": "The entire strategy depends on Balustrade Spy or Undercity Informer milling your complete library when it targets you. If there were any lands in the deck, the mill would stop at the first land. With zero lands, your entire library goes to the graveyard, triggering Narcomoeba, enabling Dread Return, and winning with Thassa's Oracle."},
    {"instruction": "Why does Oops All Spells play Force of Will?", "input": "", "output": "Despite being a combo deck, Oops plays Force of Will because it needs protection for its combo turn. The deck is extremely vulnerable to a single counterspell or Surgical Extraction, so free countermagic is essential."},
    {"instruction": "Why does Eldrazi play Chalice of the Void?", "input": "", "output": "Chalice on 1 counters the majority of Legacy's most played spells: Brainstorm, Ponder, Swords to Plowshares, Lightning Bolt, Thoughtseize, Daze, and many more. Eldrazi can deploy Chalice on turn 1 via Ancient Tomb, and since Eldrazi creatures cost 2+ mana, the Chalice does not affect your own spells."},
    {"instruction": "Why does Doomsday play Thassa's Oracle as its win condition?", "input": "", "output": "After resolving Doomsday (which leaves a 5-card library), you draw through the pile and cast Oracle with 0-1 cards remaining. Oracle wins on ETB when devotion to blue meets or exceeds cards in library. It is a single compact win condition that cannot be stopped by creature removal once the trigger is on the stack."},

    # === MATCHUP REASONING ===
    {"instruction": "Why is Dimir Tempo favored against Storm?", "input": "", "output": "Dimir Tempo has the exact disruption package Storm hates: Thoughtseize strips key combo pieces before the combo turn, Force of Will and Daze counter critical spells during the combo turn, and Wasteland can deny the mana Storm needs. The tempo clock means Storm cannot take many turns to rebuild after disruption."},
    {"instruction": "Why does Lands struggle against Oops All Spells?", "input": "", "output": "Lands has almost no instant-speed interaction that can stop the Oops combo. Wasteland, Maze of Ith, and Punishing Fire are all irrelevant against a deck that wins by milling itself and casting Thassa's Oracle. Lands needs to rely entirely on sideboard graveyard hate, which is insufficient against Force of Will backup."},
    {"instruction": "Why is Death and Taxes good against fair blue decks?", "input": "", "output": "Thalia taxes every cantrip and counterspell, Rishadan Port and Wasteland deny mana, and Aether Vial bypasses countermagic entirely. The cumulative tax effect means blue decks can rarely operate at full efficiency. Flickerwisp and Skyclave Apparition handle problematic permanents."},
    {"instruction": "Why is Sneak and Show favored against Lands?", "input": "", "output": "Lands does not play counterspells, so Show and Tell resolves easily. Once Emrakul enters play, Lands has no removal that handles protection from colored spells. Maze of Ith prevents damage but not the annihilator trigger, so Lands still loses permanents every turn."},
    {"instruction": "Why does Burn struggle in the current Legacy metagame?", "input": "", "output": "Orcish Bowmasters in 29% of decks punishes Burn's reliance on drawing cards. Force of Will counters critical burn spells for free. Many current decks gain incidental life or run enough interaction to survive. Burn also cannot beat combo decks that win before it deals 20 damage."},
    {"instruction": "Why is Painter favored against combo decks?", "input": "", "output": "Painter has a fast combo of its own that can win on turn 2-3, racing most combo decks. It also plays Chalice of the Void and Red Elemental Blast effects that become unconditional counters when Painter's Servant is in play."},
    {"instruction": "Why does Eldrazi struggle against Sneak and Show?", "input": "", "output": "Eldrazi's primary disruption is Chalice on 1, but Show and Tell costs 3 and Sneak Attack costs 4 so Chalice does not help. Thought-Knot Seer can strip a key card, but Sneak and Show has enough cantrips to recover. Eldrazi creatures cannot race an Emrakul."},
    {"instruction": "Why is the Dimir Tempo vs Ocelot Pride matchup close?", "input": "", "output": "Dimir has Thoughtseize and Bowmasters which are effective against creatures, but Ocelot generates tokens and energy that overwhelm one-for-one removal. Ocelot does not rely on cantrips so Bowmasters draw-punishing ability is less relevant. The matchup often comes down to whether Dimir sticks an early Murktide and races."},

    # === CARD CHOICES AND FLEX SLOTS ===
    {"instruction": "Should I play Lightning Bolt or Fatal Push in Izzet Delver?", "input": "", "output": "Lightning Bolt is generally better because it deals 3 damage to any target including the opponent. This reach is critical for closing games. Fatal Push is better against Murktide Regent which dodges Bolt, but cannot go face. Most lists play 4 Bolt with 0-2 Push."},
    {"instruction": "How many Force of Will should I play?", "input": "", "output": "Almost always 4 copies. Force of Will is the format safety valve against unfair decks, and you need to see it consistently against combo. You need at least 19 blue cards in your deck, preferably 23-24, to reliably pitch to Force."},
    {"instruction": "When should I cut Daze from my deck?", "input": "", "output": "Daze is bad in pure control decks that want to hit every land drop. It is also weak in grindy post-board matchups where opponents have plenty of mana. Most Delver players sideboard out 1-2 Dazes against midrange and control but keep all 4 against combo."},
    {"instruction": "When is Pyroblast better than Red Elemental Blast?", "input": "", "output": "They are functionally identical in almost all situations. Pyroblast can target non-blue things (fizzling on resolution), while REB cannot target non-blue at all. This matters with Chalice on 1 or Meddling Mage. Most players split 2-2."},
    {"instruction": "Should I play Surgical Extraction or Leyline of the Void?", "input": "", "output": "Leyline is better as a hard lock against dedicated graveyard decks since it prevents cards from entering the graveyard entirely. Surgical is better as a reactive answer that removes specific combo pieces while leaving your own graveyard intact for Murktide. Choose based on how much graveyard combo you expect and whether your deck uses its own graveyard."},
    {"instruction": "What makes a good Legacy sideboard?", "input": "", "output": "A good Legacy sideboard covers the top 5-8 matchups with 2-3 cards each. Include graveyard hate, artifact and enchantment removal, color-specific answers like Pyroblast, anti-combo cards like Flusterstorm, and creature removal like Toxic Deluge. Avoid narrow one-ofs."},
    {"instruction": "How many cantrips should a blue Legacy deck play?", "input": "", "output": "Most blue Legacy decks play 8 cantrips: 4 Brainstorm and 4 Ponder. This provides the consistency needed in a format with diverse matchups. Some decks add Preordain as 9-10. Control decks sometimes play fewer to fit more answers."},

    # === MANA BASE CONSTRUCTION ===
    {"instruction": "How many dual lands does Dimir Tempo need?", "input": "", "output": "Typically 3-4 Underground Sea. You need enough blue and black sources for Brainstorm, Force of Will, Thoughtseize, and Bowmasters reliably. Three Underground Sea plus fetchlands gives around 10+ sources of each color. Some builds run 4 for Wasteland resilience."},
    {"instruction": "How many basic lands should I play in Legacy?", "input": "", "output": "Most Legacy decks play 2-4 basic lands to protect against Wasteland and Blood Moon. Tempo decks typically play 2, control decks play 3-5. Running zero basics is risky when 48% of decks play Wasteland."},
    {"instruction": "When should I fetch a basic land instead of a dual?", "input": "", "output": "Fetch a basic when you expect Wasteland, when you do not need the second color this turn, or when at low life against aggro. Against Blood Moon decks, get basics in play before Moon resolves. When in doubt, fetch basic Island first."},
    {"instruction": "Why do Legacy decks play so many fetchlands?", "input": "", "output": "Fetchlands fix mana by finding any dual land type, shuffle away bad cards after Brainstorm, fill the graveyard for Murktide and delve, and thin the deck slightly. A Polluted Delta can find Underground Sea, Volcanic Island, Tropical Island, Tundra, or basic lands."},
    {"instruction": "How does Mox Diamond work in Lands?", "input": "", "output": "Mox Diamond enters play by discarding a land card, then taps for any color. In Lands this is pure upside because discarded lands return with Life from the Loam. It enables explosive turn-1 plays like Exploration plus two land drops."},

    # === SIDEBOARD STRATEGY ===
    {"instruction": "What should I sideboard against Reanimator?", "input": "", "output": "Bring in all graveyard hate: Leyline of the Void, Surgical Extraction, or Endurance. Leyline is best because it comes down before the game starts. Also keep counterspells since Force of Will and Daze are critical for stopping the reanimate spell itself."},
    {"instruction": "When do I sideboard out Force of Will?", "input": "", "output": "Board out Force in grindy fair matchups where the 2-for-1 card disadvantage is too costly. Against midrange decks, every card matters and pitching to counter a creature is a bad trade. Keep Force against any deck that can win with a single spell."},
    {"instruction": "How many sideboard slots should I dedicate to combo hate?", "input": "", "output": "In the current meta, 4-6 slots is typical. With combo at about 40% of the metagame, you need enough to improve multiple matchups. A common setup is 3-4 Leyline of the Void plus 2 Flusterstorm."},
    {"instruction": "What is the best sideboard card in Legacy right now?", "input": "", "output": "Leyline of the Void at 36% of decks is the most played sideboard card. It shuts down Reanimator, Dredge, Oops All Spells, and weakens Doomsday without costing any mana when in your opening hand."},
    {"instruction": "Should I play Endurance or Leyline of the Void?", "input": "", "output": "Leyline is a hard lock against dedicated graveyard decks. Endurance is a flexible card that is also a 3/4 body and works with Green Sun's Zenith. Green-based fair decks prefer Endurance; blue decks needing a hard shutdown prefer Leyline."},
    {"instruction": "How do I sideboard against a diverse Legacy metagame?", "input": "", "output": "Focus on the top 5-8 decks by metagame share rather than covering everything. Have a plan for Dimir Tempo, Ocelot Pride, Oops/combo, and Sneak and Show. Accept weak matchups against fringe decks since the math favors being heavily favored against common opponents."},
]

outpath = os.path.join(os.path.dirname(__file__), "..", "data", "training", "deckbuilding_rationale.jsonl")
with open(outpath, "w", encoding="utf-8") as f:
    for pair in pairs:
        f.write(json.dumps(pair, ensure_ascii=False) + "\n")

print(f"Written {len(pairs)} pairs to {outpath}")
