"""Generate training data - Mega batch 10. Final push to 1500."""
import json
import os

rules = [
    {"instruction": "Can I activate a planeswalker ability the turn it enters?", "input": "", "output": "Yes. Planeswalker loyalty abilities can be activated once per turn at sorcery speed (during your main phase when stack is empty). They can be activated the same turn the planeswalker enters the battlefield. There is no summoning sickness for planeswalkers. Example: play Jace the Mind Sculptor (enters with 3 loyalty), immediately activate +2 to go to 5 loyalty or 0 to Brainstorm."},
    {"instruction": "What is the maximum hand size in Legacy?", "input": "", "output": "Seven cards by default. During the cleanup step of each turn, if you have more than 7 cards in hand, you discard down to 7. Some cards modify this: Reliquary Tower gives unlimited hand size, Ensnaring Bridge cares about your hand size for blocking. In practice, most Legacy games do not involve exceeding 7 cards because spells are cheap and you cast them as quickly as you draw them. The exception is after a big card draw spell like Ad Nauseam (draw 10-15 cards, then go off immediately)."},
    {"instruction": "How does cascade interact with Chalice of the Void?", "input": "", "output": "The cascaded spell IS cast (cascade says 'you may cast it'), so Chalice can counter it. If Chalice is on 0 and you cascade into a 0-cost spell (Ancestral Vision, Crashing Footfalls), Chalice counters the cascaded spell. This is a common interaction: Eldrazi plays Chalice on 0 against Cascade Crash decks to stop the free Crashing Footfalls. The cascading spell itself (e.g., Shardless Agent at MV 3) is not affected by Chalice on 0."},
    {"instruction": "What is the interaction between Wasteland and basic land types?", "input": "", "output": "Wasteland says 'destroy target nonbasic land.' Basic lands cannot be targeted by Wasteland. However, a nonbasic land WITH a basic land type (like Underground Sea, which is a 'Land - Island Swamp') IS a nonbasic land and CAN be Wastelanded. The basic land types (Plains, Island, Swamp, Mountain, Forest) are different from the basic supertype. Dual lands have basic land types but are NOT basic lands. Only cards with the 'Basic' supertype (Basic Land - Island) are immune to Wasteland."},
    {"instruction": "Can I equip a creature at instant speed?", "input": "", "output": "Normally no. The equip keyword ability is activated at sorcery speed only. However, some cards allow instant-speed equipping: Stoneforge Mystic's second ability puts equipment from hand to battlefield (not equip, but similar), Leonin Shikari gives all equip abilities flash, and Sigarda's Aid auto-attaches equipment when it enters. In Legacy, instant-speed equipment attachment is most relevant with Stoneforge Mystic putting Batterskull into play and it auto-equipping the Germ token (this is ETB attachment, not equip, so it happens at any speed Show and Tell could)."},
    {"instruction": "What happens if a spell resolves but its controller has already lost?", "input": "", "output": "If a player loses the game (goes to 0 life, draws from empty library, etc.), they leave the game immediately. All spells and abilities they control are removed from the stack. Their permanents leave the game. In two-player games, this means the other player wins. Spells or abilities controlled by the losing player that are on the stack never resolve. Example: you cast Tendrils of Agony with lethal storm, but in response opponent kills you with Lightning Bolt. You lose, your Tendrils and copies are removed from the stack, and opponent wins (even though they would have died to Tendrils)."},
    {"instruction": "Can I pay costs with opponent's permanents?", "input": "", "output": "Generally no. You can only sacrifice permanents you control, tap permanents you control, and pay mana from sources you control. However, some costs specifically let you interact with opponent's permanents: Thoughtseize makes the opponent discard, sacrifice effects like Liliana force the opponent to sacrifice. Convoke lets you tap creatures YOU control. The exception: if you control an opponent's creature (via Reanimate, Control Magic), you CAN sacrifice it because you control it. Costs always refer to things you control unless specifically stated otherwise."},
    {"instruction": "What is the difference between a token and a card?", "input": "", "output": "Tokens are permanents created by effects that are not cards. They can be creatures, artifacts, enchantments, etc. Key differences from cards: 1) Tokens cease to exist when they leave the battlefield (move to graveyard, hand, exile, or library). They briefly exist in the new zone then vanish as a state-based action. 2) Tokens cannot be 'drawn' or 'searched' from a library. 3) Tokens trigger 'dies' abilities (they do go to the graveyard briefly before ceasing to exist). In Legacy, tokens are created by: Orcish Bowmasters (Orc Army), Urza's Saga (Constructs), Batterskull (Germ), Empty the Warrens (Goblins), Marit Lage (from Dark Depths)."},
    {"instruction": "How does damage assignment work with trample?", "input": "", "output": "With trample, the attacking creature must assign lethal damage to each blocker before assigning remaining damage to the defending player. Lethal damage = the blocker's toughness minus damage already marked. Example: 8/8 trample blocked by a 3/3. Assign 3 damage to the 3/3 (lethal), remaining 5 tramples over to the player. With deathtouch + trample: since deathtouch means ANY amount of damage is lethal, you only need to assign 1 damage to each blocker (1 is lethal with deathtouch) and the rest tramples. A 1/1 deathtouch trample blocked by a 10/10 assigns 1 to the 10/10 (lethal with deathtouch) and 0 tramples (1/1 has no remaining power)."},
    {"instruction": "Can I respond to my own spell before it resolves?", "input": "", "output": "Yes. After casting a spell, you receive priority before passing to your opponent. You can cast another instant or activate abilities before your opponent even gets a chance to respond. This is called 'retaining priority' or 'holding priority.' In Legacy, this is critical for: 1) Casting Lion's Eye Diamond after Burning Wish (crack LED in response to Wish before it resolves). 2) Casting multiple spells in a row to build storm count before opponent can respond. 3) Stacking multiple abilities. You must explicitly announce you are retaining priority; by default, priority passes to the opponent."},
    {"instruction": "What is the 'Legend Rule' exception for different controllers?", "input": "", "output": "The Legend Rule only applies to legendary permanents controlled by the SAME player. If you control Emrakul and your opponent controls Emrakul, both stay in play because different players control them. The rule only forces a choice when one player controls two or more legends with the same name. This matters with Show and Tell: if both players put Emrakul into play, both stay (different controllers). If you somehow put two copies of your own Emrakul into play (very rare), you choose one and the other goes to the graveyard."},
    {"instruction": "What happens if a triggered ability triggers during the resolution of a spell?", "input": "", "output": "The triggered ability waits. During spell resolution, no player has priority and nothing goes on the stack. Once the spell finishes resolving, state-based actions are checked, then triggered abilities that triggered during resolution are put on the stack. The active player puts their triggers on the stack first (in any order), then the non-active player. Then players get priority normally. Example: Balustrade Spy enters and mills your library. Narcomoeba triggers go on the stack AFTER Spy finishes resolving (after the entire library is milled). All Narcomoeba triggers then resolve, putting them into play."},
]

card_eval = [
    {"instruction": "Is Emrakul, the Aeons Torn the best creature in Legacy?", "input": "", "output": "It is the best creature to CHEAT into play. A 15/15 flying, protection from colored spells, annihilator 6, and extra turn on cast makes it nearly unbeatable once in play. Via Sneak Attack, one attack usually wins (15 damage + annihilator 6). Via Show and Tell, it dominates the battlefield permanently. However, it has weaknesses: Karakas bounces it (it is legendary), sacrifice effects kill it (Liliana's -2, Diabolic Edict), and it costs 15 mana to hard cast. The 'best creature' depends on context: for fair gameplay, Orcish Bowmasters at 1B is more impactful per mana. For unfair gameplay, Emrakul is the ultimate payoff."},
    {"instruction": "Is Terminus better than Supreme Verdict in Legacy?", "input": "", "output": "Terminus is significantly better. Terminus miracle costs W (one white mana) vs Supreme Verdict at 1WWU. In a cantrip-heavy format where you can set up the top of your library, miracling Terminus on your draw step for W is trivially easy. Terminus also puts creatures on the bottom of libraries (not destroy), bypassing indestructible and preventing death triggers. Supreme Verdict cannot be countered, which is nice, but 4 mana is too slow for Legacy board wipes. The only advantage of Verdict is the guaranteed cast cost; Terminus without miracle costs 4WW which is worse."},
    {"instruction": "Is Uro, Titan of Nature's Wrath still viable after the meta shifted?", "input": "", "output": "Yes, but in fewer decks. Uro provides life gain (stabilize against aggro), card draw (card advantage), ramp (land drop), and a 6/6 escape body (recursive threat). In grindy control mirrors, Uro is near-unbeatable card advantage. However, the current meta is faster: Oops wins turn 1-2, Dimir Tempo is hyper-efficient, and Orcish Bowmasters punishes the cantrips needed to fill the graveyard for Uro's escape. Uro sees play in 4-color Beanstalk Control and some Bant builds where the 3-mana ETB value justifies the slot. It has moved from mainboard staple to meta-dependent role player."},
    {"instruction": "Is Umezawa's Jitte Legacy-playable?", "input": "", "output": "Barely, and declining. Jitte costs 2 to cast and 2 to equip, gaining charge counters whenever the equipped creature deals combat damage. Counters can: remove for +2/+2, remove for -1/-1 to any creature, or remove for 2 life. It was a Legacy staple for years in Stoneforge decks. However, the format has sped up: Jitte's combat-dependent value is too slow when games are decided by turn 3-4 interaction. Batterskull (immediate lifelink 4/4) and Kaldra Compleat (indestructible, trample, haste) are better Stoneforge targets. Jitte occasionally appears as a sideboard 1-of against creature-heavy metas."},
    {"instruction": "Is Fiery Confluence Legacy-playable?", "input": "", "output": "Yes, in Red Stompy. Fiery Confluence costs 2RR and you choose 3 modes (can repeat): deal 1 damage to each creature, deal 2 damage to each opponent, destroy target artifact. The flexibility is key: against creatures, 3x mode 1 deals 3 to all creatures (kills most Legacy creatures). Against control, 3x mode 2 deals 6 to each opponent. Against artifacts, mix and match. At 4 mana it is expensive, but Red Stompy has Ancient Tomb and Chrome Mox for acceleration. It is Stompy's Swiss army knife for matchups where Chalice and Blood Moon are insufficient."},
    {"instruction": "Is Mindbreak Trap Legacy-playable?", "input": "", "output": "Yes, as a premium anti-Storm sideboard card. Mindbreak Trap costs 2UU normally but can be cast for free if an opponent cast 3+ spells this turn. Against Storm (which casts 5-10 spells per combo turn), Trap is always free. It EXILES spells rather than countering them, so it cannot be fought by Flusterstorm. It hits any number of spells on the stack, so it can exile the original Tendrils plus all storm copies. It is in 18% of Legacy sideboards and is the most decisive anti-Storm card available."},
    {"instruction": "Is Grim Monolith Legacy-playable?", "input": "", "output": "Yes, in artifact combo decks. Grim Monolith costs 2 and taps for 3 colorless (net +1 mana). It does not untap normally - you must pay 4 to untap it. In Mystic Forge Combo, it provides the fast mana needed to deploy The One Ring and Mystic Forge early. With Voltaic Key (tap to untap an artifact, 1 mana), Grim Monolith generates infinite mana (tap Monolith for 3, use 1 for Key to untap Monolith, net +2). It is in about 9% of Legacy decks, concentrated in Mystic Forge and Karn-based strategies."},
    {"instruction": "Is Dismember Legacy-playable?", "input": "", "output": "Marginally. Dismember costs 1BB or 1 mana + 4 life (Phyrexian mana) for -5/-5 to a creature until end of turn. The Phyrexian mana cost lets any color cast it, and -5/-5 kills Murktide Regent (usually 5/5 to 8/8, so -5/-5 may not be enough), kills Orcish Bowmasters, and most other creatures. At 14% of decks it sees play, mostly in sideboards of non-black decks that need creature removal but cannot cast Swords to Plowshares (no white) or Fatal Push (no black). The 4 life cost is real against aggro but acceptable in other matchups."},
    {"instruction": "Is Karn, Scion of Urza Legacy-playable?", "input": "", "output": "No, Karn, Scion is generally outclassed by Karn, the Great Creator in Legacy artifact strategies. Scion costs 4 and makes construct tokens or provides card advantage, but Great Creator costs 4 and provides a wishboard of silver bullets plus shuts off opponent artifact abilities. In non-artifact decks, 4 mana for a planeswalker is too slow unless it provides immediate impact (like Jace's bounce or Teferi's static). Karn, Scion of Urza sees essentially zero Legacy play."},
    {"instruction": "Is Prismatic Ending Legacy-playable?", "input": "", "output": "Yes. Prismatic Ending costs XW and exiles a nonland permanent with mana value X or less, where X is the number of colors spent. At W (1 color, X=1), it exiles MV 1 or less. At WU (2 colors, X=2), MV 2 or less. This scales flexibly: it hits Chalice of the Void (MV 0 on battlefield), Aether Vial (MV 1), Orcish Bowmasters (MV 2), Thalia (MV 2), and many more. The exile is permanent (no graveyard recursion). It sees play in UW and Jeskai as flexible removal. The downside: sorcery speed, and it cannot hit expensive permanents without spending many colors."},
    {"instruction": "Is Flusterstorm the best counterspell in Legacy?", "input": "", "output": "Not the best overall (that is Force of Will), but Flusterstorm is the best STACK counterspell. For U, it counters an instant or sorcery unless they pay 1, AND it has storm (creates copies for each prior spell this turn). Against Storm combo, your Flusterstorm might have storm 3-4, creating enough copies to counter every ritual and wincon on the stack. Against counter wars, each Flusterstorm copy individually must be paid for. It CANNOT counter creatures, planeswalkers, artifacts, or enchantments. It is in 11% of Legacy sideboards as the premium blue-on-blue and anti-combo card."},
]

deckbuilding = [
    {"instruction": "How do I tune my deck for a specific local metagame?", "input": "", "output": "1) Track your local meta: write down what every player plays over 4-6 weeks. Calculate rough percentages. 2) Identify your top 3 matchups by frequency. These are what you optimize for. 3) Adjust flex slots (usually 2-4 mainboard, 4-6 sideboard) to improve those matchups. 4) Do NOT weaken your core for niche metagaming. If you cut Force of Will to improve the D&T matchup, you auto-lose to combo. 5) Test changes for 2 weeks before changing again. Knee-jerk reactions cause constant flux without improvement. Local metas are smaller and more exploitable than MTGO, so targeted adjustments have higher payoff."},
    {"instruction": "When is it correct to play a companion in Legacy?", "input": "", "output": "The only competitively viable companion in Legacy is Yorion, Sky Nomad (requires 80-card deck). Play Yorion when: 1) Your deck has 6+ strong ETB creatures to blink (Stoneforge, Flickerwisp, Solitude, Bowmasters). 2) The value of guaranteed Yorion access outweighs the consistency loss of 80 cards. 3) Your deck is grindy enough that one extra value creature matters. Decks that use Yorion: D&T (BW Yorion), Beanstalk Control (Yorion version), some Esper builds. Decks that should NOT use Yorion: tempo (consistency is paramount), combo (need specific pieces), prison (need fast lock draws)."},
    {"instruction": "Should I maindeck graveyard hate in Legacy?", "input": "", "output": "In the current meta with 36% of decks playing Leyline of the Void in sideboards and graveyard combo at ~15% of the meta: mainboard graveyard hate is viable but not standard. If you play green, 1-2 Endurance mainboard is excellent (also a body and pitch for Vigor). If you play black, 1 Surgical Extraction mainboard provides information and graveyard disruption. If you play white, 1 Containment Priest mainboard stops Reanimate, Show and Tell, and Vial creatures. Full Leyline is too narrow for mainboard. The sweet spot: 1-2 versatile graveyard hate cards that have utility in non-graveyard matchups."},
    {"instruction": "What is the difference between a tempo deck and an aggro deck in Legacy?", "input": "", "output": "Tempo deploys a cheap threat then PROTECTS it with disruption (countermagic, hand disruption, mana denial). The win comes from the opponent being unable to deal with the threat while also being disrupted. Dimir Tempo: Bowmasters + Force + Daze + Wasteland. Aggro deploys threats and does NOT protect them, instead relying on overwhelming the opponent with more threats than they can answer. Ocelot Pride: creature after creature, token generators, go wide. The key difference: tempo plays from behind on board presence (1-2 threats) but ahead on tempo. Aggro plays ahead on board presence (5+ threats) but behind on interaction. Tempo folds if its few threats are answered; aggro folds if the opponent stabilizes."},
    {"instruction": "Why do most Legacy combo decks include a Plan B?", "input": "", "output": "Legacy has too much interaction for any single combo to be reliable. 45% of decks play Force of Will, 36% play Leyline of the Void, 25% play Surgical Extraction. Without a Plan B, you lose whenever your primary combo is disrupted. Examples: TES has Empty the Warrens as Plan B when Tendrils is countered (20+ goblin tokens instead). Doomsday can side into Show and Tell when graveyard hate is present. Painter has Red Elemental Blast becoming unconditional counters as Plan B. Even Oops plays Force of Will (protect the combo) and can side into a longer game plan. The best combo decks have 2-3 angles of attack."},
    {"instruction": "How do I build a sideboard for a rogue deck?", "input": "", "output": "Rogue decks need sideboards more than meta decks because you cannot afford bad matchups that would be addressed by established sideboard plans. Process: 1) Goldfish against the top 5 decks and identify which matchups are bad. 2) Allocate MORE sideboard slots to bad matchups than a meta deck would because you cannot rely on mainboard strength. 3) Prioritize versatile hate (Leyline covers all graveyard, Pyroblast covers all blue). 4) Include at least 2 cards that improve your mirror or similar matchups. 5) Leave 1-2 slots flexible for cards you discover you need after first tournaments. Rogue decks also benefit from 'gotcha' sideboard cards that opponents do not expect."},
    {"instruction": "What are the most common sideboard mistakes in Legacy?", "input": "", "output": "1) Overboarding: bringing in 8+ cards and cutting core engine pieces. If you cut Brainstorm and Ponder, your deck stops functioning. Maximum 5-6 cards in, 5-6 out. 2) Not knowing what to cut: write sideboard plans BEFORE the tournament. Do not figure it out mid-match. 3) Bringing in hate that hurts your own deck: Null Rod with Lotus Petal, Leyline in a Murktide deck... wait, Leyline only hits opponents. But Grafdigger's Cage stops your own Green Sun's Zenith. 4) Not enough copies of key hate: 1 Leyline is much weaker than 3-4 because you need it in your opening hand. 5) Too narrow: a card that only comes in for 1 matchup is usually worse than a card that comes in for 3."},
]

deck_analysis = [
    {"instruction": "What makes Legacy metagames cycle over time?", "input": "", "output": "Legacy metagames follow predictable cycles: 1) A deck becomes dominant (Dimir Tempo at 14.6%). 2) Players adapt by choosing decks that beat the dominant deck (Lands is great vs Dimir). 3) The predator decks rise, reducing the dominant deck's share. 4) The predator decks have their own weaknesses (Lands loses to combo). 5) Combo rises to exploit the predator shift. 6) Players return to the originally dominant deck because it beats combo. This cycle repeats every 4-8 weeks. New card printings and bans can break the cycle by introducing new strategies. Understanding the cycle helps you anticipate metagame shifts: if Dimir Tempo is rising, Lands will follow 2-3 weeks later."},
    {"instruction": "How does the Legacy metagame differ between MTGO and paper?", "input": "", "output": "MTGO: faster meta adaptation (daily data), more combo (execution is easier digitally), fewer creature decks (Daze math and Brainstorm are harder in paper), tournament-tested lists dominate. Paper: slower adaptation (weekly events), more rogue decks (players invest in one deck and stick with it), more creature strategies (simpler to execute), local metas are smaller and more predictable. The implication: MTGO data is more useful for understanding macro trends, but paper metagames are more exploitable through local knowledge. If your MTGO data shows Dimir Tempo at 14.6% but your store has 0 Dimir players, adjust accordingly."},
    {"instruction": "How do I interpret a Legacy deck's matchup spread?", "input": "", "output": "A matchup spread shows win rates against each opposing archetype. Reading it: 1) Add up expected win rate weighted by meta share. If your total is above 52%, you are well-positioned. 2) Look for auto-losses (below 30% against any deck above 3% meta share). These are structural weaknesses that sideboarding may not fix. 3) Count your 'free wins' (above 65% against decks above 3% meta). These are matchups where you thrive. 4) The ideal spread: no matchup below 35%, several above 55%, and weighted average above 52%. 5) A deck with all 50% matchups is worse than a deck with 60%/40% polarization IF the good matchups are more common than the bad ones."},
    {"instruction": "What metagame conditions favor combo in Legacy?", "input": "", "output": "Combo thrives when: 1) Fair creature decks are dominant (they lack free countermagic). 2) Sideboard hate shifts to creature interaction (fewer Leylines, more removal). 3) The metagame is diverse (opponents cannot bring the right hate for YOUR specific combo). 4) New combo cards are printed (MH sets often enable new combos). 5) Recent bans remove a combo predator. Combo declines when: 1) Blue tempo/control dominates (Force + Daze + Thoughtseize covers all combos). 2) Sideboard hate is concentrated (everyone has 4 Leyline + 2 Surgical). 3) Prison decks rise (Chalice on 1 stops most combo setup)."},
    {"instruction": "How do I evaluate whether to play a proven deck or brew something new?", "input": "", "output": "The expected value calculation: a proven deck with an established 53% win rate played by an experienced pilot is almost always better than a brew with unknown win rate. Brewing is correct when: 1) You are an experienced Legacy player who understands the format deeply. 2) You have identified a specific metagame weakness to exploit. 3) You have tested the brew for 30+ matches and confirmed its matchup spread. 4) The brew uses a powerful engine that the meta is not prepared for. Brewing is wrong when: 1) You are new to Legacy. 2) You have not tested against the top 5 decks. 3) Your motivation is boredom rather than strategic advantage. The best Legacy brewers (Reid Duke, EFro) build on existing shells, not from scratch."},
]

conversation = [
    {"instruction": "I want to teach my friend to play Legacy. Where should we start?", "input": "", "output": "Start with a simple matchup between two straightforward decks:\n\nBeginner pair: Burn vs Mono Red Stompy. Both are mono-color, have clear game plans, and do not require Brainstorm decisions. Burn teaches damage math and sequencing. Stompy teaches prison strategy and threat deployment.\n\nIntermediate pair: Izzet Delver vs Death and Taxes. This teaches cantrip sequencing, Daze math, Aether Vial timing, and sideboarding. Both decks have clear roles.\n\nTeach in stages: 1) Start with goldfish (just play your own deck). 2) Then play game 1s only (no sideboarding). 3) Then add sideboards. 4) Then discuss specific Brainstorm lines.\n\nKey: do not start with combo decks. Learning Legacy through Storm or Doomsday is overwhelming. The format fundamentals (cantrips, fetchlands, Force of Will) are best learned through fair decks."},
    {"instruction": "What are the most common mistakes when sideboards are built for Legacy?", "input": "", "output": "1) Too many singletons: 15 different cards means you rarely draw any specific one. Better to have 3-4 copies of your most important hate cards. 2) Cards that do not come in for any specific matchup: if you cannot name 2+ matchups where a card improves your win rate, cut it. 3) Hate that is too narrow: Tormod's Crypt ONLY hits graveyards. Endurance hits graveyards AND is a 3/4 body AND pitches to Force of Vigor. Choose flexible cards. 4) Not adjusting for your local meta: online sideboards are built for the MTGO meta. Your local meta may be 50% combo, requiring 8 combo hate slots instead of 5. 5) Forgetting to test sideboard games: most players test game 1s and guess at sideboard plans. Test post-board games too."},
    {"instruction": "What format should I try after Legacy?", "input": "", "output": "If you love Legacy, you will probably enjoy: 1) Vintage: even more powerful card pool, Power 9 unrestricted... wait, they are restricted. The ultimate power fantasy with Moxen and Ancestral Recall at 1 copy each. Very small community. 2) Old School (93/94): only cards from 1993-1994. Pure nostalgia and the origins of Magic. 3) Canadian Highlander: 100-card singleton with a points system for powerful cards. Combines Legacy's power with deck diversity. 4) Commander/cEDH: multiplayer, uses many Legacy cards. cEDH is competitive and has a Legacy-like feel. 5) Modern: more accessible, less powerful, but still a non-rotating format with good gameplay.\n\nMost Legacy players also play Commander casually and occasionally Modern. Very few quit Legacy for another format - the gameplay is too good."},
    {"instruction": "How has Legacy changed since I last played in 2019?", "input": "", "output": "Massive changes since 2019:\n\nBanned since 2019: Wrenn and Six (2019), Underworld Breach (2020), Arcum's Astrolabe (2020), Ragavan (2022), Expressive Iteration (2023), White Plume Adventurer (2023), Grief (2024), Nadu (2024), Psychic Frog (2025), Entomb (2025).\n\nFormat-defining additions: Orcish Bowmasters (2023, most played creature), Murktide Regent (2021, premier threat), Urza's Saga (2021, artifact enabler), The One Ring (2023, card advantage engine), energy cards from MH3 (2024, created non-blue aggro).\n\nMeta shift: 2019 was UR Delver dominance with Wrenn and Six. 2026 is Dimir Tempo (14.6%) with diverse combo. The format is healthier and more diverse than 2019. Bowmasters fundamentally changed how cantrips are used. Energy cards made non-blue competitive for the first time in years."},
    {"instruction": "Is it too late to start playing Legacy in 2026?", "input": "", "output": "Absolutely not. It is actually a great time to start:\n\n1) The format is the healthiest it has been in years: 54 archetypes, balanced meta, no oppressive deck.\n\n2) Budget entry points exist: Oops ($1100), Burn ($1500), MTGO ($300-500). You do not need dual lands on day 1.\n\n3) Proxy acceptance is growing. More stores allow proxied Legacy events, removing the cost barrier.\n\n4) MTGO provides unlimited practice at low cost.\n\n5) The player base is stable and welcoming. Legacy communities actively recruit new players because growing the format benefits everyone.\n\n6) Reserved List cards appreciate, so your investment grows over time.\n\nThe only argument against starting Legacy is the cost, and there are now multiple ways to play competitively without the full investment. Start on MTGO or at a proxy-friendly store. Master one deck. Then decide if you want to invest in paper. By the time you are ready for paper, you will know the format well enough to make smart purchasing decisions."},
]

board_state = [
    {"instruction": "Board state: I have Painter's Servant naming blue in play. Opponent casts Veil of Summer. What happens?", "input": "", "output": "Veil of Summer says: you and spells you control cannot be the target of blue or black spells or abilities this turn. Draw a card if an opponent has cast a blue or black spell this turn. With Painter naming blue, ALL spells are blue (including your own). When Veil resolves: the opponent draws a card (you have cast blue spells this turn because all your spells are blue). They and their spells gain hexproof from blue and black. This means YOUR Grindstone activation (which targets them) is... wait, Grindstone targets an opponent to mill, and Grindstone is an artifact ability, not a spell. Veil protects from spells and abilities that are blue. The Grindstone ability is now blue (because Painter makes everything blue). Can Veil's protection stop a blue ability? Veil says 'blue or black spells or abilities' so yes. You cannot target the Veil player with Grindstone while Veil is active. Wait until Veil's protection expires at end of turn, then combo."},
    {"instruction": "Board state: I have 4 Islands and Daze in hand. Opponent casts Show and Tell with 3 mana (2U). They have 1 untapped Island remaining. Should I Daze?", "input": "", "output": "Yes, Daze the Show and Tell. Opponent cast S&T for 3 mana and has 1 Island untapped. If you Daze (return your Island to hand), they must pay 1 more to resolve S&T. They have 1 untapped Island, so they CAN pay. But here is the critical question: do they have Force of Will backup? If they pay for Daze, they used all their mana AND their combo spell resolved - they are likely going for the combo this turn. If you do not Daze, S&T resolves for free and they still have 1 untapped Island for... nothing useful. Actually, forcing them to tap their last Island is valuable because it means they cannot activate any instant-speed abilities. Daze here is correct: at minimum it costs them their last mana, and if they cannot pay (maybe the untapped land produces colorless), S&T is countered. Always Daze a must-counter spell when the opponent is mana-constrained."},
    {"instruction": "Board state: My opponent just cast Terminus miracle for W, putting all creatures on bottom of libraries. I have Karakas and my own Thalia on the battlefield. Can I save Thalia?", "input": "", "output": "Yes! In response to Terminus (while it is on the stack), activate Karakas targeting Thalia (she is legendary). Thalia returns to your hand before Terminus resolves. When Terminus resolves, it puts all creatures on the bottom of libraries - but Thalia is safely in your hand, not on the battlefield. Next turn, replay Thalia. You protected your key creature from a board wipe for 0 mana (Karakas tap costs nothing). This is one of the most important Karakas interactions: saving your own legends from removal."},
    {"instruction": "Board state: I have Leyline of the Void and Helm of Obedience, but opponent has Force of Vigor in hand (I know from Thoughtseize). How do I win?", "input": "", "output": "Force of Vigor can destroy both Leyline and Helm in one shot (it destroys up to 2 artifacts/enchantments). If you activate Helm while both are in play, opponent can Force of Vigor in response: destroy Leyline first. Without Leyline, Helm's activation stops at the first creature or after X cards go to graveyard normally. You do not win.\n\nBetter line: activate Helm for X=1 BEFORE they get priority to cast Vigor... wait, they have priority to respond to the activation. The activation goes on the stack, they can Vigor in response. The key: you need to strip the Vigor first. Options: 1) Thoughtseize it (you already know about it). 2) Duress it. 3) Wait until they use Vigor on something else. 4) Force of Will their Vigor in response to Helm activation. If you have Force + blue card, the line is: activate Helm, they Vigor targeting Leyline + Helm, you Force their Vigor. Helm resolves and mills them out."},
    {"instruction": "Board state: I am playing Elves. I have 5 elves in play, Heritage Druid, and Natural Order in hand but only 2 green mana from lands. Can I cast Natural Order?", "input": "", "output": "Yes! Heritage Druid's ability: tap three untapped elves you control to add GGG. You have 5 elves total. Tap 3 (including Heritage Druid itself) for GGG. You now have GGG + 2G from lands = GGGGG (5 green mana). Natural Order costs 2GG (4 mana). Cast Natural Order sacrificing one of your 2 remaining untapped elves (the cost). Search your library for Craterhoof Behemoth. Craterhoof enters: you control 4 creatures (5 original - 1 sacrificed to NO + Craterhoof = 5, wait: 5 - 1 sac'd = 4, + Craterhoof = 5). Craterhoof gives all creatures +5/+5 and trample. Your 4 remaining elves (roughly 1/1 each) become 6/6 tramplers, Craterhoof is 10/10 trample. Total attack: 34 damage with trample. Lethal from 20."},
]

budget = [
    {"instruction": "What is the most cost-efficient upgrade path for Legacy?", "input": "", "output": "The most efficient path maximizes card overlap between decks:\n\nStep 1 ($0-1500): Burn or Oops (budget entry, learn the format)\nStep 2 (+$400): Add 4 Force of Will (goes in every blue deck forever)\nStep 3 (+$200): Add fetchlands if you do not have them (go in every deck)\nStep 4 (+$600): Buy 1 Underground Sea (goes in Dimir Tempo, Storm, Doomsday, BUG)\nStep 5 (+$500): Build Dimir Tempo with 1 real Sea + shock lands\nStep 6 (+$600): Second Underground Sea, complete the Dimir mana base\nStep 7 (+$500): Third Underground Sea OR first Volcanic Island (enables Sneak and Show, Izzet Delver)\n\nTotal: ~$3800 for 2-3 competitive decks sharing a core of Force of Will, fetchlands, and cantrips. Each purchase builds on the last with zero wasted cards."},
    {"instruction": "Are Legacy decks cheaper to rent or own on MTGO?", "input": "", "output": "Break-even analysis: Renting costs $20-50/month. Buying a deck costs $300-600 one-time with 80-90% resale. At $30/month rent: 12 months = $360. Buying at $400 with $360 resale = $40 net cost. Buying wins after ~2 months.\n\nBut renting has flexibility: switch decks freely, no capital locked up, try everything. If you switch decks monthly, renting at $30 beats buying 12 decks at $400 each.\n\nRecommendation: Rent for months 1-2 (try 3-4 decks, find your favorite). Buy your chosen deck in month 3. Rent other decks occasionally to test new strategies. This hybrid approach costs ~$460/year (2 months rent + 1 deck bought) vs pure rent ($360/year) or pure buy ($400+ with no flexibility). The small premium for the hybrid is worth the informed purchasing decision."},
    {"instruction": "How do I find the best prices on Legacy cards?", "input": "", "output": "Price comparison strategies: 1) TCGPlayer: largest US marketplace, competitive pricing from hundreds of sellers. Always check for damaged/heavily played cards at 20-30% discounts if condition is acceptable. 2) CardKingdom: slightly higher prices but guaranteed quality and excellent customer service. Buylist is generous for selling. 3) eBay: best for Reserved List cards where auction dynamics can produce deals 10-20% below market. 4) Facebook groups (MTG Sick Deals, High End): peer-to-peer sales at 10-15% below retail. 5) Your LGS: support local stores, negotiate on bulk purchases. 6) Trade: Legacy players often have cards they are willing to trade. Bring trade binders to events.\n\nTiming: buy non-RL cards after reprint announcements (prices dip 20-40%). Buy RL cards ASAP (they only go up). Sell into hype spikes from tournament results."},
]

# Write all
categories = [
    ("rules_qa.jsonl", rules),
    ("card_evaluation.jsonl", card_eval),
    ("deckbuilding_rationale.jsonl", deckbuilding),
    ("deck_analysis.jsonl", deck_analysis),
    ("conversation_flow.jsonl", conversation),
    ("board_state_analysis.jsonl", board_state),
    ("budget_substitutions.jsonl", budget),
]

for filename, data in categories:
    outpath = os.path.join(os.path.dirname(__file__), "..", "data", "training", filename)
    with open(outpath, "a", encoding="utf-8") as f:
        for pair in data:
            f.write(json.dumps(pair, ensure_ascii=False) + "\n")
    print(f"Appended {len(data)} pairs to {filename}")
