"""Generate deckbuilding rationale training data - Batch 3 (append). More per-deck card explanations."""
import json
import os

pairs = [
    # === PER-DECK CARD EXPLANATIONS (covering remaining top decks) ===
    # Boros Initiative
    {"instruction": "Why does Boros Initiative play Caves of Chaos Adventurer?", "input": "", "output": "Caves of Chaos Adventurer provides the Initiative when it enters the battlefield, which advances through the Undercity dungeon. The dungeon rooms provide card advantage, removal, and eventually a 5/5 token. In a prison deck that slows the opponent with Chalice and Thalia, the Initiative provides incremental value every turn. The 5/3 body for 4 mana is reasonable, and Ancient Tomb enables turn-2 deployment."},
    {"instruction": "Why does Boros Initiative play Solitude?", "input": "", "output": "Solitude can be cast for free by pitching a white card, providing instant-speed removal at zero mana. In a deck without blue cantrips to find answers, having free removal is essential for handling surprise threats. Solitude also has lifelink on its 3/2 body, which helps stabilize after Ancient Tomb life loss. The pitch cost is acceptable because Boros Initiative runs many white cards."},
    # Dredge
    {"instruction": "Why does Dredge play Golgari Grave-Troll?", "input": "", "output": "Golgari Grave-Troll has dredge 6, the highest dredge count in Legacy. Each time you would draw a card, you can instead mill 6 cards and return Grave-Troll to hand. Milling 6 cards fills the graveyard with Ichorid, Narcomoeba, Bridge from Below triggers, and more dredge cards. The more cards milled, the more resources generated. Grave-Troll's creature body is rarely cast but its dredge ability is the engine that makes the deck work."},
    {"instruction": "Why does Dredge play Bridge from Below?", "input": "", "output": "Bridge from Below creates a 2/2 zombie token whenever a creature you control dies while Bridge is in your graveyard. In Dredge, creatures die constantly (Ichorid sacrifices itself, Narcomoeba enables Dread Return by being sacrificed). Each death creates a zombie. However, Bridge is exiled if an opponent's creature dies, which is why Orcish Bowmasters (creating a 1/1 that can die in combat) is so devastating against Dredge."},
    # Omni-Tell
    {"instruction": "Why does Omni-Tell play Omniscience instead of Sneak Attack?", "input": "", "output": "Omniscience lets you cast ALL spells from your hand for free, not just creatures. After resolving Show and Tell for Omniscience, you can cast Emrakul (extra turn + annihilator 6), Atraxa (draw 10+ cards), Brainstorm (find more threats), and Force of Will (protect your board), all for free. Sneak Attack only puts creatures in play temporarily (sacrificed at end of turn). Omniscience keeps everything permanently and enables casting any card type."},
    # Mystic Forge
    {"instruction": "Why does Mystic Forge Combo play Karn, the Great Creator?", "input": "", "output": "Karn, the Great Creator has a -2 ability that gets any artifact from outside the game (sideboard) or from exile. This provides a toolbox of silver bullets: Ensnaring Bridge against creatures, Mycosynth Lattice to lock opponent out of mana with Karn's passive (opponents cannot activate abilities of artifacts), Tormod's Crypt for graveyard hate, Walking Ballista as a win condition. Karn also shuts off opponent's artifact abilities with his passive, disabling Aether Vial, Mox, and equipment."},
    # Coveted Jewel
    {"instruction": "Why does Coveted Jewel Combo play flicker effects?", "input": "", "output": "Coveted Jewel is an artifact that taps for 3 mana of any color and draws 3 cards when it enters play. By flickering it (exiling and returning with Ephemerate or Yorion), you get the ETB again: draw 3 more cards and 3 more mana. Each flicker is a 3-card draw engine. Combined with the 3 mana it generates, flickering Jewel creates a self-sustaining combo that draws your entire deck and generates infinite mana. The kill is usually Thassa's Oracle or Walking Ballista."},
    # Hogaak
    {"instruction": "Why does Hogaak play Altar of Dementia?", "input": "", "output": "Altar of Dementia sacrifices a creature to mill that many cards from any player's library. Hogaak is an 8/8 that can be cast from the graveyard by convoking and delving. Mill Hogaak to Altar, mill 8 cards from your own library (filling graveyard with more creatures), recast Hogaak using convoke and delve, repeat. Each loop mills 8 cards and eventually mills your entire library for a Thassa's Oracle win, or mills the opponent's library directly. Altar provides both a combo finish and graveyard fueling."},

    # === MORE MATCHUP REASONING ===
    {"instruction": "Why is Painter favored against Death and Taxes?", "input": "", "output": "Painter's two-card combo (Servant + Grindstone) is faster than D&T can deploy its hatebears. D&T has no counterspells to stop the combo. Thalia taxes Grindstone activation by 0 (it is an artifact ability, not a noncreature spell). Rishadan Port and Wasteland slow Painter slightly but Ancient Tomb dodges both (produces colorless). Red Elemental Blast with Painter naming blue destroys any permanent and counters any spell, overwhelming D&T's creature-based interaction."},
    {"instruction": "Why is Oops All Spells favored against Lands?", "input": "", "output": "Lands operates entirely at sorcery speed through land abilities. It has no counterspells, no instant-speed graveyard hate in the maindeck, and no way to interact with a combo that wins by milling a library and casting Thassa's Oracle. Lands' strengths (Wasteland, Maze of Ith, Punishing Fire) are all irrelevant against Oops. The only interaction is sideboard Bojuka Bog (found by Crop Rotation) or Surgical Extraction, which requires the Oops player to fill the graveyard first."},
    {"instruction": "Why is Elves weak against Orcish Bowmasters?", "input": "", "output": "Elves runs almost entirely 1-toughness creatures: Deathrite Shaman, Heritage Druid, Quirion Ranger, Birchlore Rangers, Elvish Visionary. Bowmasters' enter-the-battlefield trigger deals 1 damage and creates a 1/1, instantly killing any of these. Additionally, every cantrip and draw effect (Glimpse of Nature draws) triggers Bowmasters again. An Elves player casting Glimpse and chaining 5 creatures draws 5 cards, triggering Bowmasters 5 times, killing 5 elves and growing the Army to a 6/6. Bowmasters single-handedly dismantles the Elves engine."},
    {"instruction": "Why does Sneak and Show struggle against Karakas?", "input": "", "output": "Karakas returns target legendary creature to its owner's hand for free (tap Karakas). Emrakul, the Aeons Torn is legendary. After you Sneak Attack or Show and Tell Emrakul into play, the opponent can simply tap Karakas to bounce it back to your hand. The annihilator trigger still happens when Emrakul attacks (if they wait until attackers are declared), but they can Karakas before the declare attackers step to prevent even that. Atraxa, Grand Unifier is also legendary. This is why 21% of Legacy decks play Karakas."},
    {"instruction": "Why does Red Stompy struggle against Force of Vigor?", "input": "", "output": "Red Stompy relies on turn-1 lock pieces like Blood Moon, Chalice of the Void, and Ensnaring Bridge. Force of Vigor destroys two artifacts and/or enchantments for free by pitching a green card. A single Force of Vigor can destroy both Chalice AND Blood Moon in one shot, completely dismantling the prison at zero mana. Green decks boarding in 2-3 Force of Vigor make Stompy's lock pieces unreliable, and without the lock, Stompy's threats are mediocre."},

    # === DECKBUILDING PRINCIPLES ===
    {"instruction": "How do I build a Legacy deck from scratch?", "input": "", "output": "Step 1: Choose a strategy (tempo, control, combo, prison, midrange). Step 2: Select your core engine cards (Brainstorm + Force for blue, Chalice + fast mana for prison, rituals + wincon for combo). Step 3: Build the mana base (14+ sources of primary color, fetchlands, 2-4 basics). Step 4: Fill with the most efficient cards for your strategy at each mana cost. Step 5: Build a 15-card sideboard covering the top 5-8 matchups. Step 6: Goldfish 20+ hands to check consistency. Step 7: Test against tier 1 decks. Step 8: Iterate based on results. Most importantly: study existing successful decklists before brewing from zero."},
    {"instruction": "What is the most important card slot in a Legacy deck?", "input": "", "output": "The 1-mana spell slot. Legacy is defined by 1-mana spells: Brainstorm, Ponder, Thoughtseize, Swords to Plowshares, Lightning Bolt, Daze (free but MV 1), Delver of Secrets, Dark Ritual, Goblin Lackey, Mother of Runes, Aether Vial. Every competitive deck maximizes its 1-mana plays. If your deck's best turn-1 play is passing with a land, you are probably too slow for Legacy. The exception is prison decks that use 0-mana acceleration (Ancient Tomb, Lotus Petal) to deploy 2-3 mana lock pieces on turn 1 instead."},
    {"instruction": "How do I know if my Legacy deck is good?", "input": "", "output": "Test against the tier 1 metagame: 1) Does it have a positive win rate against Dimir Tempo (14.6%)? If not, you lose your most common matchup. 2) Does it have a plan against fast combo (Oops, Storm)? If not, you get turn-1/2 killed. 3) Does it function through Chalice of the Void on 1? If not, prison decks destroy you. 4) Can it win by turn 5-6 against a goldfish? If not, you are too slow. 5) Is every card in your deck the most efficient version of its effect? If you are playing 2+ mana cards that could be 1-mana alternatives, replace them. A Legacy deck that passes all 5 tests is competitive."},
    {"instruction": "What is wrong with playing more than 60 cards in Legacy?", "input": "", "output": "Every card above 60 reduces your probability of drawing your best cards. If your best card is a 4-of in 60 cards, you see it in about 40% of opening hands. In 65 cards, that drops to 37%. In 80 cards (Yorion), it drops to 32%. Legacy rewards consistency because matchups are diverse and you need specific answers. The only exception is Yorion companion (80 cards), where the guaranteed companion value compensates for reduced consistency. Even then, Yorion builds accept lower consistency as a trade-off."},
    {"instruction": "When should I splash a third color in my Legacy deck?", "input": "", "output": "Splash a third color only when: 1) The splashed cards are worth the mana base damage (Uro in Bant Control, Pyroblast in Grixis). 2) You can support it with 1-2 dual lands and fetchlands that already serve your main colors. 3) The splash does not weaken your Blood Moon resilience (more nonbasics = more vulnerability). 4) You have enough cantrips to find the splash color when needed. Bad reasons to splash: adding a marginally better removal spell, or a creature that is only slightly better than alternatives in your main colors. The deckbuilding cost of a splash (life from fetching, Wasteland vulnerability, Blood Moon risk) must be outweighed by the power gain."},
]

outpath = os.path.join(os.path.dirname(__file__), "..", "data", "training", "deckbuilding_rationale.jsonl")
with open(outpath, "a", encoding="utf-8") as f:
    for pair in pairs:
        f.write(json.dumps(pair, ensure_ascii=False) + "\n")

print(f"Appended {len(pairs)} pairs to {outpath}")
