"""Generate board state analysis training data - Batch 2 (append)."""
import json
import os

pairs = [
    # === MORE OPENING HAND EVALUATION ===
    {"instruction": "Should I keep this opening hand for Sneak and Show: Ancient Tomb, Island, Show and Tell, Emrakul, Force of Will, Brainstorm, Ponder?", "input": "", "output": "Excellent keep. Ancient Tomb + Island = 3 mana on turn 2 for Show and Tell. Emrakul is your payoff. Force of Will protects the combo (you can pitch Brainstorm or Ponder if needed). If they have disruption, Brainstorm and Ponder dig for alternatives. This hand has combo, protection, and backup plan. 9/10."},
    {"instruction": "Should I keep this Oops All Spells hand: Lotus Petal, Dark Ritual, Elvish Spirit Guide, Balustrade Spy, Pact of Negation, Force of Will, Narcomoeba?", "input": "", "output": "Snap keep - this wins on turn 1. Sequence: Elvish Spirit Guide (exile for G... wait, you need B or colorless for Spy). Lotus Petal for B, Dark Ritual for BBB, cast Balustrade Spy (costs 3B) using BBB+B. Spy mills your entire library. Narcomoeba triggers. Pact of Negation and Force of Will protect against opponent's Force of Will. This is a protected turn-1 kill. 10/10."},
    {"instruction": "Should I keep this Lands hand: Exploration, Mox Diamond, Dark Depths, Thespian's Stage, Wasteland, Life from the Loam, Crop Rotation?", "input": "", "output": "Incredible keep. Turn 1: Mox Diamond (discard Wasteland), Exploration, play Dark Depths and Thespian's Stage. Turn 2: Activate Stage copying Depths (both have 0 ice counters), create Marit Lage 20/20. You have Crop Rotation and Life from the Loam as backup, plus the discarded Wasteland can be dredged back with Loam. This is a turn-2 kill hand with redundancy. 10/10."},
    {"instruction": "Should I keep this Death and Taxes hand: Aether Vial, Thalia, Stoneforge Mystic, Phyrexian Revoker, Karakas, Plains, Plains?", "input": "", "output": "Very strong keep. Turn 1: Plains, Aether Vial. Turn 2: Plains, Thalia (noncreature spells cost 1 more). Turn 3: Vial on 2, play Stoneforge (tutor Batterskull), Vial in Phyrexian Revoker naming their best activated ability. Karakas protects your legends and bounces opposing legends. This hand has the perfect D&T curve: Vial into taxing creature into equipment. 9/10."},
    {"instruction": "Should I keep this Storm hand: Dark Ritual, Dark Ritual, Burning Wish, Brainstorm, Ponder, Underground Sea, no other lands?", "input": "", "output": "Risky but keepable. You have a 1-land hand with 2 cantrips to find more mana. Dark Ritual + Dark Ritual + Underground Sea = BBBBBBB (7 black). Burning Wish costs 2 mana. That leaves 5 mana floating. But you need more storm count for lethal Tendrils (storm needs ~9 copies for 20 damage). The cantrips help find Lion's Eye Diamond or more rituals. On the play, keep - cantrips on turn 1 find your second land. On the draw, borderline - opponent might disrupt you first. 6/10 on play, 5/10 on draw."},
    {"instruction": "Should I keep this Painter hand: Ancient Tomb, Mountain, Painter's Servant, Grindstone, Goblin Welder, Pyroblast, Red Elemental Blast?", "input": "", "output": "Good keep. Turn 1: Ancient Tomb, Painter's Servant (naming blue). Turn 2: Mountain, Grindstone (2 to cast), activate Grindstone (3 total): opponent's entire library is milled since everything is blue. You have Goblin Welder as backup if Painter is removed, and Pyroblast + REB as protection that becomes unconditional countermagic with Painter in play. The only risk is opponent having Force of Will for Painter on turn 1. 8/10."},
    {"instruction": "Should I keep this Eldrazi hand: Ancient Tomb, Eldrazi Temple, Chalice of the Void, Chalice of the Void, Thought-Knot Seer, Reality Smasher, Wasteland?", "input": "", "output": "Strong keep. Turn 1: Ancient Tomb, Chalice of the Void on 1 (shuts out cantrips, Swords, Bolt, Thoughtseize). Turn 2: Eldrazi Temple, Thought-Knot Seer (4 mana from Tomb + Temple + Temple's Eldrazi bonus). You strip their best card and have a 4/4. Turn 3: Reality Smasher with the second Chalice as backup for a different number if needed. Wasteland handles problematic lands. Two Chalice is slightly redundant but the turn-1 Chalice is devastating. 8/10."},

    # === MORE BOARD STATE ANALYSIS ===
    {"instruction": "Board state: I have Delver of Secrets (still a 1/1, hasn't flipped). Top card of my library is Lightning Bolt (I know from Ponder). Should I flip Delver or cast another spell?", "input": "", "output": "Let Delver flip. During your upkeep, reveal Lightning Bolt from the top - it is an instant, so Delver transforms into Insectile Aberration (3/2 flyer). A 3/2 flyer is a 7-turn clock becoming a 4-turn clock. The Bolt stays on top for you to draw next turn. Do not cast a spell before upkeep that would change the top card (like cracking a fetchland). Sequencing: upkeep flip Delver, draw Bolt, then decide whether to use Bolt this turn or hold it."},
    {"instruction": "Board state: Opponent has Blood Moon in play. I have a Polluted Delta in hand. Should I play it?", "input": "", "output": "Yes, play Polluted Delta, but understand it enters as a Mountain under Blood Moon. You cannot activate its fetchland ability because Blood Moon removes all abilities and replaces the land type with Mountain. However, it still taps for R (red mana). If you need red mana, this is fine. If you need to search for an Island to cast Force of Will, you must destroy Blood Moon first. Consider: do you have a way to remove Blood Moon (Force of Vigor, Abrupt Decay)? If so, play the Delta now and activate it after Moon is gone."},
    {"instruction": "Board state: I have 2 Islands and a Daze in hand. Opponent casts Show and Tell with 1 Island untapped. Should I Daze?", "input": "", "output": "Yes, Daze the Show and Tell. Show and Tell costs 2U (3 mana). Your opponent has enough mana to cast it but only 1 Island untapped. If you cast Daze (returning your Island to hand), they must pay 1 to avoid the counter. They have 1 untapped Island, so they CAN pay. BUT - look at the bigger picture. If they pay for Daze, they have used their Show and Tell and 1 extra mana. You still have 1 Island in play. If they cannot pay (maybe the untapped land is not an Island), the Show and Tell is countered. Daze here forces them to either lose their combo or use their remaining mana. Either way, you bought time."},
    {"instruction": "Board state: My opponent has Leyline of the Void in play (started in opening hand). I am playing Doomsday. Can I still win?", "input": "", "output": "This is very difficult but not impossible. Leyline means your cards go to exile instead of the graveyard. This means: you cannot use graveyard-based Doomsday piles. However, Thassa's Oracle wins by checking devotion to blue vs cards in library, not the graveyard. Your pile needs to draw through itself WITHOUT putting cards in the graveyard. Pile example: Brainstorm, Ponder, Thought Scour (mills go to exile, fine), Thassa's Oracle, Force of Will (protection). You need to cast Doomsday, then draw through with cantrips and cast Oracle with 0 cards in library. The key is that Oracle checks library size, not graveyard - Leyline does not stop the win condition itself."},
    {"instruction": "Board state: I control Painter's Servant (naming blue) and Goblin Welder. Opponent destroys my Grindstone with Force of Vigor. What do I do?", "input": "", "output": "Goblin Welder to the rescue. In response to Force of Vigor (or after it resolves if Grindstone is already in the graveyard), activate Goblin Welder: swap Grindstone from the graveyard with any artifact on the battlefield (you can sacrifice a Lotus Petal or other cheap artifact). Grindstone returns to the battlefield untapped. You can then activate it immediately to combo off. This is exactly why Painter plays Goblin Welder - it provides instant-speed recursion that makes killing combo pieces very difficult. The opponent needs to kill Welder AND the combo piece to truly stop you."},
    {"instruction": "Board state: I am at 3 life. Opponent has Orcish Bowmasters (1/1) and an Orc Army token (3/3). I have Toxic Deluge in hand. What X should I choose?", "input": "", "output": "You are at 3 life and Toxic Deluge costs X life to give all creatures -X/-X until end of turn. You need X=3 to kill the 3/3 Army token (and the 1/1 Bowmasters dies too at X=1). But paying 3 life at 3 life kills you. X=1 kills only Bowmasters (1/1 gets -1/-1 = dies) but leaves the Army as a 2/2. X=2 kills Bowmasters and makes the Army a 1/1. You cannot afford X=3. Best play: X=2 (costs 2 life, you go to 1). Bowmasters dies, Army becomes 1/1 until end of turn. You survive but are at 1 life. If you have any other removal, use X=1 and deal with the Army separately."},
    {"instruction": "Board state: Opponent plays Chalice of the Void. I have Force of Will and a blue card in hand. Chalice is being cast with X=1 (2 charge counters, total cost 2). Can I Force it?", "input": "", "output": "Yes, absolutely. Chalice of the Void with X=1 has mana value 2 on the stack (X=1, XX=2). It does not counter itself or Force of Will. Force of Will has mana value 5 (even when pitched for free). Chalice only counters spells with the specified mana value AFTER it resolves and is on the battlefield. While Chalice is on the stack, it is just a spell being cast. Force of Will it now before it resolves. If you let Chalice resolve, then your 1-mana spells (Brainstorm, Ponder, Swords) will be countered, but Force of Will (MV 5) will still work fine."},
    {"instruction": "Board state: I have lethal on board (Murktide 8/8, opponent at 8 life). Opponent is tapped out. Should I attack or hold up Daze?", "input": "", "output": "Attack for lethal. Your opponent is tapped out, meaning they cannot cast any spells (no mana for removal, no alternative costs except pitch spells like Force of Will or Solitude). If they have Force of Will, they could theoretically counter your... wait, Force counters spells not attacks. If they have Solitude, they could exile your Murktide by pitching a white card. If you suspect Solitude, holding Daze does nothing since Daze counters spells and Solitude's evoke is an alternative casting cost, which Daze could counter. Actually - attack. If they Solitude your Murktide, you can Daze the Solitude (they are tapped out and cannot pay 1). Attack with Daze backup is the correct line."},
    {"instruction": "Board state: It is my opponent's turn. They have Emrakul, the Aeons Torn in play via Sneak Attack (it will be sacrificed at end of turn). They declare attack. Emrakul has annihilator 6. I have 7 permanents. What do I sacrifice?", "input": "", "output": "You must sacrifice 6 of your 7 permanents to annihilator 6. You choose which 6. Strategic priority for keeping: 1) Keep the permanent that gives you the best chance to win next turn (if you survive). 2) Keep a land if you need mana to cast a response. 3) Keep a creature if it can trade with something relevant. If Emrakul deals 15 damage and you survive, the Emrakul from Sneak Attack is sacrificed at end of turn. You get ONE turn to rebuild. Keep your best single permanent. In practice, getting annihilated for 6 usually means you lose, but if you are above 15 life, you might survive the combat and steal a win. Note: Emrakul's controller also gets an extra turn (cast trigger) if it was cast, but Sneak Attack puts it into play without casting, so NO extra turn."},

    # === COMPLEX SEQUENCING ===
    {"instruction": "I have Brainstorm and a fetchland. What is the correct sequencing?", "input": "", "output": "The classic Brainstorm sequence:\n\n1) Do NOT crack the fetchland first (you lose the shuffle).\n2) Cast Brainstorm. Draw 3 cards.\n3) Look at your hand. Identify the 2 worst cards.\n4) Put the 2 worst cards on top of your library.\n5) NOW crack the fetchland. Search and shuffle.\n6) The 2 bad cards are shuffled into your deck.\n\nNet result: You drew the best of 4 cards (3 from Brainstorm + 1 from the fresh draw later) and permanently removed 2 bad cards from the top of your deck.\n\nCommon mistake: cracking the fetchland before Brainstorm. This wastes the shuffle. Another mistake: putting back cards you might need - always consider what your opponent might be doing before choosing the 2 to put back."},
    {"instruction": "I am playing TES. I have Dark Ritual, Lion's Eye Diamond, Burning Wish, and 1 land in play. Walk me through the kill.", "input": "", "output": "Here is the sequence:\n\n1) Cast Dark Ritual (BBB in pool). Storm count: 1.\n2) Cast Lion's Eye Diamond (resolves, now on battlefield). Storm count: 2.\n3) Cast Burning Wish. Hold priority BEFORE Wish resolves.\n4) Crack LED in response to Burning Wish (LED's ability is a mana ability, does not use stack). Discard your hand (empty anyway). Add BBB. Pool: BBB from Ritual + BBB from LED = BBBBBB.\n5) Burning Wish resolves. Search sideboard for Tendrils of Agony.\n6) Cast Tendrils of Agony from your hand. Storm count: 4 (Ritual, LED, Wish, Tendrils). Tendrils creates 4 copies. Each copy drains 2 life.\n7) Total drain: 5 Tendrils (original + 4 copies) x 2 = 10 life.\n\nThat is only 10 damage, not lethal from 20. You need more storm count. If you had an additional ritual or cantrip earlier in the turn, each additional spell adds another Tendrils copy (+2 damage). The typical TES kill needs storm count 9+ for lethal."},
    {"instruction": "I am playing Lands. I have Life from the Loam in graveyard, Exploration in play, and Wasteland. How do I lock my opponent out?", "input": "", "output": "The Wasteland lock sequence:\n\n1) During your draw step, choose to dredge Life from the Loam instead of drawing (dredge 3 - mill 3 cards from library to graveyard, return Loam to hand).\n2) Cast Life from the Loam returning Wasteland and 2 other lands from your graveyard to your hand.\n3) With Exploration, you can play 2 lands per turn. Play Wasteland. Play another land.\n4) Activate Wasteland targeting opponent's best land. Destroy it.\n5) Next turn, dredge Loam again, return Wasteland to hand, repeat.\n\nThis creates a recurring loop: every turn you destroy one of their lands while never running out of your own. Combined with Rishadan Port to tap another land, your opponent effectively has 0 usable lands per turn. This is the Lands deck's primary control strategy and is extremely difficult to break once established."},
]

outpath = os.path.join(os.path.dirname(__file__), "..", "data", "training", "board_state_analysis.jsonl")
with open(outpath, "a", encoding="utf-8") as f:
    for pair in pairs:
        f.write(json.dumps(pair, ensure_ascii=False) + "\n")

print(f"Appended {len(pairs)} pairs to {outpath}")
